### ISSUE TITLE
UncategorizedSQLException with sqlserver platform

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#1032]
I've deployed patched local data flow server(version 1.1.0.RC1) with MS SQL server(version 11.0.5388.0) as primary data source using `group: 'com.microsoft.sqlserver', name: 'sqljdbc4', version: '4.0'` jdbc driver.
The startup parameters : 

````
--spring.datasource.url=jdbc:sqlserver://server;databaseName=Flow;integratedSecurity=true^
 --spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver^
 --spring.datasource.platform=sqlserver^
````

The database gets populated with tables, but when I try to create stream, I'm getting below exception :

````java
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [SELECT DEFINITION_NAME, DEFINITION FROM (SELECT DEFINITION_NAME, DEFINITION, ROW_NUMB
ER() OVER (ORDER BY DEFINITION_NAME ASC, DEFINITION ASC) AS TMP_ROW_NUM  FROM STREAM_DEFINITIONS) SCDF_PAGE  WHERE TMP_ROW_NUM >= 1 AND TMP_ROW_NUM < 11 ORDER BY DEFINITION_NAME ASC, DEFINITION ASC];
SQL state [S0002]; error code [306]; The text, ntext, and image data types cannot be compared or sorted, except when using IS NULL or LIKE operator.; nested exception is com.microsoft.sqlserver.jdbc.S
QLServerException: The text, ntext, and image data types cannot be compared or sorted, except when using IS NULL or LIKE operator.
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84) ~[spring-jdbc-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649) ~[spring-jdbc-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684) ~[spring-jdbc-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716) ~[spring-jdbc-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726) ~[spring-jdbc-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776) ~[spring-jdbc-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.cloud.dataflow.server.repository.AbstractRdbmsKeyValueRepository.queryForPageableResults(AbstractRdbmsKeyValueRepository.java:290) ~[spring-cloud-dataflow-server-core-1.
1.0.RC1.jar!/:1.1.0.RC1]
        at org.springframework.cloud.dataflow.server.repository.AbstractRdbmsKeyValueRepository.findAll(AbstractRdbmsKeyValueRepository.java:165) ~[spring-cloud-dataflow-server-core-1.1.0.RC1.jar!/:1.
1.0.RC1]
        at org.springframework.cloud.dataflow.server.repository.AbstractRdbmsKeyValueRepository$$FastClassBySpringCGLIB$$2d5a2a81.invoke(<generated>) ~[spring-cloud-dataflow-server-core-1.1.0.RC1.jar!
/:1.1.0.RC1]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.cloud.dataflow.server.repository.RdbmsStreamDefinitionRepository$$EnhancerBySpringCGLIB$$5682bc4e.findAll(<generated>) ~[spring-cloud-dataflow-server-core-1.1.0.RC1.jar!
/:1.1.0.RC1]
        at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.list(StreamDefinitionController.java:151) ~[spring-cloud-dataflow-server-core-1.1.0.RC1.jar!/:1.1.0.RC1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
````

**Comment by sabbyanandan** [comment]
@jvmlet - Thanks for reporting this! Could you also share the stream definition that you're trying?

**Comment by jvmlet** [comment]
It happens when I click on  `Streams`  tab in the dashboard. 
However, it looks like stream definition is saved to DB, but the streams definition appears empty when I restart the server and open the `Streams`  tab again.

**Comment by trisberg** [comment]
Looks like the pagination query used by the UI isn't working for SQL Server. Other features seems to work fine and I can use the shell to create and list streams. I'll see if we can fix this query.

**Comment by trisberg** [comment]
You can try fixing this by modifying the STREAM_DEFINITIONS table to use `VARCHAR(max)` instead of `TEXT` for the DEFINITION column. Same fix needed for the TASK_DEFINITIONS table as well.

**Comment by jvmlet** [comment]
Thanks, I'll try new schema tomorrow and update you,

**Comment by jvmlet** [comment]
Thanks, I've  recreated 2 tables with updated schemas - no errors.
