### ISSUE TITLE
incorrect module deployment lookup - admin attempts to find a source instead of a processor

### ISSUE THREAD

**Issue by whummer** [spring-cloud/spring-cloud-dataflow#130]
When deploying the following pipe:
```
queue:in > groovy-transform --script=.../myscript.groovy --variables='...' > queue:out
```

I get an admin exception:
```
2015-10-24 23:01:42.967 ERROR 5 --- [io-9393-exec-18] o.s.c.d.a.c.RestControllerAdvice         : Caught exception while handling a request
java.lang.IllegalArgumentException: Module groovy-transform of type source not found in registry
        at org.springframework.cloud.dataflow.admin.controller.StreamController.deployStream(StreamController.java:236) ~[admin.jar!/:1.0.0.BUILD-SNAPSHOT]
        at org.springframework.cloud.dataflow.admin.controller.StreamController.deploy(StreamController.java:219) ~[admin.jar!/:1.0.0.BUILD-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
```

The exception indicates that the admin is looking for a "source" module, while it should in fact be looking for a "processor" module (because groovy-transform receives input data from the named channel `queue:in`).

Part of this could be an issue with the code in https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-admin/src/main/java/org/springframework/cloud/dataflow/admin/controller/StreamController.java#L231
```
			boolean isFirst = !iterator.hasNext();
			boolean isLast = (i == 0);
```
Shouldn't that be the other way around?

**Comment by ericbottard** [comment]
I created https://github.com/spring-cloud/spring-cloud-dataflow/pull/131 for this.
Might be as simple as this (good for our later `deploy()` simplification @markfisher )

**Comment by whummer** [comment]
After a quick test that I did, #131 seems to fix this problem. thx

**Comment by markfisher** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/4238a95ac842627a6dc15ed9d7163164af6c93b7
