### ISSUE TITLE
Error's curling root endpoint in local data flow server

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1306]
Several issues in testing by @trisberg and myself.

Thomas reported.
```
curl -i http://localhost:9393/

2017-04-11 09:20:44.689 DEBUG 42507 --- [nio-9393-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
    at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1221) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1161) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:712) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:361) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```
This is just a debug message, but when trying https endpoint I got

```
$ curl -i https://localhost:9393
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.```

hitting that page in chrome responded with

```
An error occurred during a connection to localhost:9393. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG```

The server log reported.
```
2017-04-11 09:39:37.413  INFO 7743 --- [nio-9393-exec-2] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
    at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:421) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]```

**Comment by jvalkeal** [comment]
I think this is perfectly normal as this `OEFException` was added by our colleague per https://github.com/apache/tomcat/commit/91b78590169c0a6fa3dfc5a7d0818a5c1c630f44. Logging error on INFO level when ssl connection is made to non-ssl connector is a bit aggressive.

**Comment by jvalkeal** [comment]
And btw, behaviour is same with oob boot app from start.spring.io.

**Comment by jvalkeal** [comment]
And mark confirmed this exception behaviour in http://tomcat.10.x6.nabble.com/How-to-write-a-correct-HTTP-request-to-Tomcat-8-5-4-instance-td5054729.html. Looks like curl and wget just closes connection.

**Comment by ghillert** [comment]
@markpollack @trisberg @sabbyanandan I cannot reproduce this issue. Locally I am using a self-signed certificate as described here: http://docs.spring.io/spring-cloud-dataflow/docs/1.2.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-security-self-signed-certificates-shell

Both **wget** and **curl** work fine:

* wget https://localhost:8443/ --no-check-certificate
* curl -i https://localhost:8443/ -k

**Comment by devlhl** [comment]
怎么没看到这个问题的原因及解决就被关闭了呢？
