### ISSUE TITLE
Update to Spring Boot 1.5.4

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-dataflow#1382]
The latest versions of `spring-data-commons` (> 1.13.3.RELEASE) which include a fix for [DATACMNS-1042](https://jira.spring.io/browse/DATACMNS-1042) (Self link created with pagination request parameters) in https://github.com/spring-projects/spring-data-commons/commit/a8ff4ea1429f8a4c42df2030d7ab9ccc0d742b12 will break certain controllers using the `PagedResourcesAssembler` in `spring-cloud-dataflow-server-core`.

For example, the following exception would be thrown (using the local server for testing) when requesting http://localhost:9393/apps:

```
2017-04-22 22:24:45.941 ERROR 2253 --- [nio-9393-exec-8] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.IllegalArgumentException: Page size must not be less than one!
	at org.springframework.data.domain.AbstractPageRequest.<init>(AbstractPageRequest.java:47) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.data.domain.PageRequest.<init>(PageRequest.java:63) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.data.web.PagedResourcesAssembler.addPaginationLinks(PagedResourcesAssembler.java:222) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.data.web.PagedResourcesAssembler.createResource(PagedResourcesAssembler.java:205) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.data.web.PagedResourcesAssembler.toResource(PagedResourcesAssembler.java:115) ~[spring-data-commons-1.13.3.RELEASE.jar:na]
	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.list(AppRegistryController.java:...) ~[classes/:na]
...
```

This issue arises when upgrading to Spring Boot 1.5.3 which includes `spring-data-commons:1.13.3.RELEASE`. While not an issue for the current release it will be an issue in future.

**Comment by trisberg** [comment]
This really should go with an upgrade of the spring-cloud-build and spring-cloud version, we are now on spring-cloud-build 1.3.1/spring-cloud Dalston.RELEASE which uses Boot 1.5.2.

**Comment by donovanmuller** [comment]
Understood 👍  I assumed that the explicit reference [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/pom.xml#L34) here could allow for overriding.

The issue related to `spring-data-commons` discussed in the PR is actually more important (or will be in future). I'll revert the Boot version bump and change the issue description to reflect this...

**Comment by spencergibb** [comment]
Here is another issue with the dataflow server 1.1.4 and boot 1.5.3 https://github.com/spring-cloud/spring-cloud-cli/issues/61

**Comment by trisberg** [comment]
We can update to spring-cloud-build 1.3.2 which brings in spring-boot 1.5.3 and apply needed pagination fixes

**Comment by sabbyanandan** [comment]
The plan is to rework this issue by upgrading to Spring Boot 1.5.4 _(scheduled: [June 8th](https://github.com/spring-projects/spring-boot/milestone/86))_ and resolve the pagination problems via [spring-cloud/spring-cloud-dataflow#1397](https://github.com/spring-cloud/spring-cloud-dataflow/issues/1397) as well as the [spring-cloud-cli](https://github.com/spring-cloud/spring-cloud-cli/issues/61) side effects.

**Comment by sabbyanandan** [comment]
[1.5.4](https://spring.io/blog/2017/06/08/spring-boot-1-5-4-available-now) is available now.
