### ISSUE TITLE
StreamDefinitionController.save(..) results in java.lang.IllegalStateException if invoked outside of MVC

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-dataflow#1462]
```
Exception in thread "main" java.lang.IllegalStateException: Could not find current request via RequestContextHolder. Is this being called from a Spring MVC handler?
    at org.springframework.util.Assert.state(Assert.java:70)
    at org.springframework.hateoas.mvc.ControllerLinkBuilder.getCurrentRequest(ControllerLinkBuilder.java:291)
    at org.springframework.hateoas.mvc.ControllerLinkBuilder.getBuilder(ControllerLinkBuilder.java:265)
    at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:124)
    at org.springframework.hateoas.mvc.ResourceAssemblerSupport.createResourceWithId(ResourceAssemblerSupport.java:90)
    at org.springframework.hateoas.mvc.ResourceAssemblerSupport.createResourceWithId(ResourceAssemblerSupport.java:81)
    at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController$Assembler.toResource(StreamDefinitionController.java:377)
    at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.save(StreamDefinitionController.java:205)
    at olegz.dataflow.SomeDemo.main(SomeDemo.java:41)
```
Since MVC controllers by design must be executable outside of any Web infrastructure (i.e., testing) their execution should not result in exceptions pointing to the fact that they were executed outside of Web infrastructure.
In this particular case, the exception is well understood, since the `save(..)` operation was indeed invoked directly. Further more it did not affect anything in the flow. Every stream and the entire flow was running successfully, so in its current state it's more of a nuisance-type bug which IMHO should be easily fixed with WARN logging, thus preserving the intent of notifying user.

**Comment by olegz** [comment]
With the applied fix the user will see the following in their logs:
```
Failed to create StreamDefinitionResource. Could not find current request via RequestContextHolder. Is this being called from a Spring MVC handler?
```

**Comment by ilayaperumalg** [comment]
Can we make this into `1.2.0.RELEASE` given we just released RC now?

**Comment by olegz** [comment]
@ilayaperumalg  We probably can, I put 1.2.1 based on suggestion from @markpollack when we briefly chatted about it on slack
