### ISSUE TITLE
Cannot load driver class: com.microsoft.sqlserver.jdbc.SQLServerDriver

### ISSUE THREAD

**Issue by rroyhere** [spring-cloud/spring-cloud-dataflow#1535]
Created one stream like below to extract data from SQL server but getting cannot load driver class Cannot load driver class: com.microsoft.sqlserver.jdbc.SQLServerDriver. Can you please point which specific driver should we use or any other change?

jdbc --max-rows-per-poll=2000 --query='select SOURCE_GENERIC_TYPE, SOURCE_OWNER, SOURCE_SUBMITTER from Table_Name' --password=***** --driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver --username=**** --url='jdbc:sqlserver://hostname:14440;databaseName=dbname' | ncd-hdfs: hdfs --fs-uri=hdfs://hostname:port --file-name=ncd --directory=/tmp/hdfs/someDire

Error:
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 39 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot load driver class: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at org.springframework.util.Assert.state(Assert.java:70) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]

**Comment by sabbyanandan** [comment]
Hi, @rroyhere. This is an application specific problem; going forward, please consider asking questions like this either in [StackOverflow](https://stackoverflow.com/questions/tagged/spring-cloud-dataflow) or in the app specific repo _(in this case, [spring-cloud-stream-app-starters/jdbc](https://github.com/spring-cloud-stream-app-starters/jdbc/issues))_. 

That said, we _only_ [pre-package](http://docs.spring.io/spring-cloud-dataflow/docs/1.2.1.RELEASE/reference/htmlsingle/#configuration-rdbms) OSS/license-friendly database drivers. For proprietary drivers (e.g., SQLServer), you'll have to manually [patch](http://docs.spring.io/spring-cloud-stream-app-starters/docs/Bacon.RELEASE/reference/html/_introduction.html#_patching_pre_built_applications) the OOTB `jdbc-source` to interact with SQLServer.  There's [spring-cloud-stream-app-starters/jdbc#10](https://github.com/spring-cloud-stream-app-starters/jdbc/issues/10) to bundle the oss-friendly driver, but we haven't gotten to it yet - contributions welcome!
