### ISSUE TITLE
Embedded H2 is not allowing tasks to connect

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1628]
Tested 1.2.2, 1.2.1 of task against SCDF 1.3.0.BUILD-SNAPSHOT.
When testing against MySQL DB it works fine.
When testing against H2, the task blocks waiting to connect to h2 database. To verify that SCDF was an issue I attempted to connect to H2 via SQuirreL and it blocked as well.

(The reason you see an empty task execution record is that SCDF creates a empty task execution record prior to launching the task, and then passes the task-execution-id as a parameter to the task.)

**Comment by jvalkeal** [comment]
Maybe worth to check how I'm configuring H2 on ambari which is started as an external process. https://github.com/spring-cloud/spring-cloud-dataflow-server-yarn/blob/master/spring-cloud-dataflow-server-yarn-h2/src/main/java/org/springframework/cloud/dataflow/yarn/h2/H2ServerConfiguration.java

**Comment by cppwfs** [comment]
In this case the task needs to be able to reach the H2 embedded in the dataflow.  This used to work.   Not sure what changed.  But when I try to connect to the H2 within dataflow it fails.

**Comment by cppwfs** [comment]
This looks like a H2 version issue.  If you are running the current task starters they are currently using H2 version 1.4.192 and fail to connect to the embedded H2 (1.4.195) in Data Flow.  To test this I built the current version of timestamp and ran it (with DB properties pointing the Data Flow H2 embedded DB) and it failed.  Once Updating the H2 dependency it was able to connect.

Keep in mind the task starters are still using Spring Cloud Build 1.1.1.RELEASE while Data Flow is on 1.3.3.RELEASE.

**Comment by mminella** [comment]
Why are the task starters so far behind on the Spring Cloud Build version?

**Comment by cppwfs** [comment]
I removed the comment on the build version, I was looking at the old repo.

**Comment by cppwfs** [comment]
Also after updating the DB-Driver to 1.4.195 SQuirreL now also connects.

**Comment by cppwfs** [comment]
IMHO the proper solution is to update the versions in the Task Starters (which is due next week).  And add a note to the documentation on the H2 version issue.  Thoughts?

**Comment by jvalkeal** [comment]
ok, server have `h2-1.4.195.jar` and timestamp have `h2-1.4.192.jar`. I get error with 192 but 195 against local server embedded H2 works fine.
```
$ java -cp ./h2-1.4.192.jar org.h2.tools.Shell -url jdbc:h2:tcp://localhost:19092/mem:dataflow -user sa

Welcome to H2 Shell 1.4.192 (2016-05-26)
Exit with Ctrl+C
Commands are case insensitive; SQL statements end with ';'
help or ?      Display this help
list           Toggle result list / stack trace mode
maxwidth       Set maximum column width (default is 100)
autocommit     Enable or disable autocommit
history        Show the last 20 statements
quit or exit   Close the connection and exit

sql> show tables;
Error: org.h2.jdbc.JdbcSQLException: Connection is broken: "unexpected status 16777216" [90067-192]
```

**Comment by jvalkeal** [comment]
I compiled timestamp with 195 and it now works. IMHO, if task cannot do its thing with a DB, task itself should fail-fast and not silently bury error in a debug logs.

**Comment by cppwfs** [comment]
I tested with debug enabled on the timestamp starter and no exception was shown in the log.    However I tested with the timestamp sample from Task 2.0 (Boot 2.0) and it failed fast.

**Comment by sabbyanandan** [comment]
In Clark release-train, all the task apps are now at `h2-1.4.196`. If we continue to have issues with this H2 version, please reopen it.

**Comment by rdegracia** [comment]
@sabbyanandan 
even with 1.4.196, its failing... i tried below jar to be deployed as docker image in scdf kubernetes

https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples/batch-job

Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): localhost:19092" [90067-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:168) ~[h2-1.4.196.jar!/:na]
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:457) ~[h2-1.4.196.jar!/:na]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:334) ~[h2-1.4.196.jar!/:na]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116) ~[h2-1.4.196.jar!/:na]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100) ~[h2-1.4.196.jar!/:na]
	at org.h2.Driver.connect(Driver.java:69) ~[h2-1.4.196.jar!/:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-3.2.0.jar!/:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-3.2.0.jar!/:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157) ~[spring-jdbc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) ~[spring-jdbc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) ~[spring-jdbc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	... 78 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111-internal]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111-internal]
	at org.h2.util.NetUtils.createSocket(NetUtils.java:103) ~[h2-1.4.196.jar!/:na]
	at org.h2.util.NetUtils.createSocket(NetUtils.java:83) ~[h2-1.4.196.jar!/:na]
	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:115) ~[h2-1.4.196.jar!/:na]
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:453) ~[h2-1.4.196.jar!/:na]
	... 92 common frames omitted
