### ISSUE TITLE
Redisconnection failure exception recieved when trying to run SCDF server in docker container

### ISSUE THREAD

**Issue by prigya** [spring-cloud/spring-cloud-dataflow#1635]
we are trying to run scdf serorg.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:204) ~[spring-data-redis-1.8.4.RELEASE.jar!/:na]
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:348) ~[spring-data-redis-1.8.4.RELEASE.jar!/:na]
        at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:129) ~[spring-data-redis-1.8.4.RELEASE.jar!/:na]
        at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:92) ~[spring-data-redis-1.8.4.RELEASE.jar!/:na]
        at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:79) ~[spring-data-redis-1.8.4.RELEASE.jar!/:na]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:194) [spring-data-redis-1.8.4.RELEASE.jar!/:na]
        at org.springframework.analytics.retry.RedisRetryTemplate.access$101(RedisRetryTemplate.java:34) [spring-analytics-1.1.3.RELEASE.jar!/:na]
        at org.springframework.analytics.retry.RedisRetryTemplate$1.doWithRetry(RedisRetryTemplate.java:70) ~[spring-analytics-1.1.3.RELEASE.jar!/:na]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:286) [spring-retry-1.2.0.RELEASE.jar!/:na]ver in docker container. using docker-compose to bring up containers for redis, rabbitMQ and scdf with scdf server linking the other two containers. but we are facing this redisconnectionfailture exception .

**Comment by sabbyanandan** [comment]
Hi, @prigya. If you aren't using any of the [analytics-counters](https://docs.spring.io/spring-cloud-dataflow/docs/1.2.3.RELEASE/reference/htmlsingle/#arch-analytics), you can safely disable this feature via: `spring.cloud.dataflow.features.analytics-enabled` [feature-toggle](https://docs.spring.io/spring-cloud-dataflow/docs/1.2.3.RELEASE/reference/htmlsingle/#enable-disable-specific-features). 

Even after disabling, if you still see issues, feel free to post an update with more details. I'll close this for now.

**Comment by prigya** [comment]
Hi..

The aim is to do analytics stuff  using SCDF , hence was trying to fix this issue. However, we were trying to run SCDF and redis both in docker container . Redis was running fine, even scdf streams  ( non-alaytics streams) were running fine , but somehow redis connection to scdf server was giving above issues. however when i run Redis, rabbitmq/kafka in docker containers and run SCDF server as a normal jar process, everything works perfect, even the analytics streams! 

Let me know if there is any help on running scdf server within docker conatiner as well ( even for anaytics streams i.e. using redis) .

**Comment by trisberg** [comment]
How did you create the docker container and how did you launch it? What configuration options for the database andredis did you use?

**Comment by prigya** [comment]
i'm using below docker compose for redis, rabbitmq, scdf : 

version: '3'

services:
 redis:
  image: redis
  expose:
    - "6379"
 rabbitmq:
  image: rabbitmq
  expose:
    - "4369"
    - "5671"
    - "5672"
    - "25672"
 spring-flow:
  image: somospnt/spring-cloud-data-flow-docker
  env_file:
    - enviroment
  ports:
    - "9393:9393"
    - "7000-7010:7000-7010"
  volumes:
    - /tmp/spring-flow/logs:/tmp/spring-flow/logs
  links:
    - redis
    - rabbitmq

**Comment by trisberg** [comment]
What's in the `enviroment` env file?

**Comment by prigya** [comment]
This  file just has rabbitmq related env variables : 


spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.host=rabbitmq
spring.cloud.deployer.local.envVarsToInherit=spring.rabbitmq.username,spring.rabbitmq.password,spring.rabbitmq.host

**Comment by prigya** [comment]
Docker file 

FROM nimmis/java-centos
RUN mkdir -p /tmp/spring-flow/logs
VOLUME /tmp/spring-flow/logs
EXPOSE 7000-7010
RUN wget -O app.jar http://repo.spring.io/release/org/springframework/cloud/spring-cloud-dataflow-server-local/1.2.3.RELEASE/spring-cloud-dataflow-server-local-1.2.3.RELEASE.jar
ENV JAVA_OPTS="-Djava.io.tmpdir=/tmp/spring-flow/logs"

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar ./app.jar" ]

**Comment by trisberg** [comment]
I think you would need a `spring.redis.host=redis` entry in the environment

**Comment by prigya** [comment]
even if i add above to the env settings, still on deploying an analytics stream , getting the same error : 
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.util.Pool.getResource(Pool.java:50) ~[jedis-2.7.3.jar!/:na]
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:99) ~[jedis-2.7.3.jar!/:na]
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:12) ~[jedis-2.7.3.jar!/:na]
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:155) ~[spring-data-redis-1.6.4.RELEASE.jar!/:na]
        ... 90 common frames omitted

**Comment by sabbyanandan** [comment]
Closing this due to no activity.
