### ISSUE TITLE
Strange problem 

### ISSUE THREAD

**Issue by rut78HR** [spring-cloud/spring-cloud-dataflow#1667]
until yesterday everything was working OK. now a common task does not work anymore
I use local server 1.3.0.M2 and create simple stream

`dataflow:>stream create --name test --definition ":bosstds > log" --deploy`

til yesterday this was working as expeted. but now i got this in log 

> 2017-09-28 12:31:00.644  INFO 5156 --- [           -C-1] o.a.k.c.c.internals.AbstractCoordinator  : Successfully joined group test with generation 1
2017-09-28 12:31:00.646  INFO 5156 --- [           -C-1] o.a.k.c.c.internals.ConsumerCoordinator  : Setting newly assigned partitions [bosstds-0] for group test
2017-09-28 12:31:00.671  INFO 5156 --- [           -C-1] o.s.c.s.b.k.KafkaMessageChannelBinder$3  : partitions assigned:[bosstds-0]
2017-09-28 12:37:08.898 ERROR 5156 --- [           -L-1] o.s.c.s.b.k.KafkaMessageChannelBinder    : Could not convert message: 74657374
java.lang.StringIndexOutOfBoundsException: String index out of range: 103
	at java.lang.String.checkBounds(String.java:385) ~[na:1.8.0_144]
	at java.lang.String.<init>(String.java:425) ~[na:1.8.0_144]
	at org.springframework.cloud.stream.binder.EmbeddedHeaderUtils.oldExtractHeaders(EmbeddedHeaderUtils.java:154) ~[spring-cloud-stream-1.3.0.M2.jar!/:1.3.0.M2]
	at org.springframework.cloud.stream.binder.EmbeddedHeaderUtils.extractHeaders(EmbeddedHeaderUtils.java:115) ~[spring-cloud-stream-1.3.0.M2.jar!/:1.3.0.M2]

message is produced with   kafka-console-producer.sh  --broker-list localhost:9092 --topic bosstds  and simply send line "test" 

any suggestions ?

**Comment by sabbyanandan** [comment]
This has been addressed via: https://stackoverflow.com/questions/46482605/spring-cloud-dataflow-input-source-kafka.
