### ISSUE TITLE
[QUESTION]Can't Restart Job on version 1.2.3 

### ISSUE THREAD

**Issue by guichafy** [spring-cloud/spring-cloud-dataflow#1792]
When I try to restart my job i received this exception: 

`Caused by: java.lang.IllegalStateException: Cannot load driver class: org.h2.Driver,org.h2.Driver
	at org.springframework.util.Assert.state(Assert.java:70) ~[spring-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:232) ~[spring-boot-autoconfigure-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.initializeDataSourceBuilder(DataSourceProperties.java:184) ~[spring-boot-autoconfigure-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:42) ~[spring-boot-autoconfigure-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Tomcat.dataSource(DataSourceConfiguration.java:56) ~[spring-boot-autoconfigure-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_144]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	... 49 common frames omitted
`

**Comment by guichafy** [comment]
**Obs: At version 1.1.4 there's working**

**Comment by sabbyanandan** [comment]
It'd be great if you can share more details (see [here](https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Reporting-Issues)) about your setup and how you're trying to do the restarts.

**Comment by guichafy** [comment]
Sure, I'm using Spring cloud dataflow local version 1.2.3 on java 1.8 and  i'm not using the Shell, just the interface web.

First step: I go to the "JOBS" tab.
Second step:  I start a job.
Third  step: I stop the job.
Fourth step: I try restart the job, but happen this exception:

> Caused by: java.lang.IllegalStateException: Cannot load driver class: 
Observation: The same job running in at version 1.1.4 wok.

Sorry for my English, if necessary i try to write otherwise.

**Comment by cppwfs** [comment]
Hello @guichafy 
We need some more data from your side.  Please review the link shared by @sabbyanandan https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Reporting-Issues[here] and give us a few more details on your current versions etc. 
As a background using the current snapshot of Data Flow I was able to run the following:
1) Run a Job
2) Rerun the  Job with different parameters 
3) Run a job with same parameters and it fail with the appropriate exception
4) Run a job that failed
5) Restart the failed job and let it complete successfully
This was tested on both H2 and MySql, and thus was not able to reproduce your issue.  So if you can provide a small test app that reproduces your problem, we can take a peak.
 
Also keep in mind a job that is `stopped` can not be restarted.  This is currently not supported in Spring Batch.  But has been discussed as to be added in a future release.

**Comment by cppwfs** [comment]
I was able to reproduce the problem when rerunning the job from the UI.  If you run the same task (with the same parameters) from the shell this does not occur (it will rerun the same job).  I've opened issue: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1801

**Comment by guichafy** [comment]
Thank you for your quick answer, in case you need anything, I'm at your disposal.

**Comment by sabbyanandan** [comment]
This will be addressed in https://github.com/spring-cloud/spring-cloud-dataflow/issues/1800 (#1801 is invalid).
