### ISSUE TITLE
Can't register apps on Skipper mode

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#1959]
```
dataflow:>app import --uri http://bit.ly/Celsius-SR1-stream-applications-rabbit-maven 
Error when registering applications from http://bit.ly/Celsius-SR1-stream-applications-rabbit-maven: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

```

From the server side:
```
2018-01-19 10:45:29.146 ERROR 94890 --- [nio-9393-exec-6] o.h.engine.jdbc.spi.SqlExceptionHelper   : NULL not allowed for column "ID"; SQL statement:
insert into app_registration (id, object_version, default_version, metadata_uri, name, type, uri, version) values (null, ?, ?, ?, ?, ?, ?, ?) [23502-196]
2018-01-19 10:45:29.150 ERROR 94890 --- [nio-9393-exec-6] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:278) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:503) ~[spring-orm-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
```

**Comment by ilayaperumalg** [comment]
Looks like [this](https://github.com/spring-cloud/spring-cloud-dataflow/commit/61a206c80fd7c8a3c788910fdc79dc941c0a9f84) change broke it

**Comment by ilayaperumalg** [comment]
Specifically the following change in `local` server seems to have caused the issue:

```
spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
```

**Comment by viniciusccarvalho** [comment]
Actually we need to remove the generate-ddl, the real problem is that we are missing `spring.jpa.properties.hibernate.id.new_generator_mappings=true` in order to tell hibernate to use a sequence table for mysql, or even sequences for that matter. Just adding that would solve the issue.
