### ISSUE TITLE
Can not deploy stream when disk space is below LRUResourceLoader disk percentage threshold

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2072]
There have been a few ad-hoc reports of not being able to deploy a stream due to what looks like a corrupt jar file. 

```
I am using Celsius-SR1-stream-applications-rabbit-maven and SCDF 1.3.1. Any suggestions?

Exception in thread "AMQP Connection 127.0.0.1:5672" java.lang.NoClassDefFoundError: com/rabbitmq/client/impl/SocketFrameHandler$1
    at com.rabbitmq.client.impl.SocketFrameHandler.close(SocketFrameHandler.java:185)
    at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:680)
    at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:577)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.rabbitmq.client.impl.SocketFrameHandler$1
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 4 more
I am also using RabbitMQ 3.7.3
java version "1.8.0_144"```

is probably an example of this.  There is 4% free (22GB) on the disk)

**Comment by markpollack** [comment]
We have removed use of the LRUResourceLoader , it was getting too complicated to manage and also, inadvertently, it was not used on CF since version 1.3.  Updated docs for CF (where it is mostly an issue) to indicate using the health check type `http` to take into account the disk space health indicator.

**Comment by markpollack** [comment]
closing as invalid
