### ISSUE TITLE
Url versioning doesn't work with skipper

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#2082]
```
dataflow:>app register --name log --type sink --uri http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/log-sink-rabbit/1.1.0.RELEASE/log-sink-rabbit-1.1.0.RELEASE.jar
dataflow:>app register --name time --type source --uri http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/time-source-rabbit/1.1.1.RELEASE/time-source-rabbit-1.1.1.RELEASE.jar
dataflow:>app register --name log --type sink --uri http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/log-sink-rabbit/1.1.1.RELEASE/log-sink-rabbit-1.1.1.RELEASE.jar
dataflow:>stream create --name foostream --definition "time|log"

dataflow:>stream deploy --name foostream
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: URL resource with version as part of its path is not supported.


java.lang.IllegalArgumentException: URL resource with version as part of its path is not supported.
	at org.springframework.util.Assert.isTrue(Assert.java:92) ~[spring-core-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.cloud.dataflow.registry.support.ResourceUtils.getUrlResourceWithoutVersion(ResourceUtils.java:61) ~[spring-cloud-dataflow-registry-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.registry.support.ResourceUtils.getResourceWithoutVersion(ResourceUtils.java:204) ~[spring-cloud-dataflow-registry-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.createDependentPackage(SkipperStreamDeployer.java:340) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.createDependentPackages(SkipperStreamDeployer.java:313) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.createPackage(SkipperStreamDeployer.java:305) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.createPackageForStream(SkipperStreamDeployer.java:280) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.deployStream(SkipperStreamDeployer.java:201) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]

```

**Comment by ilayaperumalg** [comment]
I thought we ran into an issue parsing through the version as part the URL path for the UrlResource. Looking at this again, it doesn't seem so. Will submit a PR on this.
