### ISSUE TITLE
CTR DSL with blank  characters in child task arguments can't be parsed.

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#2114]
Hello
I'm trying to create CTR in dashboard with below DSL:
```
timestamp && ct-etl-results-uploader --targetDB.datasource.initSQL='set search_path to asp_integration;'
```
The `'` characters  was added automatically.

Server replies with below exception :
```
2018-03-20 10:13:08.105 ERROR 13240 --- [nio-9393-exec-6] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

org.springframework.cloud.dataflow.core.dsl.CheckPointedParseException: 163E:(pos 58): after parsing a valid task, there is still more data: 'search_path'
ct-etl-results-uploader --targetDB.datasource.initSQL=set search_path to asp_integration;
                                                         *^

        at org.springframework.cloud.dataflow.core.dsl.Tokens.raiseException(Tokens.java:276) ~[spring-cloud-dataflow-core-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.cloud.dataflow.core.dsl.TaskParser.parse(TaskParser.java:81) ~[spring-cloud-dataflow-core-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.cloud.dataflow.core.TaskDefinition.<init>(TaskDefinition.java:53) ~[spring-cloud-dataflow-core-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskService.lambda$saveTaskDefinition$6(DefaultTaskService.java:330) ~[spring-cloud-dataflow-server-core-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_144]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_144]
        at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskService.saveTaskDefinition(DefaultTaskService.java:325) ~[spring-cloud-dataflow-server-core-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
```

Creating the CTR with just single step `ct-etl-results-uploader --targetDB.datasource.initSQL='set search_path to asp_integration;'` works OK.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#694
