### ISSUE TITLE
Loading stream-list from the UI/Shell fails with IllegalArgumentException

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2185]
As a user, I'm attempting to view the deployed streams from the Shell/UI; however, I get the `IllegalArgumentException` and the page won't load.

Stream:
```
tweets = twitterstream --consumer-key= --consumer-secret= --access-token= --access-token-secret= | filter --expression=#jsonPath(payload,'$.lang')=='en' | twitter-sentiment --vocabulary=http://dl.bintray.com/big-data/generic/vocab.csv --model-fetch=output/Softmax --model=http://dl.bintray.com/big-data/generic/minimal_graph.proto | field-value-counter --field-name=sentiment --name=sentiment
```

Shell:
```
dataflow:>stream list
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Illegal group reference
```

UI:
![image](https://user-images.githubusercontent.com/1562654/39631135-3ae9a4ec-4f66-11e8-8dbb-f3057b3e5032.png)

Error:
```
  2018-05-04T06:41:49.39-0700 [RTR/6] OUT
   2018-05-04T06:41:49.40-0700 [APP/PROC/WEB/0] OUT 2018-05-04 13:41:49.406 ERROR 15 --- [io-8080-exec-10] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
   2018-05-04T06:41:49.40-0700 [APP/PROC/WEB/0] OUT java.lang.IllegalArgumentException: Illegal group reference
   2018-05-04T06:41:49.40-0700 [APP/PROC/WEB/0] OUT 	at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[na:1.8.0_162]
   2018-05-04T06:41:49.40-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.support.ArgumentSanitizer.sanitizeStream(ArgumentSanitizer.java:138) ~[spring-cloud-dataflow-server-core-1.5.0.BUILD-SNAPSHOT.jar!/:1.5.0.BUILD-SNAPSHOT]
   2018-05-04T06:41:49.40-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController$Assembler.instantiateResource(StreamDefinitionController.java:250) ~[spring-cloud-dataflow-server-core-1.5.0.BUILD-SNAPSHOT.jar!/:1.5.0.BUILD-SNAPSHOT]
   2018-05-04T06:41:49.40-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController$Assembler.instantiateResource(StreamDefinitionController.java:225) ~[spring-cloud-dataflow-server-core-1.5.0.BUILD-SNAPSHOT.jar!/:1.5.0.BUILD-SNAPSHOT]
   2018-05-04T06:41:49.40-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.hateoas.mvc.ResourceAssemblerSupport.createResourceWithId(ResourceAssemblerSupport.java:89) ~[spring-hateoas-0.23.0.RELEASE.jar!/:na]
```

**Comment by sabbyanandan** [comment]
The stream destroy command won't delete the apps after this error.
