### ISSUE TITLE
Duplicate JobInstance ids created for Tasks

### ISSUE THREAD

**Issue by noahmonster** [spring-cloud/spring-cloud-dataflow#2206]
Hi,

I am using the Dataflow server to execute some Spring Cloud Tasks.  I wrote a custom TaskLauncher/taskDeployer to run these Tasks on Singularity.  Running the tasks from the Dataflow UI seems to work fine.  It also seems to work fine when I fire a single request at the API to create a task execution.  However, when I fire 10 requests to create task executions at the API in rapid succession, something very strange is happening to my Tasks.

It appears that the Dataflow server is not properly incrementing the JobInstance ids that it uses when a task creates a new execution.  This results in the following exception:

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.oracle.odc.hello.Application.main(Application.java:10) [sb-batch-docker-test-1.0.0-11.jar:na]
Caused by: org.springframework.batch.core.repository.JobExecutionAlreadyRunningException: A job execution for this job is already running: JobInstance: id=27, version=0, Job=[importUserJob]
	at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:120) ~[spring-batch-core-4.0.1.RELEASE.jar:4.0.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:181) ~[spring-batch-core-4.0.1.RELEASE.jar:4.0.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.sun.proxy.$Proxy44.createJobExecution(Unknown Source) ~[na:na]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:131) ~[spring-batch-core-4.0.1.RELEASE.jar:4.0.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127) ~[spring-batch-core-4.0.1.RELEASE.jar:4.0.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at com.sun.proxy.$Proxy54.run(Unknown Source) ~[na:na]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.execute(JobLauncherCommandLineRunner.java:163) ~[spring-boot-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.executeLocalJobs(JobLauncherCommandLineRunner.java:179) ~[spring-boot-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.launchJobFromProperties(JobLauncherCommandLineRunner.java:134) ~[spring-boot-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.run(JobLauncherCommandLineRunner.java:128) ~[spring-boot-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
```
I suspect that the bug here is actually caused in the code that is creating new task executions rather than somewhere in this stacktrace.

I used a simple bash script to fire off the requests in quick succession:

```
#!/bin/bash

for value in {1..10}
do
echo Firing $value
curl -X POST \
  http://my-dataflow-server/tasks/executions \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d name=myTaskName
done

echo "All done"
```

**Comment by cppwfs** [comment]
In this case it looks like you are running the same job multiple times without making it unique.  i.e. to make a Job unique you must change the identifying parameters or add a Incrementer (RunIdIncrementer) to your job.

**Comment by sabbyanandan** [comment]
Hi, @noahmonster. Thanks for the issue. Could you update it with the versions in use? See the [wiki](https://github.com/spring-cloud/spring-cloud-dataflow#reporting-issues) for more details. 

That said, we have recently improved the transactions support for task/job launch and execution endpoints via spring-cloud/spring-cloud-dataflow#2181. With that in the [1.5 RC1](http://docs.spring.io/spring-cloud-dataflow/docs/1.5.0.RC1/reference/htmlsingle/#getting-started) version, I've attempted to launch the OOTB `timestamp-batch` App using your script with a slight modification. You're likley hitting a race condition in the current SCDF version in use. 

Here's the script:
```
#!/bin/bash

for value in {1..10}
do
echo Firing $value
curl -X POST \
  http://localhost:9393/tasks/executions \
  -d 'name=myTaskName&arguments=foo='$value
done

echo "All done"
```

_(Since it is a batch-job, I've had to make the job launches unique by passing a unique-value via Task arsgs. I've used your `$value` to make it unique)_

**All of the launches were succesful.**

![image](https://user-images.githubusercontent.com/1562654/39942178-8db65e2e-5513-11e8-8083-f9f8431b5767.png)

Try out the 1.5RC1 and let us know if you still see any other anomalies.

**Comment by noahmonster** [comment]
@sabbyanandan 

Thanks for the quick reply.  We're using 1.4.0.RELEASE.  I'll update to 1.5 RC1 and give it a try.

**Comment by noahmonster** [comment]
Still getting the same exception on 1.5 RC1.

**Comment by noahmonster** [comment]
@cppwfs It looks like there is a `run.id` parameter being injected into my Task by the dataflow server.

![screen shot 2018-05-11 at 1 58 45 pm](https://user-images.githubusercontent.com/975308/39944319-767d50d6-5523-11e8-8b8d-35d43863ac1e.png)

**Comment by sabbyanandan** [comment]
Not sure what your Task is doing. Maybe you can try to make the `timestamp-batch` work first. 

1) create a definition 
2) launch with your script, but make sure you pass unique k/v pair args to each subsequent launches

Unless and until you make the job launches unique, it will fail.

**Comment by cppwfs** [comment]
@noahmonster I was able to reproduce the issue that you are discussing.   But this is not a Data Flow issue but rather a Spring Batch issue.   You can reproduce the same result by taking your script and running the app vs. issuing a curl request again Data Flow.   They may recommend you writing your own incrementer vs using the RunIdIncrementer, but I'll defer to their judgement.
