### ISSUE TITLE
Skipper Mode Stream Deployment or Update issues

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-dataflow#2211]
org.springframework.cloud.dataflow.server.config.OAuth2AccessTokenProvidingClientHttpRequestInterceptor.intercept(OAuth2AccessTokenProvidingClientHttpRequestInterceptor.java:67) ~[spring-cloud-dataflow-server-core-1.5.0.RC1.jar!/:1.5.0.RC1]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:88) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:72) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660) ~[spring-web-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
	... 124 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111-internal]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111-internal]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111-internal]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.5.jar!/:4.5.5]
	... 143 common frames omitted

**Comment by sabbyanandan** [comment]
Hi, @mv78. This report is incomplete (please refer to [wiki](https://github.com/spring-cloud/spring-cloud-dataflow#reporting-issues)). Could you take a moment to describe what you're trying to do?

**Comment by mv78** [comment]
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server-kubernetes",
      "version": "1.5.0.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "1.5.0.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "1.5.0.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "1.5.0.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.5.0.RELEASE/spring-cloud-dataflow-shell-1.5.0.RELEASE.jar"
    }
  },
  "featureInfo": {
    "analyticsEnabled": true,
    "streamsEnabled": true,
    "tasksEnabled": true,
    "skipperEnabled": true
  },
  "securityInfo": {
    "isAuthenticationEnabled": true,
    "isAuthorizationEnabled": true,
    "isFormLogin": true,
    "isAuthenticated": true,
    "username": "user",
    "roles": [
      "ROLE_CREATE",
      "ROLE_VIEW"
    ]
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "1.0.4.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "1.0.4.RELEASE",
      "javaVersion": "1.8.0_111-internal",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "1.5.12.RELEASE",
      "springVersion": "4.3.16.RELEASE"
    },
    "taskLauncher": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "1.3.4.RELEASE",
      "deployerName": "KubernetesTaskLauncher",
      "deployerSpiVersion": "1.3.2.RELEASE",
      "javaVersion": "1.8.0_111-internal",
      "platformApiVersion": "v1",
      "platformClientVersion": "unknown",
      "platformHostVersion": "unknown",
      "platformType": "Kubernetes",
      "springBootVersion": "1.5.12.RELEASE",
      "springVersion": "4.3.16.RELEASE"
    }
  }
}
