### ISSUE TITLE
Unable to start Task from Stream with task‑launcher‑local‑sink‑kafka

### ISSUE THREAD

**Issue by simasch** [spring-cloud/spring-cloud-dataflow#2257]
There seems to be a version mismatch.
The current TasklauncherSink method signature is:
`taskLauncherSink(TaskLaunchRequest request)`

```
2018-06-08 13:28:42.161 ERROR 318 --- [           -L-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method taskLauncherSink(java.lang.String) cannot be found on org.springframework.cloud.task.launcher.TaskLauncherSink$$EnhancerBySpringCGLIB$$9964b14f type, failedMessage=GenericMessage [payload=06/08/18 13:28:38, headers={kafka_offset=0, id=055894f5-43b1-1705-44a4-1ee0bc9de2f8, kafka_receivedPartitionId=0, contentType=text/plain, kafka_receivedTopic=time-to-v002.time, timestamp=1528464522147}]
        at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:96)
        at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:89)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:148)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:121)
        at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:89)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:425)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:375)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:360)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:271)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:188)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70)
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:188)
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$200(KafkaMessageDrivenChannelAdapter.java:63)
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:372)
        at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:352)
        at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:79)
        at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter$1.doWithRetry(RetryingAcknowledgingMessageListenerAdapter.java:73)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
        at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:73)
        at org.springframework.kafka.listener.adapter.RetryingAcknowledgingMessageListenerAdapter.onMessage(RetryingAcknowledgingMessageListenerAdapter.java:39)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:792)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:736)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.access$2100(KafkaMessageListenerContainer.java:246)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$ListenerInvoker.run(KafkaMessageListenerContainer.java:1025)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method taskLauncherSink(java.lang.String) cannot be found on org.springframework.cloud.task.launcher.TaskLauncherSink$$EnhancerBySpringCGLIB$$9964b14f type
        at org.springframework.expression.spel.ast.MethodReference.findAccessorForMethod(MethodReference.java:212)
        at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:126)
        at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:50)
        at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:348)
        at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:132)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:360)
        at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:169)
        at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:319)
        at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:155)
        at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:93)
        ... 39 more
```
Im running the quick start from https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v1.5.0.RELEASE/spring-cloud-dataflow-server-local/docker-compose.yml
with DATAFLOW_VERSION=1.5.0.RELEASE using

**Comment by cppwfs** [comment]
What version of the task-launcher-local are you using?

**Comment by simasch** [comment]
1.3.1 is pre-installed in the docker image

**Comment by cppwfs** [comment]
Are you using the triggertask a source?  Or transforming the payload using tasklaunchrequest-transform to transform the payload prior to the tasklauncher-local?

**Comment by simasch** [comment]
No as sink. My stream is just a timer that should start a task with the task runner

**Comment by cppwfs** [comment]
Is your source or processor emitting a TaskLaunchRequest to the TaskLauncher-local?  i.e. A tasklauncher is a sink that consumes a TaskLaunchRequest message.  The task will use the --uri from the message to determine what artifact to deploy as well as the properties and arguments to execute the task.

**Comment by simasch** [comment]
Ah ok I see. Then I didn't use it correctly, I'm sorry about that. 
You can close the issue.
Is there an example how to start a task from a timer in a stream?

**Comment by cppwfs** [comment]
You can look at triggertask source as a way to send tasklaunchrequests  to the task launcher sink.
