### ISSUE TITLE
Bad error message when app resource does not exist.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2277]
given

```
dataflow:>app import --uri http://bit.ly/Celsius-SR3-stream-applications-rabbit-maven 

dataflow:>app register --name customLog --type sink --uri http://example.com/log.jar --force
dataflow:>stream create --name ticktock --definition "time | customLog" --deploy 
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: File /tmp/spring-cloud-deployer7977040175409109846/53c2def052b6377318f5faae705d5956f8e6693e must exist
```

The error message is not clear that the jar does not exist, it references some internal file.

Here is the stack trace

```java.lang.IllegalArgumentException: File /tmp/spring-cloud-deployer7977040175409109846/53c2def052b6377318f5faae705d5956f8e6693e must exist
	at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:68) ~[spring-cloud-dataflow-server-local-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:51) ~[spring-cloud-dataflow-server-local-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:83) ~[spring-cloud-dataflow-server-local-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61) ~[spring-cloud-dataflow-server-local-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57) ~[spring-cloud-dataflow-server-local-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.resolveAsArchive(BootApplicationConfigurationMetadataResolver.java:159) ~[spring-cloud-dataflow-configuration-metadata-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.listProperties(BootApplicationConfigurationMetadataResolver.java:96) ~[spring-cloud-dataflow-configuration-metadata-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.WhitelistProperties.qualifyProperties(WhitelistProperties.java:65) ~[spring-cloud-dataflow-server-core-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.cloud.dataflow.server.service.impl.AppDeploymentRequestCreator.mergeAndExpandAppProperties(AppDeploymentRequestCreator.java:308) ~[spring-cloud-dataflow-server-core-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.cloud.dataflow.server.service.impl.AppDeploymentRequestCreator.createRequests(AppDeploymentRequestCreator.java:208) ~[spring-cloud-dataflow-server-core-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.cloud.dataflow.server.service.impl.AppDeployerStreamService.doDeployStream(AppDeployerStreamService.java:75) ~[spring-cloud-dataflow-server-core-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
```

**Comment by tzolov** [comment]
Is this error description more informative: 
```
dataflow:>stream create --name ticktock --definition "time | customLog" --deploy
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Failed to resolve application resource: URL [http://example.com/log.jar], file [/var/folders/js/7b_pn0t575l790x7j61slyxc0000gn/T/spring-cloud-deployer1184533638652756250/53c2def052b6377318f5faae705d5956f8e6693e]
```
