### ISSUE TITLE
Boot2 - handle batch/task changes

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#2387]
We've customised some batch related features in boot and now this stuff is changed.

- [x] copy over minimal batch admin feature?

Child of #914

**Comment by jvalkeal** [comment]
@mminella @cppwfs What's your take on spring batch admin in dataflow? Either it needs to be replaced with something else or make compatible with framework 5.x.

**Comment by cppwfs** [comment]
Batch 4.0.1 has been updated to use Spring framework 5.x.

**Comment by cppwfs** [comment]
Yeah...  This will need to be replaced.  Because batch admin was put in the attic.

**Comment by jvalkeal** [comment]
While dataflow compiles I get runtime error:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskJobExecutionRepository' defined in class path resource [org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.class]: Unsatisfied dependency expressed through method 'taskJobExecutionRepository' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleJobServiceFactoryBean' defined in class path resource [org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:732) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:474) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
```
Not sure why this is not pulled in if it's requirement. Didn't look further as usually there's a high change that lib based on framework 4.x will anyway blow up with other errors.

**Comment by jvalkeal** [comment]
Ah right, xtreams used to come from batch itself.
