### ISSUE TITLE
schema initialization dosen`t work

### ISSUE THREAD

**Issue by findcoo** [spring-cloud/spring-cloud-dataflow#2389]
when use k8s servers and remote mysql server
```
STREAM_DEFINITIONS' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:177) ~[mariadb-java-client-2.2.5.jar!/:na]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110) ~[mariadb-java-client-2.2.5.jar!/:na]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228) ~[mariadb-java-client-2.2.5.jar!/:na]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216) ~[mariadb-java-client-2.2.5.jar!/:na]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150) ~[mariadb-java-client-2.2.5.jar!/:na]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:164) ~[mariadb-java-client-2.2.5.jar!/:na]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.1.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.1.0.jar!/:na]
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:698) ~[spring-jdbc-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639) ~[spring-jdbc-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
```
error occur
as above error, mysql schema doesn't exist except spring cloud task, spring cloud stream schema

**Comment by findcoo** [comment]
solve this issue, but there are still problem.
if database charset is utf8mb4, initialize sql script dosen't work cause key length limitation.
