### ISSUE TITLE
Upgrade MSSQL JDBC Driver to 7.0

### ISSUE THREAD

**Issue by AvijitGit** [spring-cloud/spring-cloud-dataflow#2403]
Hi,
Deploy a Spring Boot Application on local Spring cloud dataflow server.Registered a application and launch a Task through the shell, but getting the following error in the log file generated by the  Spring cloud dataflow server.

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springBatchConfiguration': Unsatisfied dependency expressed through field 'stepBuilderFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stepBuilders' defined in class path resource [org/springframework/batch/core/configuration/annotation/SimpleBatchConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.batch.core.configuration.annotation.StepBuilderFactory]: Factory method 'stepBuilders' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.task.configuration.SimpleTaskConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Unable to create a TaskExecutionDao
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:587) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:373) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1350) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:580) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
	at ucles.results.verification.service.Application.main(Application.java:21) [classes!/:0.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [gs-scheduling-tasks-0.1.0.jar:0.1.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [gs-scheduling-tasks-0.1.0.jar:0.1.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [gs-scheduling-tasks-0.1.0.jar:0.1.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [gs-scheduling-tasks-0.1.0.jar:0.1.0]

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'. ClientConnectionId:b9497473-7b79-4f53-9bbe-9b4cb18943aa
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:256) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:108) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:4548) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3409) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:85) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3373) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2261) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1921) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1762) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1077) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:623) ~[mssql-jdbc-6.4.0.jre8.jar!/:na]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_181]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_181]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:154) ~[spring-jdbc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:145) ~[spring-jdbc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205) ~[spring-jdbc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169) ~[spring-jdbc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151) ~[spring-jdbc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) ~[spring-jdbc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) ~[spring-jdbc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	... 86 common frames omitted

Many thanks.

**Comment by sabbyanandan** [comment]
Hi, @AvijitGit. It looks like you're using "mssql". Are you sure you have got the credentials configured for this database correctly? If yes, perhaps you could share a link to your Task project and the configurations.

**Comment by AvijitGit** [comment]
Hi @sabbyanandan thanks for your reply.
Yes I am using mssql.
The batch application is working fine when I am running as java -jar gs-scheduling-tasks-0.1.0.jar(gs-scheduling-tasks is the application name).
But when I am deploying the application in spring cloud data flow and creating application and task and launching the task the above error is showing in the log file.

The DB configuration in prop file 

# Datasource for candidatecentre
rvs.datasource.url=jdbc:sqlserver://sdrvssq001\\SQL01:9561;databaseName=RVS_Tracking
rvs.datasource.username=user name
rvs.datasource.password=password


# Spring JPA dependencies
spring.jpa.show-sql=true
spring.jpa.database=sql-server
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

Many Thanks

**Comment by sabbyanandan** [comment]
Thanks for the update. Is the same DB also configured for SCDF? Does the server start successfully running against this database instance? _(you can confirm from the logs whether or not the mssql schema is loaded/configured when bootstrapping)_

Also, when reporting issues, it'd help if you can share the versions -- see [README](https://github.com/spring-cloud/spring-cloud-dataflow#reporting-issues) for more details.

**Comment by AvijitGit** [comment]
Hi @sabbyanandan thanks for the reply.
As per the document "https://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#configuration-rdbms"
I am running the application by passing the DB parameters in this starting command.
java -jar spring-cloud-dataflow-server-local-1.6.1.RELEASE.jar --spring.datasource.url=jdbc:sqlserver://sdrvssq001\SQL01:9561;databaseName=RVS_Tracking --spring.datasource.username=user name --spring.datasource.password=password --spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver &

Getting the below exception 

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw e
xception; nested exception is java.lang.IllegalStateException: Cannot load driver class: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.18.RELEASE
.jar!/:4.3.18.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.18.RELEA
SE.jar!/:4.3.18.RELEASE]
        ... 49 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot load driver class: "com.microsoft.sqlserver.jdbc.SQLServerDriver".

**Comment by sabbyanandan** [comment]
You don't have the right driver in the classpath. Though we ship the SCDF server with [MSSQLServer's JDBC driver](https://github.com/spring-cloud/spring-cloud-dataflow/blob/a0b3c855a66d7bbbb4f7f85a38c41f95b6b7cfde/spring-cloud-dataflow-server-core/pom.xml#L157), that does not include `com.microsoft.sqlserver.jdbc.SQLServerDriver` in it. I'm guessing it includes a driver with the legacy package name (i.e., `com.microsoft.jdbc.sqlserver.SQLServerDriver`).  

We rely on Spring Boot to bring in the compatible version, but a very dated version could be coming from Spring Boot 1.5.x. We will look into to explicitly upgrade the driver to the latest [7.0 stable release](https://github.com/Microsoft/mssql-jdbc/releases). 

In the meantime, you have two options.

1) You can manually upgrade the version to the latest and build the SCDF project.

2) Use the legacy package (i.e., `com.microsoft.jdbc.sqlserver.SQLServerDriver`) that's available in the currently shipped binary.

**Comment by sabbyanandan** [comment]
The version provided by Spring Boot is at `mssql-jdbc-6.1.0.jre7.jar` and I was able to confirm that in this release, the driver is available at `com.microsoft.jdbc.sqlserver.SQLServerDriver`.

**Comment by AvijitGit** [comment]
hi @sabbyanandan .
Thanks For the reply .
I will wait for the next release.Meanwhile could you please tell me the process(files in which I have to change and add the dependencies) if I manually upgrade the version to the latest and build the SCDF project.

**Comment by tzolov** [comment]
@sabbyanandan, i think that the driver bundled with the `mssql-jdbc-6.1.0.jre7.jar` is `com.microsoft.sqlserver.jdbc.SQLServerDriver` **not** `com.microsoft.jdbc.sqlserver.SQLServerDriver`: 

<img width="410" alt="screen shot 2018-09-12 at 12 05 16 pm" src="https://user-images.githubusercontent.com/1351573/45418769-a3cfa480-b685-11e8-83ed-c305b5a92d6b.png">

which, it seems is the same driver @AvijitGit is been testing with?

**Comment by tzolov** [comment]
Also, i've successfully tested latest `SCDF-local 1.7.0-BUILD-SNAPSHOT` against SQL Server 2017 
 (running in a docker container and configured as explained [here](https://database.guide/how-to-install-sql-server-on-a-mac/) ) . Here are my startup properties:
```
java -jar ./target/spring-cloud-dataflow-server-local-1.7.0.BUILD-SNAPSHOT.jar --maven.remote-repositories.repo3.url=http://repo.spring.io/test-libs-snapshot-local --spring.datasource.url="jdbc:sqlserver://localhost:1433;databaseName=scdf_test" --spring.datasource.username=sa --spring.datasource.password=reallyStrongPwd123 --spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver --spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
```
e.g. 
```
--spring.datasource.url="jdbc:sqlserver://localhost:1433;databaseName=scdf_test" 
--spring.datasource.username=sa 
--spring.datasource.password=reallyStrongPwd123 
--spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver 
--spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
```

@AvijitGit cloud please share more information about the SCDF server version your are using?

**Comment by AvijitGit** [comment]
Hi @tzolov 
Initially was working with the version 1.6.1.RELEASE.
But today I have been tested with the version SCDF-local 1.7.0-BUILD-SNAPSHOT and its working fine.
