### ISSUE TITLE
Unable to access jarfile hdfs-27e6693e437b5a81b0ea8e733ec1a9f42ece866f  on dataflow-server-yarn

### ISSUE THREAD

**Issue by taoyingqi** [spring-cloud/spring-cloud-dataflow#2512]
Description:
yarn logs -applicationId application_1540258016059_0020
```
Container id: container_1540258016059_0020_01_000002
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
        at org.apache.hadoop.util.Shell.run(Shell.java:478)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:211)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 1

Container: container_1540258016059_0020_01_000002 on CDH3_8041
================================================================
LogType:Container.stderr
Log Upload Time:Tue Oct 23 17:46:46 +0800 2018
LogLength:78
Log Contents:
Error: Unable to access jarfile hdfs-27e6693e437b5a81b0ea8e733ec1a9f42ece866f

LogType:Container.stdout
Log Upload Time:Tue Oct 23 17:46:46 +0800 2018
LogLength:0
Log Contents:

You have new mail in /var/spool/mail/root
```

```
./bin/dataflow-shell
app register --name timestamp --type task --uri hdfs:/dataflow/artifacts/cache/timestamp-task-1.3.0.RELEASE.jar
task create --name printTimeStamp --definition "timestamp"
task launch printTimeStamp
```

my hdfs directory
```
[hdfs@CDH2 src]$ hadoop fs -ls -R /dataflow
drwxrwxr-x   - hdfs supergroup          0 2018-10-23 16:43 /dataflow/apps
drwxrwxr-x   - hdfs supergroup          0 2018-10-18 11:18 /dataflow/apps/stream
drwxrwxr-x   - hdfs supergroup          0 2018-10-23 17:15 /dataflow/apps/stream/app
drwxrwxr-x   - hdfs supergroup          0 2018-10-18 11:17 /dataflow/apps/task
drwxrwxr-x   - hdfs supergroup          0 2018-10-23 17:15 /dataflow/apps/task/app
-rwxrwxr-x   3 hdfs supergroup   72918225 2018-10-23 09:47 /dataflow/apps/task/app/spdb-data-splunk-1.0.1.jar
-rwxrwxr-x   3 hdfs supergroup   62115628 2018-10-18 10:46 /dataflow/apps/task/app/spring-cloud-deployer-yarn-tasklauncherappmaster-1.2.2.RELEASE.jar
-rwxrwxr-x   3 hdfs supergroup   22518771 2018-10-18 11:03 /dataflow/apps/task/app/timestamp-task-1.3.0.RELEASE.jar
drwxr-xr-x   - hdfs supergroup          0 2018-10-23 16:44 /dataflow/artifacts
drwxr-xr-x   - hdfs supergroup          0 2018-10-23 17:32 /dataflow/artifacts/cache
-rw-r--r--   3 hdfs supergroup   22518771 2018-10-23 17:32 /dataflow/artifacts/cache/timestamp-task-1.3.0.RELEASE.jar
drwxr-xr-x   - hdfs supergroup          0 2018-10-23 16:45 /dataflow/artifacts/repo
-rw-r--r--   3 hdfs supergroup   72918225 2018-10-23 16:45 /dataflow/artifacts/repo/spdb-data-splunk-1.0.1.jar
```

Release versions:
https://docs.spring.io/spring-cloud-dataflow-server-yarn/docs/1.2.2.RELEASE/reference/htmlsingle

Custom apps:
timestamp-task-1.3.0.RELEASE.jar

Steps to reproduce:

Screenshots:

Additional context:

**Comment by sabbyanandan** [comment]
Duplicates spring-cloud/spring-cloud-dataflow-server-yarn#177
