### ISSUE TITLE
SCDF dashboard UI - Can't open Streams or Tasks with the latest 2.x Version

### ISSUE THREAD

**Issue by barisa** [spring-cloud/spring-cloud-dataflow#2646]
**Description:**
When trying to add a Stream or Task via the dashboard UI I can't open the `Streams` neither `Tasks` module and get the following error _No property DEFINITION found for type StreamDefinition!_ (see Screenshot).

Error log:

```
dataflow-server    | 2018-12-04 09:32:13.167 ERROR 1 --- [nio-9393-exec-1] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
dataflow-server    |
dataflow-server    | org.springframework.data.mapping.PropertyReferenceException: No property DEFINITION found for type StreamDefinition!
dataflow-server    | 	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:94)
dataflow-server    | 	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:358)
dataflow-server    | 	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:334)
dataflow-server    | 	at org.springframework.data.mapping.PropertyPath.lambda$from$0(PropertyPath.java:287)
dataflow-server    | 	at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
dataflow-server    | 	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:269)
dataflow-server    | 	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:252)
dataflow-server    | 	at org.springframework.data.jpa.repository.query.QueryUtils.toJpaOrder(QueryUtils.java:563)
dataflow-server    | 	at org.springframework.data.jpa.repository.query.QueryUtils.toOrders(QueryUtils.java:516)
dataflow-server    | 	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java:630)
dataflow-server    | 	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java:584)
dataflow-server    | 	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:387)
dataflow-server    | 	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:357)
dataflow-server    | 	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
dataflow-server    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dataflow-server    | 	at java.lang.reflect.Method.invoke(Method.java:498)
dataflow-server    | 	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:377)
dataflow-server    | 	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
dataflow-server    | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:629)
```

**Release versions:**
```
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server-local",
      "version": "2.0.0.BUILD-SNAPSHOT"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.0.0.BUILD-SNAPSHOT"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "1.7.0.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.0.0.BUILD-SNAPSHOT",
      "url": "https://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-dataflow-shell/2.0.0.BUILD-SNAPSHOT/spring-cloud-dataflow-shell-2.0.0.BUILD-SNAPSHOT.jar"
    }
  },
  "featureInfo": {
    "analyticsEnabled": true,
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulerEnabled": false
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthorizationEnabled": false,
    "isFormLogin": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "1.1.2.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.0.0.BUILD-SNAPSHOT",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.0.4.RELEASE",
      "springVersion": "5.0.8.RELEASE"
    },
    "taskLauncher": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "1.3.9.RELEASE",
      "deployerName": "LocalTaskLauncher",
      "deployerSpiVersion": "1.3.4.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "Linux 4.9.125-linuxkit",
      "platformClientVersion": "4.9.125-linuxkit",
      "platformHostVersion": "4.9.125-linuxkit",
      "platformType": "Local",
      "springBootVersion": "2.0.4.RELEASE",
      "springVersion": "5.0.8.RELEASE"
    }
  }
}
```

**Steps to reproduce:**
```
$ wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/master/spring-cloud-dataflow-server-local/docker-compose.yml

$ export DATAFLOW_VERSION=latest
$ export SKIPPER_VERSION=1.1.2.RELEASE
$ docker-compose up
```

**Screenshots:**
<img width="1142" alt="screenshot 2018-12-04 at 10 29 10" src="https://user-images.githubusercontent.com/1219881/49432887-f0bca600-f7b0-11e8-9bca-c24e3ed9d9c8.png">

**Additional context:**
Creating and deploying streams with the SCDF shell works.

**Comment by ilayaperumalg** [comment]
@barisa Thanks for reporting this. We'll have this fixed soon.
