### ISSUE TITLE
Registered application reports error when reading configuration properties

### ISSUE THREAD

**Issue by x97mdr** [spring-cloud/spring-cloud-dataflow#2686]
**Description:**
When attempting to view a registered application, the ui reports that it was unable to retrieve configuration properties from the jar.  The server log reports:

```
java.lang.RuntimeException: Exception trying to list configuration properties for application jar:file:/Users/jcameron/.m2/repository/com/saba/shinypeasant/shiny-peasant-commits-cli/0.0.1-SNAPSHOT/shiny-peasant-commits-cli-0.0.1-SNAPSHOT.jar!/
	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.listProperties(BootApplicationConfigurationMetadataResolver.java:152)
	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.listProperties(BootApplicationConfigurationMetadataResolver.java:98)
	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.info(AppRegistryController.java:173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException: Error while creating ClassLoader for jar:file:/Users/jcameron/.m2/repository/com/saba/shinypeasant/shiny-peasant-commits-cli/0.0.1-SNAPSHOT/shiny-peasant-commits-cli-0.0.1-SNAPSHOT.jar!/
	at org.springframework.cloud.dataflow.configuration.metadata.BootClassLoaderFactory$ClassLoaderExposingLauncher.createClassLoader(BootClassLoaderFactory.java:86)
	at org.springframework.cloud.dataflow.configuration.metadata.BootClassLoaderFactory.createClassLoader(BootClassLoaderFactory.java:68)
	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.listProperties(BootApplicationConfigurationMetadataResolver.java:109)
	... 74 common frames omitted

```
**Release versions:**
```
{
  "featureInfo": {
    "analyticsEnabled": true,
    "streamsEnabled": true,
    "tasksEnabled": true,
    "skipperEnabled": false,
    "schedulerEnabled": false
  },
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server-local",
      "version": "1.7.1.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "1.7.1.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "1.7.0.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "1.7.1.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.7.1.RELEASE/spring-cloud-dataflow-shell-1.7.1.RELEASE.jar"
    }
  },
  "securityInfo": {
    "authenticationEnabled": false,
    "authorizationEnabled": false,
    "formLogin": false,
    "authenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "1.3.9.RELEASE",
      "deployerName": "LocalAppDeployer",
      "deployerSpiVersion": "1.3.4.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "Linux 3.10.0-957.1.3.el7.x86_64",
      "platformClientVersion": "3.10.0-957.1.3.el7.x86_64",
      "platformHostVersion": "3.10.0-957.1.3.el7.x86_64",
      "platformSpecificInfo": {},
      "platformType": "Local",
      "springBootVersion": "1.5.16.RELEASE",
      "springVersion": "4.3.19.RELEASE"
    },
    "taskLauncher": {
      "deployerImplementationVersion": "1.3.9.RELEASE",
      "deployerName": "LocalTaskLauncher",
      "deployerSpiVersion": "1.3.4.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "Linux 3.10.0-957.1.3.el7.x86_64",
      "platformClientVersion": "3.10.0-957.1.3.el7.x86_64",
      "platformHostVersion": "3.10.0-957.1.3.el7.x86_64",
      "platformSpecificInfo": {},
      "platformType": "Local",
      "springBootVersion": "1.5.16.RELEASE",
      "springVersion": "4.3.19.RELEASE"
    }
  },
  "_links": {
    "self": {
      "href": "http://172.16.10.38:9393/about"
    }
  }
}
```

**Custom apps:**
N/A

**Steps to reproduce:**
After registering the application, try to view the application's info.  A red popup will indicate that 

**Screenshots:**
N/A

**Additional context:**
Investigating in the debugger showed that the original stack trace was swallowed and not reported (org/springframework/cloud/dataflow/configuration/metadata/BootClassLoaderFactory.java:86 does not include the original exception in the rethrown exception).  The original exception is 
`java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/atlassian-httpclient-plugin-0.23.0.atlassian-plugin`

It appears that file that are not archives are scanned as archives anyway, causing the exception.  I am currently trying to get around this by excluding these files from the build.

I am thinking that maybe any task that has the atlassian plugins as a dependency is suspect here.  These are my atlassian deps:

```
    compile("com.atlassian.jira:jira-rest-java-client-core:4.0.0")
    compile("com.atlassian.fugue:fugue:2.2.1")
```

I don't have a public reproducible yet, but should be able to develop one shortly.

**Comment by x97mdr** [comment]
I can confirm that filtering out the *.atlassian-plugin files from the BOOT-INF allows the configuration properties to be read correctly.  I would expect that non-archives get ignored rather than trigger an exception.

**Comment by sabbyanandan** [comment]
Hi, @x97mdr. Thank you for the report and the findings. This is interesting. I guess unless we had that specific dependency in the classpath, we wouldn't have bumped into it and had the opportunity to handle it. Now that we do, we will have a review on our side. 

When you get a chance, could you share a simplified, reproducible app? We will use that as the driver to test the fix.

**Comment by sabbyanandan** [comment]
Closing this due to no activity. Feel free to post the reproducible sample; we will certainly have a look.
