### ISSUE TITLE
K8s configmap warning when starting on local server

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2707]
Seeing
```
dataflow-server    | 2018-12-20 16:18:46.279  WARN 1 --- [           main] o.s.c.k.config.ConfigMapPropertySource   : Can't read configMap with name: [] in namespace:[null]. Ignoring
dataflow-server    | 
dataflow-server    | java.lang.IllegalArgumentException: Name must be provided.
dataflow-server    |     at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:248)
dataflow-server    |     at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:63)
dataflow-server    |     at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.getData(ConfigMapPropertySource.java:85)
dataflow-server    |     at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.<init>(ConfigMapPropertySource.java:66)
dataflow-server    |     at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:77)```

when starting local server.  It shouldn't read configmapproperties untill it is running on k8s.

**Comment by markpollack** [comment]
set logging to ignore WARN for that package
