### ISSUE TITLE
 task-launcher-cloudfoundry  Application is getting into disk out of memory after several times launching of task

### ISSUE THREAD

**Issue by keerthikanthn** [spring-cloud/spring-cloud-dataflow#2713]
**Description:**
I launched a task using triggertask for every 20 min | task-launcher-cloudfoundry in PCF. 
task-launcher-cloudfoundry generally downloads the task jar supplied by triggertask and keep inside temp folder like 
```
Downloading [https://appregister-acp.pre.ptlapps.com/UTVINSummary_Task-1.0.0-SNAPSHOT.jar] to /home/vcap/tmp/spring-cloud-deployer4679647774227645681/b955e68a620b6feba7e9ebf6970788b16c6fbec0
```
So every time triggertask send task information based on it interval setting to task-launcher-cloudfoundry then task jar get downloaded to temp location of this app which leads to using up of allocated disk memory completely and leads to errors like 
```
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] org.springframework.messaging.MessageHandlingException: nested exception is reactor.core.Exceptions$ReactiveException: java.nio.file.FileSystemException: /home/vcap/tmp/spring-cloud-deployer7629046795282951794: Disk quota exceeded
```
and finally task doesn't get launched after few triggers [ as per schedule on triggertask ]

**Stream Definition:**
```
stream create  testTrigger10 --definition "triggertask  --uri=https://app123s.com/abc.jar  --triggertask.application-name='kk_test_518PM'    --trigger.fixed-delay=1500  --triggertask.environment-properties='spring.cloud.task.name=Task_temp' | task-launcher-cloudfoundry  --maven.remote-repositories.repo1.url=https://repo.spring.io/libs-snapshot   --spring.cloud.deployer.cloudfoundry.url=https://ABC.com   --spring.cloud.deployer.cloudfoundry.org=SCDF-acceptance  --spring.cloud.deployer.cloudfoundry.space=scdf-acp-space     --spring.cloud.deployer.cloudfoundry.taskTimeout=1000" --deploy
```
task-launcher-cloudfoundry Application specifications : 1GB disk space , 1 GB memory 

So app is reaching 1GB disk space after 7 iterations.So even if i increase disk space to 2GB also at one point I may face this issue again after some trigger calls from tasktrigger. 

**_How to cleanup downloaded task jar after launching the task ? Is there any parameter available to clean up disk space ?_** 

**Note:** task-launcher-cloudfoundry App is not in crashed state. It will be running state with throwing exceptions. 

**Full Stack Error :** 
```
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] org.springframework.messaging.MessageHandlingException: nested exception is reactor.core.Exceptions$ReactiveException: java.nio.file.FileSystemException: /home/vcap/tmp/spring-cloud-deployer7629046795282951794: Disk quota exceeded
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:107) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:93) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:158) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181) ~[spring-messaging-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160) ~[spring-messaging-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108) ~[spring-messaging-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$1100(AmqpInboundChannelAdapter.java:60) ~[spring-integration-amqp-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.lambda$onMessage$0(AmqpInboundChannelAdapter.java:214) [spring-integration-amqp-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287) [spring-retry-1.2.2.RELEASE.jar!/:na]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180) [spring-retry-1.2.2.RELEASE.jar!/:na]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:211) [spring-integration-amqp-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1414) [spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1337) [spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1324) [spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1303) [spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:817) ~[spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:801) ~[spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77) ~[spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1042) ~[spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] Caused by: reactor.core.Exceptions$ReactiveException: java.nio.file.FileSystemException: /home/vcap/tmp/spring-cloud-deployer7629046795282951794: Disk quota exceeded
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at reactor.core.Exceptions.propagate(Exceptions.java:326) ~[reactor-core-3.1.5.RELEASE.jar!/:3.1.5.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.AbstractCloudFoundryDeployer.getApplication(AbstractCloudFoundryDeployer.java:132) ~[spring-cloud-deployer-cloudfoundry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundry2630AndLaterTaskLauncher.pushApplication(CloudFoundry2630AndLaterTaskLauncher.java:161) ~[spring-cloud-deployer-cloudfoundry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundry2630AndLaterTaskLauncher.deployApplication(CloudFoundry2630AndLaterTaskLauncher.java:112) ~[spring-cloud-deployer-cloudfoundry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundry2630AndLaterTaskLauncher.getOrDeployApplication(CloudFoundry2630AndLaterTaskLauncher.java:149) ~[spring-cloud-deployer-cloudfoundry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundry2630AndLaterTaskLauncher.launch(CloudFoundry2630AndLaterTaskLauncher.java:93) ~[spring-cloud-deployer-cloudfoundry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.task.launcher.TaskLauncherSink.launchTask(TaskLauncherSink.java:67) ~[spring-cloud-task-stream-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.task.launcher.TaskLauncherSink.taskLauncherSink(TaskLauncherSink.java:58) ~[spring-cloud-task-stream-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source) ~[na:na]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181) ~[spring-messaging-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114) ~[spring-messaging-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.util.MessagingMethodInvokerHelper$HandlerMethod.invoke(MessagingMethodInvokerHelper.java:1056) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.util.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:574) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:468) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:312) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:104) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] ... 28 common frames omitted
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] Caused by: java.nio.file.FileSystemException: /home/vcap/tmp/spring-cloud-deployer7629046795282951794: Disk quota exceeded
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.Files.createDirectory(Files.java:674) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.TempFileHelper.create(TempFileHelper.java:136) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.Files.createTempDirectory(Files.java:991) ~[na:1.8.0_152]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.resource.support.DownloadingUrlResource.getFile(DownloadingUrlResource.java:70) ~[spring-cloud-deployer-resource-support-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.AbstractCloudFoundryDeployer.getApplication(AbstractCloudFoundryDeployer.java:127) ~[spring-cloud-deployer-cloudfoundry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
2018-12-20T18:00:16.867-05:00 [APP/PROC/WEB/0] [OUT] ... 44 common frames omitted
2018-12-20T18:00:16.868-05:00 [APP/PROC/WEB/0] [OUT] 2018-12-20 23:00:16.868 WARN 14 --- [testTrigger10-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
2018-12-20T18:00:16.868-05:00 [APP/PROC/WEB/0] [OUT] org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener threw exception
2018-12-20T18:00:16.868-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1506) ~[spring-rabbit-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.util.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:574) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:468) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:312) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:104) ~[spring-integration-core-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] ... 28 common frames omitted
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] Caused by: java.nio.file.FileSystemException: /home/vcap/tmp/spring-cloud-deployer7629046795282951794: Disk quota exceeded
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[na:1.8.0_152]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_152]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_152]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[na:1.8.0_152]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.Files.createDirectory(Files.java:674) ~[na:1.8.0_152]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.TempFileHelper.create(TempFileHelper.java:136) ~[na:1.8.0_152]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173) ~[na:1.8.0_152]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at java.nio.file.Files.createTempDirectory(Files.java:991) ~[na:1.8.0_152]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.resource.support.DownloadingUrlResource.getFile(DownloadingUrlResource.java:70) ~[spring-cloud-deployer-resource-support-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.deployer.spi.cloudfoundry.AbstractCloudFoundryDeployer.getApplication(AbstractCloudFoundryDeployer.java:127) ~[spring-cloud-deployer-cloudfoundry-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
2018-12-20T18:00:16.869-05:00 [APP/PROC/WEB/0] [OUT] ... 44 common frames omitted
2018-12-20T18:12:44.221-05:00 [APP/PROC/WEB/0] [OUT] 2018-12-20 23:12:44.220 INFO 14 --- [nio-8080-exec-8] o.a.c.c.C.[Tomcat].[localhost].[/] : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-12-20T18:12:44.221-05:00 [APP/PROC/WEB/0] [OUT] 2018-12-20 23:12:44.221 INFO 14 --- [nio-8080-exec-8] o.s.web.servlet.DispatcherServlet : FrameworkServlet 'dispatcherServlet': initialization started
2018-12-20T18:12:44.246-05:00 [APP/PROC/WEB/0] [OUT] 2018-12-20 23:12:44.246 INFO 14 --- [nio-8080-exec-8] o.s.web.servlet.DispatcherServlet : FrameworkServlet 'dispatcherServlet': initialization completed in 25 ms


```

**Release versions:**
There is an API (http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-server-meta-retrieving) to gather SCDF's system information, including the dependent projects and the associated versions. Alternatively, you can capture this information from the Dashboard's About tab (http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#dashboard). Please be sure to include the copied JSON in the bug report.

**Steps to reproduce:**
1. Use a task jar with more memory [ 100MB jar ]
2. Create a task stream with Triggertask --uri://heavy_task.jar --trigger.fixed-delay=100 |  task-launcher-cloudfoundry
3. deploy task-stream 
4. make sure task-launcher-cloudfoundry app with less disk memory configuration 
5. after few trigger launches , task-launcher-cloudfoundry app  will fail to launch task jar

**Comment by sabbyanandan** [comment]
Hi, @keerthikanthn. A few things to unpack here.

(1) You're right about `task-launcher`'s responsibility. They internally use a [platform-specific deployer implementation](https://github.com/spring-cloud?utf8=%E2%9C%93&q=deployer&type=&language=) in its classpath, so they can download and stage/launch the Tasks on every upstream event; in your case, it is triggered via the `triggertask`, of course. To avoid the accumulation of the Task JAR's in the container, if your application is resolved as Maven artifacts, you'd have the option to set the `triggertask.application-name` [see [docs](https://github.com/spring-cloud-stream-app-starters/triggertask/blob/master/spring-cloud-starter-stream-source-triggertask/README.adoc)]. With that set at the source, every new event would attempt to launch the Task (with the same name) on the desired interval. Given that Task when it completes, the droplet sticks around, and upon subsequent launches (with the same name), the same droplet will be reused to launch it on a new container. It is the Maven cache that's in action here - that's why this would work _only_ on Maven artifacts.

(2) If the application is resolved from an `http` web-server, no such caching mechanism 's available. However, in the recent deployer release, we have removed the persistent nature of the `http` resolved artifacts [see spring-cloud/spring-cloud-deployer-cloudfoundry#256]. With this, you will never run into disk capacity situation; however, there's a caveat here, though. For every new event, the application will be downloaded, staged, and launched over-and-over. This could be a slight overhead. We haven't released `task-launcher-cloudfoundry` with the new cf-deployer release in the classpath, but you can try that yourself with a local build of the app [see [FAQs](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Darwin.SR3/reference/htmlsingle/#_general_faq_on_spring_cloud_stream_app_starters)]. 

(3) If your goal is to launch Task's on a regular cadence, it'd be **recommended** that you use the [PCF Scheduler](https://network.pivotal.io/products/p-scheduler) and the [native integration](https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.7.3.RELEASE/reference/htmlsingle/#getting-started-scheduling-configuration) that's available in [SCDF](https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.7.3.RELEASE/reference/htmlsingle/#dashboard-task-scheduling). You don't need to use `triggertask` or the `task-launcher-cloudfoundry` apps. You don't even need a stream to launch a Task - no need to consume those AIs on PCF. Instead, you'd delegate to the platform's scheduler service, and schedule for your Task's to be launched on the desired cadence. Here's a [screencast](https://www.youtube.com/watch?v=BR9VcMnhXOs) that shows it in action.

(4) Lastly, we will be deprecating the `task-launcher`'s soon in favor of [`tasklauncher-dataflow`](https://github.com/spring-cloud-stream-app-starters/tasklauncher-dataflow). So, (1) and (2) options are not optimal. This new application invokes SCDF's REST-APIs to stage and launch the Tasks. You don't need to configure the application with PCF connection properties. You'd point to the SCDF-server route, and everything will come together at runtime. All that said, if you still _cannot_ use the PCF Scheduler [see (3)], and you _must_ have to rely on the stream launching the Task model, then the `tasklauncher-dataflow` is recommended. Here's an [end-to-end demonstration](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_using_the_cloud_foundry_server_2) of the new app in action.

Hope this helps.

In the future, it'd be good if you can avoid duplicate posts here and in [StackOverflow](https://stackoverflow.com/questions/53878691/task-launcher-cloudfoundry-application-is-getting-into-disk-out-of-memory-after).

**Comment by keerthikanthn** [comment]
Thanks for your suggestion. I will try for option 3 as we want to run a task jar on scheduled time interval.
