### ISSUE TITLE
Can't re-deploy streams when running in local mode

### ISSUE THREAD

**Issue by mross1080** [spring-cloud/spring-cloud-dataflow#275]
When I deploy a stream, and I undeploy it, when I try and deploy the same stream again, the scdf-admin throws an error.  The stack trace shows that the tmp directory for that stream already exists for that stream and that is preventing the stream from being deployed again.

**Comment by trisberg** [comment]
Stack trace:

```
Caused by: java.nio.file.FileAlreadyExistsException: /var/folders/kf/hchj843x1jq6zc1ks2d0gx740000gp/T/spring-cloud-data-flow-424169994914638303/ticktock.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88) ~[na:1.7.0_67]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.7.0_67]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.7.0_67]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:383) ~[na:1.7.0_67]
	at java.nio.file.Files.createDirectory(Files.java:630) ~[na:1.7.0_67]
	at org.springframework.cloud.dataflow.admin.spi.local.OutOfProcessModuleDeployer.deploy(OutOfProcessModuleDeployer.java:96) ~[spring-cloud-dataflow-admin-local-1.0.0.M2.jar!/:1.0.0.M2]
	... 74 common frames omitted
```

**Comment by mminella** [comment]
This is a bigger issue as we are adding task support since you can't launch a task more than once with the same name due to this issue.
