### ISSUE TITLE
try a Flux transform processor fail.

### ISSUE THREAD

**Issue by jchbh-duplicate** [spring-cloud/spring-cloud-dataflow#2896]
**Description:**
I modify the [Transform starter app](https://github.com/spring-cloud-stream-app-starters/transform) and change the transform logic from expression into a Reactive function according to [the document of spring cloud steam. ](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/_programming_model.html#spring-cloud-stream-overview-reactive-programming-support)

When deploy the app in steam, the stdout.log shows the Application run failed:

```

2019-02-14 03:54:01.591 ERROR 507 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalArgumentException: A method annotated with @StreamListener may use @Input or @Output annotations only in declarative mode and for parameters that are binding targets or convertible from binding targets.
        at org.springframework.util.Assert.isTrue(Assert.java:118) ~[spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor$DefaultStreamListenerSetupMethodOrchestrator.checkDeclarativeMethod(StreamListenerAnnotationBeanPostProcessor.java:431) ~[spring-cloud-stream-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor$DefaultStreamListenerSetupMethodOrchestrator.orchestrateStreamListenerSetupMethod(StreamListenerAnnotationBeanPostProcessor.java:352) ~[spring-cloud-stream-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.doPostProcess(StreamListenerAnnotationBeanPostProcessor.java:195) ~[spring-cloud-stream-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.lambda$postProcessAfterInitialization$0(StreamListenerAnnotationBeanPostProcessor.java:167) ~[spring-cloud-stream-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_192]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.injectAndPostProcessDependencies(StreamListenerAnnotationBeanPostProcessor.java:285) ~[spring-cloud-stream-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
        at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(StreamListenerAnnotationBeanPostProcessor.java:105) ~[spring-cloud-stream-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:863) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.cloud.stream.app.transform.processor.rabbit.TransformProcessorRabbitApplication.main(TransformProcessorRabbitApplication.java:29) [classes!/:2.1.0.BUILD-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [transform-processor-rabbit-2.1.0.BUILD-SNAPSHOT.jar:2.1.0.BUILD-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [transform-processor-rabbit-2.1.0.BUILD-SNAPSHOT.jar:2.1.0.BUILD-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [transform-processor-rabbit-2.1.0.BUILD-SNAPSHOT.jar:2.1.0.BUILD-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [transform-processor-rabbit-2.1.0.BUILD-SNAPSHOT.jar:2.1.0.BUILD-SNAPSHOT]

2019-02-14 03:54:01.612  INFO 507 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-02-14 03:54:01.613  INFO 507 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
```

**Release versions:**
spring-dataflow is local version 1.7.4 release running on docker, use rabbitmq. 
all pre-build apps upgrade to http://bit.ly/Einstein-RC1-stream-applications-rabbit-maven&force=true
which works great. 

**Screenshots:**
![issue](https://user-images.githubusercontent.com/785571/52763026-726e5280-2ff0-11e9-9ad9-8c3174cfe2a4.JPG)

**Additional context:**

**Comment by sabbyanandan** [comment]
Hi, @jchbh-duplicate. It'd be better to discuss this type of issues in StackOverflow or Gitter. Also, this is not related to SCDF, but it is more of a custom app development question. Feel free to start a thread in StackOverflow and share your custom app repo.
