### ISSUE TITLE
update stream in has problems(server.port is fix)

### ISSUE THREAD

**Issue by zhuwenjie11** [spring-cloud/spring-cloud-dataflow#2997]
**Description:**
i created a stream, name is A1, A1 has a app(B1),B1 is a simple spring boot web. i deploy A1，deployment param is "server.port=4010" and "dcpp.username=C1", A1 is running and woking.
i try update A1 , deployment param modify to "dcpp.username=C2" , but A1 status is failed, and B1 status is failed . i can not destory stream。
if i created new stream D1. deployment param "dcpp.username=C1",in running , then modify param "dcpp.username=C2" for update stream D1,  all going well。

why set param "server.port=4010" in stream ,and then update stream ,There will be problems。

**Release versions:**
SCDF: 2.0.0.RELEASE
Skipper: 2.0.0.RELEASE

**Custom apps:**
this is my custom apps, this is a helloword example

**Steps to reproduce:**
i created a stream, name is A1, A1 has a app(B1),B1 is a simple spring boot web. i deploy A1，deployment param is "server.port=4010" and "dcpp.username=C1", A1 is running and woking.
i try update A1 , deployment param modify to "dcpp.username=C2" , but A1 status is failed, and B1 status is failed . i can not destory stream。
if i created new stream D1. deployment param "dcpp.username=C1",in running , then modify param "dcpp.username=C2" for update stream D1,  all going well。

**Screenshots:**
~~~
2019-03-11 01:30:36.336  INFO 5944 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-03-11 01:30:36.635 ERROR 5944 --- [           main] org.apache.catalina.util.LifecycleBase   : Failed to start component [Connector[HTTP/1.1-4010]]

org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1008) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:226) [tomcat-embed-core-9.0.16.jar!/:9.0.16]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:259) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:197) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:311) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) [spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at com.eastcom.dataflow.apps.web.WebStartApplication.main(WebStartApplication.java:25) [classes!/:1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [dataflow-web-app-1.0.jar:1.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [dataflow-web-app-1.0.jar:1.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [dataflow-web-app-1.0.jar:1.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [dataflow-web-app-1.0.jar:1.0]
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_201]
	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_201]
	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_201]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_201]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_201]
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:236) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16]
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1085) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1171) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:568) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1005) ~[tomcat-embed-core-9.0.16.jar!/:9.0.16]
	... 22 common frames omitted

2019-03-11 01:30:36.640  INFO 5944 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-03-11 01:30:36.647  INFO 5944 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-03-11 01:30:36.648 ERROR 5944 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 4010 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 4010, or configure this application to listen on another port.

2019-03-11 01:30:36.650  INFO 5944 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
~~~

**Comment by ilayaperumalg** [comment]
@zhuwenjie11 I assume you are running this in `local` setup and this is expected.

The `stream update` will make sure the new application started successfully and then go ahead and stop the existing application. In this case, given the app uses the fixed port this will never work.

This is not the case in environments like k8s, CF where each app will have their containerized environment.

Also, note that the `local` deployer is only for development purposes not meant for production.

**Comment by zhuwenjie11** [comment]
I am trying to apply the local model to the production environment. I intend to learn and modify the source code to achieve this goal. Please tell me if this is feasible.

Because my current production environment actually does not have CF and k8s

**Comment by zhuwenjie11** [comment]
> @zhuwenjie11 I assume you are running this in `local` setup and this is expected.
> 
> The `stream update` will make sure the new application started successfully and then go ahead and stop the existing application. In this case, given the app uses the fixed port this will never work.
> 
> This is not the case in environments like k8s, CF where each app will have their containerized environment.
> 
> Also, note that the `local` deployer is only for development purposes not meant for production.


thank you , I am trying to apply the local model to the production environment. I intend to learn and modify the source code to achieve this goal. Please tell me if this is feasible.

Because my current production environment actually does not have CF and k8s

**Comment by sabbyanandan** [comment]
Hi, @zhuwenjie11. In Local mode, if you would want to rolling-upgrade or rolling-downgrade apps in a stream, you would have to remove the property `server.port` from an explicit value. You _cannot_ expect multiple versions of the Apps to run on the same port. That is the Local-mode limitation.

In CF and K8s, it won't be a problem, because the platform manages the routes/port-binding automatically.

There's nothing more we can do to provide a blue-green / red-black type of deployment pattern, but at the same time also retain the same port for a given app. That is by design.
