### ISSUE TITLE
mysql authentication issue

### ISSUE THREAD

**Issue by durgadevikarthikeyan** [spring-cloud/spring-cloud-dataflow#2999]
Hi Team,

i am installing Spring cloud Dataflow for kuberenetes version 2.0.0. by using below documentation
[(https://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.RELEASE/reference/htmlsingle/#_deploying_with_code_kubectl_code)
]

Getting the below exception in scdf-server logs

> `
2019-03-11 07:12:03.193  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.IllegalStateException: org.springframework.jdbc.support.MetaDataAccessException: Could not get Connection for extracting meta-data; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'root'@'10.56.2.14' (using password: YES)
2019-03-11 07:12:03.288  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-03-11 07:12:03.393 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.IllegalStateException: org.springframework.jdbc.support.MetaDataAccessException: Could not get Connection for extracting meta-data; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'root'@'10.56.2.14' (using password: YES)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
`

**Comment by ilayaperumalg** [comment]
@durgadevikarthikeyan Did you have to change your MySQL `root` user password?  If so, I hope you did what is mentioned in the documentation:

```
You can modify the password in the src/kubernetes/mysql/mysql-deployment.yaml files if you prefer to be more secure. If you do modify the password, you must also provide it as base64-encoded string in the src/kubernetes/mysql/mysql-secrets.yaml file.
``

**Comment by durgadevikarthikeyan** [comment]
@ilayaperumalg, i have not changed default password.

**Comment by durgadevikarthikeyan** [comment]
Any help will be appreciated on this

**Comment by ilayaperumalg** [comment]
You can check the password (used by the mysql secret) using this:

> kubectl get secret/mysql -o yaml

copy the encoded value from `mysql-root-password` and use below:

> echo '<encoded-value>' | base64 --decode

The default encoded value is `eW91cnBhc3N3b3Jk`.

**Comment by durgadevikarthikeyan** [comment]
@ilayaperumalg , copied the output of kubectl get secret/mysql-scdf -o yaml

 `Durgadevi.ramadoss@jenkinstest001:~$ kubectl get secret/mysql-scdf -o yaml
apiVersion: v1
data:
  mysql-root-password: eW91cnBhc3N3b3Jk
kind: Secret
metadata:
  creationTimestamp: "2019-03-07T09:04:31Z"
  labels:
    app: mysql-scdf
  name: mysql-scdf
  namespace: default
  resourceVersion: "2084304"
  selfLink: /api/v1/namespaces/default/secrets/mysql-scdf
  uid: 05514fe5-40b8-11e9-925c-42010a8a0100
type: Opaque
`

**Comment by ilayaperumalg** [comment]
@durgadevikarthikeyan I see that you have changed the secret name from `mysql` to `mysql-scdf`. This requires update in `./kubernetes/server/server-deployment.yaml` for

```
    - name: SPRING_CLOUD_KUBERNETES_SECRETS_NAME
          value: mysql
```

**Comment by durgadevikarthikeyan** [comment]
@ilayaperumalg I have changed that also. Please see below,
`Durgadevi.ramadoss@jenkinstest001:~/spring-cloud-dataflow/src/kubernetes/server$ cat server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scdf-server
  labels:
    app: scdf-server
spec:
  selector:
    matchLabels:
      app: scdf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: scdf-server
    spec:
      containers:
      - name: scdf-server
        image: springcloud/spring-cloud-dataflow-server:2.0.0.RELEASE
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1.0
            memory: 2048Mi
          requests:
            cpu: 0.5
            memory: 1024Mi
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: SERVER_PORT
          value: '80'
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: 'false'
        - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
          value: 'true'
        - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
          value: 'true'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
          value: 'true'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_NAME
          value: mysql-scdf
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
          value: scdf-server
        - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
          value: 'http://${SCDF_SERVER_SERVICE_HOST}:${SCDF_SERVER_SERVICE_PORT}'
          # Provide the Skipper service location
        - name: SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI
          value: 'http://${SKIPPER_SERVICE_HOST}/api'
          # Add Maven repo for metadata artifact resolution for all stream apps
        - name: SPRING_APPLICATION_JSON
          value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"https://repo.spring.io/libs-snapshot\"} } } }"
      serviceAccountName: scdf-sa
Durgadevi.ramadoss@jenkinstest001:~/spring-cloud-dataflow/src/kubernetes/server$
`

**Comment by durgadevikarthikeyan** [comment]
@ilayaperumalg , I could able to setup Spring cloud Data flow server successfully without changing the default names of the pod. I recreated all the deployments and services with the names as mentioned in the document
[https://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.RELEASE/reference/htmlsingle/#getting-started-kubernetes](url)

But please look into the things if we change the name of deployment and service

**Comment by sabbyanandan** [comment]
Hi, @durgadevikarthikeyan. It is not clear whether are you still having issues. Could you clarify?

**Comment by sabbyanandan** [comment]
Closing this due to no activity.
