### ISSUE TITLE
Stream with long names can result in orphaned applications

### ISSUE THREAD

**Issue by allanmoso** [spring-cloud/spring-cloud-dataflow#3005]
**Description:**

When deploying a stream with a long name,  some stream applications are deployed and some are not if they have varying name lengths.  For example:  `time | groovy-transform | log` and the stream name is around 50 characters, the `log` will deploy, the others will not.

Also, the stream status will be "Undeployed".  This means applications that are deployed on the platform are orphaned from SCDF/skipper; SCDF/Skipper no longer has control over the applications that are deployed.

The skipper server has this error:
```
2019-03-11 19:24:51.464 ERROR 1 --- [eTaskExecutor-1] o.s.c.s.server.statemachine.ErrorAction  : Going through error state DefaultStateContext [stage=STATE_ENTRY, message=GenericMessage [payload=INSTALL, headers={INSTALL_REQUEST=org.springframework.cloud.skipper.domain.InstallRequest@49a67b7d, id=4ebf7a0d-c853-ed25-bdd8-e949044f75fc, timestamp=1552332290839}], messageHeaders={INSTALL_REQUEST=org.springframework.cloud.skipper.domain.InstallRequest@49a67b7d, id=4ebf7a0d-c853-ed25-bdd8-e949044f75fc, timestamp=1552332290839}, extendedState=DefaultExtendedState [variables={ERROR=org.springframework.cloud.skipper.SkipperException: Could not install AppDeployRequest [[AppDeploymentRequest@17debb7d commandlineArguments = list[[empty]], deploymentProperties = map['spring.cloud.deployer.group' -> 'b12345678901234567890123456789012345678901234567890'], definition = [AppDefinition@52909f60 name = 'groovy-transform-v1', properties = map['spring.metrics.export.triggers.application.includes' -> 'integration**', 'spring.cloud.dataflow.stream.app.label' -> 'groovy-transform', 'spring.cloud.stream.metrics.key' -> 'b12345678901234567890123456789012345678901234567890.groovy-transform.${spring.cloud.application.guid}', 'spring.cloud.stream.bindings.input.group' -> 'b12345678901234567890123456789012345678901234567890', 'spring.cloud.stream.bindings.output.producer.requiredGroups' -> 'b12345678901234567890123456789012345678901234567890', 'spring.cloud.stream.metrics.properties' -> 'spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*', 'spring.cloud.dataflow.stream.name' -> 'b12345678901234567890123456789012345678901234567890', 'spring.cloud.stream.bindings.output.destination' -> 'b12345678901234567890123456789012345678901234567890.groovy-transform', 'spring.cloud.dataflow.stream.app.type' -> 'processor', 'spring.cloud.stream.bindings.input.destination' -> 'b12345678901234567890123456789012345678901234567890.time']], resource = Docker Resource [docker:nexus.misoenergy.org:5000/springcloudstream/groovy-transform-processor-kafka:2.0.1.RELEASE.NONROOT-v1-SNAPSHOT]]]  to platform [default].  Error Message = [Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/scdf/services?labelSelector=spring-app-id%3Db12345678901234567890123456789012345678901234567890-groovy-transform-v1. Message: unable to parse requirement: invalid label value: "b12345678901234567890123456789012345678901234567890-groovy-transform-v1": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=unable to parse requirement: invalid label value: "b12345678901234567890123456789012345678901234567890-groovy-transform-v1": must be no more than 63 characters, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).], INSTALL_REQUEST=org.springframework.cloud.skipper.domain.InstallRequest@49a67b7d}], transition=AbstractTransition [source=StateMachineState [getIds()=[INSTALL, INSTALL_INSTALL], toString()=AbstractState [id=INSTALL, pseudoState=null, deferred=[], entryActions=[], exitActions=[], stateActions=[], regions=[], submachine=INSTALL_INSTALL INSTALL_EXIT  /  / uuid=f9e0de68-b18a-40b0-9868-3fec37859760 / id=b12345678901234567890123456789012345678901234567890], getClass()=class org.springframework.statemachine.state.StateMachineState], target=ObjectState [getIds()=[ERROR_JUNCTION], getClass()=class org.springframework.statemachine.state.ObjectState, hashCode()=1917109476, toString()=AbstractState [id=ERROR_JUNCTION, pseudoState=org.springframework.statemachine.state.JunctionPseudoState@6f9ec3ba, deferred=[], entryActions=[], exitActions=[], stateActions=[], regions=[], submachine=null]], kind=EXTERNAL, guard=org.springframework.cloud.skipper.server.statemachine.StateMachineConfiguration$SkipperStateMachineFactoryConfig$$Lambda$895/576222471@5c77ba8f], stateMachine=ROLLBACK ROLLBACK_START ROLLBACK_EXIT_INSTALL ROLLBACK_CHOICE ROLLBACK_EXIT ROLLBACK_EXIT_UPGRADE DELETE DELETE_DELETE DELETE_EXIT ERROR INSTALL INSTALL_INSTALL INSTALL_EXIT INITIAL UPGRADE UPGRADE_WAIT_TARGET_APPS UPGRADE_DEPLOY_TARGET_APPS UPGRADE_CHECK_TARGET_APPS UPGRADE_START UPGRADE_DELETE_SOURCE_APPS UPGRADE_DEPLOY_TARGET_APPS_FAILED UPGRADE_CANCEL UPGRADE_DEPLOY_TARGET_APPS_SUCCEED UPGRADE_EXIT UPGRADE_CHECK_CHOICE ERROR_JUNCTION  / ERROR / uuid=fca3bce0-a95f-4412-8922-d26b51d489e5 / id=b12345678901234567890123456789012345678901234567890, source=null, target=null, sources=null, targets=null, exception=null] {}

org.springframework.cloud.skipper.SkipperException: Could not install AppDeployRequest [[AppDeploymentRequest@17debb7d commandlineArguments = list[[empty]], deploymentProperties = map['spring.cloud.deployer.group' -> 'b12345678901234567890123456789012345678901234567890'], definition = [AppDefinition@52909f60 name = 'groovy-transform-v1', properties = map['spring.metrics.export.triggers.application.includes' -> 'integration**', 'spring.cloud.dataflow.stream.app.label' -> 'groovy-transform', 'spring.cloud.stream.metrics.key' -> 'b12345678901234567890123456789012345678901234567890.groovy-transform.${spring.cloud.application.guid}', 'spring.cloud.stream.bindings.input.group' -> 'b12345678901234567890123456789012345678901234567890', 'spring.cloud.stream.bindings.output.producer.requiredGroups' -> 'b12345678901234567890123456789012345678901234567890', 'spring.cloud.stream.metrics.properties' -> 'spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*', 'spring.cloud.dataflow.stream.name' -> 'b12345678901234567890123456789012345678901234567890', 'spring.cloud.stream.bindings.output.destination' -> 'b12345678901234567890123456789012345678901234567890.groovy-transform', 'spring.cloud.dataflow.stream.app.type' -> 'processor', 'spring.cloud.stream.bindings.input.destination' -> 'b12345678901234567890123456789012345678901234567890.time']], resource = Docker Resource [docker:nexus.misoenergy.org:5000/springcloudstream/groovy-transform-processor-kafka:2.0.1.RELEASE.NONROOT-v1-SNAPSHOT]]]  to platform [default].  Error Message = [Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/scdf/services?labelSelector=spring-app-id%3Db12345678901234567890123456789012345678901234567890-groovy-transform-v1. Message: unable to parse requirement: invalid label value: "b12345678901234567890123456789012345678901234567890-groovy-transform-v1": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=unable to parse requirement: invalid label value: "b12345678901234567890123456789012345678901234567890-groovy-transform-v1": must be no more than 63 characters, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).]
	at org.springframework.cloud.skipper.server.deployer.DefaultReleaseManager.install(DefaultReleaseManager.java:125) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.cloud.skipper.server.service.ReleaseService.install(ReleaseService.java:196) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.cloud.skipper.server.service.ReleaseService.install(ReleaseService.java:182) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.cloud.skipper.server.service.ReleaseService.install(ReleaseService.java:139) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.cloud.skipper.server.service.ReleaseService$$FastClassBySpringCGLIB$$f1c5f0a2.invoke(<generated>) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.cloud.skipper.server.service.ReleaseService$$EnhancerBySpringCGLIB$$54f01224.install(<generated>) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.cloud.skipper.server.statemachine.InstallInstallAction.executeInternal(InstallInstallAction.java:69) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.cloud.skipper.server.statemachine.AbstractAction.execute(AbstractAction.java:41) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	at org.springframework.statemachine.state.AbstractState.executeAction(AbstractState.java:496) ~[spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.state.ObjectState.entry(ObjectState.java:158) ~[spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.entryToState(AbstractStateMachine.java:1310) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.entryToState(AbstractStateMachine.java:1254) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentStateInternal(AbstractStateMachine.java:1060) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentState(AbstractStateMachine.java:1034) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.switchToState(AbstractStateMachine.java:926) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.access$500(AbstractStateMachine.java:82) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine$3.transit(AbstractStateMachine.java:334) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.handleInitialTrans(DefaultStateMachineExecutor.java:303) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.processTriggerQueue(DefaultStateMachineExecutor.java:399) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.access$200(DefaultStateMachineExecutor.java:65) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor$1.run(DefaultStateMachineExecutor.java:331) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) [spring-core-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.scheduleEventQueueProcessing(DefaultStateMachineExecutor.java:354) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.execute(DefaultStateMachineExecutor.java:163) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.doStart(DefaultStateMachineExecutor.java:175) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.LifecycleObjectSupport.start(LifecycleObjectSupport.java:120) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.doStart(AbstractStateMachine.java:418) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.LifecycleObjectSupport.start(LifecycleObjectSupport.java:120) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.state.StateMachineState.entry(StateMachineState.java:236) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.entryToState(AbstractStateMachine.java:1310) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.entryToState(AbstractStateMachine.java:1254) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentStateInternal(AbstractStateMachine.java:1060) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentState(AbstractStateMachine.java:1034) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.switchToState(AbstractStateMachine.java:926) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.access$500(AbstractStateMachine.java:82) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine$3.transit(AbstractStateMachine.java:337) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.handleTriggerTrans(DefaultStateMachineExecutor.java:288) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.handleTriggerTrans(DefaultStateMachineExecutor.java:211) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.processTriggerQueue(DefaultStateMachineExecutor.java:451) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.access$200(DefaultStateMachineExecutor.java:65) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor$1.run(DefaultStateMachineExecutor.java:331) [spring-statemachine-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/scdf/services?labelSelector=spring-app-id%3Db12345678901234567890123456789012345678901234567890-groovy-transform-v1. Message: unable to parse requirement: invalid label value: "b12345678901234567890123456789012345678901234567890-groovy-transform-v1": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=unable to parse requirement: invalid label value: "b12345678901234567890123456789012345678901234567890-groovy-transform-v1": must be no more than 63 characters, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472) ~[kubernetes-client-4.0.4.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:411) ~[kubernetes-client-4.0.4.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[kubernetes-client-4.0.4.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[kubernetes-client-4.0.4.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328) ~[kubernetes-client-4.0.4.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:598) ~[kubernetes-client-4.0.4.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:63) ~[kubernetes-client-4.0.4.jar!/:na]
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.status(KubernetesAppDeployer.java:196) ~[spring-cloud-deployer-kubernetes-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.deploy(KubernetesAppDeployer.java:103) ~[spring-cloud-deployer-kubernetes-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.cloud.skipper.server.deployer.DefaultReleaseManager.install(DefaultReleaseManager.java:115) ~[spring-cloud-skipper-server-core-2.0.0.RC1.jar!/:2.0.0.RC1]
	... 50 common frames omitted


```

**Release versions:**
Version Information
Implementation Version: 2.0.0.RELEASE (spring-cloud-dataflow-server)
Core: 2.0.0.RELEASE (Spring Cloud Data Flow Core)
Dashboard: 2.0.0.RELEASE (Spring Cloud Dataflow UI)
Shell: 2.0.0.RELEASE (Spring Cloud Data Flow Shell)

**Steps to reproduce:**
Create a stream with the following applications: `time | groovy-transform | log` and name it `b12345678901234567890123456789012345678901234567890`.

**Additional context:**
Deployed in Kubernetes.

**Comment by sabbyanandan** [comment]
Hi, @allanmoso. Based on the error [i.e: `invalid label value: "b12345678901234567890123456789012345678901234567890-groovy-transform-v1": must be no more than 63 characters`], it appears you're running into the maximum default value applicable in Kubernetes for labels and pod naming conventions. 

There are a [lot of threads](https://www.google.com/search?q=kubernetes+label+must+be+no+more+than+63+characters&oq=kubernetes+label+must+be+no+more+than+63+characters&aqs=chrome..69i57.5101j0j7&sourceid=chrome&ie=UTF-8) on this subject. Most relevant one probably is the [StackOverflow discussion](https://stackoverflow.com/questions/50412837/kubernetes-label-name-63-character-limit).

It seems you're running this on some automation. Is there a reason to not restrict the automated names to be under 63? Note also, SCDF would append `v1`, `v2` as suffixes on rolling upgrades on top of the pod labels/names.

**Comment by allanmoso** [comment]
I understand @sabbyanandan . I think the stacktrace might have been more confusing than helpful. I'm sorry about that.

The issue is that it doesn't completely prevent the stream from deploying. It partially deploys the stream. In my example where I had `time | groovy-transform | log`.  The `log` application still got deployed to Kubernetes after that error occured.  Also, the stream status is `Undeployed` and it doesn't allow me to undeploy the `log` stream application.

**Comment by allanmoso** [comment]
Also, just to clarify, I am not running this on an some automation.  The name is just that way because I am just testing the length of the name.

Also, the error regarding the name being more than 63 characters is not on the stream name but the `{stream-name}-{app-name}-{version-tag}`.  When creating streams on SCDF, you will not only need to pay attention to the length of the stream names, but also conscious about the length of the application names in your stream, and allow for enough characters for version increments.

**Comment by sabbyanandan** [comment]
Correct. The pod name is a "derived name" based on multiple things. That is by design. The `log-sink` could have deployed successfully because the name would have been `b12345678901234567890123456789012345678901234567890-log-v1` _(I derived it based on `groovy-transform-v1` name that was shared previously)_, and it is about 58 chars. 

Since it is a platform-specific requirement, there's nothing more we can do to work around it.

**Comment by allanmoso** [comment]
@sabbyanandan   I understand that name length is a Kubernetes requirement. But, SCDF is currently not able to handle the error gracefully; having applications deployed in Kubernetes that is no longer associated to SCDF streams is not good.  You cannot undeploy the orphaned applications (the stream is "Undeployed").  These orphaned applications do not show up as "running applications" in the Runtime page in SCDF; you will not know that there are deployed applications unless you look in your Kubernetes namespace.  In our restricted environment, I would have to contact the administrator to remove those orphaned applications everytime this happens.

Is there a way to allow these applications to be undeployed after this error happens so that we can clean it up?

Or maybe have a configurable stream name and application name length validation?

**Comment by sabbyanandan** [comment]
I'm back from the PTO and I looked at it closely today. I tried a similar stream and I ran into the error, of course. Specifically:

```
2019-03-19 21:54:43.898 ERROR 1 --- [nio-8080-exec-1] o.s.c.d.s.stream.SkipperStreamDeployer   : Skipper install failed. Deleting the package: b12345678901234567890123456789012345678901234567891
2019-03-19 21:54:43.965 ERROR 1 --- [nio-8080-exec-1] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

org.springframework.cloud.skipper.SkipperException: Could not install AppDeployRequest [[AppDeploymentRequest@1933f148 commandlineArguments = list[[empty]], deploymentProperties = map['spring.cloud.deployer.group' -> 'b12345678901234567890123456789012345678901234567891'], definition = [AppDefinition@3f5805ce name = 'groovy-transform-v1', properties = map['spring.metrics.export.triggers.application.includes' -> 'integration**', 'spring.cloud.dataflow.stream.app.label' -> 'groovy-transform', 'spring.cloud.stream.metrics.key' -> 'b12345678901234567890123456789012345678901234567891.groovy-transform.${spring.cloud.application.guid}', 'spring.cloud.stream.bindings.input.group' -> 'b12345678901234567890123456789012345678901234567891', 'spring.cloud.stream.bindings.output.producer.requiredGroups' -> 'b12345678901234567890123456789012345678901234567891', 'spring.cloud.stream.metrics.properties' -> 'spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*', 'spring.cloud.dataflow.stream.name' -> 'b12345678901234567890123456789012345678901234567891', 'spring.cloud.stream.bindings.output.destination' -> 'b12345678901234567890123456789012345678901234567891.groovy-transform', 'spring.cloud.dataflow.stream.app.type' -> 'processor', 'spring.cloud.stream.bindings.input.destination' -> 'b12345678901234567890123456789012345678901234567891.time']], resource = Docker Resource [docker:springcloudstream/groovy-transform-processor-kafka:2.1.0.RELEASE]]]  to platform [default].  Error Message = [Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/default/services?labelSelector=spring-app-id%3Db12345678901234567890123456789012345678901234567891-groovy-transform-v1. Message: unable to parse requirement: invalid label value: "b12345678901234567890123456789012345678901234567891-groovy-transform-v1": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=unable to parse requirement: invalid label value: "b12345678901234567890123456789012345678901234567891-groovy-transform-v1": must be no more than 63 characters, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.deployStream(SkipperStreamDeployer.java:254)
```

Looking at the following lines:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/51d191dba5562fafffe3488764895c16dc9a5486/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java#L246-L255

It does seem odd that on any or all exceptions, we are _already_ deleting the package from Skipper repository, which would mean we cannot clean up afterward because there's no footprint. Without the package in Skipper, we won't be able to list the stream and likewise to trigger the `stream destroy ...` at a later time. That's why ` b12345678901234567890123456789012345678901234567891-log-v1b7tg9` continues to run when the other apps failed to deploy.

```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Pods(default)[6] ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ NAME                                                                                  READY                       STATUS                        RESTARTS                       CPU                       MEM                       IP                                NODE                            QOS                               AGE                         │
│ b12345678901234567890123456789012345678901234567891-log-v1b7tg9                       1/1                         Running                       0                                                                                  172.17.0.11                       10.0.2.15                       Guaranteed                        59m                         │
│ my-release-data-flow-server-74db6cbc98-bt72v                                          1/1                         Running                       0                                                                                  172.17.0.6                        10.0.2.15                       BestEffort                        77m                         │
│ my-release-data-flow-skipper-96cb995db-kqzvf                                          1/1                         Running                       0                                                                                  172.17.0.7                        10.0.2.15                       BestEffort                        77m                         │
│ my-release-kafka-0                                                                    1/1                         Running                       0                                                                                  172.17.0.10                       10.0.2.15                       BestEffort                        77m                         │
│ my-release-mysql-55d447f9cf-mrcfz                                                     1/1                         Running                       0                                                                                  172.17.0.9                        10.0.2.15                       Burstable                         77m                         │
│ my-release-zookeeper-0                                                                1/1                         Running                       0                                                                                  172.17.0.8                        10.0.2.15                       BestEffort                        77m                         │
│                                                                                                                                                                                                                                                                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

There must be some reasons for this design choice, so let's see what @ilayaperumalg or @markpollack have had to say.

**Comment by sabbyanandan** [comment]
cc:/ @jeffgbutler

**Comment by ilayaperumalg** [comment]
It looks like a bug. The deletion of package upon stream deploy failure was introduced to fix this https://github.com/spring-cloud/spring-cloud-dataflow/issues/2225. I think we need to also issue stream undeployment request for the apps that are deployed so far.

**Comment by markpollack** [comment]
We will also address in skipper the case of failed application deployments and final name length checks.
