### ISSUE TITLE
Spring Cloud Dataflow registered application (as Task) is NOT tirggering jobs

### ISSUE THREAD

**Issue by jobas2007** [spring-cloud/spring-cloud-dataflow#3153]
In Continuation of https://github.com/spring-cloud/spring-cloud-dataflow/issues/3116  , somehow was able to set up "Spring Cloud Dataflow Server local (SCDF)" as a spring boot project and was able to connect to Oracle 11.2  to have Task/Batch metadata tables created in schema.

The issue now i am still facing is that 'SCDF is still NOT recognizing  Spring Task/Batch "Jobs" and the "Jobs" are yet to be triggered when "triggering" the task from SCDF UI. 

The things could be more confusing because the Spring task/batch application is using 2 datasources (one for Spring Batch Metadata and one for application tables - details are in the issue https://github.com/spring-cloud/spring-cloud-task/issues/585   with github link)
and now have the SCDF datasource use the same as that used for Spring Batch Metadata.

Have uploaded the code to github 
SCDF local (as boot) - https://github.com/jobas2007/scdf-local-as-spring-boot
Spring Task/batch app - https://github.com/jobas2007/spring_proj

Appreciate any help or suggestion.

NOTE: i am using a slightly older version of SCDF, as that was the one more easy to set up as spring boot project, so appreciate if you can use the same as reference

**Comment by sabbyanandan** [comment]
Sorry to say this again, but we do not promote bundling SCDF into a new Spring Boot application - it is not recommended. We have never attempted to test any of this workflow in this angle, so it is likely you will run into one problem after another. I'm not sure what more we can do to help here.

Why can't you just clone/build SCDF with the Oracle driver from the source? You can build the source from the GA tag, too, so it would be the _released_ code/branch. Example: https://github.com/spring-cloud/spring-cloud-dataflow/tree/v1.7.4.RELEASE

**Comment by jobas2007** [comment]
Thanks for reply . Again as I understand, have bypassed the issue related to SCDF build / set up.

Keeping SCDF building aside , My core underlying problem is , when a standard application of type “Task” is registered with SCDF ( even when I am using SCDF directly as JAR downloaded from repo 1, that is connecting to MySQL ) , and when a “Task” is created out of registered application , the launch of task is NOT triggering the underlying batch “job”.

Again this could be happening because my application is using 2 data sources ( one for spring metadata and second for application ) which is causing me to force to disable “ spring batch “ auto configuration and to use custom “ batch configurer “ , along with using different properties keys ( that one used with auto configuration . For example , using ‘spring.batch.datasource.url’ than standard ‘spring.datasource.url’ [which is also used by standard data flow ]) . Unsure , if using different data source properties and disabling spring batch auto enabled is causing this behavior ? My sample spring batch app with 2 datasoruces is on github ( poster in previous post). Appreciate any help

**Comment by jobas2007** [comment]
Further tried option of enabling Spring Batch Job Enabled into the Spring Batch/Task Application, (by spring.batch.job.enabled=true), which does seems to at least trigger the batch jobs when "Task" is launched from Spring Cloud Data Flow, but then got below exception (which appear to be related to some kind of transaction locking) :


**2019-04-14 11:54:30,753 ERROR org.springframework.boot.SpringApplication [main] Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringA**pplication.java:816)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.db.sts.marketdata.MarketDataApplication.main(MarketDataApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.dao.CannotSerializeTransactionException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; ORA-08177: can't serialize access for this transaction
; nested exception is java.sql.SQLException: ORA-08177: can't serialize access for this transaction

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:270)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1442)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:632)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:861)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:916)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:921)
	at org.springframework.batch.core.repository.dao.JdbcJobInstanceDao.createJobInstance(JdbcJobInstanceDao.java:117)
	at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:181)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy77.createJobExecution(Unknown Source)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy75.run(Unknown Source)
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.execute(JobLauncherCommandLineRunner.java:214)
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.executeLocalJobs(JobLauncherCommandLineRunner.java:186)
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.launchJobFromProperties(JobLauncherCommandLineRunner.java:172)
	at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.run(JobLauncherCommandLineRunner.java:166)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
	... 13 common frames omitted
**Caused by: java.sql.SQLException: ORA-08177: can't serialize access for this transaction**

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3665)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1352)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:866)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:616)
	... 49 common frames omitted

**Comment by cppwfs** [comment]
This is being discussed in Spring Cloud Task issue: https://github.com/spring-cloud/spring-cloud-task/issues/594   Closing this here because it's a duplicate post.
