### ISSUE TITLE
can not run on wondows 10 use the docker-compose

### ISSUE THREAD

**Issue by jinxiyin** [spring-cloud/spring-cloud-dataflow#3179]
1.download the docker-compose.yml to windows 10 'C:\open-data\data-flow'
https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.1.0.M1/spring-cloud-dataflow-server/docker-compose.yml
2.install Docker for Windows Installer.exe 2.0.0.3 
Docker Engine 18.09.2 Compose 1.23.2
3.open the powershell execute：
```
set DATAFLOW_VERSION=2.1.0.M1
set SKIPPER_VERSION=2.0.2.RC1
docker-compose up
```

4.the error
```
C:\open-data\data-flow>docker-compose up
[0x7FFE972063B0] ANOMALY: meaningless REX prefix used
Pulling zookeeper (confluentinc/cp-zookeeper:5.2.1)...
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1080, in up
  File "compose\cli\main.py", line 1076, in up
  File "compose\project.py", line 475, in up
  File "compose\service.py", line 352, in ensure_image_exists
  File "compose\service.py", line 1217, in pull
  File "compose\progress_stream.py", line 101, in get_digest_from_pull
  File "compose\service.py", line 1182, in _do_pull
  File "site-packages\docker\api\image.py", line 381, in pull
  File "site-packages\docker\auth.py", line 48, in get_config_header
  File "site-packages\docker\auth.py", line 96, in resolve_authconfig
  File "site-packages\docker\auth.py", line 129, in _resolve_authconfig_credstore
  File "site-packages\dockerpycreds\store.py", line 36, in get
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 342, in decode
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 94)
[7140] Failed to execute script docker-compose
```

**Comment by sabbyanandan** [comment]
Hi, @jinxiyin. There are multiple hits in [Google search](https://www.google.com/search?q=ANOMALY%3A+meaningless+REX+prefix+used&oq=ANOMALY%3A+meaningless+REX+prefix+used&aqs=chrome..69i57j69i58.291j0j7&sourceid=chrome&ie=UTF-8) of this error, which hints to issues pertaining to drivers and/or software patches installed in the Windows box. Have you tried running any other docker-compose deployments?

For validation, you could run Kafka standalone with [Docker Compose](https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html). I'd assume you will see the same error here as well.

Until you resolve this, I'm not sure what more we can do to assist. I will close this for now but feel free to drop a comment if you see any issues related to SCDF, we can reopen then.
