### ISSUE TITLE
Adding an application with a period in the name field renders the app overview page unusable 

### ISSUE THREAD

**Issue by driesdeproost** [spring-cloud/spring-cloud-dataflow#3244]
**Description:**
When adding an application through the dashboard there seems to be no validation on the name. It is thus possible for users to enter names with periods in it, like in a version number. Having a period in the name produces the stacktrace attached at the bottom of this issue report. The big problem is that the Apps overview page will be loading forever and the users won't even be able to delete there erroneously added application.

This issue occurs both when adding a task through filesystem or maven URI.  

I think this is an important issue since it might scare off potential users that want to try out the sample setup and enter an app name with a version number. Just some validation on the input fields as to not allow periods could help greatly already.

**Release versions:**

- I set this up using docker, image: `springcloud/spring-cloud-dataflow-server-local:2.0.0.M2`

- about JSON:  
`{"featureInfo":{"analyticsEnabled":true,"streamsEnabled":true,"tasksEnabled":true,"skipperEnabled":false,"schedulerEnabled":false},"versionInfo":{"implementation":{"name":"spring-cloud-dataflow-server-local","version":"1.7.0.RELEASE"},"core":{"name":"Spring Cloud Data Flow Core","version":"1.7.0.RELEASE"},"dashboard":{"name":"Spring Cloud Dataflow UI","version":"1.7.0.RELEASE"},"shell":{"name":"Spring Cloud Data Flow Shell","version":"1.7.0.RELEASE","url":"https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.7.0.RELEASE/spring-cloud-dataflow-shell-1.7.0.RELEASE.jar"}},"securityInfo":{"authenticationEnabled":false,"authorizationEnabled":false,"formLogin":false,"authenticated":false,"username":null,"roles":[]},"runtimeEnvironment":{"appDeployer":{"deployerImplementationVersion":"1.3.9.RELEASE","deployerName":"LocalAppDeployer","deployerSpiVersion":"1.3.4.RELEASE","javaVersion":"1.8.0_192","platformApiVersion":"Linux 4.15.0-48-generic","platformClientVersion":"4.15.0-48-generic","platformHostVersion":"4.15.0-48-generic","platformSpecificInfo":{},"platformType":"Local","springBootVersion":"1.5.16.RELEASE","springVersion":"4.3.19.RELEASE"},"taskLauncher":{"deployerImplementationVersion":"1.3.9.RELEASE","deployerName":"LocalTaskLauncher","deployerSpiVersion":"1.3.4.RELEASE","javaVersion":"1.8.0_192","platformApiVersion":"Linux 4.15.0-48-generic","platformClientVersion":"4.15.0-48-generic","platformHostVersion":"4.15.0-48-generic","platformSpecificInfo":{},"platformType":"Local","springBootVersion":"1.5.16.RELEASE","springVersion":"4.3.19.RELEASE"}},"_links":{"self":{"href":"http://localhost:9393/about"}}}`

**Custom apps:**

**Steps to reproduce:**
- Add a task at `http://yourserver:9393/dashboard/#/apps/add/register` and make sure to enter a name with a period in it.
- Try to got to te Apps overview page at  `http://yourserver:9393/dashboard/#/apps`

**Screenshots:**
Defining the task with a period:  
![image](https://user-images.githubusercontent.com/14177727/57915654-88124300-7891-11e9-8c72-4a37a24eea77.png)
Trying to use the Apps overview page afterwards:  
![image](https://user-images.githubusercontent.com/14177727/57915699-a11af400-7891-11e9-9531-63471deefb09.png)

**Additional context:**
stacktrace:
```2019-05-17 08:34:59.044  INFO 1 --- [Pool-1-worker-2] o.s.c.d.s.c.AppRegistryController        : Eagerly fetching maven://eu.xenit.dataflow.task:apix-export:jar:1.0.2-SNAPSHOT
2019-05-17 08:34:59.123 ERROR 1 --- [io-9393-exec-10] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.IllegalArgumentException: Invalid format for app key 'task.app-with-version-1.0.2.metadata'in file. Must be <type>.<name> or <type>.<name>.metadata
	at org.springframework.util.Assert.isTrue(Assert.java:92) ~[spring-core-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.cloud.dataflow.registry.AppRegistry.toValidAppRegistration(AppRegistry.java:145) ~[spring-cloud-dataflow-registry-1.7.0.RELEASE.jar!/:1.7.0.RELEASE]
	at org.springframework.cloud.dataflow.registry.AppRegistry.lambda$findAll$1(AppRegistry.java:96) ~[spring-cloud-dataflow-registry-1.7.0.RELEASE.jar!/:1.7.0.RELEASE]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[na:1.8.0_192]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[na:1.8.0_192]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_192]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_192]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_192]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_192]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_192]
	at org.springframework.cloud.dataflow.registry.AppRegistry.findAll(AppRegistry.java:98) ~[spring-cloud-dataflow-registry-1.7.0.RELEASE.jar!/:1.7.0.RELEASE]
	at org.springframework.cloud.dataflow.registry.AppRegistry.findAll(AppRegistry.java:102) ~[spring-cloud-dataflow-registry-1.7.0.RELEASE.jar!/:1.7.0.RELEASE]
	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.list(AppRegistryController.java:120) ~[spring-cloud-dataflow-server-core-1.7.0.RELEASE.jar!/:1.7.0.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849) ~[spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760) ~[spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111) [spring-boot-actuator-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208) [spring-security-web-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) [spring-security-web-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103) [spring-boot-actuator-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

2019-05-17 08:34:59.133  WARN 1 --- [io-9393-exec-10] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [java.lang.IllegalArgumentException: Invalid format for app key 'task.app-with-version-1.0.2.metadata'in file. Must be <type>.<name> or <type>.<name>.metadata]
```

**Comment by sabbyanandan** [comment]
Hi, @driesdeproost. Thanks for the details. It seems like, with bogus entries to the app registry, someone can corner themselves and not be able to use the Apps page in the Dashboard. 

However, I tried the same scenario in 2.0.2 and 2.1.0 RC1, and in both, I was able to register the following apps without any issues. The Apps page in the Dashboard loads successfully after the new entries, too.

1) Shell:

> dataflow:>app register --name app-with-version-1.0.2 --type task --uri maven://org.springframework.cloud.stream.app:cassandra-sink-rabbit:2.1.0.RELEASE

2) Dashboard:
![image](https://user-images.githubusercontent.com/1562654/57931994-a9ae0300-786e-11e9-9c92-4d8004d79c8a.png)

**Comment by sabbyanandan** [comment]
I notice from your description that you're using `springcloud/spring-cloud-dataflow-server-local:2.0.0.M2` - what is this image? There's no such tag that exists for this image! (see [here](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-local/tags))

Starting from v2.0.x, we have a single server and that goes by the name: `springcloud/spring-cloud-dataflow-server`, and the latest tags for this image are [here](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server/tags).

**Comment by driesdeproost** [comment]
Hi @sabbyanandan

Thanks for the quick feedback! Next week, I will try out one of the images from `springcloud/spring-cloud-dataflow-server` instead of `springcloud/spring-cloud-dataflow-server-local:2.0.0.M2` and report back!

As for the image that I'm using, the tag does exist at the [link](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-local/tags) you provided. For me it's the fifth entry.
![image](https://user-images.githubusercontent.com/14177727/57933395-852d4780-78bd-11e9-8127-19091a855c43.png)

I will set a reminder to test out and report back next week. Thanks for the help so far, have a nice weekend!

**Comment by sabbyanandan** [comment]
Ah, I missed that! Right after the 2.0 M2 is when we might have decided to rename to consolidate all platform-specific implementation into a single Spring Boot application. That's why you still see that image.

All that said, please do give 2.0.2 or 2.1.0.RC1 a try and let us if you see any issues with it.

**Comment by driesdeproost** [comment]
@sabbyanandan 
I gave `springcloud/spring-cloud-dataflow-server:2.1.0.RELEASE` a try and it seems to be fixed in the newer images indeed!

Thanks for your help!

**Comment by sabbyanandan** [comment]
Glad you're unblocked now. 😄
