### ISSUE TITLE
Spring Cloud data flow server stream with access to persistent volume

### ISSUE THREAD

**Issue by durgadevikarthikeyan** [spring-cloud/spring-cloud-dataflow#3251]
Hi Team, 
I am trying to setup persistent volume for scdf stream
I already posted a question and got response we need to follow this link
[(https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_running_the_demo_3)]
i started setting up the things as mentioned the document but ended up in the below error  when deploying the stream

`dataflow:>stream deploy inboundSftp --properties 'deployer.sftp.kubernetes.volumes=[{"name":"mypvc","persistentVolumeClaim":{"claimName":"nfs"}}],deployer.sftp.kubernetes.volumeMounts=[{"mountPath":"/exports","name":"mypvc"}],deployer.*.kubernetes.bootMajorVersion=2'
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Error waiting to get Release from a statemachine
Error waiting to get Release from a statemachine
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Error waiting to get Release from a statemachine
    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65)
    at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:414)
    at org.springframework.cloud.dataflow.rest.client.StreamTemplate.deploy(StreamTemplate.java:127)
    at org.springframework.cloud.dataflow.shell.command.StreamCommands.deployStream(StreamCommands.java:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:246)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:748)
`

Actually my requirement is scdf stream kubernetes pods should get associated with persistent volumes when it is getting deployed

Any help will be really appreciated

**Comment by sabbyanandan** [comment]
Hi, @durgadevikarthikeyan. Questions like this are better to be discussed in StackOverflow. We use GitHub for feature requests and/or bug-reports. 

Since we are already discussing this in Gitter, I'm closing this.
