### ISSUE TITLE
Restarting a failed job results with IllegalStateException

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3257]
As a user, when attempting to restart a failed job from the dashboard, I encounter the following exception. All this on v2.1 Docker Compose based release versions.

```
dataflow-server      | 2019-05-30 01:21:42.094  INFO 1 --- [nio-9393-exec-5] o.s.c.d.s.s.impl.DefaultTaskJobService   : Restarting Job with Id 17
dataflow-server      | 2019-05-30 01:21:42.115 ERROR 1 --- [nio-9393-exec-5] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
dataflow-server      |
dataflow-server      | java.lang.IllegalStateException: Did not find platform for taskName=[ComposedTask] , taskId=[17]
dataflow-server      |  at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService.restartJobExecution(DefaultTaskJobService.java:202)
dataflow-server      |  at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService$$FastClassBySpringCGLIB$$d486827e.invoke(<generated>)
dataflow-server      |  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
dataflow-server      |  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
dataflow-server      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
dataflow-server      |  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
dataflow-server      |  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
dataflow-server      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dataflow-server      |  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
dataflow-server      |  at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService$$EnhancerBySpringCGLIB$$d78e4062.restartJobExecution(<generated>)
dataflow-server      |  at org.springframework.cloud.dataflow.server.controller.JobExecutionController.restartJobExecution(JobExecutionController.java:163)
dataflow-server      |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataflow-server      |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
dataflow-server      |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dataflow-server      |  at java.lang.reflect.Method.invoke(Method.java:498)
dataflow-server      |  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
dataflow-server      |  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
dataflow-server      |  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
dataflow-server      |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
dataflow-server      |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
dataflow-server      |  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
dataflow-server      |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
dataflow-server      |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
dataflow-server      |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
dataflow-server      |  at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:919)
dataflow-server      |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:663)
dataflow-server      |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
dataflow-server      |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server      |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server      |  at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
dataflow-server      |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server      |  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
dataflow-server      |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server      |  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
dataflow-server      |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server      |  at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
dataflow-server      |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server      |  at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
dataflow-server      |  at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
dataflow-server      |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server      |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
dataflow-server      |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server      |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server      |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
dataflow-server      |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
dataflow-server      |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
dataflow-server      |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
dataflow-server      |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
dataflow-server      |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
dataflow-server      |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
dataflow-server      |  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
dataflow-server      |  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
dataflow-server      |  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
dataflow-server      |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
dataflow-server      |  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
dataflow-server      |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dataflow-server      |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dataflow-server      |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
dataflow-server      |  at java.lang.Thread.run(Thread.java:748)
dataflow-server      |
```

While the initial launch goes through successfully, it appears that the platform configuration is missing when restarting the same job from the failed step.

**Comment by cppwfs** [comment]
The issue lies in the following sections of code: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java#L194-L204
and
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java#L163-L170

[Background]
Currently DefaultTaskJobService requires the `platform name` in order to restart a job.   It tries to obtain this information from the deployment repository using the JobExecutionId.  

[Issue]
The DefaultTaskJobService tries to obtain the `platform name` from the DeploymentRepository using the `JobExecutionId`.   This will not work, because the `JobExecutionId` is not the `deploymentid`.  

[Resolution]
Since the DeploymentID is not stored till after the Task is launched, we have to store the `platform name` in the JobParameters of the Job at task launch time.  This is so that when the job is restarted using the DefaultTaskJobService, it can obtain the `platform name` from the job.  Thus bypassing the need for the DeploymentRepository.
