### ISSUE TITLE
NPE when registering the app without the app resolution schema

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3264]
As a user, I copied the following app registration command from the [Microsite](https://dataflow.spring.io/docs/recipes/polyglot/processor/), but it failed with an NPE.

register:
```
app register --type processor --name python-processor --uri springcloud/polyglot-python-processor:0.1
```

error:
```
2019-06-04 22:03:20.278 ERROR 1 --- [nio-8080-exec-9] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request                                   │
│                                                                                                                                                                              │
│ java.lang.NullPointerException: null                                                                                                                                         │
│     at org.springframework.cloud.dataflow.registry.support.AppResourceCommon.getResource(AppResourceCommon.java:154)                                                         │
│     at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.getResourceVersion(DefaultAppRegistryService.java:266)
```

1) We need to add `docker:` schema in the microsite instructions
2) Handle the NPE gracefully

**Comment by sabbyanandan** [comment]
The microsite bugs were fixed via:

https://github.com/spring-io/dataflow.spring.io/pull/84
https://github.com/spring-cloud/spring-cloud-dataflow-samples/pull/104
