### ISSUE TITLE
scdf k8s scheduler task failed mount volume in tasks

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3324]
**Description:**
As a user, i create a schedule task, with  params

``scheduler.kubernetes.taskServiceAccountName=scdf2-server-data-flow
scheduler.kubernetes.kubernetes.volumeMounts=[{name: secret-volume, mountPath: '/etc/secret-volume'},{name: 'logback', mountPath: '/etc/logback'},{name: 'logpath', mountPath: '/etc/mklog'}]`` 

Then, all task launched by cronjob using a scheduler mask ' * * * * *' , should be to get volume mounted.

but, i get following stacktrace:

````
Namespace default
Logs from  a9  in  a9-1562750280-9hcqt
     
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.2.RELEASE)
2019-07-10 11:18:13.580  INFO 1 --- [           main] m.t.a.a.AdobeAnalyticsApplication        : The following profiles are active: kubernetes
2019-07-10 11:18:14.898  WARN 1 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2019-07-10 11:18:15.519 ERROR 1 --- [           main] m.t.a.a.c.AdobeAnalyticsConfiguration    : There was an error loading secret: "ssaas.crt".
2019-07-10 11:18:15.520  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'adobeAnalyticsService': Unsatisfied dependency expressed through field 'sftpService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sftpService': Unsatisfied dependency expressed through field 'saaasService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ssaasService': Unsatisfied dependency expressed through field 'httpClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'httpClient' defined in class path resource [mk/task/adobe/analitycs/config/AdobeAnalyticsConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.http.client.HttpClient]: Factory method 'httpClient' threw exception; nested exception is BadSecretException()
2019-07-10 11:18:15.548 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'adobeAnalyticsService': Unsatisfied dependency expressed through field 'sftpService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sftpService': Unsatisfied dependency expressed through field 'sssaasService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sssasService': Unsatisfied dependency expressed through field 'httpClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'httpClient' defined in class path resource [mk/task/adobe/analitycs/config/AdobeAnalyticsConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.http.client.HttpClient]: Factory method 'httpClient' threw exception; nested exception is BadSecretException()
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at mk.task.adobe.analitycs.AdobeAnalyticsApplication.main(AdobeAnalyticsApplication.java:14) [classes/:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sftpService': Unsatisfied dependency expressed through field 'sssaasService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sssasService': Unsatisfied dependency expressed through field 'httpClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'httpClient' defined in class path resource [mk/task/adobe/analitycs/config/AdobeAnalyticsConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.http.client.HttpClient]: Factory method 'httpClient' threw exception; nested exception is BadSecretException() rg.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
````
The message is descriptive, failed to mount secrets into volumen.
`` There was an error loading secret: "sssas.crt".`` 

but, if i launch the same task without scheduler, runs ok, mounting volumens with secrets.

I've read documentation about scheduler and i cant get it works

**Release versions:**
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.1.2.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.1.2.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.1.2.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.1.2.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.1.2.RELEASE/spring-cloud-dataflow-shell-2.1.2.RELEASE.jar"
    }
  },
  "featureInfo": {
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulesEnabled": true,
    "grafanaEnabled": true
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "2.0.2.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.0.3.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.1.3.RELEASE",
      "springVersion": "5.1.5.RELEASE"
    },
    "taskLaunchers": [
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.2.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.2.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      },
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.2.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.2.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      },
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.2.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.2.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      },
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.2.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.2.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      }
    ]
  },
  "grafanaInfo": {
    "url": "http://localhost:3000",
    "token": "",
    "refreshInterval": 15
  }
}

**Custom apps:**
Simple task date time log

**Steps to reproduce:**
schedule a task

**Screenshots:**
Where applicable, add screenshots to help explain your problem.

![imagen](https://user-images.githubusercontent.com/1777753/60959113-ec88d600-a307-11e9-8490-d545e95be731.png)

![imagen](https://user-images.githubusercontent.com/1777753/60959257-2bb72700-a308-11e9-8791-87742dfde717.png)

![imagen](https://user-images.githubusercontent.com/1777753/60959131-f4e11100-a307-11e9-8166-547810655310.png)

**Additional context:**

**Comment by sabbyanandan** [comment]
Hi, @eskuai. It appears you're opening new issues with version details and screenshots, but there's really nothing pertaining to what you're attempting to do. There are no stream/task definitions or there's any indication to the steps what you did. There's not much information to help.

Looking at the stacktrace, though, it seems your custom `adobeAnalyticsService` is choking not able to find a required service, which in turn appears to rely on some secret. Without seeing the actual code and your secrets configurations, we won't be able to comment as to what is missing.

> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'adobeAnalyticsService': Unsatisfied dependency expressed through field 'sftpService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sftpService': Unsatisfied dependency expressed through field 'sssaasService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sssasService': Unsatisfied dependency expressed through field 'httpClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'httpClient' defined in class path resource [mk/task/adobe/analitycs/config/AdobeAnalyticsConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.http.client.HttpClient]: Factory method 'httpClient' threw exception; nested exception is BadSecretException()

All that said, questions like this are better discussed in StackOverflow or Gitter. Please open new issues only if you there's a feature request or you have a reproducible bug similar to the ones you opened re: timezone + formatting errors in the UI.

**Comment by eskuai** [comment]
Hi @sabbyanandan .

Using scdf with k8s,  the requirement to access to secret using volumens and pvcs required a mapping to to the secret - scdf need to declare the following properties as i write at first lines from 

```scheduler.kubernetes.taskServiceAccountName=scdf2-server-data-flow scheduler.kubernetes.kubernetes.volumeMounts=[{name: secret-volume, mountPath: '/etc/secret-volume'},{name: 'logback', mountPath: '/etc/logback'},{name: 'logpath', mountPath: '/etc/mklog'}]
```
Using  theses properties  deploying task or streams are running ok ( deployer.,* as needed), but using "scheduler" , nor volumen is mounted neither access to underlay resource.

**Comment by sabbyanandan** [comment]
I just realized that volume mounts are not supported in K8s-deployer. See: https://github.com/spring-cloud/spring-cloud-scheduler-kubernetes/issues/21 -- until that is supported, you won't be able to do that.
