### ISSUE TITLE
Task launch fails when "default" platform configuration isn't set

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3367]
As a user, I have a custom platform configuration for Task launches (see below); however, when launching the Task without the `platformName`, I get the following error.

Config:
```
    MAVEN_REMOTEREPOSITORIES[REPO1]_URL: http://repo.spring.io/test-libs-snapshot-local
    SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[sabbycfdev]_CONNECTION_URL: 
    SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[sabbycfdev]_CONNECTION_ORG: 
    SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[sabbycfdev]_CONNECTION_SPACE: 
    SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[sabbycfdev]_CONNECTION_DOMAIN: 
    SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[sabbycfdev]_CONNECTION_USERNAME: 
    SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[sabbycfdev]_CONNECTION_PASSWORD: 
    SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[sabbycfdev]_DEPLOYMENT_SERVICES: 
    SPRING_PROFILES_ACTIVE: cloud
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
```

Error:
```
dataflow:>task launch --name task1
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: No Launcher found for the platform named 'default'.  Available platform names are [sabbycfdev]
No Launcher found for the platform named 'default'.  Available platform names are [sabbycfdev]
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: No Launcher found for the platform named 'default'.  Available platform names are [sabbycfdev]
    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65)
    at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:414)
    at org.springframework.cloud.dataflow.rest.client.TaskTemplate.launch(TaskTemplate.java:162)
    at org.springframework.cloud.dataflow.shell.command.TaskCommands.launch(TaskCommands.java:222)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:748)
```
Since I only have 1 platform defined, it'd be nice to use that instead of complaining about no "default" platform. 

At the same time, it'd be better to throw this error, when  "default" is not available, but if we have >1 platform configurations. In other words, it is the user's responsibility to make a decision as to where to launch the Task.

Also: What do we do for Streams in Skipper?

**Comment by sabbyanandan** [comment]
**Update:** As the next steps, we will adapt the platform resolution design as described in https://github.com/spring-cloud/spring-cloud-skipper/issues/901, so for both Streams and Tasks, we will have consistent behavior.
