### ISSUE TITLE
Move to spring security oauth support

### ISSUE THREAD

**Issue by Tetradeus** [spring-cloud/spring-cloud-dataflow#3370]
**Problem description:**
Right now the project is using Spring Security Oauth Project.
Since spring security 5.1+, there is now a (better ? simpler ?) support for oauth and openid.
https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix

I tried to setup openid or even just oauth2 with Azure AD and it has been a burden for several reason with the actual implementation. (Validation of token via endpoint instead of validation of jwt token with JWK, no openid token support required to get groups claims, ...) 

Moreover, I do not even understand why there are Spring Dataflow specificities directly in spring security oauth jars.

**Solution description:**
Last openid implementation of spring security is quite simple to setup with most well known providers.

** Azure temp solution **
I had to copy org.springframework.cloud.common.security.OAuthSecurityConfiguration
without TokenValidatingUserInfoTokenServices bean, but with these beans (copied from JWK support !)

```java
  @Bean
  public DefaultTokenServices jwkTokenServices(TokenStore jwkTokenStore) {
    DefaultTokenServices services = new DefaultTokenServices();
    services.setTokenStore(jwkTokenStore);
    return services;
  }

  @Bean
  public TokenStore jwkTokenStore() {
    return new JwkTokenStore("https://login.microsoftonline.com/xxx/discovery/keys");
  }
```

**Comment by sabbyanandan** [comment]
Hi, @Tetradeus. It is unclear as to what release you are using. However, starting from SCDF v.2.0 and onwards (currently at v2.2), we have already defaulted to OAuth/OIDC as the default mechanism for authentication and authorization. 

Specifically, we rely on Spring Security's 5.1.x to integrate and expose the various security options with the help of UAA. A thorough walkthrough of all the steps involved in this transition is documented at https://github.com/spring-cloud/spring-cloud-dataflow/issues/2574 - please pay attention to the checkboxes.

There are improvements in the pipeline for Spring Security 5.2.x (e.g., Opaque tokens), and we aim to revise the security in SCDF when 5.2.x ships to a GA release. Also, there's Spring Security OAuth2 and Spring Security - 2 projects - until everything formally moves into Spring Security, we won't be able to make the switch yet.

All that said,

> I tried to setup openid or even just oauth2 with Azure AD and it has been a burden for several reason with the actual implementation. (Validation of token via endpoint instead of validation of jwt token with JWK, no openid token support required to get groups claims, ...)

I'd appreciate if you can share more details here. Perhaps even a sample of your configurations (sensitive properties redacted, of course). The more information we have, the better it would be for us to review to see what can be improved in this area.

**Comment by Tetradeus** [comment]
Hi @sabbyanandan, thank you for your reply.
I am using SCDF v2.1. I looked at oauth/openid support in this version. However, the default configuration looks to be incompatible with Azure AD open id support.

The first issue I hit with Azure AD is about token validation. UAA has a check token endpoint.
You can then use security.oauth2.resource.token-info-uri and security.oauth2.resource.user-info-uri.
Azure does not have such "check token endpoint" : 
https://stackoverflow.com/questions/12296017/how-to-validate-an-oauth-2-0-access-token-for-a-resource-server

Tokens are jwt and must be validated with jwk key set. I am pretty sure it is the same thing with AWS Cognito.
I should then use jwk key set to validate the access token (https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/html/boot-features-security-oauth2-resource-server.html)

I then replace security.oauth2.resource.token-info-uri and security.oauth2.resource.user-info-uri with
resource.jwk.key-set-uri.

Now I get this error : 
```

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.common.security.OAuthSecurityConfiguration$ResourceServerConfiguration': Unsatisfied dependency expressed through field 'resourceServerTokenServices'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceServerTokenServices' defined in class path resource [org/springframework/cloud/common/security/OAuthSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.common.security.support.TokenValidatingUserInfoTokenServices]: Factory method 'resourceServerTokenServices' threw exception; nested exception is java.lang.IllegalArgumentException: The userInfoEndpointUrl must be set.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at com.landy.tools.springclouddataflowserver.SpringCloudDataflowServerApplication.main(SpringCloudDataflowServerApplication.java:12) ~[classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceServerTokenServices' defined in class path resource [org/springframework/cloud/common/security/OAuthSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.common.security.support.TokenValidatingUserInfoTokenServices]: Factory method 'resourceServerTokenServices' threw exception; nested exception is java.lang.IllegalArgumentException: The userInfoEndpointUrl must be set.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.common.security.support.TokenValidatingUserInfoTokenServices]: Factory method 'resourceServerTokenServices' threw exception; nested exception is java.lang.IllegalArgumentException: The userInfoEndpointUrl must be set.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 32 common frames omitted
Caused by: java.lang.IllegalArgumentException: The userInfoEndpointUrl must be set.
```

Indeed, this bean is directly declared in org.springframework.cloud.common.security.OAuthSecurityConfiguration so we cannot beneficiate from autoconfiguration of this class org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerTokenServicesConfiguration that is supposed to create the token service based on these properties.

This is why I had to redefine a copy of OAuthSecurityConfiguration with the jwk default token service.

Now I am able to connect thanks to an access token (not an id token).

The second point is about openid support. I am not sure of my understanding but looking at the way azure ad spec for open id works, in order to get an id token, reponse_type must include "id_token" :
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code#send-the-sign-in-request

The problem is that this reponse_type is hard coded here : 
org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.java:331 -> 		requestParameters.put("response_type", "code"); // oauth2 spec, section 3

The "nonce" parameter is also required and not sent.

Now if I would like an id_token I must also rewrite this part ....

I know that spring security 5 oauth support is not complete yet, but at list the open id connect support really looks to be better supported and simpler to use with common open id servers. Several services already using it are working very well. 

On other services we did, it works with this configuration :
```
spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
            client-name: azure
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/xxx/oauth2/authorize
            token-uri: https://login.microsoftonline.com/xxx/oauth2/token
            jwk-set-uri: https://login.microsoftonline.com/xxx/discovery/keys
            user-info-uri: https://login.microsoftonline.com/xxxd/openid/userinfo
            logout-uri: https://login.microsoftonline.com/xxx/oauth2/logout
            description-uri: https://login.microsoftonline.com/xxx/.well-known/openid-configuration
            userNameAttribute: name
```

It may be good to ask spring security folks about their thinking for scdf ?

I hope it is clearer.

**Comment by sabbyanandan** [comment]
Thanks! That's a lot to grok here; unfortunately, I don't fully understand the Azure AD or its OIDC capabilities. I will have to request our security SME (cc:/ @ghillert) to review to see if there are anything as incremental improvements here.

Of course, the larger goal is to eventually move to Spring Security 5.2.x when that is ready for prime consumption.

**Comment by ghillert** [comment]
Hi @Tetradeus - Thank you for your submission. Let me try to answer the issue. First of all - Possibly we can+should add explicit support for Azure Active Directory.

The initial focus was UAA-support and originally, opaque token support was kind of the default. I still believe that Opaque Tokens are easier to reason about and easier to setup. I understand, though, that we should support JWT.

Regarding Spring Security 5.x:

We are actively tracking the support provided in Spring Security `5.x`. As you have noted yourself, the support in Spring Security itself is not on par yet with that was previously supported via Spring Security OAuth + Spring Boot (Now via https://github.com/spring-projects/spring-security-oauth2-boot).

Version `5.2` should have (almost) all relevant pieces to migrate over but it is not GA, yet. One thing we also wait for is the Migration Guide - https://github.com/spring-projects/spring-security/issues/6733. Currently it is still an open issue.

Caveat - ResourceServer support is not schedule before middle of next year (Spring Security `5.3.0`). Only used for testing, so I think we can work around that.

**Comment by Tetradeus** [comment]
Hello @ghillert ,

Thanks for these great feedbacks. I am happy to see that these issues/migrations are already in the scope of next versions.

**Comment by sabbyanandan** [comment]
@Tetradeus: Going forward, please follow https://github.com/spring-cloud/spring-cloud-dataflow/issues/3747 for updates. We have done rough experiments against Azure AD, and we plan on further exploring the best options to provide the pluggable support for identity providers.
