### ISSUE TITLE
Step execution list throws exception when a step execution status is UNKNOWN

### ISSUE THREAD

**Issue by svesch84** [spring-cloud/spring-cloud-dataflow#3381]
**Description:**
When I use the method stepExecutionList() of the org.springframework.cloud.dataflow.rest.client.JobOperations class I sporadically receive the following error: 

```
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Id must not be null!
        at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65) ~[spring-cloud-dataflow-rest-client-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:311) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
        at org.springframework.cloud.dataflow.rest.client.JobTemplate.stepExecutionList(JobTemplate.java:140) ~[spring-cloud-dataflow-rest-client-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at de.ubs.xdm3.core.dataflow.access.RestDataFlowAccess.getSteps(RestDataFlowAccess.java:262) ~[xdm3-core-dataflow-access-1.0-SNAPSHOT.jar!/:na]
```

**Release versions:**
Spring Boot: 2.1.1.RELEASE
Spring Cloud Data Flow: 2.1.2.RELEASE

**Steps to reproduce:**

1. Execute a SCDF Task that forks a spring batch job with a couple of steps. 

1. Actively polling the status of the running job sometimes causes the "Id must not be null!" error. 

**Screenshots:**
![screen](https://user-images.githubusercontent.com/45757892/61873274-d8d39700-aee5-11e9-826f-1c8cbce9d102.png)

**Comment by ilayaperumalg** [comment]
Hi @svesch84, 

Thanks for the detailed problem description. 

It appears that you have the step execution with the state `UNKNOWN`. This means that this step execution isn't part of any job execution at all (at least not persisted in the Batch job tables). 

Do you see this specific step completes eventually? or, does it fail?

Irrespective of that,  I think the REST response should handle the step execution with the null ID. Hence, this is a bug. Thanks for reporting!

**Comment by svesch84** [comment]
Hello ilayaperumalg, 
thanks for your fast response. The last step that had the status UNKNOWN actually completed successfully. I was also just wondering why the second step still hat the status STARTED and the last step already has the exist status EXECUTING. 

Let me know if you need any further information to fix that issue.

**Comment by cppwfs** [comment]
@svesch84 When the result list of steps is being populated, any Step that has not been executed is returned with a stubbed step execution entry.   And the default for the stubbed step execution is Executing.  I will update that as a part of this effort.
