### ISSUE TITLE
SCDF server customized for Oracel DB throw exceptions when the server starts at local

### ISSUE THREAD

**Issue by t873529** [spring-cloud/spring-cloud-dataflow#3387]
My steps:
1. I clone and made a local branch from tag v2.1.2.RELEASE. 
2.  I run mvnw clean install, success.
3. I import the  github.com\spring-cloud-dataflow\spring-cloud-dataflow-server to eclipse as java project. I change the pom.xml by adding com.oracle.jdbc : ojdbc8 : 18.3.0.0  at top entry inside dependencies. then I update the project in Eclipse. 
3. I run org.springframework.cloud.dataflow.server.single.DataFlowServerApplication as Java Application by setup arguments:
--spring.cloud.dataflow.features.streams-enabled=false 
--spring.datasource.driver-class-name=oracle.jdbc.OracleDriver 
--spring.datasource.url=jdbc:oracle:thin:@db:41521/FWDSPT 
--spring.datasource.username=user
--spring.datasource.password=pwd

Then I meet exceptions below.

My questions:  

Q1: Can this been fixed by change to a different version Oracle Jdbc driver? I tried 12.2.0.1 and 18.3.0.0, not working, same error.
Q2: Can the flyway be disabled by given additional arguments?
Q3: Not directly related, but helper. Is there a way to NOT build the customized server uber jar, in my local laptop, by run java command by giving additional arguments, for example, ojdbc8-12.2.0.1.jar  to overwrite the default jdbc jar? I am focus on evaluating the SCDF server alone with Orace DB. I have 2 Spring Batch applications. I want to see how the server's dashboard shows related to my running batch jobs.
Q4: I am OK to use older version of SCDF server. If I have to rebuild the server to connect to Oracle DB, which version of SCDF version  can I use to start build from?

Thanks,
Chen Wang

--

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.license.FlywayEnterpriseUpgradeRequiredException: Flyway Enterprise Edition or Oracle upgrade required: Oracle 11.2 is past regular support by Oracle and no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)
...
Caused by: org.flywaydb.core.internal.license.FlywayEnterpriseUpgradeRequiredException: Flyway Enterprise Edition or Oracle upgrade required: Oracle 11.2 is past regular support by Oracle and no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.
	at org.flywaydb.core.internal.database.base.Database.ensureDatabaseIsCompatibleWithFlywayEdition(Database.java:162)

**Comment by jvalkeal** [comment]
We currently depend on flyway so that's no workaround not using it. It's a driver giving DB version and looks like support for anything older than `12.2` has been dropped from a flyway community edition. Driver is telling you have `11.2` so any change using/trying with a newer version?

`1.7.x` line was a last one without flayway dependencies.

Theoretically it should be possible to unjar/jar a fatjar and add needed driver manually. I once tried to just add a driver to a fatjar using zip tools in ubuntu but that caused some errors in boot to read a jar. This was probably caused by zip itself and jdk's jar command would probably create a working package.

**Comment by t873529** [comment]
Driver is telling you have 11.2 so any change using/trying with a newer version?

Yes. I tried Oracle JDBC driver, versions: 12.2.0.1, 18.3.0.0 andeven 19.3.0.0 showed today. All have same exact error.  The flyway used in 2.1.2.RELEASE does NOT supporting Oracel by default.  The page ( https://flywaydb.org/download/ ) proves.

**Comment by jvalkeal** [comment]
I was referring to a an actual database version, not driver version. Didn't oracle `11.2` reach its end of life like 6 years ago so I'm not surprised that flyway has dropped support, at least from oss version.

**Comment by sabbyanandan** [comment]
@t873529: Do you have any other thoughts to share?

**Comment by sabbyanandan** [comment]
Closing this due to no activity.
