### ISSUE TITLE
Bulk destroy tasks throws error

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#3521]
Just created two tasks, `timestamp` and `t1:timestamp&&t2:timestamp`. From UI select all(4 as one is composed) and bulk destroy and I constantly get error like:
```
dataflow-server_1  | 
dataflow-server_1  | org.springframework.orm.ObjectOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: HikariProxyPreparedStatement@1601909279 wrapping prep115: delete from task_definitions where definition_name=? {1: 'task2-t1'}; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: HikariProxyPreparedStatement@1601909279 wrapping prep115: delete from task_definitions where definition_name=? {1: 'task2-t1'}
dataflow-server_1  | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:339)
dataflow-server_1  | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:254)
dataflow-server_1  | 	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:537)
dataflow-server_1  | 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:744)
dataflow-server_1  | 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:712)
dataflow-server_1  | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:619)
dataflow-server_1  | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:372)
dataflow-server_1  | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
dataflow-server_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dataflow-server_1  | 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
dataflow-server_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dataflow-server_1  | 	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
dataflow-server_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dataflow-server_1  | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
dataflow-server_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dataflow-server_1  | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
dataflow-server_1  | 	at com.sun.proxy.$Proxy189.deleteById(Unknown Source)
dataflow-server_1  | 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.destroyTask(DefaultTaskDeleteService.java:340)
dataflow-server_1  | 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.destroyPrimaryTask(DefaultTaskDeleteService.java:331)
dataflow-server_1  | 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.deleteTaskDefinition(DefaultTaskDeleteService.java:325)
dataflow-server_1  | 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.deleteTaskDefinition(DefaultTaskDeleteService.java:289)
dataflow-server_1  | 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService$$FastClassBySpringCGLIB$$13444684.invoke(<generated>)
dataflow-server_1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
dataflow-server_1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
dataflow-server_1  | 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService$$EnhancerBySpringCGLIB$$ddd5aac6.deleteTaskDefinition(<generated>)
dataflow-server_1  | 	at org.springframework.cloud.dataflow.server.controller.TaskDefinitionController.destroyTask(TaskDefinitionController.java:127)
dataflow-server_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataflow-server_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
dataflow-server_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dataflow-server_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
dataflow-server_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
dataflow-server_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
dataflow-server_1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
dataflow-server_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
dataflow-server_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
dataflow-server_1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
dataflow-server_1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
dataflow-server_1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
dataflow-server_1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
dataflow-server_1  | 	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931)
dataflow-server_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:666)
dataflow-server_1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
dataflow-server_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server_1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
dataflow-server_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server_1  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
dataflow-server_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server_1  | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
dataflow-server_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server_1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
dataflow-server_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
dataflow-server_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
dataflow-server_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
dataflow-server_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
dataflow-server_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
dataflow-server_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
dataflow-server_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
dataflow-server_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
dataflow-server_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
dataflow-server_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
dataflow-server_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
dataflow-server_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
dataflow-server_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dataflow-server_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dataflow-server_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
dataflow-server_1  | 	at java.lang.Thread.run(Thread.java:748)
dataflow-server_1  | Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: HikariProxyPreparedStatement@1601909279 wrapping prep115: delete from task_definitions where definition_name=? {1: 'task2-t1'}
dataflow-server_1  | 	at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)
dataflow-server_1  | 	at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)
dataflow-server_1  | 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
dataflow-server_1  | 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3519)
dataflow-server_1  | 	at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3778)
dataflow-server_1  | 	at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:100)
dataflow-server_1  | 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
dataflow-server_1  | 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478)
dataflow-server_1  | 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:361)
dataflow-server_1  | 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
dataflow-server_1  | 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1493)
dataflow-server_1  | 	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:496)
dataflow-server_1  | 	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3371)
dataflow-server_1  | 	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2540)
dataflow-server_1  | 	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473)
dataflow-server_1  | 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:178)
dataflow-server_1  | 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:39)
dataflow-server_1  | 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:271)
dataflow-server_1  | 	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
dataflow-server_1  | 	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:533)
dataflow-server_1  | 	... 80 common frames omitted
dataflow-server_1  | 
```

**Comment by sabbyanandan** [comment]
We have addressed a few improvements in this area recently. At least on 2.5, this problem doesn't surface, though.
