### ISSUE TITLE
Restricting concurrent task execution on Spring Cloud Data Flow

### ISSUE THREAD

**Issue by duyetphamm** [spring-cloud/spring-cloud-dataflow#3631]
I have deployed a Spring Batch project as a task on Spring Cloud Data Flow (Using @EnableTask).

I have used spring.cloud.task.singleInstanceEnabled=true to avoid relaunching task while task's status is still running on Spring Cloud Data Flow. This property is placed in application.properties of Spring Batch project. (following this link -- https://docs.spring.io/spring-cloud-task/docs/2.0.0.RELEASE/reference/htmlsingle/#_restricting_spring_cloud_task_instances)

However, the results are not as my expectation while testing:

1st time run: job A is launched successfully (about 15 minutes)

2nd time run: job A is launched again during 1st time run so it had the error:

ERROR o.s.c.t.l.TaskLifecycleListener - org.springframework.cloud.task.listener.TaskExecutionException: Failed to process @BeforeTask or @AfterTask annotation because: Task with name "A" is already running.
ERROR o.s.c.t.l.TaskLifecycleListener - An event to end a task has been received for a task that has not yet started.
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
...
Caused by: org.springframework.cloud.task.listener.TaskExecutionException: Failed to process @BeforeTask or @AfterTask annotation because: Task with name "A" is already running.
...
Caused by: java.lang.reflect.InvocationTargetException: null
...
Caused by: org.springframework.cloud.task.listener.TaskExecutionException: Task with name "A" is already running.
When I launch the job 2nd time the Spring Cloud Data Flow still show that Successfully launched task "A" but the log got error which I mentioned above.

And at the end, the status of Task is "ERROR" while the 1st time run is completed. ( I think the status should be COMPLETE because the job 1st time)

How can I restrict Spring Cloud Task Instances correctly?

**Comment by cppwfs** [comment]
Hello @duyetphamm,

You are using the `singleInstanceEnabled` properly in preventing a simultaneous execution of a task.  The issue comes in the interpretation of what the task definition page or the results of the `task list` command from the shell.   
SCDF's TaskDefinition page can only show you the state of the last execution of the task.  In that each task launch is an independent execution and the task definition page can only show you the state of the last finished execution of that task definition.   To get the detail you need you need to look at the task execution page.

**Comment by cppwfs** [comment]
After looking at the response in SO.  Can you rewrite your request to state something along the line of:
Need ability for Spring Cloud Data Flow to prevent a task execution from being launched for a specified task definition while a previously launched task execution from the same definition is running.

**Comment by duyetphamm** [comment]
Thank for your response Mr. Glenn Renfro. I have known that SCDF's TaskDefinition page can only show the state of the last execution of the task but why does my task in the 2nd time run throw the error? Are there anything wrong which my configurations (Because "Caused by: java.lang.reflect.InvocationTargetException: null")? In the other test case, I have waited for the task completing at the 1st time run, after that I have run the task again (2nd time run when the 1st time finished). However, It had the same error too! That mean I could not run the task anymore. Besides, I found 1 new row in TASK_LOCK table, When I deleted it, the task could be launched again.

**Comment by duyetphamm** [comment]
There are some information of my project:
_ I used spring-cloud-starter-task version 2.1.0.RELEASE which called spring-cloud-task-core version 2.1.0.RELEASE (are there any differences with https://github.com/cppwfs/spring-cloud-task/commit/bce492dcf035372b2f2d60b34601b12406bcc1f6 ?)
_ When I lauched my task in SCDF, I have used the Arguments: --spring.batch.job.names=jobA. Do I need more arguments?

**Comment by cppwfs** [comment]
So to reproduce you did the following:
1) Run Task A `Execution 1`
2) Run Task A `Execution 2` while `Execution 1` is still running.  And `Execution 2` fails (as expected)
3) Run Task A `Execution 3` after `Execution 1` and `Execution 2` have stopped and `Execution 3` fails with the exception `org.springframework.cloud.task.listener.TaskExecutionException: Task with name "A" is already running`

If this is the case: 
Were there any exceptions in Task A `Execution 1`?  
Did Task A `Execution 1` actually terminate or is still running?   This can be found if you do a (jps(local), check tasks (Cloud Foundry), check pods (K8s).
What database and version were you using?
What version of dataflow?

**Comment by duyetphamm** [comment]
Actually, I did 2 cases:
Case 1: 
1.1. Run Task A Execution 1
1.2. Run Task A Execution 2 while Execution 1 is still running. And Execution 2 fails.

Case 2: 
2.1. Run Task A Execution 1
2.2. Run Task A Execution 2 while Execution 1 is COMPLETED. But Execution 2 fails.

And for 2 case, I have deployed on local and they did not throw any exceptions in Execution 1 of Task A. and I think Task A is terminated because the status of Task A Execution 1 in SCDF is COMPLETED and the log of it showed that:
```
2019-11-15 08:23:03.934  INFO 61952 --- [       Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-11-15 08:23:03.958  INFO 61952 --- [       Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

What database and version were you using? -> I have used ojdbc8 19.3.0.0
What version of dataflow? -> I have used spring-cloud-dataflow-server-core 2.2.0.RELEASE

**Comment by duyetphamm** [comment]
There is the full log of Task A Execution 1
```
2019-11-15 08:35:34.177  INFO 46796 --- [           main] org.Application                         : Starting Application v0.0.1 on PC with PID 46796 (D:\Deploy\batch-sample-first-0.0.1.jar started by duyetpt in C:\Users\DUYETPT\AppData\Local\Temp\SSCExportFileJob1661711979380249120\1562980048500\SSCExportFileJob-b796bc49-89ac-49d3-a5e6-f49429a15ddf)
2019-11-15 08:35:34.179  INFO 46796 --- [           main] org.Application                         : No active profile set, falling back to default profiles: default
2019-11-15 08:35:35.035  INFO 46796 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-11-15 08:35:35.770  INFO 46796 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-11-15 08:35:35.873  INFO 46796 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: ORACLE
2019-11-15 08:35:35.889  INFO 46796 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : No TaskExecutor has been set, defaulting to synchronous executor.
2019-11-15 08:35:36.199  INFO 46796 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2019-11-15 08:35:36.895  INFO 46796 --- [           main] org.Application                         : Started Application in 3.18 seconds (JVM running for 3.665)
2019-11-15 08:35:36.997  INFO 46796 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=SSCExportJob]] launched with the following parameters: [{-spring.cloud.task.executionid=28, run.id=1, -spring.batch.job.names=SSCExportJob, -spring.cloud.data.flow.platformname=default}]
2019-11-15 08:35:37.007  INFO 46796 --- [           main] o.s.c.t.b.l.TaskBatchExecutionListener   : The job execution id 22 was run within the task execution 28
2019-11-15 08:35:37.054  INFO 46796 --- [           main] o.s.batch.core.job.SimpleStepHandler     : Executing step: [createSSCFileStep]
2019-11-15 08:35:47.067  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : 0A
2019-11-15 08:35:57.067  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : 1A
2019-11-15 08:36:07.067  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : 2A
2019-11-15 08:36:17.068  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : 3A
2019-11-15 08:38:07.073  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : Total time: 0 minutes
2019-11-15 08:38:07.115  INFO 46796 --- [           main] o.s.batch.core.job.SimpleStepHandler     : Executing step: [exportSSCFileStep]
2019-11-15 08:38:07.124  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : 0B
2019-11-15 08:38:07.124  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : 1B
2019-11-15 08:38:07.124  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : 2B
2019-11-15 08:38:07.124  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : 3B
2019-11-15 08:38:08.124  INFO 46796 --- [           main] org.jobs.SSCExportFile                  : Total time: 0 minutes
2019-11-15 08:38:08.147  INFO 46796 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=SSCExportJob]] completed with the following parameters: [{-spring.cloud.task.executionid=28, run.id=1, -spring.batch.job.names=SSCExportJob, -spring.cloud.data.flow.platformname=default}] and the following status: [COMPLETED]
2019-11-15 08:38:08.158  INFO 46796 --- [       Thread-5] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2019-11-15 08:38:08.159  INFO 46796 --- [       Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-11-15 08:38:08.191  INFO 46796 --- [       Thread-5] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

**Comment by duyetphamm** [comment]
And log of Task A Execution 2 for both cases
```
2019-11-15 08:45:31.898  INFO 25948 --- [           main] org.Application                         : Starting Application v0.0.1 on PC with PID 25948 (D:\Deploy\batch-sample-first-0.0.1.jar started by duyetpt in C:\Users\DUYETPT\AppData\Local\Temp\SSCExportFileJob1661711979380249120\2160918395100\SSCExportFileJob-3c6a069e-0f86-4f8f-9246-b2cfed111eb4)
2019-11-15 08:45:31.903  INFO 25948 --- [           main] org.Application                         : No active profile set, falling back to default profiles: default
2019-11-15 08:45:32.689  INFO 25948 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-11-15 08:45:33.402  INFO 25948 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-11-15 08:45:33.506  INFO 25948 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: ORACLE
2019-11-15 08:45:33.521  INFO 25948 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : No TaskExecutor has been set, defaulting to synchronous executor.
2019-11-15 08:45:33.879  INFO 25948 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2019-11-15 08:45:35.096 ERROR 25948 --- [           main] o.s.c.t.listener.TaskLifecycleListener   : org.springframework.cloud.task.listener.TaskExecutionException: Failed to process @BeforeTask or @AfterTask annotation because: Task with name "SSCExportFileJob" is already running.
2019-11-15 08:45:35.123  WARN 25948 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is org.springframework.cloud.task.listener.TaskExecutionException: Failed to process @BeforeTask or @AfterTask annotation because: Task with name "SSCExportFileJob" is already running.
2019-11-15 08:45:35.124  INFO 25948 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2019-11-15 08:45:35.129  INFO 25948 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-11-15 08:45:35.149  INFO 25948 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-11-15 08:45:35.152 ERROR 25948 --- [           main] o.s.c.t.listener.TaskLifecycleListener   : An event to end a task has been received for a task that has not yet started.
2019-11-15 08:45:35.157 ERROR 25948 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is org.springframework.cloud.task.listener.TaskExecutionException: Failed to process @BeforeTask or @AfterTask annotation because: Task with name "SSCExportFileJob" is already running.
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at org.Application.main(Application.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.cloud.task.listener.TaskExecutionException: Failed to process @BeforeTask or @AfterTask annotation because: Task with name "SSCExportFileJob" is already running.
	at org.springframework.cloud.task.listener.annotation.TaskListenerExecutor.executeTaskListener(TaskListenerExecutor.java:90)
	at org.springframework.cloud.task.listener.annotation.TaskListenerExecutor.onTaskStartup(TaskListenerExecutor.java:58)
	at org.springframework.cloud.task.listener.TaskLifecycleListener.invokeOnTaskStartup(TaskLifecycleListener.java:301)
	at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:284)
	at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:390)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	... 20 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.cloud.task.listener.annotation.TaskListenerExecutor.executeTaskListener(TaskListenerExecutor.java:84)
	... 25 common frames omitted
Caused by: org.springframework.cloud.task.listener.TaskExecutionException: Task with name "SSCExportFileJob" is already running.
	at org.springframework.cloud.task.configuration.SingleInstanceTaskListener.lockTask(SingleInstanceTaskListener.java:120)
	... 30 common frames omitted

```

**Comment by duyetphamm** [comment]
The code for task project:
_ Because I have multiple jobs, I have the class to do configuration in generally
```
```
@Configuration
@EnableBatchProcessing
public class CommonBatchConfiguration {

	@Autowired
	public JobBuilderFactory jobBuilderFactory;

	@Autowired
	public StepBuilderFactory stepBuilderFactory;

}
```
_ The configuration detail of 1 job
@Configuration
public class SSCExportFile extends CommonBatchConfiguration{
	
	@Autowired
	private SSCTasklet sscTasklet;
	
	@Bean
	public Job SSCExportJob() {
		return jobBuilderFactory
				.get("SSCExportJob")
				.incrementer(new RunIdIncrementer())
				.start(createSSCFileStep())
				.next(exportSSCFileStep())  
				.build();
	}

	@Bean
	public Step createSSCFileStep() {
		return stepBuilderFactory
				.get("createSSCFileStep")
				.tasklet(createSSCFileTasklet())
				.build();
	}
	
	@Bean
	public Step exportSSCFileStep() {
		return stepBuilderFactory
				.get("exportSSCFileStep").
				tasklet(exportSSCFileTasklet())
				.build();
	}

	public Tasklet createSSCFileTasklet() {
		return (contribution, chunkContext) -> {
			sscTasklet.createSSCFile();	
			return RepeatStatus.FINISHED;
		};
	}

	public Tasklet exportSSCFileTasklet() {
		return (contribution, chunkContext) -> {
			sscTasklet.exportSSCFile();
			return RepeatStatus.FINISHED;

		};
	}
}
```
_The main class:
```
@EnableTask
@SpringBootApplication
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
```

**Comment by duyetphamm** [comment]
During viewing your source code, I have found the properties spring.cloud.task.single-instance-lock-ttl to set the time that task is locked. 
I have tried to set the maximum time about 5 minutes. After that, the case 2 I mentioned above is worked now. Particularly:
Case 2:
2.1. Run Task A Execution 1
2.2. Run Task A Execution 2 while Execution 1 is LAUNCHED after 5 minutes. and Execution 2 works.

However, I think this way of setting is not flexible in some cases. (multiple jobs have much different started & processed time. Are there anyway to configure that when Task A Execution 1 is COMPLETED, Task A Execution 2 could be launched?.

**Comment by duyetphamm** [comment]
Do you still support me? Mr.@cppwfs

**Comment by cppwfs** [comment]
I'm still here.  Just coding my life away :-)   Can you provide this project on github including a maven pom.   Also include which oracle version you are using and I'll try to reproduce.

**Comment by duyetphamm** [comment]
I have provided the source code of my task project included pom.xml above. What information do you need? @cppwfs . As I asked before,  Are there no way to configure that when Task A Execution 1 is COMPLETED, Task A Execution 2 could be launched straightway?

**Comment by cppwfs** [comment]
Hello.   We haven't been able to reproduce the problem that you have discussed.  This is why I requested the Database and Database version you are using as well as a project that reproduces the problem.     While the excerpts are helpful, I still can't reproduce the problem. Thus why I requested a repo with a cleansed version of the project (corporate data and processes removed) so that I can try to reproduce it here.

**Comment by duyetphamm** [comment]
These is my source code Mr. @cppwfs 
https://github.com/duyetphamm/springbatch

**Comment by duyetphamm** [comment]
Do you try to reproduce my project Mr. @cppwfs

**Comment by cppwfs** [comment]
Hello @duyetphamm I was out for the US based holidays and then spoke at a conference.   However while at the conference I reviewed your project and tried to get it to compile because of missing classes, missing imports, and inconsistent encoding across the files.   So for future reference please make sure your sample project can be compiled.   Also in the future if your project has table creation requirements please provide those in the readme.   I made several changes to the project to get it into compilable condition and I will try to run it later today to see if I can reproduce the issue.

**Comment by duyetphamm** [comment]
Because of some private problems, I cant upload the full code. Sorry for the inconvenience caused to you.  Hope to hear from you soon.

**Comment by cppwfs** [comment]
I was able to reproduce the problem using Oracle DB.    Investigation continuing.

**Comment by cppwfs** [comment]
I'm going to move this issue to https://github.com/spring-cloud/spring-cloud-task/issues/640.
