### ISSUE TITLE
Error when bulk-deleting CT tasks' from the list page

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3655]
As a user, when bulk-deleting composed-task tasks' from the list page, I get the following error. However, upon re-submitting the bulk operation, the delete goes through successfully.

**error:**
```
│ scdf-server Caused by: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: HikariProxyPreparedStatement@1572217451 wrapping sql : 'delete from task_d │
│ efinitions where definition_name=?', parameters : ['test-timestamp']                                                                                                                                                                                   │
│ scdf-server     at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:67)                                                                                                                                                 │
│ scdf-server     at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:54)                                                                                                                                                │
│ scdf-server     at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)                                                                                                                                      │
│ scdf-server     at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3513)                                                                                                                                    │
│ scdf-server     at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3772)                                                                                                                                    │
│ scdf-server     at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:100)                                                                                                                                               │
│ scdf-server     at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)                                                                                                                                                           │
│ scdf-server     at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)                                                                                                                                                  │
│ scdf-server     at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)                                                                                                                                                                             │
│ scdf-server     at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)                                                                                                                                                           │
│ scdf-server     at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)                                                                                                                │
│ scdf-server     at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)                                                                                                                                   │
│ scdf-server     at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:108)                                                                                                                │
│ scdf-server     at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1344)                                                                                                                                                                   │
│ scdf-server     at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:435)                                                                                                                                                               │
│ scdf-server     at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3221)                                                                                                                                          │
│ scdf-server     at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2389)                                                                                                                                               │
│ scdf-server     at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447)                                                                                                                    │
│ scdf-server     at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)                                                 │
│ scdf-server     at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)                                                                │
│ scdf-server     at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)                                      │
│ scdf-server     at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)                                                                                                                                          │
│ scdf-server     at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534)                                                                                                                                          │
│ scdf-server     ... 84 common frames omitted
```

**graph:**
```
timestamp && timestamp-batch
```

**delete:**
![image](https://user-images.githubusercontent.com/1562654/69557481-8968aa80-0f5b-11ea-9ba3-c00b5d8730ec.png)

**Comment by sabbyanandan** [comment]
I haven't tried it on 2.2.x yet, so we may have the issue, and so it may need backporting.

**Comment by cppwfs** [comment]
Hmm... I thought we had a reported issue on this already.  But I can't seem to find it.  This is a long existing problem.   The issue is that the UI deletes the tasks by issuing individual deletes that are not in any order.   Thus it may delete the one of the composed task child apps first.  So when the command to delete the parent is issued SCDF back-end throws an exception stating that there is a problem in the definition in that the child app is missing.  While there is code there to prevent this from being a problem, the issue is that the read  performed by the parent happens prior to the child delete issued by another request.   

The solution to the issue is just to ignore this error and keep on trodding away.  ie. catch the `ObjectOptimisticLockingFailureException` thrown at https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskDeleteService.java#L339
