### ISSUE TITLE
Task issues with oracle/db2

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#3664]
```
dataflow    |   at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$EnhancerBySpringCGLIB$$b3fc309.findTaskManifestById(<generated>) ~[spring-cloud-dataflow-server-core-2.3.0.BUILD-SNAPSHOT.jar!/:2.3.0.BUILD-SNAPSHOT]
dataflow    |   at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.getPageableRelationships(TaskExecutionController.java:247) ~[spring-cloud-dataflow-server-core-2.3.0.BUILD-SNAPSHOT.jar!/:2.3.0.BUILD-SNAPSHOT]
dataflow    |   at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.list(TaskExecutionController.java:128) ~[spring-cloud-dataflow-server-core-2.3.0.BUILD-SNAPSHOT.jar!/:2.3.0.BUILD-SNAPSHOT]
```

```
dataflow    | org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select m.task_execution_manifest as task_execution_manifest
dataflow    | from task_execution_metadata m inner join
dataflow    |         TASK_EXECUTION e on m.task_execution_id = e.TASK_EXECUTION_ID
dataflow    | where e.TASK_EXECUTION_ID = ?
dataflow    | ;]; nested exception is java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
```

```
dataflow    | org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select m.task_execution_manifest as task_execution_manifest
dataflow    | from task_execution_metadata m inner join
dataflow    |         TASK_EXECUTION e on m.task_execution_id = e.TASK_EXECUTION_ID
dataflow    | where e.TASK_EXECUTION_ID = ?
dataflow    | ;]; nested exception is com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=;;SK_EXECUTION_ID = ?
dataflow    | ;END-OF-STATEMENT, DRIVER=4.19.26

```
Looks like caused by commit https://github.com/spring-cloud/spring-cloud-dataflow/commit/f15e50a4f8c2607492eab1d93f50d8087175dc60

**Comment by jvalkeal** [comment]
Issue seem to be that extra semicolon at the end. Tried locally without it and things started to work.
