### ISSUE TITLE
Unable to schedule tasks on Kubernetes when the cronjob-name exceeds the allowed length

### ISSUE THREAD

**Issue by gdubya** [spring-cloud/spring-cloud-dataflow#3682]
**Description:**
We've set up dataflow-server on an Openshift 3.11 cluster to execute tasks. This is working without issues (once we set the entrypoint style to "shell").

Now we're trying to create some schedules for some tasks, however when we try to create the schedule we get an error message: "Unable to create directory for local repository: ?/.m2/repository"

Given that this is a kubernetes environment we have specified all our tasks as docker images, so why is dataflow trying to use a local maven repository?

The stacktrace in the dataflow server is:
```
2019-12-06 14:12:57.394 ERROR 1 --- [io-9393-exec-10] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
java.lang.IllegalArgumentException: Unable to create directory for local repository: ?/.m2/repository
    at org.springframework.util.Assert.isTrue(Assert.java:118)
    at org.springframework.cloud.deployer.resource.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:110)
    at org.springframework.cloud.deployer.resource.maven.MavenResource.<init>(MavenResource.java:122)
    at org.springframework.cloud.deployer.resource.maven.MavenResource.parse(MavenResource.java:268)
    at org.springframework.cloud.dataflow.registry.support.AppResourceCommon.getResource(AppResourceCommon.java:167)
    at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.getAppResource(DefaultAppRegistryService.java:266)
    at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService$$FastClassBySpringCGLIB$$a8bae4.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
    at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService$$EnhancerBySpringCGLIB$$fbe3ad15.getAppResource(<generated>)
    at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.getTaskLauncherResource(DefaultSchedulerService.java:404)
    at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.schedule(DefaultSchedulerService.java:206)
    at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController.save(TaskSchedulerController.java:152)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:158)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Release versions:**
2.3.0-SNAPSHOT. See [this gist](https://gist.github.com/gdubya/16afb2e15321227d9f621ca490c1e3b9) for output from about endpoint.

The URL requested from the UI is: https://scdf.awesome.com/tasks/schedules?scheduleName=test-once-a-minute&taskDefinitionName=test-task&arguments=&properties=scheduler.cron.expression=*/1%20*%20*%20*%20*

**Comment by cppwfs** [comment]
Please try using the entry point of `exec` or `boot`.  Because we are passing scheduling information via command line and docker `shell` does not read the command line args.

**Comment by gdubya** [comment]
Would that have to be set 'globally' or can we do it just for this app? I tried setting "deployer.test-task.kubernetes.entryPointStyle=exec" as a property on the "setup the schedule" page, but got the same result.

But, entryPointStyle aside, why does scheduling a task require a local repository?

**Comment by cppwfs** [comment]
Hello @gdubya Thanks for the reply.    I made a mistake in my first assessment and I apologize. I assumed this was occurring when the scheduler-task-launcher was launching the app.   Your issue is occurring when you are scheduling the task.   
 
How are you installing your Data Flow.   i.e. by Helm, Data Flow yaml, or by hand?
It looks like the `spring.cloud.dataflow.task.schedulerTaskLauncherUrl` is not getting to the appropriate docker image.   In our yaml files it looks like:  i.e.  
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/kubernetes/server/server-deployment.yaml#L43-L44

**Comment by gdubya** [comment]
Ah, thanks @cppwfs. I missed that property when looking at the helm chart yaml template. We've installed it by hand, so we need to add that property manually to the dataflow-server deployment config. 

But... once i've done that then why I try to create a task with a schedule that should fire every minute (`*/1 * * * *`)then it fails and the only message (with no stacktrace) is: 

2019-12-08 18:18:21.658  WARN 1 --- [nio-9393-exec-1] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: Failed to create schedule Failed to create schedule my-once-a-minute-test-task

Hmmm i guess i need to get some more logging out of the dataflow server

**Comment by cppwfs** [comment]
Yes, a log would be most useful!  

Thanks!

**Comment by gdubya** [comment]
Setting DEBUG level logging for the org.springframework logger didn't reveal much:

```2019-12-08 19:53:42.930 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Found thread-bound EntityManager [SessionImpl(1046670442<open>)] for JPA transaction
2019-12-08 19:53:42.930 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Creating new transaction with name [org.springframework.data.jpa.repository.support.SimpleJpaRepository.findById]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT,readOnly
2019-12-08 19:53:42.932 DEBUG 1 --- [nio-9393-exec-5] o.s.jdbc.datasource.DataSourceUtils      : Setting JDBC Connection [HikariProxyConnection@1856600049 wrapping oracle.jdbc.driver.T4CConnection@18371d89] read-only
2019-12-08 19:53:42.932 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@4781c7f2]
2019-12-08 19:53:42.939 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2019-12-08 19:53:42.939 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(1046670442<open>)]
2019-12-08 19:53:42.940 DEBUG 1 --- [nio-9393-exec-5] o.s.jdbc.datasource.DataSourceUtils      : Resetting read-only flag of JDBC Connection [HikariProxyConnection@1856600049 wrapping oracle.jdbc.driver.T4CConnection@18371d89]
2019-12-08 19:53:42.941 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Not closing pre-bound JPA EntityManager after transaction
2019-12-08 19:53:42.941 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Found thread-bound EntityManager [SessionImpl(1046670442<open>)] for JPA transaction
2019-12-08 19:53:42.941 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Creating new transaction with name [org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.find]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
2019-12-08 19:53:42.941 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@34ba120]
2019-12-08 19:53:42.941 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Found thread-bound EntityManager [SessionImpl(1046670442<open>)] for JPA transaction
2019-12-08 19:53:42.941 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Participating in existing transaction
2019-12-08 19:53:42.947 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2019-12-08 19:53:42.947 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(1046670442<open>)]
2019-12-08 19:53:42.951 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Not closing pre-bound JPA EntityManager after transaction
2019-12-08 19:53:42.951 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Found thread-bound EntityManager [SessionImpl(1046670442<open>)] for JPA transaction
2019-12-08 19:53:42.951 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Creating new transaction with name [org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.getAppMetadataResource]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
2019-12-08 19:53:42.951 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@fa949e]
2019-12-08 19:53:42.951 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2019-12-08 19:53:42.951 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(1046670442<open>)]
2019-12-08 19:53:42.958 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Not closing pre-bound JPA EntityManager after transaction
2019-12-08 19:53:42.959 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Found thread-bound EntityManager [SessionImpl(1046670442<open>)] for JPA transaction
2019-12-08 19:53:42.960 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Creating new transaction with name [org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.getAppResource]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
2019-12-08 19:53:42.960 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@1ade2cd7]
2019-12-08 19:53:42.960 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2019-12-08 19:53:42.960 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(1046670442<open>)]
2019-12-08 19:53:42.968 DEBUG 1 --- [nio-9393-exec-5] o.s.orm.jpa.JpaTransactionManager        : Not closing pre-bound JPA EntityManager after transaction
2019-12-08 19:53:42.994  WARN 1 --- [nio-9393-exec-5] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: Failed to create schedule Failed to create schedule my-once-a-minute-test-task
```

It guess it may be related to the configuration of the Openshift cluster, but i'm not sure how to dig deeper there. Do you have any suggestions?

**Comment by gdubya** [comment]
I read through the [Openshift 3.11 documentation](https://docs.openshift.com/container-platform/3.11/dev_guide/cron_jobs.html) and was able to create a cronjob using the oc cli, so it looks like cronjobs do work at a lower level...

**Comment by cppwfs** [comment]
Hmm... So no stack trace appeared after this exception on another line?

This is thrown when a  KubernetesClientException is thrown.   Can you share the lines of the log before and after the exception.  

Thanks!

**Comment by gdubya** [comment]
Ahhh here we go. I switched logging to TRACE instead of DEBUG, and then the stacktrace is included:
```

Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.58.0.1/apis/batch/v1beta1/namespaces/dev/cronjobs . Message: CronJob.batch "my-task-blah-blah" is invalid: metadata.name: Invalid value: "my-task-blah-blah": must be no more than 52 characters. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "my-task-blah-blah": must be no more than 52 characters, reason=FieldValueInvalid, additionalProperties={})], group=batch, kind=CronJob, name=my-task-blah-blah retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=CronJob.batch "my-task-blah-blah" is invalid: metadata.name: Invalid value: "my-task-blah-blah": must be no more than 52 characters, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
--
```

And here we see the problem is actually because my crontjob name is longer than 52 characters (note: "my-task-blah-blah" is not the actual name. I modified it for this report). It looks like this name is the concatenation of both the schedule name + the task name? And it's this total length that is going over the limit.

If i make the schedule name shorter then the SCDF request is successful and I can see the cronjob in Openshift. It still doesn't actually run the task correctly yet, but that's probably something regarding my task code, so we can ignore that here :)

So, if we'd like to reformat this bug report into something constructive for dataflow server improvement: maybe the schedule name length needs to be restricted? Or, in the event of a KubernetesClientException, the details of the exception should be propagated back to the GUI so that the user knows what to do.

**Comment by sabbyanandan** [comment]
@gdubya: Thank you for digging into this. This can be improved, of course, to supplement with a more meaningful error message. Likewise, we can look into length enforcement, as well.

**Comment by cppwfs** [comment]
Resolved issue for Kubernetes here:
https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/353

**Comment by cppwfs** [comment]
Resolved issue for Cloud Foundry here:
https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/331

**Comment by sabbyanandan** [comment]
The CF and K8s PRs are merged, so closing this epic.
