### ISSUE TITLE
Error when destroying a composed task in Cloud Foundry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3711]
As a user, when destroying an unlaunched composed-task on 2.3.1 BS, I get the attached error.

_Definition:_
> <extractDB: timestamp || extractFiles: timestamp> && merge: timestamp && cleanse: timestamp && <writetohdfs: timestamp || transform: timestamp && writetos3: timestamp>

_Error:_
```
2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 2019-12-18 16:22:35.569 ERROR 6 --- [nio-8080-exec-5] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT io.netty.handler.codec.CorruptedFrameException: invalid JSON received at byte position 0: 343034204e6f7420466f756e643a2052657175657374656420726f7574652028277363686564756c65722e6366617070732e696f272920646f6573206e6f742065786973742e0a
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.codec.json.JsonObjectDecoder.decode(JsonObjectDecoder.java:175)
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 	reactor.core.publisher.Mono.checkpoint(Mono.java:1854)
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 	io.pivotal.reactor.scheduler.v1.jobs.ReactorJobs.list(ReactorJobs.java:92)
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT Error has been observed at the following site(s):
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 	|_ Mono.checkpoint ⇢ at io.pivotal.reactor.scheduler.v1.jobs.ReactorJobs.list(ReactorJobs.java:92)
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT Stack trace:
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 		at io.netty.handler.codec.json.JsonObjectDecoder.decode(JsonObjectDecoder.java:175)
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
   2019-12-18T08:22:35.57-0800 [APP/PROC/WEB/0] OUT 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerConte
```

**Comment by cppwfs** [comment]
Tested Master and it was working.   Will test 2.3.x next.

**Comment by cppwfs** [comment]
Unable to reproduce in Navy using 2.3.1.BUILD-SNAPSHOT under scheduling/glenntwo org space.

**Comment by sabbyanandan** [comment]
Alright, thanks. A few extra insights from my environment on PWS. 

1) I have had the scheduler feature enabled (i.e: `SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED: false`). I wasn't sure if `https://scheduler.cfapps.io` is in working condition in PWS. Perhaps try to delete the compose with scheduler enabled — see if it is breaking for you.

2) Also, I tried switching from 2.3.1 BS to 2.4.0 BS, and I notice the same error on both the builds with scheduler enabled.

3) Just for the tease, I turned off the scheduler feature in SCDF, and in that setup, I was able to delete the composed task. However, when I now load the task executions, I get the following error. Maybe there's something lurking around existing tasks executions with and without schedules. This is a whole different problem anyway. I think the only option for me is to nuke the MySQL SI entirely and reestablish everything from scratch.

```
2019-12-18T13:10:16.71-0800 [RTR/4] OUT
   2019-12-18T13:10:16.74-0800 [RTR/8] OUT sabby-test-dataflow-server20.cfapps.io - [2019-12-18T21:10:16.648+0000] "GET /about HTTP/1.1" 200 0 1866 "http://sabby-test-dataflow-server20.cfapps.io/dashboard/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36" "10.10.2.41:18778" "10.10.149.166:61076" x_forwarded_for:"209.234.137.222, 10.10.2.41" x_forwarded_proto:"http" vcap_request_id:"7388866d-8035-43e4-72c9-3e54f8563dd4" response_time:0.099104694 app_id:"319b0790-1e67-443c-bcff-6e30437a9627" app_index:"0" x_b3_traceid:"ad6cbe158a7bc392" x_b3_spanid:"ad6cbe158a7bc392" x_b3_parentspanid:"-" b3:"ad6cbe158a7bc392-ad6cbe158a7bc392"
   2019-12-18T13:10:16.74-0800 [RTR/8] OUT
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.repository.JdbcDataflowTaskExecutionMetadataDao.lambda$findManifestById$1(JdbcDataflowTaskExecutionMetadataDao.java:170)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:748)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:236)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.repository.JdbcDataflowTaskExecutionMetadataDao.findManifestById(JdbcDataflowTaskExecutionMetadataDao.java:163)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.findTaskManifestById(DefaultTaskExecutionService.java:592)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$FastClassBySpringCGLIB$$422cda43.invoke(<generated>)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$EnhancerBySpringCGLIB$$3fd88bf4.findTaskManifestById(<generated>)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.getPageableRelationships(TaskExecutionController.java:247)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.list(TaskExecutionController.java:128)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:158)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:79)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2019-12-18T13:10:16.78-0800 [APP/PROC/WEB/0] OUT Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "subTaskDeploymentRequests" (class org.springframework.cloud.dataflow.core.TaskManifest), not marked as ignorable (2 known properties: "taskDeploymentRequest", "platformName"])
```

**Comment by cppwfs** [comment]
On the 2.3.x line.   I did the following
1) Created the Composed Task as you displayed.
2) Created Schedule for Composed Task
3) Deleted Composed Task from task definition page
This worked as well.
Wonder if the CI/CD Task has a problem with old task-executions?

**Comment by cppwfs** [comment]
In the first scenario it looks like the data coming back from the PCF Scheduler is corrupted somehow.   We can chat with Paul and see if he has seen it before.

The second issue looks like there are some old Task Manifest that were created prior to this commit: https://github.com/spring-cloud/spring-cloud-dataflow/commit/e0df5be5de4f6ed816e85d5f933e7ccdf38b92b1
This is shown in the exception as follows: `Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "subTaskDeploymentRequests"`d
And SCDF can't read the old versions.

**Comment by sabbyanandan** [comment]
I have had to nuke the old MySQL SI from my org/space, and upon recreating all the things from scratch, I was able to create and destroy a brand new composed task (on a brand new DB instance). I will retry this with schedules enabled next.

**Comment by sabbyanandan** [comment]
So yeah, on this brand new DB, I see the same error when destroying the composed task _with_ schedules enabled.

```
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT io.netty.handler.codec.CorruptedFrameException: invalid JSON received at byte position 0: 343034204e6f7420466f756e643a2052657175657374656420726f7574652028277363686564756c65722e6366617070732e696f272920646f6573206e6f742065786973742e0a
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT 	at io.netty.handler.codec.json.JsonObjectDecoder.decode(JsonObjectDecoder.java:175)
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT 	reactor.core.publisher.Mono.checkpoint(Mono.java:1854)
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT 	io.pivotal.reactor.scheduler.v1.jobs.ReactorJobs.list(ReactorJobs.java:92)
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT Error has been observed at the following site(s):
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT 	|_ Mono.checkpoint ⇢ at io.pivotal.reactor.scheduler.v1.jobs.ReactorJobs.list(ReactorJobs.java:92)
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT Stack trace:
   2019-12-18T15:10:06.30-0800 [APP/PROC/WEB/0] OUT 		at io.netty.handler.codec.json.JsonObjectDecoder.decode(JsonObjectDecoder.java:175)
```

My guess is that `SPRING_CLOUD_SCHEDULER_CLOUDFOUNDRY_SCHEDULER_URL: https://scheduler.cfapps.io` is not a good shape in PWS; although it is available for all the PWS users, though. So there's something maybe missing extra from the configuration perspective. I think we need to share this with PCFJC team, so they gracefully handle this error or improve the workflow.

I do not know if there's anything else to do here in SCDF.

**Comment by cppwfs** [comment]
Let's chat when you get a chance.

**Comment by cppwfs** [comment]
I agree.  I don't think this is a SCDF issue.

**Comment by sabbyanandan** [comment]
I created https://github.com/pivotal-cf/pcf-java-client/issues/12 to track this on the PCFJC side — we might be able to improve something there.
