### ISSUE TITLE
On k8s,   deployment and svc yaml for helm grafana not found 

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3716]
**Description:**
As a user, I use helm to deploy scdf and check grafana 

I applied helm from 

``https://github.com/helm/charts/tree/master/stable/spring-cloud-data-flow/templates``

Looking into list of files, i can not find a yaml about grafana service.
If i run helm with 

``--set features.monitoring.enabled=true``

and then

``kubectl get svc my-release-grafana``

There is not svc for grafana neither deployment
Where are the svc and deployment yaml for grafana?

**Release versions:**

helm vesion 
``https://hub.helm.sh/charts/stable/spring-cloud-data-flow/2.5.1``

**Screenshots:**

grafana svc yaml not found 
![image](https://user-images.githubusercontent.com/1777753/71370428-2c89ff80-25ae-11ea-997d-0cd1d2649164.png)
**Additional context:**

**Comment by sabbyanandan** [comment]
Hi, @eskuai. I am not sure how are you using the Helm chart, at least I didn't see it in your description. Here's my attempt on a Minikube.

** Install Chart:**
```
± helm install --name my-release stable/spring-cloud-data-flow --set features.monitoring.enabled=true

NAME:   my-release
LAST DEPLOYED: Mon Dec 23 10:27:39 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                            AGE
my-release-grafana-clusterrole  1s

==> v1/ClusterRoleBinding
NAME                                   AGE
my-release-grafana-clusterrolebinding  1s

==> v1/ConfigMap
NAME                                   AGE
my-release-data-flow-server            2s
my-release-data-flow-skipper           2s
my-release-grafana                     2s
my-release-grafana-dashboards-default  2s
my-release-grafana-test                2s
my-release-mysql-test                  2s
my-release-prometheus-server           2s
scdf-grafana-ds-cm                     2s

==> v1/Deployment
NAME                          AGE
my-release-data-flow-server   1s
my-release-data-flow-skipper  1s
my-release-grafana            1s
my-release-prometheus-proxy   1s
my-release-prometheus-server  1s

==> v1/PersistentVolumeClaim
NAME                          AGE
my-release-mysql              2s
my-release-prometheus-server  2s
my-release-rabbitmq           2s

==> v1/Pod(related)
NAME                                           AGE
my-release-data-flow-server-5778c47d67-q5qh5   1s
my-release-data-flow-skipper-bccf94877-z2n6g   1s
my-release-grafana-7c5d6974b6-rfghr            1s
my-release-mysql-67f6c8d87-85chl               1s
my-release-prometheus-proxy-59b8f6dc6f-t59pz   1s
my-release-prometheus-server-6d956cc9bf-wxchx  1s
my-release-rabbitmq-86646949df-4rmdg           1s

==> v1/Role
NAME                     AGE
my-release-data-flow     1s
my-release-grafana-test  1s

==> v1/RoleBinding
NAME                     AGE
my-release-data-flow     1s
my-release-grafana-test  1s

==> v1/Secret
NAME                 AGE
my-release-mysql     2s
my-release-rabbitmq  2s
scdf-grafana-secret  2s

==> v1/Service
NAME                          AGE
my-release-data-flow-server   1s
my-release-data-flow-skipper  1s
my-release-grafana            1s
my-release-mysql              1s
my-release-prometheus-proxy   1s
my-release-prometheus-server  1s
my-release-rabbitmq           1s

==> v1/ServiceAccount
NAME                          AGE
my-release-data-flow          2s
my-release-grafana            2s
my-release-grafana-test       2s
my-release-prometheus-proxy   2s
my-release-prometheus-server  2s

==> v1beta1/ClusterRole
NAME                                AGE
my-release-prometheus-alertmanager  1s
my-release-prometheus-pushgateway   1s
my-release-prometheus-server        1s

==> v1beta1/ClusterRoleBinding
NAME                                AGE
my-release-prometheus-alertmanager  1s
my-release-prometheus-proxy         1s
my-release-prometheus-pushgateway   1s
my-release-prometheus-server        1s

==> v1beta1/Deployment
NAME                 AGE
my-release-mysql     1s
my-release-rabbitmq  1s

==> v1beta1/PodSecurityPolicy
NAME                                      AGE
my-release-grafana                        2s
my-release-grafana-test                   2s
my-release-prometheus-alertmanager        2s
my-release-prometheus-kube-state-metrics  2s
my-release-prometheus-pushgateway         2s
my-release-prometheus-server              2s

==> v1beta1/Role
NAME                AGE
my-release-grafana  1s

==> v1beta1/RoleBinding
NAME                AGE
my-release-grafana  1s


NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of the server by running 'kubectl get svc -w my-release-data-flow-server'
  export SERVICE_IP=$(kubectl get svc --namespace default my-release-data-flow-server -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo http://$SERVICE_IP:80
``` 

**Services:**
![image](https://user-images.githubusercontent.com/1562654/71374368-4f48f380-256f-11ea-99b7-4fa5d2dfbed9.png)

**Access Endpoint:**
```
± minikube service my-release-grafana --url
http://192.168.64.28:31268
```

**Comment by dmego** [comment]
I have problems when run this command
```bash
helm install --name my-release stable/spring-cloud-data-flow --set features.monitoring.enabled=true
```
when I run `kubectl get pods` , the ruturn is
```bash
NAME                                            READY   STATUS             RESTARTS   AGE
my-release-data-flow-server-796c4895cd-wkqtk    1/1     Running            0          2m51s
my-release-data-flow-skipper-68f7cb4c86-xjhzz   1/1     Running            0          2m51s
my-release-grafana-5c449679c7-tj4j9             1/1     Running            0          2m51s
my-release-mysql-57cc7f7444-pfxgs               1/1     Running            0          2m51s
my-release-prometheus-proxy-7cdd9975d8-qqsw6    1/1     Running            0          2m51s
my-release-prometheus-server-5bc45fdcc6-gqswm   1/2     CrashLoopBackOff   4          2m51s
my-release-rabbitmq-77cbd6666-hwd7l             1/1     Running            0          2m51s
```
the pod `my-release-prometheus-server-5bc45fdcc6-gqswm` STATUS  is `CrashLoopBackOff`, and the pod logs is
```bash
level=info ts=2019-12-24T15:23:11.202Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"
level=info ts=2019-12-24T15:23:11.202Z caller=main.go:333 build_context="(go=go1.13.1, user=root@88e419aa1676, date=20191017-13:15:01)"
level=info ts=2019-12-24T15:23:11.202Z caller=main.go:334 host_details="(Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 my-release-prometheus-server-5bc45fdcc6-gqswm localdomain)"
level=info ts=2019-12-24T15:23:11.202Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-12-24T15:23:11.202Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2019-12-24T15:23:11.202Z caller=query_logger.go:85 component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffe7e4b3ed4, 0x5, 0x14, 0x29db1e0, 0xc000103860, 0x29db1e0)
	/app/promql/query_logger.go:115 +0x48c
main.main()
	/app/cmd/prometheus/main.go:364 +0x5229
``` 
I don`t konw how to save this problem

**Comment by sabbyanandan** [comment]
Hi, @dmego. The error `file=/data/queries.active err="open /data/queries.active: permission denied` indicates that the UID that Prometheus is attempting to use to mount a volume (for configuration) does not have the necessary permission. This is nothing to do with SCDF or the default configurations that we ship for Prometheus, however. The default settings work as expected at least in Minikune, GKE, and PKS so far.

That said, there are a [several threads about this error](https://www.google.com/search?q=file%3D%2Fdata%2Fqueries.active+err%3D%22open+%2Fdata%2Fqueries.active%3A+permission+denied%22&oq=file%3D%2Fdata%2Fqueries.active+err%3D%22open+%2Fdata%2Fqueries.active%3A+permission+denied%22&aqs=chrome..69i57.146j0j7&sourceid=chrome&ie=UTF-8) — you may want to review the recommendations.

**Comment by eskuai** [comment]
Hi @sabbyanandan 

My mistake, you got right,  

As I user, I need to check grafana svc and dashboard,  then if I run helm ....

`` 
darkstar ~]$ helm install --name my-release stable/spring-cloud-data-flow --set kafka.enabled=true,rabbitmq.enabled=false  --set features.monitoring.enabled=true 
``

then, to get grafana svc,

`` 
darkstar ~]$ minikube service my-release-grafana --url
http://192.168.39.78:30992
``

then, svc list

```
darkstar ~]$  kubectl get svc  --all-namespaces
NAMESPACE              NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
default                kubernetes                      ClusterIP      10.96.0.1        <none>        443/TCP                         17d
default                my-release-data-flow-server     LoadBalancer   10.109.91.224    <pending>     80:31154/TCP                    3m58s
default                my-release-data-flow-skipper    ClusterIP      10.100.194.188   <none>        80/TCP                          3m58s
default                my-release-grafana              LoadBalancer   10.107.161.147   <pending>     80:30992/TCP                    3m58s
default                my-release-kafka                ClusterIP      10.101.62.213    <none>        9092/TCP                        3m58s
default                my-release-kafka-headless       ClusterIP      None             <none>        9092/TCP                        3m58s
default                my-release-mysql                ClusterIP      10.98.82.168     <none>        3306/TCP                        3m58s
default                my-release-prometheus-proxy     LoadBalancer   10.109.78.174    <pending>     8080:32216/TCP,7001:31337/TCP   3m58s
default                my-release-prometheus-server    ClusterIP      10.107.29.116    <none>        80/TCP                          3m58s
default                my-release-zookeeper            ClusterIP      10.110.156.80    <none>        2181/TCP                        3m58s
default                my-release-zookeeper-headless   ClusterIP      None             <none>        2181/TCP,3888/TCP,2888/TCP      3m58s
kube-system            kube-dns                        ClusterIP      10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP          17d
kube-system            tiller-deploy                   ClusterIP      10.97.236.220    <none>        44134/TCP                       4m19s
kubernetes-dashboard   dashboard-metrics-scraper       ClusterIP      10.103.0.157     <none>        8000/TCP                        17d
kubernetes-dashboard   kubernetes-dashboard            ClusterIP      10.109.72.136    <none>        80/TCP                          17d
darkstar ~]$ 
```

You know, so sorry about the noise, you guys.

**Comment by dmego** [comment]
Hi @sabbyanandan sorry, i got it wrong, my kubernetes version is too high
