### ISSUE TITLE
SCDF major version 2 giving flyway error while starting

### ISSUE THREAD

**Issue by DasBratin** [spring-cloud/spring-cloud-dataflow#3731]
SCDF major version 2  giving flyway error when previous version 1.5 was installed in the same environment.
1.7.1 could successfully be installed.
How to install 2.0.3 smoothly?
Stacktrace :

2020-01-09 14:40:44.692  INFO 17639 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 1 migration (execution time 00:00.029s)
2020-01-09 14:40:44.735  INFO 17639 --- [           main] o.s.c.d.s.d.m.AbstractBaselineCallback   : Detected old Data Flow schema, doing baseline.
2020-01-09 14:40:44.890  INFO 17639 --- [           main] d.m.AbstractMigrateUriRegistrySqlCommand : Detected URI_REGISTRY, migrating
2020-01-09 14:40:45.330  WARN 17639 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Error while executing beforeBaseline callback: StatementCallback; bad SQL grammar [create table audit_records_tmp (
  id int8 not null,
  audit_action int8,
  audit_data text,
  audit_operation int8,
  correlation_id varchar(255),
  created_by varchar(255),
  created_on timestamp,
  primary key (id)
)]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "audit_records_tmp" already exists
2020-01-09 14:40:45.333  INFO 17639 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-01-09 14:40:45.348  INFO 17639 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2020-01-09 14:40:45.350  INFO 17639 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-01-09 14:40:45.391 ERROR 17639 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Error while executing beforeBaseline callback: StatementCallback; bad SQL grammar [create table audit_records_tmp (
  id int8 not null,
  audit_action int8,
  audit_data text,
  audit_operation int8,
  correlation_id varchar(255),
  created_by varchar(255),
  created_on timestamp,
  primary key (id)
)]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "audit_records_tmp" already exists
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)

**Comment by jvalkeal** [comment]
Looks like there has been a previous failed attempt to migrate and that failed. `audit_records_tmp` table is a cause of that. We have a tests for these migrations but I have to ask, do you have a reproducible steps to show this same error if you start from scratch?

I think there were some minor manual changes needed between 1.5 and 1.7. We only support full schema created by 1.7.

**Comment by DasBratin** [comment]
Steps to reproduce :

- - Have 1.5 SCDF installed in the environment
- - Trying to install 2.x SCDF version in the same environment
- - Failing I guess because flyway was only introduced from SCDF 2.x versions

My question is how we can successfully install SCDF 2.x version in an environment where we already had SCDF 1.5 installed & tables are already present in DB & may be thats why flyway is failing  I guess?

**Comment by jvalkeal** [comment]
I'm not sure what is your current state of a DB but generic steps:
* install/run 1.5.x
* install/run 1.7.x
* install/run 2.x

`1.7.x` should create this table which we had for people handling DB manually https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/resources/migration/1.7.x/migration-postgresql.sql

`2.x` only works from schema created by `1.7.x`. This `AUDIT_RECORDS` table was only change between `1.5` and `1.7`.

If you have existing tables, give me a list of those from a DB. Not sure how easy it's to clean a failed migration if something were left behind.

**Comment by DasBratin** [comment]
Following is the screenshot for SCDF related tables I see in my DB :+1: 

![Capture](https://user-images.githubusercontent.com/59680876/72233402-155a9280-35ed-11ea-8dda-b2b90f2e587e.PNG)

**Comment by jvalkeal** [comment]
Well you could try to drop that `audit_records_tmp` table and see how it works then. I think something went wrong initially and original migration error happened then. Looks like you've also tried to start skipper as `flyway_schema_history` would come from there, so I expect skipper failed as well. With dataflow flyway table is named `flyway_schema_history_dataflow`.

**Comment by DasBratin** [comment]
I guess as 1.5.x version was installed previously,flyway_schema_history got created because this version used skipper,please correct me if I'm wrong here.
Now,once I try to drop audit_records_tmp table,I get the same flyway error with app_registration table.

**Comment by jvalkeal** [comment]
One thing to remember is that schema/db should be empty. You seem to have those other tables like `site_cd` and flyway might be getting confused if it should do baseline or migration. There's only one case where existing tables from scdf `1.7.x` can go through via custom baselining as we can expect what should be there. It's difficult to say where things go wrong without seeing logs and what you actually have in a database.

While skipper and dataflow can exist in a same database, it's better if both have their own database.

**Comment by DasBratin** [comment]
I leave the logs below,please let me know if you can help.




2020-02-05 06:19:17.911  INFO 18560 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 1 migration (execution time 00:00.024s)
2020-02-05 06:19:18.027  INFO 18560 --- [           main] o.s.c.d.s.d.m.AbstractBaselineCallback   : Detected old Data Flow schema, doing baseline.
2020-02-05 06:19:18.581  INFO 18560 --- [           main] d.m.AbstractMigrateUriRegistrySqlCommand : Detected URI_REGISTRY, migrating
2020-02-05 06:19:19.180  WARN 18560 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Error while executing beforeBaseline callback: StatementCallback; bad SQL grammar [CREATE TABLE TASK_LOCK (
  LOCK_KEY CHAR(36) NOT NULL,
  REGION VARCHAR(100) NOT NULL,
  CLIENT_ID CHAR(36),
  CREATED_DATE TIMESTAMP NOT NULL,
  constraint LOCK_PK primary key (LOCK_KEY, REGION)
)]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "task_lock" already exists
2020-02-05 06:19:19.182  INFO 18560 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-02-05 06:19:19.204  INFO 18560 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2020-02-05 06:19:19.205  INFO 18560 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-02-05 06:19:19.242 ERROR 18560 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Error while executing beforeBaseline callback: StatementCallback; bad SQL grammar [CREATE TABLE TASK_LOCK (
  LOCK_KEY CHAR(36) NOT NULL,
  REGION VARCHAR(100) NOT NULL,
  CLIENT_ID CHAR(36),
  CREATED_DATE TIMESTAMP NOT NULL,
  constraint LOCK_PK primary key (LOCK_KEY, REGION)
)]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "task_lock" already exists
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.springframework.cloud.dataflow.server.single.DataFlowServerApplication.main(DataFlowServerApplication.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.flywaydb.core.api.FlywayException: Error while executing beforeBaseline callback: StatementCallback; bad SQL grammar [CREATE TABLE TASK_LOCK (
  LOCK_KEY CHAR(36) NOT NULL,
  REGION VARCHAR(100) NOT NULL,
  CLIENT_ID CHAR(36),
  CREATED_DATE TIMESTAMP NOT NULL,
  constraint LOCK_PK primary key (LOCK_KEY, REGION)
)]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "task_lock" already exists
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.handleEvent(DefaultCallbackExecutor.java:129)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.execute(DefaultCallbackExecutor.java:122)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.execute(DefaultCallbackExecutor.java:113)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.onEvent(DefaultCallbackExecutor.java:62)
	at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:93)
	at org.flywaydb.core.Flyway.doBaseline(Flyway.java:1403)
	at org.flywaydb.core.Flyway.access$200(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1381)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)
	... 26 common frames omitted
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE TASK_LOCK (
  LOCK_KEY CHAR(36) NOT NULL,
  REGION VARCHAR(100) NOT NULL,
  CLIENT_ID CHAR(36),
  CREATED_DATE TIMESTAMP NOT NULL,
  constraint LOCK_PK primary key (LOCK_KEY, REGION)
)]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "task_lock" already exists
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:418)
	at org.springframework.cloud.dataflow.server.db.migration.SqlCommandsRunner.execute(SqlCommandsRunner.java:61)
	at org.springframework.cloud.dataflow.server.db.migration.AbstractCallback.handle(AbstractCallback.java:70)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.handleEvent(DefaultCallbackExecutor.java:127)
	... 39 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "task_lock" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:409)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
	... 43 common frames omitted

**Comment by pradeepkarnam** [comment]
Even I am facing the same issue

**Comment by sabbyanandan** [comment]
There's no direct switch possible from 1.x -> 2.x. To move from a minor release on 1.x to 2.x first requires to sequentially switch to the incremental 1.x minor releases, to then 2.x and onwards.

Besides that, 2.x is a major release line and the first 2.0 GA release was on [Mar 2019](https://github.com/spring-cloud/spring-cloud-dataflow/releases), so a lot has evolved both in the codebase and as well in DB schema since then.
