### ISSUE TITLE
error with task-launcher-dataflow failed  Parameter conditions "name"

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3749]
**Description:**
As a user, I create a stream with the following definition:

```
triggertask 
--time-unit=SECONDS 
--fixed-delay=10 
--uri=docker:springcloudtask/timestamp-task:2.1.0.RELEASE | 
task-launcher-dataflow 
--oauth2-client-credentials-scopes=openid 
--oauth2-client-credentials-token-uri=http://keycloak-http:8844/auth/realms/scdf23/protocol/openid-connect/token 
--oauth2-client-credentials-client-secret=<secret>
--dataflow-server-access-token=<keycloak token>
--oauth2-client-credentials-client-id=dataflow 
--username=<user>
--password=<password>
--server-uri=http://scdf2-server-data-flow-server:8080
```

loggin error is:

`
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Parameter conditions "name" not met for actual request parameters: properties={spring.cloud.dataflow.task.platformName=default}, arguments={}, failedMessage=GenericMessage [payload=org.springframework.cloud.stream.app.task.launcher.dataflow.sink.LaunchRequest@1de4559b, headers={kafka_offset=11, acknowledgmentCallback=org.springframework.integration.kafka.inbound.KafkaMessageSource$KafkaAckCallback@7aaa57f1, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@580129cf, kafka_timestampType=CREATE_TIME, id=69bedae1-fa34-7d55-bc6b-0004d6d140d8, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTopic=t5555.triggertask, kafka_receivedTimestamp=1579603030839, kafka_acknowledgment=org.springframework.integration.kafka.inbound.KafkaMessageSource$KafkaAckCallback@7aaa57f1, timestamp=1579603032204}]
`

**Release versions:**
```
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.3.0.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.3.0.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.3.0.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.3.0.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.3.0.RELEASE/spring-cloud-dataflow-shell-2.3.0.RELEASE.jar"
    }
  },
  "featureInfo": {
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulesEnabled": true,
    "grafanaEnabled": false
  },
  "securityInfo": {
    "isAuthenticationEnabled": true,
    "isAuthenticated": true,
    "username": "mk",
    "roles": [
      "ROLE_CREATE",
      "ROLE_DEPLOY",
      "ROLE_DESTROY",
      "ROLE_MANAGE",
      "ROLE_MODIFY",
      "ROLE_SCHEDULE",
      "ROLE_VIEW"
    ]
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "2.2.1.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.2.1.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.2.1.RELEASE",
      "springVersion": "5.2.1.RELEASE"
    },
    "taskLaunchers": [
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.1.1.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.1.0.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.2.1.RELEASE",
        "springVersion": "5.2.1.RELEASE"
      }
    ]
  },
  "grafanaInfo": {
    "url": "",
    "token": "",
    "refreshInterval": 15
  }
}
```

**Custom apps:**
the stacktrace shows:
```
2020-01-21 11:37:14.862  INFO 1 --- [pool-3-thread-1] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 2.0.1
2020-01-21 11:37:14.862  INFO 1 --- [pool-3-thread-1] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : fa14705e51bd2ce5
2020-01-21 11:37:14.866  INFO 1 --- [pool-3-thread-1] org.apache.kafka.clients.Metadata        : Cluster ID: hYtgMcLtSAGMPK6Yh6Bfrw
2020-01-21 11:37:15.231  INFO 1 --- [pool-2-thread-1] o.s.c.s.a.t.l.d.s.LaunchRequestConsumer  : Launching Task null on platform default
2020-01-21 11:37:15.246 ERROR 1 --- [pool-2-thread-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: nested exception is org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Parameter conditions "name" not met for actual request parameters: properties={spring.cloud.dataflow.task.platformName=default}, arguments={}, failedMessage=GenericMessage [payload=org.springframework.cloud.stream.app.task.launcher.dataflow.sink.LaunchRequest@1de4559b, headers={kafka_offset=11, acknowledgmentCallback=org.springframework.integration.kafka.inbound.KafkaMessageSource$KafkaAckCallback@7aaa57f1, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@580129cf, kafka_timestampType=CREATE_TIME, id=69bedae1-fa34-7d55-bc6b-0004d6d140d8, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTopic=t5555.triggertask, kafka_receivedTimestamp=1579603030839, kafka_acknowledgment=org.springframework.integration.kafka.inbound.KafkaMessageSource$KafkaAckCallback@7aaa57f1, timestamp=1579603032204}]
        at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.doHandleMessage(DefaultPollableMessageSource.java:309)
        at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.handle(DefaultPollableMessageSource.java:340)
        at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.lambda$poll$1(DefaultPollableMessageSource.java:213)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
        at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.poll(DefaultPollableMessageSource.java:212)
        at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.poll(DefaultPollableMessageSource.java:65)
        at org.springframework.cloud.stream.app.task.launcher.dataflow.sink.LaunchRequestConsumer.lambda$consume$1(LaunchRequestConsumer.java:105)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Parameter conditions "name" not met for actual request parameters: properties={spring.cloud.dataflow.task.platformName=default}, arguments={}
        at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:414)
        at org.springframework.cloud.dataflow.rest.client.TaskTemplate.launch(TaskTemplate.java:159)
        at org.springframework.cloud.stream.app.task.launcher.dataflow.sink.LaunchRequestConsumer.launchTask(LaunchRequestConsumer.java:257)
        at org.springframework.cloud.stream.app.task.launcher.dataflow.sink.LaunchRequestConsumer.lambda$null$0(LaunchRequestConsumer.java:108)
        at org.springframework.cloud.stream.binder.DefaultPollableMessageSource.doHandleMessage(DefaultPollableMessageSource.java:306)
        ... 16 more
2020-01-21 11:37:15.251  INFO 1 --- [pool-2-thread-1] o.s.c.s.a.t.l.d.s.LaunchRequestConsumer  : Polling period reset to 1000 ms.
2020-01-21 11:37:16.323  INFO 1 --- [pool-2-thread-1] o.s.c.s.a.t.l.d.s.LaunchRequestConsumer  : No task launch request received- i
```

**Additional context:**

```
org.springframework`[payload=org.springframework.cloud.stream.app.task.launcher.dataflow.sink.LaunchRequest@1de4559b, headers={kafka_offset=11, acknowledgmentCallback=org.springframework.integration.kafka.inbound.KafkaMessageSource$KafkaAckCallback@7aaa57f1, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@580129cf, kafka_timestampType=CREATE_TIME, id=69bedae1-fa34-7d55-bc6b-0004d6d140d8, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTopic=t5555.triggertask, kafka_receivedTimestamp=1579603030839, kafka_acknowledgment=org.springframework.integration.kafka.inbound.KafkaMessageSource$KafkaAckCallback@7aaa57f1, timestamp=1579603032204}]
```

**Comment by sabbyanandan** [comment]
@eskuai: It appears you're not passing the required properties expected by the `task-launcher-dataflow` sink application. A task definition is expected to exist beforehand, and the name of the task definition is required when deploying the stream with this application. Please take a moment to [review the docs](https://github.com/spring-cloud-stream-app-starters/tasklauncher-dataflow/blob/master/spring-cloud-starter-stream-sink-task-launcher-dataflow/README.adoc) to follow along what is expected.

We have a [full-blown sample](https://dataflow.spring.io/docs/recipes/file-ingest/sftp-to-jdbc/#kubernetes) that exercises some of the `task-launcher-dataflow` functionality, as well.

Besides that, if you see legitimate issues with the app, you can open the dialog in the application-repo since it is not SCDF related.
