### ISSUE TITLE
Error by installation on Oracle Database with error "ORA-00972: identifier is too long"

### ISSUE THREAD

**Issue by zwbear** [spring-cloud/spring-cloud-dataflow#3814]
Hi community,

Currently, I tried to install spring-cloud-data-flow server on an oracle database, and the Flyway failed to create the database schema, because the oracle database with version before 12c do not support identity name longer than 30 characters like "AUDIT_RECORDS_AUDIT_OPERATION_IDX", "AUDIT_RECORDS_CORRELATION_ID_IDX". 

Exception : 
```
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [drop index AUDIT_RECORDS_AUDIT_OPERATION_IDX]; nested exception is java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long

        at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:418)
        at org.springframework.cloud.dataflow.server.db.migration.SqlCommandsRunner.execute(SqlCommandsRunner.java:61)
        at org.springframework.cloud.dataflow.server.db.migration.AbstractCallback.handle(AbstractCallback.java:72)
```

See [reference code in the repo](https://github.com/spring-cloud/spring-cloud-dataflow/blob/4fb122aef866306a0d8a961f899ca72d890ffeef/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/oracle/OracleBeforeBaseline.java#L39)

Is it possible to provide a workaround for this problem?

**Comment by sabbyanandan** [comment]
Hi, @zwbear. What version of Oracle are you using?

**Comment by zwbear** [comment]
@sabbyanandan 

Our database version:
```
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
"CORE	11.2.0.4.0	Production"
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production
```

That is not the current version 12c.

**Comment by eskuai** [comment]
Hi @zwbear,
If you are using Oracle 11.2  it could be a possible fix.

Can you check using database owner prefix into the object (Index).
 For example,
``
sql> desc "AUDIT_RECORDS_AUDIT_OPERATION_IDX"
``
You got error, bit

``
sql> desc "owner"."AUDIT_RECORDS_AUDIT_OPERATION_IDX"``

You should get the right info.

I don't know if database owner is dbo ... I don't know what owner flyway use or apply.

And , I suppose,  it needed yo know if there is a hibernate config option to force apply owner prefix into all sentences generated.

Tx

**Comment by sabbyanandan** [comment]
Thanks, @eskuai, for jumping in here. 

@zwbear: To be clear, though, we rely on Flyway for DB schema migrations, and the open-source Flyway (v5.2.4) that we use appears to supports Oracle 12.2 and onwards. 

```
jar tvf spring-cloud-dataflow-server/target/spring-cloud-dataflow-server-2.5.0.BUILD-SNAPSHOT.jar | grep Flyway
509251 Tue Dec 04 18:00:18 PST 2018 BOOT-INF/lib/flyway-core-5.2.4.jar
```

The older releases of Oracle requires an enterprise version of Flyway dependency — see: https://flywaydb.org/documentation/database/oracle

Unfortunately, we cannot bake any non-open-source library in our release binaries. You can patch SCDF/Skipper with the desired version on your own, however — see instructions:  https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/custom-dataflow-builds

**Comment by zwbear** [comment]
@sabbyanandan 
Thanks for info. I have tried to shut down the flyway and managing the schema manual and renames the index keys. It works so far as expected.
