### ISSUE TITLE
App Info throws exception after rebuilding local snapshot

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow#3829]
**Description:**
Using local deployer and registering a SNAPSHOT from local maven repo fails following `mvn clean install` of a registered app.

```
dataflow-server    | java.lang.RuntimeException: Exception trying to list configuration properties for application file:/root/.m2/repository/org/springframework/cloud/stream/app/task-launcher-dataflow-sink-kafka/1.1.0.BUILD-SNAPSHOT/task-launcher-dataflow-sink-kafka-1.1.0.BUILD-SNAPSHOT-metadata.jar
dataflow-server    | 	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.listProperties(BootApplicationConfigurationMetadataResolver.java:171)
dataflow-server    | 	at org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver.listProperties(BootApplicationConfigurationMetadataResolver.java:112)
dataflow-server    | 	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.getInfo(AppRegistryController.java:180)
dataflow-server    | 	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.info(AppRegistryController.java:167)
dataflow-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataflow-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
dataflow-server    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dataflow-server    | 	at java.lang.reflect.Method.invoke(Method.java:498)
dataflow-server    | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
dataflow-server    | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
```

**Release versions:**
2.4.x

**Steps to reproduce:**
Register a locally built app with separate `metadata` jar.
Verify `app info` works.
Rebuild the app with maven.
`app info` fails.
**Screenshots:**

**Additional context:**
Experienced this multiple times lately with locally deployed SCDF both with docker compose and standalone install.

**Comment by sabbyanandan** [comment]
Stale; closing.
