### ISSUE TITLE
Helm Chart doesn't provide way to set dialect for SqlServer

### ISSUE THREAD

**Issue by techy16** [spring-cloud/spring-cloud-dataflow#3889]
**Description:**
Currently i was trying to deploy Spring Cloud Data Flow Server on Kubernetes cluster and Database we are using SqlServer but i am getting exception while connecting to it as it says hibenerate.Dialect not set.

**Logs:**
```
2020-04-17 16:34:21.824  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2020-04-17 16:34:21.909  INFO 1 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Initializing ProtocolHandler ["http-nio-8080"]
2020-04-17 16:34:21.910  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-17 16:34:21.910  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.30]
2020-04-17 16:34:22.201  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-17 16:34:24.295  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2020-04-17 16:34:24.812  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2020-04-17 16:34:25.425  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 5.2.4 by Boxfuse
2020-04-17 16:34:25.507  INFO 1 --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:sqlserver://*******:*****;useFmtOnly=false;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=30;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=appt_scheduler_security_DEV;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 14.0)
2020-04-17 16:34:26.048  INFO 1 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 4 migrations (execution time 00:00.050s)
2020-04-17 16:34:26.101  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema [dbo]: 3
2020-04-17 16:34:26.104  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Schema [dbo] is up to date. No migration necessary.
2020-04-17 16:34:26.489  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2020-04-17 16:34:26.905  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.4.10.Final}
2020-04-17 16:34:27.691  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-04-17 16:34:28.196  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.SQLServer2012Dialect
2020-04-17 16:34:28.319  WARN 1 --- [           main] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata : java.lang.Integer cannot be cast to java.lang.Long
2020-04-17 16:34:28.320  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
2020-04-17 16:34:28.382  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-04-17 16:34:28.387  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2020-04-17 16:34:28.388  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-04-17 16:34:28.485 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.cloud.dataflow.server.single.DataFlowServerApplication.main(DataFlowServerApplication.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:175)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:118)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1202)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1233)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:378)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 24 common frames omitted
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:137)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	... 41 common frames omitted
```

**Comment by sabbyanandan** [comment]
Hi, @techy16. I am not sure what to make out of this error. Is this a problem because you're trying a forked chart with SQLServer, and that SCDF is unable to work with it? If yes, have you tried SCDF using the plain deployment YAMLs that we ship with necessary extra configurations?

It is not ideal to expose SQLServer-specific properties and/or every other possible DB configs as Helm-chart configs. Perhaps the best approach would be to either customize the deployment YAMLs that we ship or further customize the forked chart with extra SQLServer-specific properties as you find fit.

Let's see if @chrisjs has any other thoughts.

**Comment by techy16** [comment]
Hi @sabbyanandan, yes i am trying to forked the chart and using SQL Server as DB but it is giving me this error. Not sure whether you have externalize the configs to set the dialect or something. But wanted to check with you guys right now i see the dialect is by default picked this one - org.hibernate.dialect.SQLServer2012Dialect and SQL Server 14 is running on my environment.  Can you please confirm is this correct and supported the drivers as well? 

Because this is what the main exception here which causing SCDF pods are not coming up 

**### `2020-04-17 16:34:28.196  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.SQLServer2012Dialect
2020-04-17 16:34:28.319  WARN 1 --- [           main] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata : java.lang.Integer cannot be cast to java.lang.Long`**

**Comment by sabbyanandan** [comment]
We don't explicitly muck around and define the dialects on our side. We do ship the `mssql-jdbc` JAR in the classpath, though: https://github.com/spring-cloud/spring-cloud-dataflow/blob/35886ad0116689ed8db5f1f97b62a3a3d84eb9dd/spring-cloud-dataflow-server-core/pom.xml#L142

The version of this driver, however, is defined at the level of Spring Boot. 

In SCDF 2.5 BUILD-SNAPSHOT, it is at `7.4.1.jre8`.

```
± jar tvf spring-cloud-dataflow-server/target/spring-cloud-dataflow-server-2.5.0.BUILD-SNAPSHOT.jar| grep mssql-jdbc
1209660 Fri Aug 02 14:43:20 PDT 2019 BOOT-INF/lib/mssql-jdbc-7.4.1.jre8.jar
```

Perhaps you can confirm whether this driver is compatible with the SQLServer version that you're running in your environment. If it is not, you can locally build SCDF/Skipper with the different versions of the driver to get things going.

cc:/ @jvalkeal

**Comment by chrisjs** [comment]
in helm, out of the box mysql is used. if you would like to connect to another database one option would be to set the appropriate parameters, see:

* https://github.com/helm/charts/tree/master/stable/spring-cloud-data-flow#data-store

* https://github.com/helm/charts/tree/master/stable/spring-cloud-data-flow#external-database-configuration

not sure you would have to fork and modify unless for some reason these options don't provide what you need, which if they don't id be interesting in hearing as they may be useful to others.

**Comment by techy16** [comment]
@chrisjs that exactly how i defined my configs in values.yml for my SQLServer connection details.
If the configs are not picked up by Helm Charts then i wouldn't reach with the exception i shared right.
This exception which i pasted above is more on the DB connection problem right but what is causing that error not getting it.

database:
--
  | driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  | scheme: sqlserver
  | host: **********
  | port: *****
  | user: ***********
  | password: *********
  | dataflow: mydbname
  | skipper: skipper

**Comment by techy16** [comment]
@sabbyanandan Please look at this blog, this is what i am facing.

[https://hibernate.atlassian.net/projects/HHH/issues/HHH-13805?filter=allopenissues&orderby=priority%20DESC]

Click on this - **Dialect is not autodetected on Sql Server 2014 with custom INT sequences**

**Comment by jvalkeal** [comment]
There seem to be active issue for this on driver side https://github.com/microsoft/mssql-jdbc/issues/1302

**Comment by chrisjs** [comment]
referenced issue (https://github.com/microsoft/mssql-jdbc/issues/1302) was closed 16 days ago, please give that a try
