### ISSUE TITLE
DataFlowClient does not renew Oauth access token when expired.

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow#3894]
The dataflow task launcher sink connects to the server running on PCF, creating a service key that includes client id, client secret and the token url.  At first the connection is successful. Over time, we start to see UnAuthorized errors when launching a task.  

The premise is that he token expires and is not refreshed or a new access token requested. This is needed since the sink process runs indefinitely.  

```
...
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] 2020-04-20 10:01:58.568 ERROR 13 --- [pool-3-thread-1] o.s.c.s.a.t.l.d.s.LaunchRequestConsumer : Unauthorized
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Unauthorized
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:74) ~[spring-cloud-dataflow-rest-client-2.4.2.RELEASE.jar:2.4.2.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:785) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:743) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:615) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.dataflow.rest.client.TaskTemplate.currentTaskExecutions(TaskTemplate.java:230) ~[spring-cloud-dataflow-rest-client-2.4.2.RELEASE.jar:2.4.2.RELEASE]
```

**Comment by dturanski** [comment]
Apparently username password session also expires after 6 to 8 hours...

**Comment by jvalkeal** [comment]
Updated my sample https://github.com/jvalkeal/randomstuff/tree/master/dataflow-uaa for using shell with proper oauth config. As those task apps use same facilities this allows automatic renewal.

**Comment by jvalkeal** [comment]
Updated my sample https://github.com/jvalkeal/randomstuff/tree/master/dataflow-uaa for using shell with proper oauth config. As those task apps use same facilities this allows automatic renewal.

**Comment by dturanski** [comment]
What allows automatic renewal? I don't see anything different in the config for your example than what we are doing.

**Comment by dturanski** [comment]
So, in theory, I need to do something like 
```
http | tasklauncher-dataflow 
--spring.security.oauth2.client.registration.tasklauncher.provider=uaa 
--spring.security.oauth2.client.registration.tasklauncher.client-id=clientid
--spring.security.oauth2.client.registration.tasklauncher.client-secret=secret 
--spring.security.oauth2.client.registration.tasklauncher.authorization-grant-type=password 
--spring.security.oauth2.client.registration.tasklauncher.scope=some-resource-defined-scopes
--spring.security.oauth2.client.provider.uaa.issuer-uri=https://uaa.example.com --
--spring.cloud.dataflow.client.authentication.oauth2.username=user 
--spring.cloud.dataflow.client.authentication.oauth2.password=mypassword
```
That's 8 properties that cannot be parsed in the dataflow UI form since they use arbitrary registration and provider keys vs.  3 currently:  `client-id, client-secret, token url`   (BTW - I still can't get these settings to work because the scope is invalid but that's another story)

I understand the motivation to configure these apps with native spring security oauth2 settings but can we not just modify the RequestInterceptor that can obtain an access token, given 3 properties, to get a new token when the request returns a 401?  perhaps with retry logic.
