### ISSUE TITLE
Error bulk deleting task Composed Tasks (task definition)

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow#3930]
![image](https://user-images.githubusercontent.com/886859/81195411-c8c80800-8f8b-11ea-930d-379d6a5443b2.png)

Reported by customer running SCDF for Tanzu 1.7  I have seen this in my test 1.7 environment as well.  Not sure what causes it.

**Comment by ilayaperumalg** [comment]
@dturanski Do we see anything at the server log when this error occurs? If so, please share it.

**Comment by dturanski** [comment]
```2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT 2020-05-05 19:19:52.660 ERROR 14 --- [nio-8080-exec-7] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT reactor.core.Exceptions$ReactiveException: java.net.UnknownHostException: $%7Bvcap.services.scheduler.credentials.api-endpoint%7D: Name or service not known
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:79)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at java.lang.Thread.run(Thread.java:748)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         Suppressed: java.lang.Exception: #block terminated with an error
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT                 at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT                 ... 124 common frames omitted
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT Caused by: java.net.UnknownHostException: $%7Bvcap.services.scheduler.credentials.api-endpoint%7D: Name or service not known
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         reactor.core.publisher.Mono.checkpoint(Mono.java:1863)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         io.pivotal.reactor.scheduler.v1.jobs.ReactorJobs.list(ReactorJobs.java:92)
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT Error has been observed at the following site(s):
2020-05-05T19:19:52.66+0000 [APP/PROC/WEB/0]OUT         |_ Mono.checkpoint ? at io.pivotal.reactor.scheduler.v1.jobs.ReactorJobs.list(ReactorJobs.java:92)```

**Comment by cppwfs** [comment]
Are they deleting Task Executions?  or Task Definitions?

**Comment by cppwfs** [comment]
I setup an environment in the scheduling/glenn (org/space) and I can't reproduce the problem.  Either by deleting a task definition nor task executions.      It could be the SPRING_CLOUD_SCHEDULER_CLOUDFOUNDRY_SCHEDULER_URL property is not setup properly on SCDF.

**Comment by cppwfs** [comment]
When deleting a task definition and scheduling is enabled, SCDF will request the schedules from the scheduling service of the platform for the task definition.   In our case it is PCF Scheduler.  If there is a hiccup in PCF Scheduler or the CF platform this error will result.   We can put a retry in place for x number of attempts before aborting the delete.
