### ISSUE TITLE
Spring Cloud Data Flow in Docker Compose can not run streams as a docker containers

### ISSUE THREAD

**Issue by donbeave** [spring-cloud/spring-cloud-dataflow#3966]
**Description:**
I'm not really sure is it a bug or not. I have tried to find an answer in the documentation, can not find it too (probably didn't check properly). But it seems if use Docker Compose and try to run a stream that uses "docker:" apps, it will fail.

**Release versions:**
DATAFLOW_VERSION=2.5.1.RELEASE
SKIPPER_VERSION=2.4.1.RELEASE

**Steps to reproduce:**

1. Download `docker-compose.yml` file and run it with changed `STREAM_APPS_URI` and `TASK_APPS_URI`.

```bash
wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/master/spring-cloud-dataflow-server/docker-compose.yml

export DATAFLOW_VERSION=2.5.1.RELEASE
export SKIPPER_VERSION=2.4.1.RELEASE
export STREAM_APPS_URI="https://dataflow.spring.io/kafka-docker-latest"
export TASK_APPS_URI="https://dataflow.spring.io/task-docker-latest"
docker-compose up
```

2. Try to create a stream, for example (http -> log):

<img width="480" alt="image" src="https://user-images.githubusercontent.com/139017/82545953-f3b87b80-9b89-11ea-8989-ddb3702dca58.png">

3. Deploy the stream and check errors:

*skipper* will fail with:

```
skipper            | Caused by: java.lang.RuntimeException: Exception trying to deploy [AppDeploymentRequest@600547e8 commandlineArguments = list[[empty]], deploymentProperties = map['spring.cloud.deployer.group' -> 'test-stream'], definition = [AppDefinition@2f5001ab name = 'http-v1', properties = map['spring.cloud.dataflow.stream.app.label' -> 'http', 'spring.cloud.stream.kafka.streams.binder.zkNodes' -> 'zookeeper:2181', 'spring.cloud.stream.metrics.properties' -> 'spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*', 'spring.cloud.dataflow.stream.name' -> 'test-stream', 'spring.cloud.stream.kafka.streams.binder.brokers' -> 'PLAINTEXT://kafka-broker:9092', 'spring.metrics.export.triggers.application.includes' -> 'integration**', 'spring.cloud.stream.metrics.key' -> 'test-stream.http.${spring.cloud.application.guid}', 'spring.cloud.stream.bindings.output.producer.requiredGroups' -> 'test-stream', 'spring.cloud.stream.bindings.output.destination' -> 'test-stream.http', 'spring.cloud.stream.kafka.binder.zkNodes' -> 'zookeeper:2181', 'spring.cloud.dataflow.stream.app.type' -> 'source', 'spring.cloud.stream.kafka.binder.brokers' -> 'PLAINTEXT://kafka-broker:9092']], resource = Docker Resource [docker:springcloudstream/http-source-kafka:2.1.2.RELEASE]]
skipper            | 	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer.deploy(LocalAppDeployer.java:144) ~[spring-cloud-deployer-local-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
skipper            | 	at org.springframework.cloud.skipper.server.deployer.DefaultReleaseManager.install(DefaultReleaseManager.java:141) ~[spring-cloud-skipper-server-core-2.4.1.RELEASE.jar!/:2.4.1.RELEASE]
skipper            | 	... 52 common frames omitted
skipper            | Caused by: java.io.IOException: Cannot run program "docker" (in directory "/tmp/1590054111852/test-stream.http-v1"): error=2, No such file or directory
skipper            | 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_192]
skipper            | 	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.start(LocalAppDeployer.java:464) ~[spring-cloud-deployer-local-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
skipper            | 	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.start(LocalAppDeployer.java:488) ~[spring-cloud-deployer-local-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
skipper            | 	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.access$200(LocalAppDeployer.java:356) ~[spring-cloud-deployer-local-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
skipper            | 	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer.deployApp(LocalAppDeployer.java:330) ~[spring-cloud-deployer-local-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
skipper            | 	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer.deploy(LocalAppDeployer.java:140) ~[spring-cloud-deployer-local-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
skipper            | 	... 53 common frames omitted
```

**Additional context:**
The error message is *Caused by: java.io.IOException: Cannot run program "docker"*, which clearly tell there is no docker exec in `springcloud/spring-cloud-skipper-server` docker image.

I think it can be fixed by installing docker program inside that image and mount docker socket to that container, which will allow to test docker app locally by using Docker Compose.

So is it a bug or it's by design like this? Any reason for this limitation?

**Comment by sabbyanandan** [comment]
@donbeave: There were a few attempts at this in the past, but there were a few caveats with the approaches, as well—one of those approaches you can see in Christian's PR connected to this issue. I'd suggest pulling the PR locally and playing with it. See if that works for your workflow and in your environment. 

Once when we have you validate it, perhaps then we can decide how to proceed with it

**Comment by donbeave** [comment]
@sabbyanandan Already tried that workaround, it works, can use that way also. Just not a good practice, but can use now as a working alternative.

As we discuss in this topic: https://github.com/spring-cloud/spring-cloud-deployer-local/issues/185, I'll make a PR by adding docker support by using Docker API directly.
