### ISSUE TITLE
Launch Task IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 2 at

### ISSUE THREAD

**Issue by PatrickWe** [spring-cloud/spring-cloud-dataflow#4021]
I use the SCDF-Server with a DB2 and my task is also using the same db2.
If I launch the Task the first and second time it works and i see the logs and the exit code = 0.
If I launch the Task the for the third time I got a exception:

In the Table TASK_EXECUTION_METADATA there are two Entries. If i delete one entry, after that i can start the third run and it runs sucessfull:

```
2020-06-30 11:50:34.355 ERROR 26828 --- [nio-9393-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
 java.lang.IllegalStateException: Unable to generate query
         at org.springframework.cloud.dataflow.server.repository.JdbcDataflowTaskExecutionMetadataDao.getLatestManifest(JdbcDataflowTaskExecutionMetadataDao.java:153)
         at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.executeTask(DefaultTaskExecutionService.java:263)
         at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$FastClassBySpringCGLIB$$422cda43.invoke(<generated>)
         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
         at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$EnhancerBySpringCGLIB$$c0db39b2.executeTask(<generated>)
         at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.launch(TaskExecutionController.java:172)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:498)
         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
         at java.lang.Thread.run(Thread.java:748)
 Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 2
         at org.springframework.dao.support.DataAccessUtils.nullableSingleResult(DataAccessUtils.java:100)
         at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:237)
         at org.springframework.cloud.dataflow.server.repository.JdbcDataflowTaskExecutionMetadataDao.getLatestManifest(JdbcDataflowTaskExecutionMetadataDao.java:139)
         ... 70 common frames omitted
```

**Comment by cppwfs** [comment]
Verified the issue:   
We are getting 2 results back from the query generated for DB2 where we are only expecting one .
The query generated for DB2 is different than the one generated for Mysql for example:
`DB2`
```
SELECT task_execution_manifest FROM (SELECT task_execution_manifest, ROW_NUMBER() OVER() as TMP_ROW_NUM FROM (SELECT task_execution_manifest FROM task_execution_metadata m inner join TASK_EXECUTION e on m.task_execution_id = e.TASK_EXECUTION_ID WHERE e.TASK_NAME = 'db2test0813a' ORDER BY e.TASK_EXECUTION_ID DESC)) WHERE TMP_ROW_NUM BETWEEN 1 AND 2
```


`MySql`
```
SELECT task_execution_manifest FROM task_execution_metadata m inner join TASK_EXECUTION e on m.task_execution_id = e.TASK_EXECUTION_ID WHERE e.TASK_NAME = 'ts0813a' ORDER BY e.TASK_EXECUTION_ID DESC LIMIT 0, 1
```

**Comment by cppwfs** [comment]
Merged with PR.
