### ISSUE TITLE
405 status on Dashboard runtime,stream

### ISSUE THREAD

**Issue by kalkir** [spring-cloud/spring-cloud-dataflow#4077]
We have successfully installed scdf via compose file, but seeing 405 response boy when accessing streams in dashboard. 
Seeing following warning in skipper server. 

WARN 1 --- [nio-7577-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]

Any additional property need to be add to support GET method?

**Comment by sabbyanandan** [comment]
@kalkir: Please update the description with versions in use and the entire stacktrace when you launch the streams list page in the dashboard.

**Comment by kalkir** [comment]
skipper server :  2.2.1.RELEASE
data flow-server: 2.5.3.RELEASE


dataflow-server
==================
    | 2020-08-04 15:09:05.609 ERROR 1 --- [nio-9393-exec-2] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request   
     org.springframework.web.client.HttpClientErrorException$MethodNotAllowed: 405 : [no body]
     	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:117)
     	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170)
     	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:112)
     	at org.springframework.cloud.skipper.client.SkipperClientResponseErrorHandler.handleError(SkipperClientResponseErrorHandler.java:78)
     	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
     	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
     	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
     	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
     	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:612)
     	at org.springframework.cloud.skipper.client.DefaultSkipperClient.states(DefaultSkipperClient.java:167)
     	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.streamsStates(SkipperStreamDeployer.java:169)
     	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.state(DefaultStreamService.java:347)
     	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService$$FastClassBySpringCGLIB$$89697014.invoke(<generated>)
     	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
     	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
     	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
     	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
     	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
     	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
     	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
     	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
     	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService$$EnhancerBySpringCGLIB$$c4914663.state(<generated>)
     	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController$Assembler.<init>(StreamDefinitionController.java:192)
     	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.list(StreamDefinitionController.java:100)
     	at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source)
     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     	at java.lang.reflect.Method.invoke(Method.java:498)
     	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
     	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
     	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
     	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
     	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
     	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
     	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
     	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
     	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
     	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
     	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
     	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
     	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:158)
     	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
     	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
     	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
     	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
     	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
     	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
     	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
     	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
     	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
     	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
     	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
     	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
     	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
     	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
     	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
     	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     	at java.lang.Thread.run(Thread.java:748)
skipper server:
============
 WARN 1 --- [io-7577-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported

**Comment by sabbyanandan** [comment]
Thanks, @kalkir. That helps. However, it isn't fully clear how you bumped into this situation. It'd further help if you can describe the steps with some details, and the stream that you deployed, etc.

**Comment by kalkir** [comment]
well, we haven't deployed any stream yet, implemented it using  compose with rabbitmq as message broker: https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.6.0/spring-cloud-dataflow-server/docker-compose.yml
Have noticed this error when click on streams in dashboard.

**Comment by sabbyanandan** [comment]
FWIW, I tried to reproduce it both in 2.6.0 and as well as with 2.5.3 versions of SCDF, and I am unable to replicate the error that you are seeing in your box locally. It works just fine on my laptop.

I had thought it could be something to do with your Docker daemon and the permissions around it, but then I noticed the Skipper version that you are using with SCDF 2.5.3 — Skipper 2.2.1 is very old, and it is likely, not compatible with SCDF 2.5.3.

If you want to use 2.5.3, you _must_ also use Skipper 2.4.3. Likewise, for SCDF 2.6.0, you should be on Skipper 2.5.0. We have this documented in the [getting-started](https://dataflow.spring.io/docs/2.5.x/installation/local/docker/) guide for all the releases versions, specifically to highlight the compatibility. 

If the docs aren't sufficient, you can also look at the release tags to review the SCDF <-> Skipper compatibility [see: [example](https://github.com/spring-cloud/spring-cloud-dataflow/releases/tag/v2.5.3.RELEASE)].

**Comment by kalkir** [comment]
@sabbyanandan Thanks :) , skipper version 2.4.3 fixed the issue.
