### ISSUE TITLE
Stream won't deploy with Custom App

### ISSUE THREAD

**Issue by gkonc001** [spring-cloud/spring-cloud-dataflow#4108]
I created a custom s3-sink app for Spring Cloud Dataflow but during stream deployment the app maintains the Deploying status. I included the both the web and acutuator dependencies but I am still facing the same issue. I believe the app itself is working as it adds data to the s3-bucket but after some time the app will show Failed status and I get the following warnings.
`  Warning  Unhealthy  3m54s (x4 over 7m54s)  kubelet, ip-x-x-x-x.ec2.internal  Liveness probe failed: HTTP probe failed with statuscode: 404
  Warning  Unhealthy  3m45s (x15 over 8m4s)  kubelet, ip-x-x-x-x.ec2.internal  Readiness probe failed: HTTP probe failed with statuscode: 404
`
I am deploying this app as a dockerized image of a maven project in a Kubernetes environmnet. Here is my code for the custom app.

```
@SpringBootApplication
@EnableBinding(Processor.class)
@EnableConfigurationProperties(Properties.class)
public class SpringCloudCustomApp {
    
        private Properties AWSProperties;
        
        @ServiceActivator(inputChannel = Processor.INPUT)
        public void handleMessage(String msg) throws InterruptedException {

                
                Regions clientRegion = Regions.US_EAST_1;
                
                //TODO: add batch size to config
                try {
                //Generate Unique ID
                String uuid = (UUID.randomUUID().toString());
                //Add Unique ID prefix to file name
                String outName = uuid + "-" + AWSProperties.getFileObjKeyName();


                    //Generate AWS Credentials using Properties class
                    BasicAWSCredentials awsCreds = new BasicAWSCredentials(AWSProperties.getAccessKey(), AWSProperties.getSecretKey());
                    //Create S3 Client
                    AmazonS3 s3Client = AmazonS3ClientBuilder.standard().withRegion(clientRegion).withCredentials(new AWSStaticCredentialsProvider(awsCreds)).build();
        
                    // Upload a text string as a new object.
                    ObjectMetadata metadata = new ObjectMetadata();
                    metadata.setContentType("application/json");
                    InputStream targetStream = new ByteArrayInputStream(msg.getBytes());
                    s3Client.putObject(AWSProperties.getBucketName(), outName, targetStream, metadata);

                
                } catch (AmazonServiceException e) {
                    // The call was transmitted successfully, but Amazon S3 couldn't process 
                    // it, so it returned an error response.
                    e.printStackTrace();
                } catch (SdkClientException e) {
                    // Amazon S3 couldn't be contacted for a response, or the client
                    // couldn't parse the response from Amazon S3.
                    e.printStackTrace();
                } catch (Exception e)
                {
                    e.printStackTrace();
                }

        }

        public static void main(String[] args) {
            SpringApplication.run(SpringCloudCustomApp.class, args);
        }
            
}
```

When I deployed this as a local maven project rather than a docker image the app functions as it should but the stream never shows as `Deployed`. 
I have included the actuator maven dependencies and tried enabling the endpoints with `management.endpoints.web.exposure.include=health,info` as well as disabling those probe endpoints but the issue remains. I feel it has something to do with the docker image not being properly recognized as live by kubernetes pods which causes the pods to restart and eventually terminate.
I was able to find a workaround where I deploy two different streams on spring cloud at the same time, the one I am trying to deploy `time | httpclient | custom-sink` and another using `time | httpclient | jdbc`. When I do this, my custom sink app shows as `Deployed` but the time and httpclient apps won't fully deploy until I un-deploy the second the stream using those apps.
However, when I use this method I get this error from the custom-sink app:

```
2020-08-14 17:05:36.314 ERROR 1 --- [container-0-C-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@7100af0b]; nested exception is java.lang.NullPointerException, failedMessage=GenericMessage [payload=byte[35905], headers={kafka_offset=730, scst_nativeHeadersPresent=true, deliveryAttempt=3, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62f1a395, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTopic=custom-sink-s3.httpclient, kafka_receivedTimestamp=1597424586062, kafka_groupId=custom-sink-s3}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:192)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:111)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:104)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:134)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:62)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:384)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:75)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:443)
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:417)
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.lambda$onMessage$0(RetryingMessageListenerAdapter.java:120)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211)
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:114)
	at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:40)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:1854)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1836)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1779)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1719)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1617)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1348)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1064)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:972)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.springframework.cloud.springcloudstreambinderkstream.SpringCloudStreamBinderKstreamApplication.handleMessage(SpringCloudStreamBinderKstreamApplication.java:48)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper$HandlerMethod.invoke(MessagingMethodInvokerHelper.java:1102)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:581)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:477)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:355)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:108)
	... 34 more

2020-08-14 17:05:36.314  INFO 1 --- [container-0-C-1] o.a.k.clients.consumer.KafkaConsumer     : [Consumer clientId=consumer-custom-sink-s3-2, groupId=custom-sink-s3] Seeking to offset 730 for partition custom-sink-s3.httpclient-0
2020-08-14 17:05:36.316 ERROR 1 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Error handler threw an exception

org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@7100af0b]; nested exception is java.lang.NullPointerException, failedMessage=GenericMessage [payload=byte[35905], headers={kafka_offset=730, scst_nativeHeadersPresent=true, deliveryAttempt=3, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@62f1a395, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTopic=custom-sink-s3.httpclient, kafka_receivedTimestamp=1597424586062, kafka_groupId=custom-sink-s3}]
	at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:157) ~[spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:103) ~[spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:1887) [spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1792) [spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1719) [spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1617) [spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1348) [spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1064) [spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:972) [spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```

Any help is appreciated.

**Comment by sabbyanandan** [comment]
Hi, @gkonc001. It's no fun when the app runs locally just fine, but it fails to operate the same way in cloud platforms. I'd start by making sure you're using the [JDK layer that we ship and support](https://dataflow.spring.io/docs/stream-developer-guides/streams/standalone-stream-kafka/#building-docker-images) for the custom apps; it has to do with how the environment variables and the other properties are translated over in the layers when the Docker container starts in Kubernetes.

You can use any of the recent samples [see: [example](https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/multi-io-samples)] that we have in the repo for reference, as well.

**Comment by gkonc001** [comment]
Hi, @sabbyanandan. I just tried using the JDK layer you provided for my build but I am still having the same issue. I am taking a look at the examples to see if I can find anything that can help.

**Comment by gkonc001** [comment]
I seem to have figured out my issue, I was building my docker images under the latest tag and I don't think it was being properly updated on Spring Cloud's side. Building it under different version tags and re-importing the app has fixed it.
