### ISSUE TITLE
Restart Task IllegalStateException

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#4119]
Hi,

I upgraded SCDF to latest master version(2.7.0). But I'm still getting error during restart task execution step. 

_{"message":"Did not find platform for taskName=[hopeTask] , taskId=[3645]","logref":"IllegalStateException"}_

_Originally posted by @umutcann in https://github.com/spring-cloud/spring-cloud-dataflow/issues/4080#issuecomment-678930078_

**Comment by cppwfs** [comment]
Can you share your steps and a full stack trace.  
Here are the steps that I followed.   
1) Go to task launch page.
2) Launch a task that contains a batch job that fails.
3) Go to job page and verify that the job fails. 
4) Restart the failed job.
5) No exception was thrown.

**Comment by umutcann** [comment]
Hi @cppwfs 

Actually I am following same steps as you did. I was using SCDF REST API's to launch and restart task. I tried same steps on SCDF dashboard. I got same error.

![image](https://user-images.githubusercontent.com/18632831/91128612-2dc97a00-e6b1-11ea-8f90-c192bbfda661.png)

![image](https://user-images.githubusercontent.com/18632831/91128678-46d22b00-e6b1-11ea-8d0d-0b1e6e63b465.png)


![image](https://user-images.githubusercontent.com/18632831/91129139-235bb000-e6b2-11ea-8eac-f44e121238e0.png)


2020-08-25 06:15:52.767  INFO 7 --- [nio-9376-exec-8] o.s.c.d.s.s.impl.DefaultTaskJobService   : Restarting Job with Id 6192
2020-08-25 06:15:52.774  INFO 7 --- [nio-9376-exec-8] o.s.c.d.server.batch.SimpleJobService    : Cannot load execution context for job execution: JobExecution: id=6192, version=2, startTime=2020-08-24 06:16:42.887, endTime=2020-08-24 06:16:44.98, lastUpdated=2020-08-24 06:16:44.983, status=FAILED, exitStatus=exitCode=FAILED;exitDescription=org.springframework.batch.item.file.FlatFileParseException: Parsing error at line: 2 in resource=[file [/deployments/M:/data/Inbox/filetodb_input.csv]], input=[2020-06-25 18:43:36.999999;Aurora10;2020-07-03 18:43:36.434123;Nata251;asjhgW;25.06.2020 18:43;4.798]
	at org.springframework.batch.item.file.FlatFileItemReader.doRead(FlatFileItemReader.java:184)
	at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.read(AbstractItemCountingItemStreamItemReader.java:92)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:94)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:161)
	at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:119)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:113)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:69)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:203)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.AbstractJob.han, job=[JobInstance: id=6214, version=0, Job=[sampleFileToDbJob]], jobParameters=[{execution_id=3645, run.id=48, execution_date=Mon Aug 24 06:16:42 UTC 2020, tws_job_name=TNOX0016, -spring.cloud.data.flow.platformname=backend-architecture-dev, execution_time=Mon Aug 24 06:16:42 UTC 2020}]
2020-08-25 06:15:52.785 ERROR 7 --- [nio-9376-exec-8] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

**java.lang.IllegalStateException: Did not find platform for taskName=[hopeTask] , taskId=[3645]
	at** org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService.restartJobExecution(DefaultTaskJobService.java:194)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService$$FastClassBySpringCGLIB$$d486827e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService$$EnhancerBySpringCGLIB$$23467e8b.restartJobExecution(<generated>)
	at org.springframework.cloud.dataflow.server.controller.JobExecutionController.restartJobExecution(JobExecutionController.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cppwfs** [comment]
Hmm...  
Can you share command line args of the task you launched from the Task Execution Screen from the task that failed.  I ask because, this is where the platform name is obtained.  Also is the platform that is associated with the failed still present?

**Comment by umutcann** [comment]
Actually I'm not sending command line args while launching job. I am sending only properties. 

The answer of other question is Yes It's present. When I tried to launch task different namespace, I'm getting error like below.

_{"_embedded":{"errors":[{"message":"Task definition [hopeTask] has already been deployed on platform [backend-architecture-dev].  Requested to deploy on platform [backend-architecture-test].","logref":"IllegalStateException","_links":{"self":{"href":"/"}}}]}}_

![image](https://user-images.githubusercontent.com/18632831/91184670-90446980-e6f5-11ea-9b11-0b78a566e86f.png)

**Comment by cppwfs** [comment]
Can you share the command line args section of the task execution page for the task launch that failed?

**Comment by umutcann** [comment]
Hi @cppwfs 

Sorry, I couldn't see command line args section for initial task launch(3642). 

Am I missing something? 

![image](https://user-images.githubusercontent.com/18632831/91259458-456b3600-e777-11ea-930e-c954a73ba0cd.png)

![image](https://user-images.githubusercontent.com/18632831/91259605-895e3b00-e777-11ea-8fae-373b8d508b07.png)

**Comment by cppwfs** [comment]
Hmm.  
I'll have to dig in a bit.  The task platform is not present in you properties nor your command line args . This is why job restart is failing.

**Comment by umutcann** [comment]
Thanks @cppwfs I will be waiting response from you. 

Actually It is little bit weird. Because Task is already keeping platformName as I sad previous my response.

**Comment by umutcann** [comment]
Hi @cppwfs 

Is there any update on your side?

**Comment by cppwfs** [comment]
It is on the radar to be worked on.

**Comment by umutcann** [comment]
Do that issues have possible to cause retrieving log?

![image](https://user-images.githubusercontent.com/18632831/93223175-70deb080-f778-11ea-9f0f-cbe1dd52a5d1.png)

**Comment by cppwfs** [comment]
@umutcann opened issue for the log problem:   https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/397

**Comment by cppwfs** [comment]
@umutcann what entrypoint style are you using?    i.e. https://dataflow.spring.io/docs/installation/kubernetes/helm/#entry-point-style
Also is it possible you could share the propeties (cleansed) and args that you are using to launch your task.  

Sorry for the delay in the response.

Thanks

**Comment by umutcann** [comment]
Hi @cppwfs , not problem.

We are using **shell** as entry point style.

We are only passing properties, not an args as you see below.

deployer.appname.kubernetes.environmentVariables=PROJECT_NAME=backend-architecture,OPENSHIFT_DEPLOY_NAMESPACE=backend-architecture-dev,OPENSHIFT_APP_NAME=ark-batch-template-filetodb,ENV=dev,CONFIG_SERVER_HOST=host,CONFIG_SERVER_PORT=80,TWS_JOB_NAME=TNOX0016,spring.profiles.active=dev

![image](https://user-images.githubusercontent.com/18632831/93296033-0e78c500-f7f7-11ea-92cd-d9c9cb7d7f23.png)

**Comment by cppwfs** [comment]
Was able to reproduce.   
In short dataflow stores the platform that was used to deploy the task as a command line arg in the task execution.  This is used by dataflow to know which platform to use when restarting a batch job.   However When using the `shell` entrypoint the command line args are not passed on to the task and thus are not stored as a part of the task execution.   

Within dataflow I can obtain this platform from the Task Manifest of the previous run when the user restarts a batch job.   However I want to check with the deployer folks to see if this the expected behavior, before apply the fix above.

**Comment by umutcann** [comment]
Thanks @cppwfs . I'm waiting good news from you 👍

**Comment by cppwfs** [comment]
To resolve this issue will require 3 stories.
1) Dataflow component:  will allow dataflow to determine the platform to use for this restart, instead of gathering this info from the task execution.  This fix will be applied to this Issue
2) Dataflow ui component: to make sure that logs for a task are obtained from the correct platform, a UI change will need to be implemented.  As discussed here: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1559
3) Boot component: To make sure that Job Params are supported using the `shell` `entrypoint`.   The following issue will need to be worked on https://github.com/spring-projects/spring-boot/issues/23411
