### ISSUE TITLE
Restarting Skipper container makes stream redeployment impossible

### ISSUE THREAD

**Issue by radu-almasan** [spring-cloud/spring-cloud-dataflow#4293]
**Description:**
When using Docker Compose to run Spring Cloud DataFlow locally, if the Skipper container is restarted while a stream is deployed the applications are still visible in the Runtime section but with status "Unknown", without any way of removing them. This blocks the redeployment of the stream, DataFlow throwing the following exception in the log:

<details>
    <summary>Dataflow Server log</summary>

    2020-12-17 17:59:09.004  INFO 1 --- [nio-9393-exec-4] o.s.c.d.s.stream.SkipperStreamDeployer   : Deploying Stream dev-sherlock-ingestion-lines using skipper.
    2020-12-17 17:59:09.022  INFO 1 --- [nio-9393-exec-4] o.s.c.d.s.stream.SkipperStreamDeployer   : Using platform 'default'
    2020-12-17 17:59:09.068 ERROR 1 --- [nio-9393-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
    
    org.springframework.cloud.skipper.SkipperException: 
        at org.springframework.cloud.skipper.client.SkipperClientResponseErrorHandler.handleSkipperException(SkipperClientResponseErrorHandler.java:109)
        at org.springframework.cloud.skipper.client.SkipperClientResponseErrorHandler.handleError(SkipperClientResponseErrorHandler.java:76)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:610)
        at org.springframework.cloud.skipper.client.DefaultSkipperClient.upload(DefaultSkipperClient.java:455)
        at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.deployStream(SkipperStreamDeployer.java:260)
        at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.doDeployStream(DefaultStreamService.java:179)
        at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.deployStream(DefaultStreamService.java:472)
        at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService$$FastClassBySpringCGLIB$$89697014.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService$$EnhancerBySpringCGLIB$$d59febdb.deployStream(<generated>)
        at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:214)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)

</details>

**Release versions:**
<details>
    <summary>SCDF's system information</summary>

    {
      "featureInfo": {
        "analyticsEnabled": true,
        "streamsEnabled": true,
        "tasksEnabled": true,
        "schedulesEnabled": false,
        "monitoringDashboardType": "GRAFANA"
      },
      "versionInfo": {
        "implementation": {
          "name": "spring-cloud-dataflow-server",
          "version": "2.7.0"
        },
        "core": {
          "name": "Spring Cloud Data Flow Core",
          "version": "2.7.0"
        },
        "dashboard": {
          "name": "Spring Cloud Dataflow UI",
          "version": "3.0.0"
        },
        "shell": {
          "name": "Spring Cloud Data Flow Shell",
          "version": "2.7.0",
          "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.0/spring-cloud-dataflow-shell-2.7.0.jar"
        }
      },
      "securityInfo": {
        "authenticationEnabled": false,
        "authenticated": false,
        "username": null,
        "roles": []
      },
      "runtimeEnvironment": {
        "appDeployer": {
          "deployerImplementationVersion": "2.6.0",
          "deployerName": "Spring Cloud Skipper Server",
          "deployerSpiVersion": "2.6.0",
          "javaVersion": "11.0.8",
          "platformApiVersion": "",
          "platformClientVersion": "",
          "platformHostVersion": "",
          "platformSpecificInfo": {
            "default": "local"
          },
          "platformType": "Skipper Managed",
          "springBootVersion": "2.3.5.RELEASE",
          "springVersion": "5.2.10.RELEASE"
        },
        "taskLaunchers": [
          {
            "deployerImplementationVersion": "2.5.0",
            "deployerName": "LocalTaskLauncher",
            "deployerSpiVersion": "2.5.0",
            "javaVersion": "11.0.8",
            "platformApiVersion": "Linux 4.19.121-linuxkit",
            "platformClientVersion": "4.19.121-linuxkit",
            "platformHostVersion": "4.19.121-linuxkit",
            "platformSpecificInfo": {},
            "platformType": "Local",
            "springBootVersion": "2.3.5.RELEASE",
            "springVersion": "5.2.10.RELEASE"
          }
        ]
      },
      "monitoringDashboardInfo": {
        "url": "http://localhost:3000",
        "refreshInterval": 15,
        "dashboardType": "GRAFANA",
        "source": "default-scdf-source"
      },
      "_links": {
        "self": {
          "href": "http://localhost:9393/about"
        }
      }
    }
</details>

**Custom apps:**
Using standard S3 and log apps.

**Steps to reproduce:**
1. `docker-compose -p scdf -f docker-compose.yml -f docker-compose-prometheus.yml up -d`
2. Create a stream using s3 source and log sink
3. `docker-compose -p scdf -f docker-compose.yml -f docker-compose-prometheus.yml restart skipper-server`

**Comment by sabbyanandan** [comment]
Hi, @radu-almasan. It appears you're using the stock Docker Compose without any customization. In that setup, could you confirm you're using MySQL for both SCDF and Skipper? You should be able to see that in Skipper startup logs. If in-memory storage is used, and when Skipper or SCDF restarts, the state won't be retained, so things would fall apart. So, let's confirm this first.

**Comment by radu-almasan** [comment]
Yes, using MySQL:

    2020-12-17 20:24:42.254  INFO 1 --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:mysql://mysql:3306/dataflow (MySQL 5.7)

**Comment by jvalkeal** [comment]
Could you post startup log and that specific error in skipper as well. We've seen many times misconfiguration with skipper that it uses embedded DB which doesn't persist anything with restart.

**Comment by radu-almasan** [comment]
[skipper.log](https://github.com/spring-cloud/spring-cloud-dataflow/files/5712513/skipper.log)
[dataflow-server.log](https://github.com/spring-cloud/spring-cloud-dataflow/files/5712515/dataflow-server.log)

**Comment by jvalkeal** [comment]
Ah yeah I think we should communicate these states better as this is equivalent of a platform problem. I get same "error" with cloudfoundry when I manually delete my stream apps(in a platform itself) and skipper as it should still thinks stream is deployed:
```
skipper:>release list
╔════╤═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤═════════════╤═══════════════════════════════╗
║Name│Version│        Last updated        │ Status │Package Name│Package Version│Platform Name│        Platform Status        ║
╠════╪═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪═════════════╪═══════════════════════════════╣
║s1  │1      │Fri Dec 18 08:30:09 GMT 2020│DEPLOYED│s1          │1.0.0          │default      │[s1.log-v1], State = [unknown] ║
║    │       │                            │        │            │               │             │[s1.time-v1], State = [unknown]║
╚════╧═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧═════════════╧═══════════════════════════════╝
```
With local you see this every time because those stream apps are run in skipper container and goes byebye with container restart.

You kinda see this from a history:
```
dataflow:>stream history --name s1
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║1      │Fri Dec 18 08:30:09 GMT 2020│DEPLOYED│s1          │1.0.0          │Install complete║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
```

I think it'd be nice if we could provide easier way to remedy this rather than destroying and re-creating a stream again.

**Comment by sabbyanandan** [comment]
Thanks for the findings, @jvalkeal. 

@radu-almasan: This is yet another reason we recommend the use of a container platform like Kubernetes in higher-level environments, including staging and production. The local implementation of SCDF and the Docker Compose equivalent is suited only for rapid experimentation in the development environment. 

There are no resiliency measures baked into the local variant, so whatever we end up adding, we will have to work around a lot internally on our side (in the code) to fake it being robust.
