### ISSUE TITLE
Failure to open list of schedules

### ISSUE THREAD

**Issue by sadovnikov** [spring-cloud/spring-cloud-dataflow#4366]
**Description:**

When SCDF fails to query resources in Kubernetes namespaces (platforms), the `/dashboard/#/tasks-jobs/schedules` page hangs, without showing any errors. The problem is seen only in SCDF server logs.

Expected behaviour: schedules from the platforms, which could be accessed by SCDF, are shown. Ideally, an error message about the failure(s) to access other platforms is displayed too. 

**Release versions:**

Version is 2.7.1

```
{"featureInfo":{"analyticsEnabled":true,"streamsEnabled":true,"tasksEnabled":true,"schedulesEnabled":true,"monitoringDashboardType":"NONE"},"versionInfo":{"implementation":{"name":"spring-cloud-dataflow-server","version":"2.7.1"},"core":{"name":"Spring Cloud Data Flow Core","version":"2.7.1"},"dashboard":{"name":"Spring Cloud Dataflow UI","version":"3.0.1"},"shell":{"name":"Spring Cloud Data Flow Shell","version":"2.7.1","url":"https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.1/spring-cloud-dataflow-shell-2.7.1.jar"}},"securityInfo":{"authenticationEnabled":false,"authenticated":false,"username":null,"roles":[]},"runtimeEnvironment":{"appDeployer":{"deployerImplementationVersion":"2.6.1","deployerName":"Spring Cloud Skipper Server","deployerSpiVersion":"2.6.1","javaVersion":"1.8.0_282","platformApiVersion":"","platformClientVersion":"","platformHostVersion":"","platformSpecificInfo":{"sandbox":"kubernetes","default":"kubernetes","reference-apps":"kubernetes"},"platformType":"Skipper Managed","springBootVersion":"2.3.7.RELEASE","springVersion":"5.2.12.RELEASE"},"taskLaunchers":[{"deployerImplementationVersion":"2.5.1","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.1","javaVersion":"1.8.0_282","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"sandbox","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.7.RELEASE","springVersion":"5.2.12.RELEASE"},{"deployerImplementationVersion":"2.5.1","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.1","javaVersion":"1.8.0_282","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"reference-apps","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.7.RELEASE","springVersion":"5.2.12.RELEASE"},{"deployerImplementationVersion":"2.5.1","deployerName":"KubernetesTaskLauncher","deployerSpiVersion":"2.5.1","javaVersion":"1.8.0_282","platformApiVersion":"v1","platformClientVersion":"unknown","platformHostVersion":"unknown","platformSpecificInfo":{"namespace":"reference-apps","master-url":"https://172.17.224.1:443/"},"platformType":"Kubernetes","springBootVersion":"2.3.7.RELEASE","springVersion":"5.2.12.RELEASE"}]},"monitoringDashboardInfo":{"url":"","refreshInterval":15,"dashboardType":"NONE","source":"default-scdf-source"},"_links":{"self":{"href":"http://localhost:8080/about"}}}
```

Installed with Bitnami Helm

```
- name: spring-cloud-dataflow
  version: 2.7.0
  repository: https://charts.bitnami.com/bitnami
```

**Steps to reproduce:**

Our installation uses multiple accounts in `spring.cloud.dataflow.task.platform.kubernetes.accounts` for server and in `spring.cloud.skipper.server.platform.kubernetes.accounts` for skipper. The owners of the namespaces are responsible for adding a RoleBinding to allow SA of SCDF to control their namespaces. If one of them fails to do so, the `/dashboard/#/tasks-jobs/schedules` page hangs and the exception below is printed in logs.

```
2021-02-02 11:07:10.361  WARN 1 --- [nio-8080-exec-3] i.f.k.client.internal.VersionUsageUtils  : The client is using resource type 'cronjobs' with unstable version 'v1beta1'
2021-02-02 11:07:10.458 ERROR 1 --- [nio-8080-exec-3] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.17.224.1/apis/batch/v1beta1/namespaces/search-process/cronjobs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. cronjobs.batch is forbidden: User "system:serviceaccount:spring-cloud-data-flow:spring-cloud-data-flow" cannot list resource "cronjobs" in API group "batch" in the namespace "search-process".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:505)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:166)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:640)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:79)
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesScheduler.list(KubernetesScheduler.java:146)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.listForPlatform(DefaultSchedulerService.java:380)
	at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController.list(TaskSchedulerController.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by cppwfs** [comment]
Thank you @sadovnikov for reporting this issue.  
I've created a new issue in SCDF-UI.  It is located here: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1642.
I will close this issue and it will be resolved in the UI issue above.
