### ISSUE TITLE
Shell: Improve Error Handling for handling Modules

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#437]
When executing the shell command  `module unregister timestamp` I am missing the module type:

```
spring> module unregister timestamp

Command failed java.lang.IllegalArgumentException: Expected format of 'name:type' for module name timestamp

Expected format of 'name:type' for module name timestamp
java.lang.IllegalArgumentException: Expected format of 'name:type' for module name timestamp
    at org.springframework.cloud.dataflow.shell.command.ModuleCommands.processArgs(ModuleCommands.java:234)
    at org.springframework.cloud.dataflow.shell.command.ModuleCommands.unregister(ModuleCommands.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:745)
spring> 
```

I wonder if we should eliminate showing the stacktrace for the sake of better UX.

**Comment by sabbyanandan** [comment]
This has been already addressed. We only show relevant error messages and not the entire stacktrace.
