### ISSUE TITLE
[Kubernetes] NPE on Task Execution 

### ISSUE THREAD

**Issue by Manu10744** [spring-cloud/spring-cloud-dataflow#4478]
**Description:**
We have deployed Spring Cloud Data Flow v2.6.3 to Kubernetes. On the dashboard we are registering a Spring Batch by registering a SCDF Task Application using `file://root/batchapplication-21.6.0-SNAPSHOT.jar`. This works without problems.
When we try to execute the Batch via REST API or manually on the dashboard, we get the following `NullPointerException`:

```java
2021-04-16 14:30:24.993 ERROR 1 --- [nio-8080-exec-2] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.NullPointerException: null
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.executeTask(DefaultTaskExecutionService.java:247)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$FastClassBySpringCGLIB$$422cda43.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$EnhancerBySpringCGLIB$$176d9e70.executeTask(<generated>)
	at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.launch(TaskExecutionController.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

We are using external H2 DB, which is running in a Pod in the same Kubernetes namespace (and which is accessible by the serveice `h2`). 
After looking into the database, i can tell that all tables were created by SCDF. So, the database connection shouldn't be the problem here.
These are the SCDF logs on startup of the pod:

```java
Spring Cloud Data Flow Server  (v2.6.3)

2021-04-16 14:27:13.181  INFO 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
2021-04-16 14:27:13.282  INFO 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:8888. Will be trying the next url if available
2021-04-16 14:27:13.283  WARN 1 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/spring-cloud-dataflow-server/kubernetes": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2021-04-16 14:27:13.352  INFO 1 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-configmap.spring-cloud-dataflow-server.demosuite-21-06-k8s-i'}]
2021-04-16 14:27:13.458  INFO 1 --- [           main] o.s.c.d.s.s.DataFlowServerApplication    : The following profiles are active: kubernetes
2021-04-16 14:27:15.774  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-04-16 14:27:15.775  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Map repositories in DEFAULT mode.
2021-04-16 14:27:16.130  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 329ms. Found 1 Map repository interfaces.
2021-04-16 14:27:16.941  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-04-16 14:27:16.945  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-04-16 14:27:16.974  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 22ms. Found 0 JPA repository interfaces.
2021-04-16 14:27:17.311  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-04-16 14:27:17.311  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-04-16 14:27:17.435  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 123ms. Found 5 JPA repository interfaces.
2021-04-16 14:27:17.836  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=4e51374d-c710-3892-af21-2296dbb0d682
2021-04-16 14:27:19.246  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-04-16 14:27:19.269  INFO 1 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Initializing ProtocolHandler ["http-nio-8080"]
2021-04-16 14:27:19.270  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-04-16 14:27:19.270  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.36]
2021-04-16 14:27:19.430  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-04-16 14:27:20.028  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-04-16 14:27:20.175  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-04-16 14:27:20.972  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2021-04-16 14:27:21.686  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.17.Final
2021-04-16 14:27:22.139  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2021-04-16 14:27:22.740  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2021-04-16 14:27:25.043  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2021-04-16 14:27:25.075  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-04-16 14:27:25.875  INFO 1 --- [           main] urationMetadataResolverAutoConfiguration : Final Registry Configurations: {registry-1.docker.io=RegistryConfiguration{registryHost='registry-1.docker.io', user='null', secret='****'', authorizationType=dockeroauth2, manifestMediaType='application/vnd.docker.distribution.manifest.v2+json', disableSslVerification='false', extra={registryAuthUri=https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repository}:pull&offline_token=1&client_id=shell}}}
2021-04-16 14:27:27.867  INFO 1 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: H2
2021-04-16 14:27:27.960  INFO 1 --- [           main] o.s.c.d.s.b.SimpleJobServiceFactoryBean  : No database type set, using meta data indicating: H2
2021-04-16 14:27:28.133  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2021-04-16 14:27:28.351  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-04-16 14:27:29.617  INFO 1 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Starting ProtocolHandler ["http-nio-8080"]
2021-04-16 14:27:29.674  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-04-16 14:27:29.679  INFO 1 --- [           main] o.s.c.d.s.s.DataFlowServerApplication    : Started DataFlowServerApplication in 22.893 seconds (JVM running for 24.852)
2021-04-16 14:27:38.194  INFO 1 --- [nio-8080-exec-5] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
```

**Release versions:**
Here is the prettified JSON from the `/about` endpoint: 

```json
{
   "featureInfo":{
      "analyticsEnabled":true,
      "streamsEnabled":false,
      "tasksEnabled":true,
      "schedulesEnabled":false,
      "grafanaEnabled":false,
      "wavefrontEnabled":false,
      "monitoringDashboardType":"NONE"
   },
   "versionInfo":{
      "implementation":{
         "name":"spring-cloud-dataflow-server",
         "version":"2.6.3"
      },
      "core":{
         "name":"Spring Cloud Data Flow Core",
         "version":"2.6.3"
      },
      "dashboard":{
         "name":"Spring Cloud Dataflow UI",
         "version":"2.5.1"
      },
      "shell":{
         "name":"Spring Cloud Data Flow Shell",
         "version":"2.6.3",
         "url":"https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.6.3/spring-cloud-dataflow-shell-2.6.3.jar"
      }
   },
   "securityInfo":{
      "authenticationEnabled":false,
      "authenticated":false,
      "username":null,
      "roles":[
         
      ]
   },
   "runtimeEnvironment":{
      "appDeployer":{
         "deployerImplementationVersion":null,
         "deployerName":null,
         "deployerSpiVersion":null,
         "javaVersion":null,
         "platformApiVersion":null,
         "platformClientVersion":null,
         "platformHostVersion":null,
         "platformSpecificInfo":{
            
         },
         "platformType":null,
         "springBootVersion":null,
         "springVersion":null
      },
      "taskLaunchers":[
         
      ]
   },
   "grafanaInfo":{
      "url":"",
      "refreshInterval":15
   },
   "monitoringDashboardInfo":{
      "url":"",
      "refreshInterval":15,
      "dashboardType":"NONE",
      "source":"default-scdf-source"
   },
   "_links":{
      "self":{
         "href":"http://localhost:8080/about"
      }
   }
}
```

We are using our own Docker Image of Spring Cloud Dataflow which basically only contains the v2.6.3 JAR and the Batch JAR in folder `root`. I thought it has no right to access root folder, so i tried with another but the problem still persists.

We are starting SCDF in a Deployment with the following arguments / configuration:
(Dont mind the ENV syntax for the namespace, we are using a jenkins plugin that resolves these)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-dataflow-deployment
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: spring-cloud-dataflow
  template:
    metadata:
      labels:
        app: spring-cloud-dataflow
    spec:
      containers:
        - name: spring-cloud-dataflow-${NAMESPACE}
          image: private-docker-registry/images/scdf:2.6.3
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.1"
              memory: "500M"
            limits:
              cpu: "2"
              memory: "2G"
          command: ["java", "-jar", "spring-cloud-dataflow-server-2.6.3.jar"]
          args:
            - --spring.cloud.dataflow.features.streams-enabled=false
            - --spring.cloud.dataflow.features.schedules-enabled=false
            - --spring.cloud.dataflow.features.tasks-enabled=true
            - --spring.datasource.url=jdbc:h2:tcp://h2:1521/db
            - --spring.datasource.driver-class-name=org.h2.Driver
            - --spring.datasource.initialization-mode=always
            - --spring.datasource.schema=classpath*:/org/springframework/cloud/dataflow/server/db/migration/h2/V1__INITIAL_SETUP.sql
            - --spring.flyway.enabled=false
            - --server.port=8080
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: private-docker-registry-secret
```

**Additional context:**
When deployed to Docker / locally in the exact same way, we've never experienced this NPE. Everything works like a charm there.

Even when trying to start out-of-the-box test apps from SCDF it doesn't work. It just won't let me start any tasks, no matter whats registered.

Any help on this?
Thanks in Advance!

**Comment by cppwfs** [comment]
It looks like your SCDF is not configured properly.
Note in your runtime environment you have no task launchers enumerated.  
```
   "runtimeEnvironment":{
      "appDeployer":{
         "deployerImplementationVersion":null,
         "deployerName":null,
         "deployerSpiVersion":null,
         "javaVersion":null,
         "platformApiVersion":null,
         "platformClientVersion":null,
         "platformHostVersion":null,
         "platformSpecificInfo":{
            
         },
         "platformType":null,
         "springBootVersion":null,
         "springVersion":null
      },
      "taskLaunchers":[
         
      ]
   },
```

We have instructions for installing and configuring kubernetes located here:
https://dataflow.spring.io/docs/installation/kubernetes/
