### ISSUE TITLE
Execption while launch of task which have same name

### ISSUE THREAD

**Issue by sandip0018** [spring-cloud/spring-cloud-dataflow#448]
I have created one custom task and now when i launch it first time it works perfect.
but when i try to launch same task another time it give me below error in shell.

```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Exception trying to deploy org.springframework.cloud.dataflow.c
ore.ModuleDeploymentRequest@18e0609f

Exception trying to deploy org.springframework.cloud.dataflow.core.ModuleDeploymentRequest@18e0609f

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Exception trying to deploy org.springframework.cloud.dataflow.core.ModuleDeplo
ymentRequest@18e0609f

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:357)
    at org.springframework.cloud.dataflow.rest.client.TaskTemplate.launch(TaskTemplate.java:80)
    at org.springframework.cloud.dataflow.shell.command.TaskCommands.launch(TaskCommands.java:118)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Unknown Source)
```

and in server console it gives below error
```
Caused by: java.nio.file.FileAlreadyExistsException: C:\Users\1085950\AppData\Local\Temp\spring-cloud-data-flow-5071359913354765303\mongo2Hadoop.mongo
hadoop-custom
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[na:1.8.0_45]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_45]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[na:1.8.0_45]
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source) ~[na:1.8.0_45]
        at java.nio.file.Files.createDirectory(Unknown Source) ~[na:1.8.0_45]
        at org.springframework.cloud.dataflow.admin.spi.local.OutOfProcessModuleDeployer.deploy(OutOfProcessModuleDeployer.java:96) ~[spring-cloud-dat
aflow-admin-local-1.0.0.M2.jar!/:1.0.0.M2]

```

**Comment by sabbyanandan** [comment]
Hi, @sandip0018: Could you please retry this on 1.0 GA release? There have been lot of new changes and improvements around this workflow.

**Comment by sabbyanandan** [comment]
No response from the reporter. Closing it.
