### ISSUE TITLE
NPE when trying to unregister a group of apps and one is in use by a stream

### ISSUE THREAD

**Issue by tomgeraghty3** [spring-cloud/spring-cloud-dataflow#4501]
**Description:**
A `NullPointerException` occurs when using the "Group Actions" in "Applications" and trying to unregister 2 or more apps when at least 1 of those apps is in use by a Stream. This is when running SCDF locally

In my example I have "file" as a source in use by a stream. If I try to unregister this app I get:
The app [file:source:3.0.1] you're trying to unregister is currently used in stream 'mystr' 
![image](https://user-images.githubusercontent.com/47372735/116998057-9273b480-acd5-11eb-8b78-840055e7ff0c.png)
as expected.

However if I try to unregister this app at the same time as any other app (i.e. selecting 2 or more apps to unregister at once) I get the following:
![image](https://user-images.githubusercontent.com/47372735/116998013-84259880-acd5-11eb-92b2-0a3b6ebb3f5a.png)

Stack trace:

```dataflow-server    | 2021-05-04 11:38:47.351  WARN 1 --- [nio-9393-exec-2] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: The app [file:source:3.0.1] you're trying to unregister is currently used in stream 'mystr'.
dataflow-server    | 2021-05-04 11:38:47.359 ERROR 1 --- [nio-9393-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
dataflow-server    |
dataflow-server    | java.lang.NullPointerException: null
dataflow-server    | 	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.findStreamContainingAppOf(AppRegistryController.java:337)
dataflow-server    | 	at org.springframework.cloud.dataflow.server.controller.AppRegistryController.unregister(AppRegistryController.java:284)
dataflow-server    | 	at jdk.internal.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
dataflow-server    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
dataflow-server    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
dataflow-server    | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
dataflow-server    | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
dataflow-server    | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
dataflow-server    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
dataflow-server    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
dataflow-server    | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
dataflow-server    | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
dataflow-server    | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
dataflow-server    | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
dataflow-server    | 	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931)
dataflow-server    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:658)
dataflow-server    | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
dataflow-server    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server    | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
dataflow-server    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server    | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
dataflow-server    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server    | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
dataflow-server    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server    | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
dataflow-server    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
dataflow-server    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
dataflow-server    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
dataflow-server    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
dataflow-server    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
dataflow-server    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
dataflow-server    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
dataflow-server    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
dataflow-server    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
dataflow-server    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
dataflow-server    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
dataflow-server    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
dataflow-server    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
dataflow-server    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
dataflow-server    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
dataflow-server    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
dataflow-server    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
dataflow-server    | 	at java.base/java.lang.Thread.run(Unknown Source)
```

I also noticed there was a correlation between the number of times this stack trace appears and the number of none-in-use apps I try to unregister e.g. when I try to unregister 3 apps (1 of them being the one in use by the Stream) then the same stack trace appears twice in the logs whereas if I try to unregister just 1 additional app to the one in use then the stack trace appears only once in the logs.

**Release versions:**
```{
    "featureInfo": {
        "analyticsEnabled": true,
        "streamsEnabled": true,
        "tasksEnabled": true,
        "schedulesEnabled": false,
        "monitoringDashboardType": "NONE"
    },
    "versionInfo": {
        "implementation": {
            "name": "spring-cloud-dataflow-server",
            "version": "2.7.1"
        },
        "core": {
            "name": "Spring Cloud Data Flow Core",
            "version": "2.7.1"
        },
        "dashboard": {
            "name": "Spring Cloud Dataflow UI",
            "version": "3.0.1"
        },
        "shell": {
            "name": "Spring Cloud Data Flow Shell",
            "version": "2.7.1",
            "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.1/spring-cloud-dataflow-shell-2.7.1.jar"
        }
    },
    "securityInfo": {
        "authenticationEnabled": false,
        "authenticated": false,
        "username": null,
        "roles": []
    },
    "runtimeEnvironment": {
        "appDeployer": {
            "deployerImplementationVersion": "2.6.1",
            "deployerName": "Spring Cloud Skipper Server",
            "deployerSpiVersion": "2.6.1",
            "javaVersion": "11.0.8",
            "platformApiVersion": "",
            "platformClientVersion": "",
            "platformHostVersion": "",
            "platformSpecificInfo": {
                "default": "local"
            },
            "platformType": "Skipper Managed",
            "springBootVersion": "2.3.7.RELEASE",
            "springVersion": "5.2.12.RELEASE"
        },
        "taskLaunchers": [
            {
                "deployerImplementationVersion": "2.5.1",
                "deployerName": "LocalTaskLauncher",
                "deployerSpiVersion": "2.5.1",
                "javaVersion": "11.0.8",
                "platformApiVersion": "Linux 5.4.39-linuxkit",
                "platformClientVersion": "5.4.39-linuxkit",
                "platformHostVersion": "5.4.39-linuxkit",
                "platformSpecificInfo": {},
                "platformType": "Local",
                "springBootVersion": "2.3.7.RELEASE",
                "springVersion": "5.2.12.RELEASE"
            }
        ]
    },
    "monitoringDashboardInfo": {
        "url": "",
        "refreshInterval": 15,
        "dashboardType": "NONE",
        "source": "default-scdf-source"
    },
    "_links": {
        "self": {
            "href": "http://localhost:9393/about"
        }
    }
}

**Comment by ilayaperumalg** [comment]
Hi @tomgeraghty3 , Thanks for reporting this.

I try to replicate the issue you see and have a question.

> However if I try to unregister this app at the same time as any other app (i.e. selecting 2 or more apps to unregister at once) I get the following:

In this, Could you tell me how this is different from the first step where you tried to unregister one of the used apps along with unused apps?

**Comment by tomgeraghty3** [comment]
Hi @ilayaperumalg,

In the first screenshot I tried to unregister the app that was in use on it's own - i.e. I only unregister **that** app and nothing else - and I get the correct message.
In the second screenshot I tried to unregister the app that was in use at the same time as unregistering any other app through the use of the checkboxes in the UI - and I get the `NullPointerException`

Does this clarify things?

**Comment by ilayaperumalg** [comment]
> In the first screenshot I tried to unregister the app that was in use on it's own - i.e. I only unregister that app and nothing else - and I get the correct message.
In the second screenshot I tried to unregister the app that was in use at the same time as unregistering any other app through the use of the checkboxes in the UI - and I get the NullPointerException
Does this clarify things?

Yes, it does. But, I could not successfully replicate the issue as I don't see NPE with the above step. Are you seeing this every time when you try the above step?

**Comment by ilayaperumalg** [comment]
Closing this as non-issue. But, please feel free to re-open if you still see this. Thanks!
