### ISSUE TITLE
how to deploy on docker

### ISSUE THREAD

**Issue by keryhu** [spring-cloud/spring-cloud-dataflow#452]
I use the https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-app-launcher ,

OS: ubuntu 15.10

then

```
$ mvn package docker:build
$ docker-compose up
```
but meet errors :

  ```
  timesource_1 | java.lang.IllegalStateException: No 'Start-Class' manifest entry specified in jar:file:/root/.m2/repository/org/springframework/cloud/stream/module/time-source/1.0.0.BUILD-SNAPSHOT/time-source-1.0.0.BUILD-SNAPSHOT.jar!/
timesource_1 |  at org.springframework.boot.loader.archive.Archive.getMainClass(Archive.java:57)
timesource_1 |  at org.springframework.boot.loader.ExecutableArchiveLauncher.getMainClass(ExecutableArchiveLauncher.java:69)
timesource_1 |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
timesource_1 |  at org.springframework.cloud.dataflow.app.launcher.ModuleJarLauncher.launch(ModuleJarLauncher.java:47)
timesource_1 |  at org.springframework.cloud.dataflow.app.launcher.ModuleLauncher.launchModule(ModuleLauncher.java:238)
timesource_1 |  at org.springframework.cloud.dataflow.app.launcher.ModuleLauncher.launchIndividualModules(ModuleLauncher.java:228)
timesource_1 |  at org.springframework.cloud.dataflow.app.launcher.ModuleLauncher.launch(ModuleLauncher.java:100)
timesource_1 |  at org.springframework.cloud.dataflow.app.launcher.ModuleLauncherRunner.run(ModuleLauncherRunner.java:67)
timesource_1 |  at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806)
timesource_1 |  at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:790)
timesource_1 |  at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:777)
timesource_1 |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
timesource_1 |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
timesource_1 |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
timesource_1 |  at org.springframework.cloud.dataflow.app.launcher.ModuleLauncherApplication.main(ModuleLauncherApplication.java:45)
timesource_1 |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
timesource_1 |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
timesource_1 |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
timesource_1 |  at java.lang.reflect.Method.invoke(Method.java:498)
timesource_1 |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
timesource_1 |  at java.lang.Thread.run(Thread.java:745)
```
Is my method error？ Or how to deploy on docker ?

**Comment by sabbyanandan** [comment]
Hi, @keryhu: Sorry for the delayed response. The app-launcher is gone and replaced by [spring-cloud-deployer](https://github.com/spring-cloud/spring-cloud-deployer) project, an SPI for deploying long lived applications and short lived tasks.

If you're looking to generate docker images for OOTB apps, we do that already, so you could just reuse them. See this [list of images](https://hub.docker.com/u/springcloudstream/) in docker hub. 

If you're looking to generate docker image for the server, please follow the pointers in [this issue](https://github.com/spring-cloud/spring-cloud-dataflow/issues/423#issuecomment-233462617).
