### ISSUE TITLE
Error when no schedules exist

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4536]
@sabbyanandan commented on [Thu May 06 2021](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1708)

See:
![image](https://user-images.githubusercontent.com/1562654/117371399-aefe2100-ae7c-11eb-829e-869bce6a351a.png)

Build: 2.8 SNAPSHOT on K8s.

---

@oodamien commented on [Mon May 10 2021](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1708#issuecomment-836350101)

@cppwfs The issue is there is no platform define (basic setup on minikube).
The issue affect all the schedule pages (creation, view, ...) since we are not able to have a list of platforms.

```
{
  "_links": {
    "self": {
      "href": "http://localhost:4200/tasks/platforms?page=0&size=1000"
    }
  },
  "page": {
    "size": 1000,
    "totalElements": 0,
    "totalPages": 0,
    "number": 0
  }
}
```

---

@cppwfs commented on [Mon May 10 2021](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1708#issuecomment-837098898)

🤔  I just did a 2.8 deployment to TKS using our packaging scripts and there was no issue
@sabbyanandan How did you deploy your SCDF?

---

@sabbyanandan commented on [Mon May 10 2021](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1708#issuecomment-837119270)

SCDF4K8s .. v1.2.1 on Minikube. 

---

@cppwfs commented on [Tue May 11 2021](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1708#issuecomment-838705174)

is investigating.   This is not a scheduler issue. There is an issue with the 2.8 snapshot that it is not retrieving properties from the configmaps when running on minikube.    This started after we upgraded to the latest Spring Cloud release.    

---

@sabbyanandan commented on [Wed May 26 2021](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1708#issuecomment-848989556)

On 1.3 SNAPSHOT in TAS, I get this error again.

![image](https://user-images.githubusercontent.com/1562654/119707078-9b0c6600-be0f-11eb-9295-3e7793b9ddab.png)

Logs:
```
fone.io/dashboard/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" "192.168.4.4:15782" "192.168.16.43:61058" x_forwarded_for:"10.166.51.253, 192.168.4.4" x_forwarded_proto:"https" vcap_request_id:"32de0cee-4de8-431a-6bec-4c660ebf1d6c" response_time:0.091693 gorouter_time:0.000412 app_id:"6f4d78df-8098-4989-8a38-6dac4ec7ceef" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"76a36650bac10d1e" x_b3_spanid:"76a36650bac10d1e" x_b3_parentspanid:"-" b3:"76a36650bac10d1e-76a36650bac10d1e"
   2021-05-26T10:41:28.29-0700 [RTR/2] OUT
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 2021-05-26 17:41:28.349 ERROR 16 --- [nio-8080-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.list(DefaultSchedulerService.java:361) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController.filteredList(TaskSchedulerController.java:122) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_282]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_282]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_282]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_282]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) [tomcat-embed-core-9.0.45.jar:4.0.FR]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.45.jar:4.0.FR]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:156) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [spring-boot-actuator-2.4.5.jar:2.4.5]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.34-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:79) [client_certificate_mapper-1.11.0_RELEASE.jar:na]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T10:41:28.35-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
   2021-05-26T10:41:28.36-0700 [RTR/1] OUT sabby-dataflow-server.apps.pcfone.io - [2021-05-26T17:41:28.342171959Z] "GET /tasks/schedules/instances/test?platform=cf-staging HTTP/1.1" 500 0 124 "https://sabby-dataflow-server.apps.pcfone.io/dashboard/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" "192.168.4.4:61965" "192.168.16.43:61058" x_forwarded_for:"10.166.51.253, 192.168.4.4" x_forwarded_proto:"https" vcap_request_id:"ad67f005-3b5a-4639-4a7c-1bb2f05bdc77" response_time:0.020540 gorouter_time:0.000316 app_id:"6f4d78df-8098-4989-8a38-6dac4ec7ceef" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"5d880dad28c6fcf7" x_b3_spanid:"5d880dad28c6fcf7" x_b3_parentspanid:"-" b3:"5d880dad28c6fcf7-5d880dad28c6fcf7"
```

This task in my test is manually launched, and not schedule driven. And, yet, when going to Tasks detail page, I get this NPE.

**Comment by cppwfs** [comment]
Please verify that the SCDF is configured properly.   A simple way to do this is to launch a task and attempt to select a platform.   You should see at least one option `default (kubernetes)`.   If none appears then the container that you are using may not have been built correctly.

**Comment by jvalkeal** [comment]
1. Server should be better not to throw npe if scheduler is not defined
2. I'm questioning that we're just throwing too much stuff into those toast messages(as in this case that schedules box could then tell no schedules).

**Comment by cppwfs** [comment]
When I've seen this before (not saying its the case here) it was a problem in the setup of the dataflow.  ie. dataflow didn't have a task launcher for example.   We can break up the command to give us more data.

**Comment by sabbyanandan** [comment]
I am not sure if this is addressed differently, but here's some thesis.

With this config, I am able to get around several errors:

```
 SPRING_APPLICATION_JSON: |-
      {
          "logging.level.com.zaxxer.hikari": "debug",
          "management.endpoints.web.exposure.include": "*",
          "maven": {
            "remote-repositories": {
              "repo1": {
                "url": "https://repo.spring.io/libs-snapshot-local"
              }
            }
          },
          "spring.cloud.dataflow.server.uri": "https://sabby-server.apps.pcfone.io",
          "spring.cloud.dataflow.task.platform.cloudfoundry.accounts": {
            "default": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "k8s-default": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "cf-staging": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "cf-staging",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "cf-prod": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            }
          },
          "spring.profiles.active": "cloud"
      }
```

There's also https://github.com/spring-cloud/spring-cloud-dataflow/pull/4550, which may address the blunt NPEs.
