### ISSUE TITLE
Launching a previously created CT definition fails with NPE

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4537]
As a user, on CF, I attempted to relaunch the same CT definition from last week, and I get an NPE in CTR instead.

Notes:
- I don't have any schedule created on this definition.
- I don't have any existing droplets on the tasks in the CTR.
- I don't have a successful launch of this task from last week either, just the definition was created last week.
- Of course, I don't have any task executions either.

Logs:
```
2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT  / ____|                                       | | |__   __|      | |
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT | |     ___  _ __ ___  _ __   ___  ___  ___  __| |    | | __ _ ___| | __
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT | |    / _ \| '_ ` _ \| '_ \ / _ \/ __|/ _ \/ _` |    | |/ _` / __| |/ /
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT | |___| (_) | | | | | | |_) | (_) \__ \  __/ (_| |    | | (_| \__ \   <
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT  \_____\___/|_| |_| |_| .__/ \___/|___/\___|\__,_|    |_|\__,_|___/_|\_\
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT                       | |
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT                       |_|
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT  _____
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT |  __ \
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT | |__) |   _ _ __  _ __   ___ _ __
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT |  _  / | | | '_ \| '_ \ / _ \ '__|
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT | | \ \ |_| | | | | | | |  __/ |
   2021-05-26T11:08:57.16-0700 [APP/TASK/task-fab/0] OUT |_|  \_\__,_|_| |_|_| |_|\___|_|
   2021-05-26T11:08:57.29-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:08:57.280  INFO 17 --- [           main] o.s.c.d.c.ComposedTaskRunner             : Starting ComposedTaskRunner v2.8.0-SNAPSHOT using Java 1.8.0_242 on 77a8c98d-9243-41a3-83db-426f1598351c with PID 17 (/home/vcap/app/BOOT-INF/classes started by vcap in /home/vcap/app)
   2021-05-26T11:08:57.29-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:08:57.293  INFO 17 --- [           main] o.s.c.d.c.ComposedTaskRunner             : The following profiles are active: cloud
   2021-05-26T11:08:58.49-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:08:58.499  INFO 17 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
   2021-05-26T11:08:58.50-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:08:58.501  INFO 17 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
   2021-05-26T11:08:58.54-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:08:58.540  INFO 17 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 26 ms. Found 0 JPA repository interfaces.
   2021-05-26T11:08:59.00-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:08:59.009  INFO 17 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.task.batch.configuration.TaskBatchAutoConfiguration' of type [org.springframework.cloud.task.batch.configuration.TaskBatchAutoConfiguration$$EnhancerBySpringCGLIB$$be6d01e6] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
   2021-05-26T11:08:59.88-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:08:59.883  INFO 17 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
   2021-05-26T11:09:00.05-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:00.055  INFO 17 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
   2021-05-26T11:09:00.17-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:00.169  INFO 17 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
   2021-05-26T11:09:00.27-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:00.279  INFO 17 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.30.Final
   2021-05-26T11:09:00.54-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:00.540  INFO 17 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
   2021-05-26T11:09:00.80-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:00.802  INFO 17 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MariaDB53Dialect
   2021-05-26T11:09:01.16-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:01.160  INFO 17 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
   2021-05-26T11:09:01.17-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:01.178  INFO 17 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
   2021-05-26T11:09:01.40-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:01.406  INFO 17 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'taskExecutor'
   2021-05-26T11:09:01.44-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:01.448  INFO 17 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: MYSQL
   2021-05-26T11:09:01.47-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:01.478  INFO 17 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : No TaskExecutor has been set, defaulting to synchronous executor.
   2021-05-26T11:09:02.17-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.177  INFO 17 --- [           main] o.s.c.d.c.ComposedTaskRunner             : Started ComposedTaskRunner in 5.794 seconds (JVM running for 6.513)
   2021-05-26T11:09:02.18-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.181  INFO 17 --- [           main] o.s.b.a.b.JobLauncherApplicationRunner   : Running default command line with: []
   2021-05-26T11:09:02.32-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.321  INFO 17 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [FlowJob: [name=task-fab]] launched with the following parameters: [{run.id=1}]
   2021-05-26T11:09:02.34-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.344  INFO 17 --- [           main] o.s.c.t.b.l.TaskBatchExecutionListener   : The job execution id 11 was run within the task execution 17
   2021-05-26T11:09:02.46-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.461  INFO 17 --- [ taskExecutor-1] o.s.batch.core.job.SimpleStepHandler     : Executing step: [task-fab-extractDB_0]
   2021-05-26T11:09:02.47-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.475  INFO 17 --- [ taskExecutor-2] o.s.batch.core.job.SimpleStepHandler     : Executing step: [task-fab-extractFiles_0]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.747 ERROR 17 --- [ taskExecutor-2] o.s.batch.core.step.AbstractStep         : Encountered an error executing step task-fab-extractFiles_0 in job task-fab
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT java.lang.NullPointerException: null
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.cloud.dataflow.composedtaskrunner.TaskLauncherTasklet.execute(TaskLauncherTasklet.java:169) ~[classes/:2.8.0-SNAPSHOT]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.6.jar:5.3.6]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:152) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:94) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:91) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.748  INFO 17 --- [ taskExecutor-2] .c.d.c.ComposedTaskStepExecutionListener : AfterStep processing for stepExecution task-fab-extractFiles_0
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.748 ERROR 17 --- [ taskExecutor-2] o.s.batch.core.step.AbstractStep         : Exception in afterStep callback in step task-fab-extractFiles_0 in job task-fab
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT java.lang.IllegalArgumentException: TaskLauncherTasklet did not return a task-execution-id.  Check to see if task exists.
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.6.jar:5.3.6]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.cloud.dataflow.composedtaskrunner.ComposedTaskStepExecutionListener.afterStep(ComposedTaskStepExecutionListener.java:65) ~[classes/:2.8.0-SNAPSHOT]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.listener.CompositeStepExecutionListener.afterStep(CompositeStepExecutionListener.java:64) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:247) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:152) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:94) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:91) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
   2021-05-26T11:09:02.74-0700 [APP/TASK/task-fab/0] OUT 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 2021-05-26 18:09:02.750 ERROR 17 --- [ taskExecutor-1] o.s.batch.core.step.AbstractStep         : Encountered an error executing step task-fab-extractDB_0 in job task-fab
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT java.lang.NullPointerException: null
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.cloud.dataflow.composedtaskrunner.TaskLauncherTasklet.execute(TaskLauncherTasklet.java:169) ~[classes/:2.8.0-SNAPSHOT]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.6.jar:5.3.6]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:152) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:94) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at org.springframework.batch.core.job.flow.support.state.SplitState$1.call(SplitState.java:91) [spring-batch-core-4.3.2.jar:4.3.2]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
   2021-05-26T11:09:02.75-0700 [APP/TASK/task-fab/0] OUT 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
```

**Comment by sabbyanandan** [comment]
FWIW, I see this on PRO 1.3-SNAP (2.8 SNAP) on TAS.

**Comment by cppwfs** [comment]
When creating a new CTR does this occur?

**Comment by sabbyanandan** [comment]
It fails for new CT on my end. You should try it on your side.

**Comment by jvalkeal** [comment]
This somehow has to be configuration issue around server address.

**Comment by sabbyanandan** [comment]
With this config, I am able to get around several errors:

```
 SPRING_APPLICATION_JSON: |-
      {
          "logging.level.com.zaxxer.hikari": "debug",
          "management.endpoints.web.exposure.include": "*",
          "maven": {
            "remote-repositories": {
              "repo1": {
                "url": "https://repo.spring.io/libs-snapshot-local"
              }
            }
          },
          "spring.cloud.dataflow.server.uri": "https://sabby-server.apps.pcfone.io",
          "spring.cloud.dataflow.task.platform.cloudfoundry.accounts": {
            "default": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "k8s-default": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "cf-staging": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "cf-staging",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "cf-prod": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            }
          },
          "spring.profiles.active": "cloud"
      }
```

There's also https://github.com/spring-cloud/spring-cloud-dataflow/pull/4550, which may address the blunt NPEs.
