### ISSUE TITLE
Destroying an existing CT definition without a schedule fails with an NPE

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4538]
This is probably an extension of #4537. 

Notes:
1- I do have a scheduler instance available in the ORG/Space where I am launching this task (see screenshot). However, I am _not_ scheduling the launch. 
2- I do have the platform accounts in SCDF wired with the available scheduler instance; of course, I am not using it, anyway.
3- No task executions exist for this task either. DB is clean for this given task.

CF Services:
![image](https://user-images.githubusercontent.com/1562654/119714639-f5a9c000-be17-11eb-96e5-9855ece77122.png)

Logs:
```
2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 2021-05-26 18:41:55.432 ERROR 16 --- [nio-8080-exec-1] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.listForPlatform(DefaultSchedulerService.java:380) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.unscheduleForTaskDefinition(DefaultSchedulerService.java:335) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.deleteTaskDefinition(DefaultTaskDeleteService.java:346) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.deleteTaskDefinition(DefaultTaskDeleteService.java:309) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.deleteTaskDefinition(DefaultTaskDeleteService.java:327) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService$$FastClassBySpringCGLIB$$13444684.invoke(<generated>) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService$$EnhancerBySpringCGLIB$$d6e72816.deleteTaskDefinition(<generated>) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.TaskDefinitionController.destroyTask(TaskDefinitionController.java:134) ~[spring-cloud-dataflow-server-core-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_282]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_282]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_282]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_282]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:658) [tomcat-embed-core-9.0.45.jar:4.0.FR]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.45.jar:4.0.FR]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:156) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [spring-boot-actuator-2.4.5.jar:2.4.5]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.6.jar:5.3.6]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:79) [client_certificate_mapper-1.11.0_RELEASE.jar:na]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.45.jar:9.0.45]
   2021-05-26T11:41:55.43-0700 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
   2021-05-26T11:41:55.43-0700 [RTR/2] OUT sabby-dataflow-server.apps.pcfone.io - [2021-05-26T18:41:55.421986929Z] "DELETE /tasks/definitions/task-fab HTTP/1.1" 500 0 124 "https://sabby-dataflow-server.apps.pcfone.io/dashboard/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" "192.168.4.4:18984" "192.168.16.43:61058" x_forwarded_for:"10.166.51.253, 192.168.4.4" x_forwarded_proto:"https" vcap_request_id:"5f7028fd-5bed-40be-7c31-52adbd66ca03" response_time:0.012694 gorouter_time:0.000236 app_id:"6f4d78df-8098-4989-8a38-6dac4ec7ceef" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"2ce3d5e7a1c6779e" x_b3_spanid:"2ce3d5e7a1c6779e" x_b3_parentspanid:"-" b3:"2ce3d5e7a1c6779e-2ce3d5e7a1c6779e"
   2021-05-26T11:41:55.43-0700 [RTR/2] OUT
```

**Comment by sabbyanandan** [comment]
With this config, I am able to get around several errors:

```
 SPRING_APPLICATION_JSON: |-
      {
          "logging.level.com.zaxxer.hikari": "debug",
          "management.endpoints.web.exposure.include": "*",
          "maven": {
            "remote-repositories": {
              "repo1": {
                "url": "https://repo.spring.io/libs-snapshot-local"
              }
            }
          },
          "spring.cloud.dataflow.server.uri": "https://sabby-server.apps.pcfone.io",
          "spring.cloud.dataflow.task.platform.cloudfoundry.accounts": {
            "default": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "k8s-default": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "cf-staging": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "cf-staging",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            },
            "cf-prod": {
              "connection.domain": "apps.pcfone.io",
              "connection.org": "pivot-sanandan",
              "connection.password": "***",
              "connection.space": "space-sabby",
              "connection.url": "https://api.run.pcfone.io",
              "connection.username": "***",
              "deployment.services": "scheduler,pmysql",
              "scheduler.scheduler-url": "https://scheduler.run.pcfone.io"
            }
          },
          "spring.profiles.active": "cloud"
      }
```

There's also https://github.com/spring-cloud/spring-cloud-dataflow/pull/4550, which may address the blunt NPEs.
