### ISSUE TITLE
Local admin server allows multiple "deploy"s for same stream definition

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-dataflow#456]
After creating a stream at local admin server one can deploy and undeploy the stream.

However, when the stream is deployed and one issues a `deploy` command again in the shell for this stream, this is handled as if there was no stream deployed at all. The old stream deployment stays running and the new deployment is now "in focus", meaning, you can undeploy it. The old stream however stays running as ghost with no reference in the shell/admin server.

Due to short startup timeouts mentioned here https://github.com/spring-cloud/spring-cloud-dataflow/issues/435#issuecomment-196307644 I cannot test on cloud foundry what the behaviour is there. But I guess a `deploy` against an already deployed stream should give some "bad request"-like error.

**Comment by sabbyanandan** [comment]
We do have the validation rules in place to not accept stream definitions with the same name. I tried the following and I was able to see the validation errors. 

```
dataflow:>stream create foo --definition "http | log" --deploy
Created and deployed new stream 'foo'
dataflow:>stream create foo --definition "jdbc | log" --deploy
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Cannot register stream definition foo because another one has already been registered with the same name

Cannot register stream definition foo because another one has already been registered with the same name
```

Are you running on the latest from master or using the M2 release? The startup timeout you're referring is CF specific and it is not required when running the local deployer.

**Comment by styjdt** [comment]
What I tried was more kind of the following:

    dataflow:>stream create foo --definition "http | log"
    dataflow:>stream deploy foo
    dataflow:>stream deploy foo

So multiple deployments of the same stream definition. Not only multiple definitions with same stream name.
True about the CF related timeout. Wanted only to mention that I would like to verify how the behaviour in another SPI is implemented to be able to tell which one is the correct way :) And unfortunately I could not compare with CF because I got my scenario there not running due to the timeout issue...

I'm running the local admin server from master.

**Comment by sabbyanandan** [comment]
Thanks for the details! This is a bug indeed. :smile: 

We would have to update our validation code to account for unique stream deployments, too. Ideally, you'd see an error message something like "_The stream named 'foo' is already deployed_".

We will get this addressed soon.

**Comment by styjdt** [comment]
As of the last pull from master, I cannot deploy a stream multiple times, probably due to last changes regarding the deployer.
The shell shows:

    dataflow:>stream deploy tocktick
    Deployed stream 'tocktick'
    dataflow:>stream deploy tocktick
    Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: App for 'tocktick.log' is already running

    App for 'tocktick.log' is already running

    org.springframework.cloud.dataflow.rest.client.DataFlowClientException: App for 'tocktick.log' is already running

        at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:357)
        at org.springframework.cloud.dataflow.rest.client.StreamTemplate.deploy(StreamTemplate.java:92)
        at org.springframework.cloud.dataflow.shell.command.StreamCommands.deployStream(StreamCommands.java:129)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
        at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
        at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
        at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
        at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
        at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
        at java.lang.Thread.run(Thread.java:812)
    dataflow:>

So this issue seems to be solved. If the kind of the response to the user is really the intended one (including a stacktrace...), you should decide.

Alexander

**Comment by ericbottard** [comment]
Fixed by a change in deployer(s)
