### ISSUE TITLE
Spring Data flow server 2.7.2 is not recognizing  stream name with underscore ("_") character

### ISSUE THREAD

**Issue by suresh-chidham** [spring-cloud/spring-cloud-dataflow#4640]
Recently we are trying to migrate from 2.4.1 to 2.7.2 version spring data flow server.
When we try to deploy existing stream name,  **SCDF_test**,  Unable to deploy the stream. We are getting below error.

o.s.c.d.s.c.RestControllerAdvice : Caught exception while handling a request: Stream name must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123')
2021-07-27T10:12:33.017+05:30 [RTR/1] [OUT] dataflow-server.acp..com - [2021-07-27T04:42:32.990442450Z] "POST /streams/definitions HTTP/1.1" 400 835 281

 we have lot of streams are running with underscore("_") character in production environment.
Please can you help on this without renaming all streams to resolve this issue?.  Otherwise Its very tedious process.

**Comment by suresh-chidham** [comment]
Please can you update on this?

**Comment by ilayaperumalg** [comment]
Hi! 

You can find the reasonings on why we don't support underscore as part of the stream name [here](https://github.com/spring-cloud/spring-cloud-dataflow/issues/4079).

**Comment by suresh-chidham** [comment]
Thanks for reasoning.  As per my understanding,  if data flow server runs in kubernetes ,you are restricting underscore character in stream name. But we are running data flow server in PCF platform. is there way to bypass this validation?
why i am asking that, Lot of streams are having with underscore name.

**Comment by ilayaperumalg** [comment]
We discussed this and unfortunately SCDF will be aware of the platform only at the time of stream deployment. At the time of stream creation we can't conditionally validate the platform. We also have users who use both PCF as well as K8s using the same SCDF instance. This was the idea behind enforcing this constraint. 

I see the pain point you have in migrating the stream names in this case. We'll try to see the possibility of adding a server level flag to explicitly bypass this validation (to address your specific case).

**Comment by ilayaperumalg** [comment]
We have a PR #4641 to address this issue. We'll subsequently back-port the changes into 2.7.x and 2.8.x. Please watch the release updates on the same in the upcoming weeks.

**Comment by suresh-chidham** [comment]
Thanks for fixing. When we will expect this fix  in 2.7.x version?

**Comment by suresh-chidham** [comment]
Hi 
Which dependency version we will take for this fix and apply below configuration?
spring.cloud.dataflow.features.underscore-names-enabled

**Comment by ilayaperumalg** [comment]
We have PRs on the fixes on 2.7.x, 2.8.x and 2.9.x. The release plan isn't final yet and we can update the release timeline once decided.  Meanwhile, once the PR is merged you can test it using the SNAPSHOT build that has the fix.

**Comment by suresh-chidham** [comment]
I tried with  below snapshot. Its giving same error. Can you share snapshot version? I will try.
<spring.cloud.dataflow.version>2.7.2-SNAPSHOT</spring.cloud.dataflow.version>

**Comment by ilayaperumalg** [comment]
Hi,

You can try on the snapshot **only after** the PR is merged. Also, the latest snapshot is https://github.com/spring-cloud/spring-cloud-dataflow/blob/2.7.x/pom.xml#L5

Meanwhile, if you can build locally, you can also build the PR and test it out.

**Comment by suresh-chidham** [comment]
is the PR merged to snapshot?

**Comment by ilayaperumalg** [comment]
Hi @suresh-chidham , I guess you are new to Github. The corresponding Github repo will be updated once the PR is merged and the associated PR will be closed as well. Once the Github repo is updated, we have a CI process which generates a snapshot with the changes.

**Comment by suresh-chidham** [comment]
Thanks Ilayaperumal for your information

**Comment by suresh-chidham** [comment]
@ilayaperumalg  Can i use  below dependency to test this stream name "_"  issue with enabling below properties in cloudfoundry environment?
**spring.cloud.dataflow.features.underscore-names-enable: true**

 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dataflow-server</artifactId>
            <version>**2.7.2.SNAPSHOT**</version>
            <scope>import</scope>
        </dependency>

**Comment by ilayaperumalg** [comment]
Hi @suresh-chidham , The changes are now back ported into 2.7.x and the latest 2.7.3-SNAPSHOT has the changes to fix this issue. You **don't** need to have the feature flag `spring.cloud.dataflow.features.underscore-names-enable: true` set as the latest change infers the platform at the time of deployment and perform the validation only for K8s.

**Comment by ilayaperumalg** [comment]
Please let us know if you are able to test this with your environment. Thanks!

**Comment by suresh-chidham** [comment]
@ilayaperumalg   Thanks for info. Before fix, I used 2.7.2 version. After fix Which latest release version i have  to use?

**Comment by ilayaperumalg** [comment]
You will use the 2.7.3 but until that gets released and to get going with your testing, you can use 2.7.3-SNAPSHOT

**Comment by suresh-chidham** [comment]
@ilayaperumalg  thanks. Looks like its working fine. We will do some regression testing with 2.7.3-snapshot version.
We have one question. We can't merge to 2.7.2 release. We are already using 2.7.2 version. it can't be backported to 2.7.2?

**Comment by suresh-chidham** [comment]
@ilayaperumalg  After releasing 2.7.3, Difference between 2.7.2 and 2.7.3 is only this fix or any other new feature available in 2.7.3.  Please can you confirm on this?

**Comment by ilayaperumalg** [comment]
We'll consider adding any other existing fixes or anything that may come up until we do the release from the upstream branches into 2.7.x. So, we can only see the differences of the changes at the time of the release.

**Comment by suresh-chidham** [comment]
@ilayaperumalg  Thanks for update. Please let us know once 2.8.2 release with this fix. Meanwhile i will test with 2.8.2-snapshot.

**Comment by suresh-chidham** [comment]
@ilayaperumalg  We are using dataflowserver: 2.8.2 skipper-server: 2.7.2 version. So far testing are good. we are able to create stream with under_score character through CICD process. 
When i test to create sample stream from dataflow server dashboard (web console), i am not able to create a stream with under_score character.  Refer attached screen shot. 

![image](https://user-images.githubusercontent.com/29041520/132286001-868ae31f-bbb8-4bc9-bb49-d5de3f11f5c9.png)

**Comment by ilayaperumalg** [comment]
Hi @suresh-chidham, We missed this at the UI and thanks for catching it. I have created a UI story on this: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1761 we'll get this addressed soon as part of 2.8.3

**Comment by suresh-chidham** [comment]
Thanks @ilayaperumalg

**Comment by suresh-chidham** [comment]
@ilayaperumalg   When we are testing acceptance ### and staging environment, We are getting  kubernetes error in skipper server
**Spring data flow server:**  2.8.2
**Skipper server:** 2.7.2

**2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] Caused by: java.net.UnknownHostException: kubernetes.default.svc: Name or service not known**

Below is Error stack in skipper server

[APP/PROC/WEB/0] [OUT] 2021-09-16 17:10:52.449 INFO 23 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown completed.
2021-09-16T13:10:52.873-04:00 [APP/PROC/WEB/0] [OUT] Exit status 143
2021-09-16T13:10:52.888-04:00 [CELL/0] [OUT] Cell 35b1d42c-e768-4f29-b529-9cc5a9afd81c destroying container for instance dd2b3997-a0bb-4acf-52ee-ce1a
2021-09-16T13:10:53.125-04:00 [PROXY/0] [OUT] Exit status 137
2021-09-16T13:10:53.302-04:00 [CELL/0] [OUT] Cell 35b1d42c-e768-4f29-b529-9cc5a9afd81c successfully destroyed container for instance dd2b3997-a0bb-4acf-52ee-ce1a
2021-09-16T13:11:33.614-04:00 [API/1] [OUT] Starting app with guid 914711c6-8095-4098-ae61-543e45c10145
2021-09-16T13:11:34.295-04:00 [CELL/0] [OUT] Cell 35b1d42c-e768-4f29-b529-9cc5a9afd81c creating container for instance a64d202e-f3cf-4995-7329-d0de
2021-09-16T13:11:34.746-04:00 [CELL/0] [OUT] Cell 35b1d42c-e768-4f29-b529-9cc5a9afd81c successfully created container for instance a64d202e-f3cf-4995-7329-d0de
2021-09-16T13:11:34.966-04:00 [CELL/0] [OUT] Downloading droplet...
2021-09-16T13:11:40.082-04:00 [CELL/0] [OUT] Downloaded droplet (130.3M)
2021-09-16T13:11:40.504-04:00 [APP/PROC/WEB/0] [OUT] JVM Memory Configuration: -Xmx3494207K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=188096K
2021-09-16T13:11:43.413-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:43.408 WARN 16 --- [ main] ubernetesProfileEnvironmentPostProcessor : Not running inside kubernetes. Skipping 'kubernetes' profile activation.
2021-09-16T13:11:43.474-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:43.474 INFO 16 --- [ main] s.b.CfDataSourceEnvironmentPostProcessor : Setting spring.datasource properties from bound service [rds-skipper_shared-credhub-sb]
2021-09-16T13:11:43.474-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:43.474 WARN 16 --- [ main] i.p.c.s.boot.CfEnvironmentPostProcessor : Skipping auto-configuration: No unique CredHub service found. Found services named [rds-skipper_shared-credhub-sb,scdf-server_credhub-sb]
2021-09-16T13:11:44.189-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:44.188 WARN 16 --- [ main] io.fabric8.kubernetes.client.Config : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2021-09-16T13:11:44.198-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:44.197 WARN 16 --- [ main] io.fabric8.kubernetes.client.Config : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2021-09-16T13:11:44.200-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:44.200 WARN 16 --- [ main] o.s.c.k.f.Fabric8AutoConfiguration : No namespace has been detected. Please specify KUBERNETES_NAMESPACE env var, or use a later kubernetes version (1.3 or later)
2021-09-16T13:11:44.247-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:44.246 INFO 16 --- [ main] ContainerTrustManagerFactory$PKIXFactory : Adding System Trust Manager
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:44.898 WARN 16 --- [ main] s.c.k.f.c.Fabric8ConfigMapPropertySource : Can't read configMap with name: [application] in namespace:[null]. Ignoring.
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get] for kind: [ConfigMap] with name: [application] in namespace: [null] failed.
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:225) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:84) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource.getData(Fabric8ConfigMapPropertySource.java:61) [spring-cloud-kubernetes-fabric8-config-2.0.3.jar:2.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource.<init>(Fabric8ConfigMapPropertySource.java:50) [spring-cloud-kubernetes-fabric8-config-2.0.3.jar:2.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySourceLocator.getMapPropertySource(Fabric8ConfigMapPropertySourceLocator.java:51) [spring-cloud-kubernetes-fabric8-config-2.0.3.jar:2.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:81) [spring-cloud-kubernetes-commons-2.0.3.jar:2.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:67) [spring-cloud-kubernetes-commons-2.0.3.jar:2.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at java.util.Collections$SingletonList.forEach(Collections.java:4824) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:67) [spring-cloud-kubernetes-commons-2.0.3.jar:2.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.0.3.jar:3.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) ~[spring-cloud-context-3.0.3.jar:3.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.0.3.jar:3.0.3]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:639) ~[spring-boot-2.4.7.jar:2.4.7]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:402) ~[spring-boot-2.4.7.jar:2.4.7]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.4.7.jar:2.4.7]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.7.jar:2.4.7]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318) ~[spring-boot-2.4.7.jar:2.4.7]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.skipper.server.app.SkipperServerApplication.main(SkipperServerApplication.java:48) ~[classes/:2.7.2]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app/:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app/:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app/:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app/:na]

2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] Caused by: java.net.UnknownHostException: kubernetes.default.svc: Name or service not known


2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[na:1.8.0_292]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.Dns.lambda$static$0(Dns.java:39) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.utils.OIDCTokenRefreshInterceptor.intercept(OIDCTokenRefreshInterceptor.java:41) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:153) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:472) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:402) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:384) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:935) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220) ~[kubernetes-client-4.13.3.jar:na]
2021-09-16T13:11:44.899-04:00 [APP/PROC/WEB/0] [OUT] ... 26 common frames omitted
2021-09-16T13:11:44.905-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:44.904 INFO 16 --- [ main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-configmap.application.null'}]
2021-09-16T13:11:44.954-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:44.953 WARN 16 --- [ main] ubernetesProfileEnvironmentPostProcessor : Not running inside kubernetes. Skipping 'kubernetes' profile activation.
2021-09-16T13:11:44.959-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:44.959 INFO 16 --- [ main] o.s.c.s.s.app.SkipperServerApplication : The following profiles are active: cloud
2021-09-16T13:11:48.077-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:48.076 INFO 16 --- [ main] o.s.cloud.context.scope.GenericScope : BeanFactory id=a12a2304-3fe3-3262-8ff8-c7d485830129
2021-09-16T13:11:49.160-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:49.159 INFO 16 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat initialized with port(s): 8080 (http)
2021-09-16T13:11:49.178-04:00 [APP/PROC/WEB/0] [OUT] 2021-09-16 17:11:49.178 INFO 16 --- [ main] o.apache.catalina.core.StandardService : Starting service [Tomcat]



Please can you fix this issue in 2.8.2 and 2.7.2 data flow and skipper server respectively?

**Comment by ilayaperumalg** [comment]
This looks like an environment issue as we have been running our acceptance tests using the latest snapshots of 2.8.x which uses Skipper 2.7.x and they look good so far.

**Comment by suresh-chidham** [comment]
Thanks for your update.  We will check and let you know

**Comment by suresh-chidham** [comment]
@ilayaperumalg   Currently we are using below skipper and data flow server versions.
Spring data flow server: 2.8.2
Skipper server: 2.7.2

We are getting some exception stack trace of skipper server as below . It cause that we are not able to do deploy stream, unable to view streams in data flow server dashboard, and so on

9-21T09:36:54.481-04:00 [APP/PROC/WEB/0] [OUT] |_ Mono.checkpoint â‡¢ at org.cloudfoundry.reactor.client.v2.spaces.ReactorSpaces.listApplications(ReactorSpaces.java:177)
2021-09-21T09:36:54.481-04:00 [APP/PROC/WEB/0] [OUT] |_ Mono.checkpoint â‡¢ at org.cloudfoundry.reactor.client.v2.spaces.ReactorSpaces.listApplications(ReactorSpaces.java:177)
2021-09-21T09:36:54.481-04:00 [APP/PROC/WEB/0] [OUT] |_ Mono.checkpoint â‡¢ at org.cloudfoundry.operations.applications.DefaultApplications.get(DefaultApplications.java:263)
2021-09-21T09:36:54.481-04:00 [APP/PROC/WEB/0] [OUT] |_ Mono.checkpoint â‡¢ at org.cloudfoundry.operations.applications.DefaultApplications.get(DefaultApplications.java:263)

**Comment by ilayaperumalg** [comment]
@suresh-chidham This looks like a CF Java client issue that the Skipper server issue. Our team is investigating the issue.

**Comment by suresh-chidham** [comment]
@ilayaperumalg  Thanks.  If we restart the skipper, its working fine. But after some hours, again we are getting same issue.

**Comment by jvalkeal** [comment]
Regarding that k8s config map propertysource error on CF, spring-cloud-kubernetes is trying to be a bit too aggressive but looks like `spring.cloud.kubernetes.config.enable-api=false` will turn it off. I think we need to find away to turn off all k8s stuff on cf and vice versa. It all boils down to having a `cloud` profile active.
