### ISSUE TITLE
MongoDB Sink (3.0.1) not working

### ISSUE THREAD

**Issue by MathanmohanT** [spring-cloud/spring-cloud-dataflow#4660]
Hi Team,

I see MongoDB sink is not working with a simple http(Source) -> MongoDB (Sink) stream. 

**App version**

3.0.1

**Stream info:**

http --port=9999 | mongosink: mongodb --collection=vendor_attr --spring.data.mongodb.database=msink --spring.data.mongodb.host=localhost --spring.data.mongodb.port=27017

**Curl Command:**

$ curl http://localhost:9999 -X POST -H "Content-type: application/json" -d "{\"attribute\": \"Part Name\", \"value\": \"Belt\"}"

**Error Message:**

2021-08-19 14:47:33.183  INFO [mongodb-sink,f6335180fa09c869,a6fdaf206fe1142b,true] 23704 --- [container-0-C-1] o.s.i.h.s.MessagingMethodInvokerHelper   : Overriding default instance of MessageHandlerMethodFactory with provided one.
2021-08-19 14:47:33.217 ERROR [mongodb-sink,f6335180fa09c869,a6fdaf206fe1142b,true] 23704 --- [container-0-C-1] m.o.ReactiveMongoDbStoringMessageHandler : An error occurred in message handler [bean 'mongoConsumerMessageHandler'; defined in: 'org.springframework.cloud.fn.consumer.mongo.MongoDbConsumerConfiguration'; from source: 'org.springframework.core.type.StandardMethodMetadata@9273a8'] on message [GenericMessage [payload=byte[47], headers={content-length=47, http_requestMethod=POST, deliveryAttempt=1, kafka_timestampType=CREATE_TIME, kafka_receivedTopic=Http2MongoDB.http, accept=*/*, b3=f6335180fa09c869-a6fdaf206fe1142b-1, nativeHeaders={b3=[f6335180fa09c869-a6fdaf206fe1142b-1]}, kafka_offset=1, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@19d907b, host=localhost:9999, http_requestUrl=http://localhost:9999/, id=53198020-b865-eed3-2bd8-4119cdeffb06, kafka_receivedPartitionId=0, contentType=application/json, kafka_receivedTimestamp=1629364653068, kafka_groupId=Http2MongoDB, user-agent=curl/7.60.0, timestamp=1629364653182}]]

org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class [B!
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79) ~[spring-data-commons-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.data.mongodb.core.EntityOperations$AdaptibleMappedEntity.of(EntityOperations.java:652) ~[spring-data-mongodb-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]
	at org.springframework.data.mongodb.core.EntityOperations$AdaptibleMappedEntity.access$100(EntityOperations.java:632) ~[spring-data-mongodb-3.0.7.RELEASE.jar!/:3.0.7.RELEASE]

**Comment by MathanmohanT** [comment]
Its working in 3.0.2 version
