### ISSUE TITLE
How to make custom data transfer objects available?

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-dataflow#475]
This is a follow-up to #462.
When registering a custom source module which emits a custom POJO as data transfer object to the message channel, this POJO cannot be used by standard modules due to the fact that the class definition is not known to the standard modules.

Consider a data transfer object definition like the attached one
[Dto.java.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/193114/Dto.java.txt)
And a custom source module like the attached 
[CustomHttpSource.java.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/193116/CustomHttpSource.java.txt), which sends instances of `Dto` to the message channel. The `Dto` class may be in a separate maven artifact for easier reuse in different modules and referenced as dependency in the source module.

When creating a stream from the custom source module to a second custom module which also knows the definition of `Dto`, everything is okay.
 But trying to create a stream from the custom source to a standard module, e.g. `log-sink` or `field-value-counter-sink` results in runtime exceptions in the standard module, when an instance of Dto arrives at the standard module:

```
2016-03-29 11:02:16.082 ERROR 12748 --- [hannel-adapter1] o.s.c.s.b.r.RedisMessageChannelBinder$2  : Failed to deliver message; retries exhausted; message sent to queue 'ERRORS:test.custom-source.test' 

org.springframework.messaging.MessageHandlingException: error occurred in message handler [test.custom-source.test.bridge.handler]; nested exception is org.springframework.core.serializer.support.SerializationFailedException: unable to deserialize [custom.Dto]. Class not found.; nested exception is java.lang.ClassNotFoundException: custom.Dto
    at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442) [spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.cloud.stream.binder.redis.RedisMessageChannelBinder$2$1.doWithRetry(RedisMessageChannelBinder.java:201) ~[spring-cloud-stream-binder-redis-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.binder.redis.RedisMessageChannelBinder$2$1.doWithRetry(RedisMessageChannelBinder.java:197) ~[spring-cloud-stream-binder-redis-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:263) [spring-retry-1.1.2.RELEASE.jar!/:na]
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:168) [spring-retry-1.1.2.RELEASE.jar!/:na]
    at org.springframework.cloud.stream.binder.redis.RedisMessageChannelBinder$2.doSend(RedisMessageChannelBinder.java:197) [spring-cloud-stream-binder-redis-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442) [spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392) [spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) [spring-messaging-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
    at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) [spring-messaging-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
    at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) [spring-messaging-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
    at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:105) [spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.redis.inbound.RedisQueueMessageDrivenEndpoint.popMessageAndSend(RedisQueueMessageDrivenEndpoint.java:224) [spring-integration-redis-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.redis.inbound.RedisQueueMessageDrivenEndpoint.access$300(RedisQueueMessageDrivenEndpoint.java:54) [spring-integration-redis-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.redis.inbound.RedisQueueMessageDrivenEndpoint$ListenerTask.run(RedisQueueMessageDrivenEndpoint.java:323) [spring-integration-redis-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.util.ErrorHandlingTaskExecutor$1.run(ErrorHandlingTaskExecutor.java:55) [spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at java.lang.Thread.run(Thread.java:812) [na:1.8.0_51]
Caused by: org.springframework.core.serializer.support.SerializationFailedException: unable to deserialize [custom.Dto]. Class not found.; nested exception is java.lang.ClassNotFoundException: custom.Dto
    at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:272) ~[spring-cloud-stream-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:244) ~[spring-cloud-stream-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayloadIfNecessary(AbstractBinder.java:224) ~[spring-cloud-stream-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.binder.redis.RedisMessageChannelBinder.access$1300(RedisMessageChannelBinder.java:69) ~[spring-cloud-stream-binder-redis-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.stream.binder.redis.RedisMessageChannelBinder$ReceivingHandler.handleRequestMessage(RedisMessageChannelBinder.java:340) ~[spring-cloud-stream-binder-redis-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
    at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
    ... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: custom.Dto
    at java.net.URLClassLoader.findClass(URLClassLoader.java:444) ~[na:1.8.0_51]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:493) ~[na:1.8.0_51]
    at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178) ~[log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar!/:1.0.0.BUILD-SNAPSHOT]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:426) ~[na:1.8.0_51]
    at org.springframework.util.ClassUtils.forName(ClassUtils.java:250) ~[spring-core-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
    at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:266) ~[spring-cloud-stream-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    ... 27 common frames omitted
```

This is an issue, since e.g. `field-value-counter-sink` explicitly supports POJOs according to the [documentation](http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#spring-cloud-stream-modules-field-value-counter). Also when only working with custom modules one can hit that issue.
Consider the tapped stream definitions:

```
dataflow:>stream create test1 --definition "custom-source > :destination" --deploy
Created and deployed new stream 'test1'
dataflow:>stream create test2 --definition ":destination1 > custom-sink" --deploy
Created and deployed new stream 'test2'
dataflow:>stream create test3 --definition ":destination > :destination1" --deploy
Created and deployed new stream 'test3'
```

For stream `test3` obviously a `bridge-processor` module is created, which eventually causes then the runtime exceptions, since it cannot deserialize from its input channel.

Probably SCDF needs some mechanism to make custom class definitions available. Perhaps registering the maven artifact via shell as `library` module or something?

**Comment by sabbyanandan** [comment]
The interpretation of payload-schema between the custom-producer and custom-consumer applications can be handled via the schema registry support in Spring Cloud Stream.

SCDF's goal is to remain independent (and stateless) and the app-specific dependencies are out of scope.
