### ISSUE TITLE
Failures in DefaultTaskExecutionServiceTests

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#4785]
Starting to see CI failures on a gh actions for `DefaultTaskExecutionServiceTests$SimpleDefaultPlatformTests` and can't get these to fail locally. Usually this indicates that some tests are executing on a different order, etc.
```
DefaultTaskExecutionServiceTests.SimpleDefaultPlatformTests in 0.814 seconds (JVM running for 158.286)
2021-12-13T10:31:43.5461251Z 2021-12-13 10:31:43.545  WARN 2827 --- [           main] .s.c.d.s.s.i.DefaultTaskExecutionService : Task repository shows a running task execution for task myTask-ORIG with no externalExecutionId.
2021-12-13T10:31:43.5611142Z 2021-12-13 10:31:43.560  INFO 2827 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2021-12-13T10:31:43.5724265Z [ThreadedStreamConsumer] ERROR org.apache.maven.plugin.surefire.SurefirePlugin - Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.879 s <<< FAILURE! - in org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionServiceTests$SimpleDefaultPlatformTests
2021-12-13T10:31:43.5742020Z [ThreadedStreamConsumer] ERROR org.apache.maven.plugin.surefire.SurefirePlugin - executeSingleTaskDefaultsToExistingSinglePlatformTest  Time elapsed: 0.106 s  <<< ERROR!
2021-12-13T10:31:43.5748817Z org.springframework.dao.DataIntegrityViolationException: 
2021-12-13T10:31:43.5818592Z StatementCallback; SQL [DELETE FROM TASK_EXECUTION;]; Referential integrity constraint violation: "TASK_EXEC_BATCH_FK: PUBLIC.TASK_TASK_BATCH FOREIGN KEY(TASK_EXECUTION_ID) REFERENCES PUBLIC.TASK_EXECUTION(TASK_EXECUTION_ID) (51)"; SQL statement:
2021-12-13T10:31:43.5861096Z DELETE FROM TASK_EXECUTION; [23503-200]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "TASK_EXEC_BATCH_FK: PUBLIC.TASK_TASK_BATCH FOREIGN KEY(TASK_EXECUTION_ID) REFERENCES PUBLIC.TASK_EXECUTION(TASK_EXECUTION_ID) (51)"; SQL statement:
2021-12-13T10:31:43.5867473Z DELETE FROM TASK_EXECUTION; [23503-200]
2021-12-13T10:31:43.5886226Z 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionServiceTests$SimpleDefaultPlatformTests.setup(DefaultTaskExecutionServiceTests.java:209)
2021-12-13T10:31:43.5896612Z Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 
2021-12-13T10:31:43.5909215Z Referential integrity constraint violation: "TASK_EXEC_BATCH_FK: PUBLIC.TASK_TASK_BATCH FOREIGN KEY(TASK_EXECUTION_ID) REFERENCES PUBLIC.TASK_EXECUTION(TASK_EXECUTION_ID) (51)"; SQL statement:
2021-12-13T10:31:43.5942691Z DELETE FROM TASK_EXECUTION; [23503-200]
2021-12-13T10:31:43.5955377Z 	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionServiceTests$SimpleDefaultPlatformTests.setup(DefaultTaskExecutionServiceTests.java:209)
2021-12-13T10:31:43.5960780Z 
2021-12-13T10:31:43.5984332Z [ThreadedStreamConsumer] INFO org.apache.maven.plugin.surefire.SurefirePlugin - Running org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionServiceTransactionTests

```

**Comment by jvalkeal** [comment]
commit was b3610feeb8dd2d59cbf33cd68fe53072fbccbef6
