### ISSUE TITLE
SCDF fail to download application starters behind corporate proxy

### ISSUE THREAD

**Issue by slobodanl** [spring-cloud/spring-cloud-dataflow#4818]
**Description:**
SCDF fail to download application starters behind a corporate proxy ( no proxy authentication )

**Release versions:**
SCDF 2.9.2

**Steps to reproduce:**
Add Applications > Stream application starters for RabbitMQ/Maven > Import Applications

**Additional context:**
Stack trace 
`dataflow-server      | java.lang.RuntimeException: Error reading from URL [https://dataflow.spring.io/rabbitmq-maven-latest]
dataflow-server      | 	at org.springframework.cloud.dataflow.registry.service.DefaultAppRegistryService.resourceAsLines(DefaultAppRegistryService.java:447)
dataflow-server      | 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
dataflow-server      | Caused by: java.net.SocketException: Network is unreachable (connect failed)
dataflow-server      | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
dataflow-server      | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
dataflow-server      | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
dataflow-server      | 	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
dataflow-server      | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
dataflow-server      | 	at java.base/java.net.Socket.connect(Unknown Source)`

**Comment by markpollack** [comment]
Aside from asking your administrator to open up access to that web site, you can host all the apps locally inside your firewall by using this tool.  https://github.com/dturanski/scdf-app-tool

**Comment by markpollack** [comment]
You can also download that list of apps from outside the firewall and then host that file inside your firewall.

**Comment by markpollack** [comment]
We can investigate if the data flow server can be configured to use a proxy server.
