### ISSUE TITLE
Composed Task Runner problem with volumes mount while launch

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow#4853]
Hi,

I try to launch CTR and set properties as:

```
deployer.composed-task-runner.kubernetes.volumes=[{name: 'config', configMap: {name: 'cm-composed-task-runner-file' }}, {name: 'config-secret', secret: { secretName: 'secret-composed-task-runner'}}]
deployer.composed-task-runner.kubernetes.volumeMounts=[{name: 'config', mountPath: '/etc/config/application.yaml', subPath: 'application.yaml'}, {name: 'config-secret', mountPath: '/etc/config/truststore.jks', subPath: 'truststore.jks'}, {name: 'config-secret', mountPath: '/etc/config/scdf-file/DB_CA.pem', subPath: 'DB_CA.pem'}, {name: 'config-secret', mountPath: '/etc/config/scdf-file/DB_CERT.pem', subPath: 'DB_CERT.pem'}, {name: 'config-secret', mountPath: '/etc/config/scdf-file/DB_KEY_PK8.pk8', subPath: 'DB_KEY_PK8.pk8'}]
deployer.ctr-test-new.my-first-task-batch-with-long-name-process.kubernetes.volumeMounts=[{name: 'config', mountPath: '/etc/config/application.yaml', subPath: 'application.yaml'}, {name: 'config-secret', mountPath: '/etc/config/truststore.jks', subPath: 'truststore.jks'}]
deployer.ctr-test-new.my-first-task-batch-with-long-name-process.kubernetes.volumes=[{name: 'config', configMap: {name: 'cm-my-first-task-batch-with-long-name-process-file' }}, {name: 'config-secret', secret: { secretName: 'secret-my-first-task-batch-with-long-name-process'}}]
deployer.ctr-test-new.my-second-task-batch-with-long-name-process.kubernetes.volumeMounts=[{name: 'config', mountPath: '/etc/config/application.yaml', subPath: 'application.yaml'}, {name: 'config-secret', mountPath: '/etc/config/truststore.jks', subPath: 'truststore.jks'}]
deployer.ctr-test-new.my-second-task-batch-with-long-name-process.kubernetes.volumes=[{name: 'config', configMap: {name: 'cm-my-second-task-batch-with-long-name-process-file' }}, {name: 'config-secret', secret: { secretName: 'secret-my-second-task-batch-with-long-name-process'}}]
```

CTR is launched but I get error:
```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:796) ~[spring-boot-2.5.8.jar!/:2.5.8]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:783) ~[spring-boot-2.5.8.jar!/:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.8.jar!/:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.8.jar!/:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.8.jar!/:2.5.8]
	at org.springframework.cloud.dataflow.composedtaskrunner.ComposedTaskRunner.main(ComposedTaskRunner.java:31) ~[classes!/:2.9.2]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[spring-cloud-dataflow-composed-task-runner.jar:2.9.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[spring-cloud-dataflow-composed-task-runner.jar:2.9.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[spring-cloud-dataflow-composed-task-runner.jar:2.9.2]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[spring-cloud-dataflow-composed-task-runner.jar:2.9.2]
Caused by: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_EXECUTION_PARAMS(JOB_EXECUTION_ID, KEY_NAME, TYPE_CD, STRING_VAL, DATE_VAL, LONG_VAL, DOUBLE_VAL, IDENTIFYING) values (?, ?, ?, ?, ?, ?, ?, ?)]; ERROR: value too long for type character varying(100); nested exception is org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1020) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.insertParameter(JdbcJobExecutionDao.java:359) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
	at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.insertJobParameters(JdbcJobExecutionDao.java:327) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
	at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.saveJobExecution(JdbcJobExecutionDao.java:166) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
	at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:158) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.14.jar!/:5.3.14]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.14.jar!/:5.3.14]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.14.jar!/:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:181) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at com.sun.proxy.$Proxy77.createJobExecution(Unknown Source) ~[na:na]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:137) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:128) ~[spring-batch-core-4.3.4.jar!/:4.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.14.jar!/:5.3.14]
	at com.sun.proxy.$Proxy80.run(Unknown Source) ~[na:na]
	at org.springframework.cloud.task.batch.handler.TaskJobLauncherApplicationRunner.execute(TaskJobLauncherApplicationRunner.java:153) ~[spring-cloud-task-batch-2.3.4.jar!/:2.3.4]
	at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.executeLocalJobs(JobLauncherApplicationRunner.java:173) ~[spring-boot-autoconfigure-2.5.8.jar!/:2.5.8]
	at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.launchJobFromProperties(JobLauncherApplicationRunner.java:160) ~[spring-boot-autoconfigure-2.5.8.jar!/:2.5.8]
	at org.springframework.cloud.task.batch.handler.TaskJobLauncherApplicationRunner.run(TaskJobLauncherApplicationRunner.java:114) ~[spring-cloud-task-batch-2.3.4.jar!/:2.3.4]
	at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.run(JobLauncherApplicationRunner.java:150) ~[spring-boot-autoconfigure-2.5.8.jar!/:2.5.8]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:793) ~[spring-boot-2.5.8.jar!/:2.5.8]
	... 13 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565) ~[postgresql-42.2.24.jar!/:42.2.24]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297) ~[postgresql-42.2.24.jar!/:42.2.24]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322) ~[postgresql-42.2.24.jar!/:42.2.24]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) ~[postgresql-42.2.24.jar!/:42.2.24]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) ~[postgresql-42.2.24.jar!/:42.2.24]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) ~[postgresql-42.2.24.jar!/:42.2.24]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130) ~[postgresql-42.2.24.jar!/:42.2.24]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar!/:na]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-5.3.14.jar!/:5.3.14]
	... 53 common frames omitted
```

Have I passed CM to child task in wrong way? Or maybe is error in CTR (too short value in table BATCH_JOB_PARAMS).

SCDF v.2.9.2

**Comment by cppwfs** [comment]
Sorry for the delayed response:
The format for setting a deployer property for a child app looks something like the below:
deployer.<childappname>.property=<value>

More can be read about setting properties [here]( https://dataflow.spring.io/docs/feature-guides/batch/composed-task/#setting-property-at-composed-task-launch-time).

**Comment by szopal** [comment]
Thanks, now it's working.
