### ISSUE TITLE
Task Lock is not released when Port is already in use error comes in Spring Cloud DataFlow

### ISSUE THREAD

**Issue by JyotiMittal93** [spring-cloud/spring-cloud-dataflow#4933]
**Description:**
When I am running Task via jar in Spring cloud dataflow, it gives the error Port **** was already in use.

**Steps to reproduce:**
I am using spring.cloud.task.singleInstanceEnabled=true in application.properties file and my task is scheduled to run after every 1 minute. So sometimes I get error Port is already in use due to which Task lock for that particular Task remains in Task_lock table and End_Time is null in Task_Execution table.
Due to this, all of the upcoming Task executions find "Failed to process @BeforeTask or @AfterTask annotation because: Task with name "TASK-NAME1" is already running."

2) I even tried to use server.port in my application.properties, but it is not overriding the port number which is randomly assigned by SCDF.

**Screenshots:**
![image](https://user-images.githubusercontent.com/106526911/170997901-c79ab492-4b8c-4030-b556-6b5a64381015.png)
![image](https://user-images.githubusercontent.com/106526911/170998066-cfbc5e8e-8f08-409b-81a9-04bde61a5787.png)

**Additional context:**
I am using spring-cloud-dataflow-server-2.9.1.jar

**Comment by cppwfs** [comment]
Can you provide a small sample task app that exhibits this behavior?

**Comment by JyotiMittal93** [comment]
Any Task app which runs very frequently like after every 1 second or after every 1 minute, there is a high possibility of getting error Port is already in use.
You can just create some task and run it multiple times in your IDE, and in 1 of the console you will see this error.

**Comment by JyotiMittal93** [comment]
![image](https://user-images.githubusercontent.com/106526911/171096490-d79a2113-ca84-4641-8ae6-bd12d0b260c3.png)
![image](https://user-images.githubusercontent.com/106526911/171096583-9bbfb96d-97b2-4237-8c8f-ca86af31d844.png)

For your refrence, attaching screenshots.

**Comment by JyotiMittal93** [comment]
Bootstrap.properties
![image](https://user-images.githubusercontent.com/106526911/171097295-3487409a-d3e0-46f0-b5d6-8d7eea318ce1.png)

**Comment by cppwfs** [comment]
I am unable to reproduce the error that you are seeing.   This can be many causes to this that are not task or dataflow related.   It would be helpful if you could provide us with a sample task that exhibits this behavior.

**Comment by JyotiMittal93** [comment]
![image](https://user-images.githubusercontent.com/106526911/171172468-9499a62c-d365-4253-8c42-2340d337a4e5.png)

**Comment by JyotiMittal93** [comment]
![image](https://user-images.githubusercontent.com/106526911/171172891-42d9b535-c168-40fe-8a20-c7bf942ad127.png)

**Comment by JyotiMittal93** [comment]
![image](https://user-images.githubusercontent.com/106526911/171173165-5e80b5c4-b64e-4122-9f76-2f0d6fd38caf.png)
![image](https://user-images.githubusercontent.com/106526911/171173319-0d572170-93e0-45fb-939b-80dfe9f68e6f.png)

**Comment by JyotiMittal93** [comment]
HikariPool-1 - Shutdown initiated...
2022-06-01 13:51:42,546 INFO  com.zaxxer.hikari.HikariDataSource.close:352  - [app=baas-task, dbid=] - HikariPool-1 - Shutdown completed.
2022-06-01 13:51:42,548 INFO  org.apache.juli.logging.DirectJDKLog.log:173  - [app=baas-task, dbid=] - Stopping service [Tomcat]
2022-06-01 13:51:42,554 INFO  o.s.i.leader.DefaultCandidate.onRevoked:64  - [app=baas-task, dbid=] - DefaultCandidate{role=baas-task-1, id=282} leadership has been revoked: LockContext{role=baas-task-1, id=282, isLeader=false}
2022-06-01 13:51:42,562 WARN  o.s.b.c.e.EventPublishingRunListener$LoggingErrorHandler.handleError:140  - [app=baas-task, dbid=] - Error calling ApplicationEventListener
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:448) ~[spring-orm-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:574) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:361) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.cloud.task.repository.support.SimpleTaskRepository$$EnhancerBySpringCGLIB$$2cd35e43.completeTaskExecution(<generated>) ~[spring-cloud-task-core-2.4.0.jar:2.4.0]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskEnd(TaskLifecycleListener.java:201) ~[spring-cloud-task-core-2.4.0.jar:2.4.0]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.onApplicationEvent(TaskLifecycleListener.java:166) ~[spring-cloud-task-core-2.4.0.jar:2.4.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:158) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.failed(EventPublishingRunListener.java:130) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.callFailedListener(SpringApplicationRunListeners.java:90) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.failed(SpringApplicationRunListeners.java:83) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:808) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at com.payu.baas.NotifyVahanMainApplication.main(NotifyVahanMainApplication.java:23) ~[classes/:na]
Caused by: java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:509) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:588) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:156) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.createEntityManagerForTransaction(JpaTransactionManager.java:466) ~[spring-orm-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:391) ~[spring-orm-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 23 common frames omitted
2022-06-01 13:51:42,569 INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener.logMessage:136  - [app=baas-task, dbid=] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-06-01 13:51:42,573 ERROR o.s.b.d.LoggingFailureAnalysisReporter.report:40  - [app=baas-task, dbid=] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8081 was already in use.

Action:

Identify and stop the process that's listening on port 8081 or configure this application to listen on another port.

**Comment by cppwfs** [comment]
@JyotiMittal93 I see that the TaskLifecycleListener is handling the doTaskEnd event.   It is reporting that `Caused by: java.lang.IllegalStateException: EntityManagerFactory is closed`.

**Comment by JyotiMittal93** [comment]
But why am I getting this error

**Comment by cppwfs** [comment]
https://github.com/spring-cloud/spring-cloud-dataflow/issues/4933#issuecomment-1142066870

**Comment by JyotiMittal93** [comment]
My issue got resolved.
I used spring.main.web-application-type=NONE in my application.properties file becoz of which no port was assigned by Spring Cloud Dataflow and I am now not getting error of Port was already in use.
In this way, my Task Lock is also released properly.
