### ISSUE TITLE
While deploying streams keep getting Error waiting to get Release from a statemachine

### ISSUE THREAD

**Issue by Noushath** [spring-cloud/spring-cloud-dataflow#4937]
**Description:**
Keep getting this errors frequently when trying to deploy streams, and it kind of goes away if restart dataflow and skipper servers
```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Error waiting to get Release from a statemachine

Error waiting to get Release from a statemachine

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Error waiting to get Release from a statemachine
```

**Release versions:**
Please note the versions used as dataflow-server : 2.9.4, skipper :2.8.1

**Steps to reproduce:**
Issue is kind of intermittent, when we try to deploy streams keep getting below, which gets resolved sometimes by restarting servers, or cleaning the mount volumes when trying with docker

```
Error waiting to get Release from a statemachine

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Error waiting to get Release from a statemachine

at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65)

at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)

at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)

at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)

at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)

at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)

at org.springframework.cloud.dataflow.rest.client.StreamTemplate.deploy(StreamTemplate.java:141)

at org.springframework.cloud.dataflow.shell.command.StreamCommands.deployStream(StreamCommands.java:167)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:567)

at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)

at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)

at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)

at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)

at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)

at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)

at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by markpollack** [comment]
What platform are you running on?  Cloud Foundry/TAS or Kubernetes.  I see mention of docker, but we don't support docker as a platform.

**Comment by Noushath** [comment]
Got it, as we moved to k8s we didn't face this issue, incase we see it there will reopen. Previously we faced with local deployer mode.
