### ISSUE TITLE
NullPointerException when destroying a stream

### ISSUE THREAD

**Issue by ractive** [spring-cloud/spring-cloud-dataflow#516]
Destroying an undeployed stream fails:
```
dataflow:>stream create --name test --definition 'time | log'
Created new stream 'test'
dataflow:>stream destroy test
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: NullPointerException
...
```
The stacktrace that leads to the NullPointerException:
```
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:1.8.0_66]
	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer.status(LocalAppDeployer.java:180) ~[spring-cloud-deployer-local-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.undeployStream(StreamDeploymentController.java:371) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.undeploy(StreamDeploymentController.java:130) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.delete(StreamDefinitionController.java:160) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
```
The variable `id` that is returned from `this.deploymentIdRepository.findOne(key)` is null in `StreamDeploymentController.undeployStream(StreamDefinition)`

**Comment by sabbyanandan** [comment]
Hi, @ractive; Thanks for reporting this! 

We have a similar issue [_spring-cloud/spring-cloud-dataflow#511_]; I'll close this and please feel to add any other thoughts in the other issue. We will address this shortly.
