### ISSUE TITLE
Local Install Fails for mysql

### ISSUE THREAD

**Issue by robertmcnees** [spring-cloud/spring-cloud-dataflow#5167]
While installing Dataflow locally for the first time following this [this guide](https://dataflow.spring.io/docs/installation/local/docker/) I initially tried mysql as a database provider.  The documentation references this as an option and [seems valid](https://github.com/spring-cloud/spring-cloud-dataflow/tree/main/src/docker-compose).

However when executing the command:
`docker-compose -f docker-compose.yml -f docker-compose-rabbitmq.yml -f docker-compose-mysql.yml up`

the application failed to start and produced this error:

```
skipper              | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.RuntimeException: Driver org.mariadb.jdbc.Driver claims to not accept jdbcUrl, jdbc:mysql://mysql:3306/dataflow
```

Changing the database to mariadb and executing the same command 
`docker-compose -f docker-compose.yml -f docker-compose-rabbitmq.yml -f docker-compose-mariadb.yml up`
was successful.

Should the local install for Dataflow support mysql as a database provider?

Full stack trace for the error:
```
dataflow-server      | 2022-12-21 18:17:52.083  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9393 (http)
dataflow-server      | 2022-12-21 18:17:52.094  INFO 1 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Initializing ProtocolHandler ["http-nio-9393"]
dataflow-server      | 2022-12-21 18:17:52.094  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
dataflow-server      | 2022-12-21 18:17:52.095  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.69]
dataflow-server      | 2022-12-21 18:17:52.169  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
dataflow-server      | 2022-12-21 18:17:52.450  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
dataflow-server      | 2022-12-21 18:17:52.515  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.RuntimeException: Driver org.mariadb.jdbc.Driver claims to not accept jdbcUrl, jdbc:mysql://mysql:3306/dataflow
dataflow-server      | 2022-12-21 18:17:52.517  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
dataflow-server      | 2022-12-21 18:17:52.602 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
dataflow-server      | 
dataflow-server      | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.RuntimeException: Driver org.mariadb.jdbc.Driver claims to not accept jdbcUrl, jdbc:mysql://mysql:3306/dataflow
dataflow-server      | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
dataflow-server      | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
dataflow-server      | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
dataflow-server      | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
dataflow-server      | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
dataflow-server      | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
dataflow-server      | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
dataflow-server      | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
dataflow-server      | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
dataflow-server      | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
dataflow-server      | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
dataflow-server      | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
dataflow-server      | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
dataflow-server      | 	at org.springframework.cloud.dataflow.server.single.DataFlowServerApplication.main(DataFlowServerApplication.java:52)
dataflow-server      | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataflow-server      | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
dataflow-server      | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
dataflow-server      | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
dataflow-server      | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
dataflow-server      | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
dataflow-server      | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
dataflow-server      | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
dataflow-server      | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.RuntimeException: Driver org.mariadb.jdbc.Driver claims to not accept jdbcUrl, jdbc:mysql://mysql:3306/dataflow
dataflow-server      | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
dataflow-server      | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
dataflow-server      | 	... 29 common frames omitted
dataflow-server      | Caused by: java.lang.RuntimeException: Driver org.mariadb.jdbc.Driver claims to not accept jdbcUrl, jdbc:mysql://mysql:3306/dataflow
dataflow-server      | 	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:110)
dataflow-server      | 	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331)
dataflow-server      | 	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
dataflow-server      | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
dataflow-server      | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
dataflow-server      | 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
dataflow-server      | 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
dataflow-server      | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
dataflow-server      | 	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:337)
dataflow-server      | 	at org.springframework.cloud.dataflow.common.flyway.DatabaseDriverUtils.getDatabaseDriver(DatabaseDriverUtils.java:52)
dataflow-server      | 	at org.springframework.cloud.dataflow.server.db.migration.DataFlowFlywayConfigurationCustomizer.customize(DataFlowFlywayConfigurationCustomizer.java:50)
dataflow-server      | 	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.lambda$flyway$0(FlywayAutoConfiguration.java:122)
dataflow-server      | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
dataflow-server      | 	at java.base/java.util.ArrayList.forEach(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
dataflow-server      | 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
dataflow-server      | 	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:122)
dataflow-server      | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataflow-server      | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
dataflow-server      | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
dataflow-server      | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
dataflow-server      | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
dataflow-server      | 	... 30 common frames omitted
```

**Comment by onobc** [comment]
HI @robertmcnees 
It sounds like the guide (or the yml) may be missing a key piece of information, the `permitMysqlScheme` parameter on the jdbc url that allows MariaDB driver to accept the `mysql` scheme. See [this section](https://docs.spring.io/spring-cloud-dataflow/docs/2.10.0/reference/htmlsingle/#configuration-local-rdbms) of the ref guide for more info. 

Adjust the jdbc url to `jdbc:mysql://mysql:3306/dataflow?permitMysqlScheme` and see if that works. 

The output of this ticket will be to update the docs/scripts to work properly for mysql. Thanks for the report and sorry for the inconvenience.

**Comment by robertmcnees** [comment]
Thanks @onobc!  That worked for me locally.  I submitted a PR #5168 with the fix.

**Comment by robertmcnees** [comment]
I tested again and mysql seems to work fine now.  Thanks for finding the issue!

**Comment by onobc** [comment]
The CI run failed but it was unrelated to this change.
