### ISSUE TITLE
SFTP source doesn't accept "ref" as reading mode

### ISSUE THREAD

**Issue by bjafet123** [spring-cloud/spring-cloud-dataflow#5225]
When a stream is created using SFTP as a source and setting the consumer mode doesn't accept the "**ref**" value. And according with the documentation and description from the app, it is an accepted value.

![sftp-source-ref](https://user-images.githubusercontent.com/100607897/220686417-7b363b0e-ee29-45f3-8e3e-9cf10211c082.png)

![sftp-source-ref2](https://user-images.githubusercontent.com/100607897/220686489-0408c938-8518-4340-8d5b-d2dfa4c8087e.png)

The stream is only a simple one that contains sftp, a transform and a log (sftp | transform | log) in the definition

The parameter are like:
```
app.sftp.allow-unknown-keys=true
app.sftp.file.consumer.mode=ref
app.sftp.host=myhost
app.sftp.password=mypassword
app.sftp.remote-dir=/mydir
app.sftp.stream=true
app.sftp.username=myuser
app.transform.spel.function.expression=new String(payload)
```

When the stream is deployed it throws an exception related to this parameter as follows:

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-02-22 09:48:47.036 ERROR [sftp-source,,] 13520 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sftpReadingFlow' defined in org.springframework.cloud.fn.supplier.sftp.SftpSupplierConfiguration$StreamingConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.reactivestreams.Publisher]: Factory method 'sftpReadingFlow' threw exception; nested exception is java.lang.IllegalArgumentException: ref is not a supported file reading mode when streaming.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.20.jar!/:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.20.jar!/:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.20.jar!/:5.3.20]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.8.jar!/:2.6.8]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) ~[spring-boot-2.6.8.jar!/:2.6.8]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420) ~[spring-boot-2.6.8.jar!/:2.6.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.6.8.jar!/:2.6.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.8.jar!/:2.6.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.8.jar!/:2.6.8]
	at org.springframework.cloud.stream.app.sftp.source.kafka.SftpSourceKafkaApplication.main(SftpSourceKafkaApplication.java:29) ~[classes!/:3.2.1]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[sftp-source-kafka-3.2.1.jar:3.2.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[sftp-source-kafka-3.2.1.jar:3.2.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[sftp-source-kafka-3.2.1.jar:3.2.1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[sftp-source-kafka-3.2.1.jar:3.2.1]


```
![image](https://user-images.githubusercontent.com/100607897/220689809-95c5f156-95f0-44d9-a1ec-f88ccc0374a5.png)

I'm using the `spring-cloud-skipper-server-2.8.2.jar` and `spring-cloud-dataflow-server-2.9.2.jar` and using Kafka or RabbitMQ as message brokers (having the same issue with both).

Thanks in advance and regards

**Comment by onobc** [comment]
Hi @bjafet123 ,
The `ref` mode is not compatible w/ the `streaming` option (the exception message is correct). 
To use `ref` mode set `app.sftp.stream=false`. 
The documentation is not clear on this and we will get that updated as part of this issue. 

Thanks

**Comment by bjafet123** [comment]
Got it, it worked

Thanks!!
