### ISSUE TITLE
Error: "Statemachine is not in state ready to do DELETE"

### ISSUE THREAD

**Issue by IvanTiba** [spring-cloud/spring-cloud-dataflow#5290]
**Description:**
Trying to deploy a stream, we receive the following error:
2023-03-22T10:24:51+0100 ERROR main o.s.s.c.SimpleExecutionStrategy:70 - Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Statemachine is not in state ready to do DELETE
2023-03-22T10:24:51+0100 WARN main o.s.c.d.s.D.exceptions:151 - Statemachine is not in state ready to do DELETE
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Statemachine is not in state ready to do DELETE
        at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
        at org.springframework.web.client.RestTemplate.delete(RestTemplate.java:555)
        at org.springframework.cloud.dataflow.rest.client.StreamTemplate.destroy(StreamTemplate.java:156)
        at org.springframework.cloud.dataflow.shell.command.StreamCommands.destroyStream(StreamCommands.java:343)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
        at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
        at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
        at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
        at org.springframework.cloud.dataflow.shell.ShellCommandLineRunner.doRun(ShellCommandLineRunner.java:90)
        at org.springframework.cloud.dataflow.shell.ShellCommandLineRunner.run(ShellCommandLineRunner.java:75)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:808)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:792)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144)
        at org.springframework.cloud.dataflow.shell.app.ShellApplication.main(ShellApplication.java:39)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

With this condition, the only way to undeploy/deploy a new stream version is to remove POD(s) manually from K8s, then re-deploy the new stream version changing its name.

**Release versions:**
2.8.2

**Steps to reproduce:**
Deploy a stream by cmd: "stream undeploy [stream name]"

**Comment by markpollack** [comment]
Not sure what is going on, but 2.8.2 was released August 2021, I would recommend upgrading as we fixed an issue that seemed related in this commit  - https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/commit/33cec5134128631a41ba80503d9a27bbd0c9cecd#diff-36baf0ad2e5ddb5337762b0b2c64b9f3bf2f81af96513863f7060358bdd23345R516

**Comment by corneil** [comment]
@IvanTiba Can you provide logs from the skipper server?

**Comment by markpollack** [comment]
@IvanTiba bump ^^

**Comment by cppwfs** [comment]
Closing due to inactivity.  If closed in error please let us know.
