### ISSUE TITLE
Spring cloud task does not show job execution list

### ISSUE THREAD

**Issue by BalajiV22** [spring-cloud/spring-cloud-dataflow#5391]
No corresponding taskExecutionId for jobExecutionId 304.  This indicates that Spring Batch application has been executed that is not a Spring Cloud Task.

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/13414643/01011ed0-59f1-4a68-9297-cfcfdb2ea1e3)

I am using spring-cloud-starter-task but it still fails to insert job execution id into TASK_TASK_BATCH.

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/13414643/ad6c9c62-d807-4f99-b938-6f91c890bad4)

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/13414643/58df2105-ff21-49d4-91fd-d0894dfecff6)

Even though by Spring job execution id 304 got executed successfully, i could not see it and it even block all by job executions. Please find this below:

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/13414643/89e792e9-9fc5-4ad6-88a3-1b6d734cdd8f)

Help me in resolving this asap. I am trying to find solution for this for many days.

**Comment by BalajiV22** [comment]
I have annotated in spring boot main class. Please find below:
![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/13414643/2741d26f-1efc-4ad2-9b9d-61826197d441)

**Comment by BalajiV22** [comment]
I am using below spring boot version:
<groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.11</version>

**Comment by BalajiV22** [comment]
Please find my exception issue log:
preparedstatementcallback; sql [insert into task_task_batch values(?, ?)]; ora-02291: integrity constraint (owner_dmf.task_exec_batch_fk) violated - parent key not found

**Comment by BalajiV22** [comment]
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT INTO TASK_TASK_BATCH VALUES(?, ?)]; ORA-02291: integrity constraint (OWNER_DMF.TASK_EXEC_BATCH_FK) violated - parent key not found
; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-02291: integrity constraint (OWNER_DMF.TASK_EXEC_BATCH_FK) violated - parent key not found

 

    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:251)
    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
    at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015)
    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1025)
    at org.springframework.cloud.task.batch.listener.support.JdbcTaskBatchDao.saveRelationship(JdbcTaskBatchDao.java:72)
    at org.springframework.cloud.task.batch.listener.TaskBatchExecutionListener.beforeJob(TaskBatchExecutionListener.java:66)
    at org.springframework.batch.core.listener.CompositeJobExecutionListener.beforeJob(CompositeJobExecutionListener.java:73)
    at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:317)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:149)
    at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
    at org.springframework.batch

**Comment by BalajiV22** [comment]
Let me check and give you in a way it can be. Thanks

**Comment by BalajiV22** [comment]
at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:113)
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:105)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:55)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:456)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:324)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:267)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:142)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:55)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:456)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:324)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:267)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.aggregator.AbstractCorrelatingMessageHandler.completeGroup(AbstractCorrelatingMessageHandler.java:928)
	at org.springframework.integration.aggregator.AbstractCorrelatingMessageHandler.processMessageForGroup(AbstractCorrelatingMessageHandler.java:574)
	at org.springframework.integration.aggregator.AbstractCorrelatingMessageHandler.handleMessageInternal(AbstractCorrelatingMessageHandler.java:541)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:55)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.router.AbstractMessageRouter.doSend(AbstractMessageRouter.java:213)
	at org.springframework.integration.router.AbstractMessageRouter.handleMessageInternal(AbstractMessageRouter.java:195)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:55)
	at org.springframework.integration.handler.ReplyProducingMessageHandlerWrapper.handleRequestMessage(ReplyProducingMessageHandlerWrapper.java:59)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:55)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:456)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:324)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:267)
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:231)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:142)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:55)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.handleMessage(SourcePollingChannelAdapter.java:196)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:474)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:460)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:412)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:347)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$5(AbstractPollingEndpoint.java:340)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; ORA-00001: unique constraint (OWNER_DMF.JOB_INST_UN) violated
; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (OWNER_DMF.JOB_INST_UN) violated

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1020)
	at org.springframework.batch.core.repository.dao.JdbcJobInstanceDao.createJobInstance(JdbcJobInstanceDao.java:120)
	at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:181)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
	at com.sun.proxy.$Proxy172.createJobExecution(Unknown Source)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:137)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:128)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
	at com.sun.proxy.$Proxy178.run(Unknown Source)
	at org.springframework.batch.integration.launch.JobLaunchingMessageHandler.launch(JobLaunchingMessageHandler.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper$HandlerMethod.invoke(MessagingMethodInvokerHelper.java:1103)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.invokeHandlerMethod(MessagingMethodInvokerHelper.java:585)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:480)
	at org.springframework.integration.handler.support.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:358)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:110)
	... 96 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (OWNER_DMF.JOB_INST_UN) violated

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3756)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3736)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1063)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
	... 140 more
Caused by: Error : 1, Position : 0, Sql = INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (:1 , :2 , :3 , :4 ), OriginalSql = INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?), Error Msg = ORA-00001: unique constraint (OWNER_DMF.JOB_INST_UN) violated

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 158 more

CLOSE
End of Modal Content

**Comment by cppwfs** [comment]
It is difficult to extrapolate what is happening based on the data provided.   But without a sample app I can only guess.   It could be that your task launched successfully however the batch job failed to run because of a duplicate key exception when  it is creating a batch job instance.   Thus there was no entry in the TASK_TASK_BATCH table.

**Comment by BalajiV22** [comment]
Do you think because of this in. batch_job_execution_context:

<img width="554" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/13414643/62caf81b-75e0-486c-9d1a-f2fee417c1f0">

**Comment by cppwfs** [comment]
If the JobInstance is not created there will be no JobExecution to view.  If the timestamp is included as a proper job parameter then the [JobInstance](https://docs.spring.io/spring-batch/docs/current/reference/html/index-single.html#jobParameters) would be unique and thus created.  In this case, the JobInstance is not being created because of a constraint violation on the JOB_INST_UN constraint.   But I can't tell very much from the information provided.

**Comment by BalajiV22** [comment]
if we triggere two jobs with same timestamp and other parameters differ for sure, will it be a issue for creating job instance.
@cppwfs - dont get harm for keep on messaging in comments, until i figure out how i can give you a code snippet. I will try to get clarified via chat as well.  I am struct up with this for more than 2 months. I need to fix this.

**Comment by BalajiV22** [comment]
@Bean(name = "ldJob")
    public Job job() {
        return jobBuilderFactory.get("ldJob")
                .incrementer(new RunIdIncrementer())
                .start(executeStep1())
                .next(executeStep2())
                .next(executeStep3())
                .next(executeStep4())
                .next(executeStep5())
                .next(executeStep6())
                .listener(JobListener)
                .build();
    }

**Comment by BalajiV22** [comment]
@ServiceActivator(inputChannel = "dInputChannel", outputChannel = "dCheckChannel")
    public Message<DL> readFile(final File dFile) {
       
        String actualStatus = <will be dynamic>;
     

        if (STATUS1.equalsIgnoreCase(actualStatus)) {
            return MessageBuilder.withPayload(DL.builder()
            
                            .fileName(fileName)
                            .filePath(dFile.getAbsolutePath())
                            .migrationStatus(STATUS1)
                            .fileType(<some type>)
                            .build())
                    .setHeader(FILE_ID, fileId)
                    .setHeader("priority", 1)
                    .setHeader(STATUS, STATUS1)
                    .build();
        }

        if (STATUS2.equalsIgnoreCase(actualStatus)) {
            return MessageBuilder.withPayload(DL.builder()
                            .fileName(fileName)
                            .filePath(dFile.getAbsolutePath())
                            .migrationStatus(STATUS2)
                            .fileType(<some type>)
                            .build())
                    .setHeader(FILE_ID, fileId)
                    .setHeader("priority", 1)
                    .setHeader(STATUS, STATUS2)
                    .build();
        }
         if (STATUS3.equalsIgnoreCase(actualStatus)) {
            return MessageBuilder.withPayload(DL.builder()
            
                            .fileName(fileName)
                            .filePath(dFile.getAbsolutePath())
                            .migrationStatus(STATUS3)
                            .fileType(<some type>)
                            .build())
                    .setHeader(FILE_ID, fileId)
                    .setHeader("priority", 1)
                    .setHeader(STATUS, STATUS3)
                    .build();
        }

        return MessageBuilder.withPayload(DL.builder()
                        .fileName(fileName)
                        .filePath(dFile.getAbsolutePath())
                         .fileType(<some type>)
                        .build())
                .setHeader(FILE_ID, fileId)
                .setHeader("priority", 1)
                .setHeader(STATUS, STATUS4)
                .build();
    }

    @Bean
    @ServiceActivator(inputChannel = "dCheckChannel")
    public HeaderValueRouter debtorHeaderValueRouter() {
        final HeaderValueRouter router = new HeaderValueRouter(STATUS);
        router.setChannelMapping(STATUS1, "1FileChannel");
        router.setChannelMapping(STATUS4, "2FileChannel");
        router.setChannelMapping(STATUS2, "3FileChannel");
        router.setChannelMapping(STATUS3, "4Channel");
        return router;
    }

config class:
@Qualifier("ldJob")
    private final Job ldJob;

    // Doing some CorrelationStrategy, ReleaseStrategy before this. Lets assume for your case, it reached here
// You will have 2FileChannel, 3FileChannel with same snippet
    @Aggregator(inputChannel = "1FileChannel", outputChannel = "1JobLaunchRequestChannel")
    public List<DL> inMigrationDebtorLedger(final List<Message<DL>> dl) {
        return dl.stream()
                .map(Message::getPayload)
                .collect(Collectors.toList());
    }

    @Transformer(inputChannel = "1JobLaunchRequestChannel", outputChannel = "jobChannel")
    public JobLaunchRequest inMigrationJob(final List<DL> dls) throws IOException {
        final DL dl = dls.stream()
                .filter(<some condition check>)
                .findAny()
                .orElse(null);
        final DL ld = dls.stream()
                .filter<some condition check>)
                .findAny()
                .orElse(null);

        JobParameters jobParameters;
        jobParameters = new JobParametersBuilder()
                .addString(D_FILE_NAME, dl.getFilePath())
                .addString(L_FILE_NAME, ld.getFilePath())
                .addString(path, debtorDetail.getDestinationPath())
                .addLong(TIMESTAMP, Instant.now().getEpochSecond())
                .toJobParameters();
        return new JobLaunchRequest(ldJob, jobParameters);
    }
    
    @Bean
    @ServiceActivator(inputChannel = "jobLaunchChannel", outputChannel = "nullChannel")
    public JobLaunchingMessageHandler launcher(final JobLauncher jobLauncher) {
        return new JobLaunchingMessageHandler(jobLauncher);
    }

**Comment by BalajiV22** [comment]
Will two spring cloud task running at same time with two different version will end up in batch serialization issue?

**Comment by cppwfs** [comment]
@BalajiV22 It depends on the transaction model you have chosen for your batch jobs.   More can be read [here](https://docs.spring.io/spring-batch/docs/current/reference/html/job.html#:~:text=Configuring%20a%20JobRepository-,Transaction%20Configuration%20for%20the%20JobRepository,-Changing%20the%20Table) on that topic.

**Comment by BalajiV22** [comment]
@cppwfs  - I hope we can close this issue. I assume since two instances of same version is running as different executions EX: 1, 2 I use 10 threads to pick files using spring integration and both the execution picked the file at same time even though i used **PropertiesPersistingMetadataStore** concept to store the logs of the file picked. Spring integration picked the file at same time and gave it to Job launcher at same time with **same timestamp**.

I added **UUID**, to be sure "**job id**" will differ for sure in running multiple instances or running multiple instance with multi threading concept. Added to this, i have used the concept of **JdbcMetadataStore** for spring integration to support multithreading concept and it does the best for me.

**Comment by cppwfs** [comment]
I'm glad you have found a solution to the issue.   If the solution has any problems, the best place to raise this question would be Spring Batch because SCDF does offer the ability to stop, restart, monitor, and track batch jobs however, it doesn't launch them.  That is up to the application itself.
