### ISSUE TITLE
Documentation Question: Connection to rabbitmq failed when deploying spring cloud data flow in the local

### ISSUE THREAD

**Issue by Jeff-Tian** [spring-cloud/spring-cloud-dataflow#5433]
I referenced the documentation: https://dataflow.spring.io/docs/installation/local/manual/ to run the spring cloud data flow in my local mac, and then deployed an `http | log` stream according to https://dataflow.spring.io/docs/stream-developer-guides/getting-started/stream/.

But during the "verifying output (local)" step (https://dataflow.spring.io/docs/stream-developer-guides/getting-started/stream/#local), I failed.

I can see there are a lot of connection error in the log:

[![enter image description here](https://i.stack.imgur.com/C7XdT.png)](https://i.stack.imgur.com/C7XdT.png)

## Summary, the steps I took:

- In terminal 1, start rabbitmq by `docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:3.7`
- Then in terminal 1, start skipper server by `java -jar spring-cloud-skipper-server-2.9.2.jar`[![enter image description here](https://i.stack.imgur.com/hFd8b.png)](https://i.stack.imgur.com/hFd8b.png)
- Then in terminal 2, start dataflow server by `java -jar spring-cloud-dataflow-server-2.10.2.jar`[![enter image description here](https://i.stack.imgur.com/izv0W.png)](https://i.stack.imgur.com/izv0W.png)
- Then in terminal 3, start dataflow shell by `java -jar spring-cloud-dataflow-shell-2.10.2.jar`[![enter image description here](https://i.stack.imgur.com/ludn3.png)](https://i.stack.imgur.com/ludn3.png)
- Open http://localhost:9393/dashboard/index.html#/streams/list/http-ingest dashboard to create stream and deploy
- Then in terminal 4, send `curl http://localhost:20100 -H "Content-type: text/plain" -d "Happy streaming"`. The request was successfully sent, but no response body.

## Additional information

I can get success response from localhost:20100 like:
[![enter image description here](https://i.stack.imgur.com/aetMm.png)](https://i.stack.imgur.com/aetMm.png)

The docker containers are as follows:
[![enter image description here][1]][1]

## Expected (Help wanted)

I can verify the output as suggested by the documentation.

[![enter image description here](https://i.stack.imgur.com/yssEZ.png)](https://i.stack.imgur.com/yssEZ.png)

## Actual

But I didn't get the log. Instead, I get the following:

```
2023-08-09 03:25:47.057  INFO [http-source,2aa0ce95298cd6b1,db9808ed2bfa4443] 1 --- [oundedElastic-1] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [localhost:5672]
2023-08-09 03:26:47.705 ERROR [http-source,2aa0ce95298cd6b1,f116c3c77334209a] 1 --- [oundedElastic-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.amqp.outbound.AmqpOutboundEndpoint@7a71c2e3]; nested exception is org.springframework.amqp.AmqpIOException: java.net.SocketTimeoutException: connect timed out, failedMessage=GenericMessage [payload=byte[15], headers={content-length=15, http_requestMethod=POST, b3=2aa0ce95298cd6b1-db9808ed2bfa4443-0, nativeHeaders={}, host=localhost:20100, http_requestUrl=http://localhost:20100/, id=1bd16f86-c76a-fb4c-4362-6df88325daf7, contentType=text/plain, user-agent=curl/7.82.0, accept=*/*, timestamp=1691551546926}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:65)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1074)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.router.AbstractMessageRouter.doSend(AbstractMessageRouter.java:213)
	at org.springframework.integration.router.AbstractMessageRouter.handleMessageInternal(AbstractMessageRouter.java:195)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	at org.springframework.integration.handler.AbstractMessageHandler.onNext(AbstractMessageHandler.java:88)
	at org.springframework.integration.handler.AbstractMessageHandler.onNext(AbstractMessageHandler.java:37)
	at org.springframework.integration.endpoint.ReactiveStreamsConsumer$SubscriberDecorator.hookOnNext(ReactiveStreamsConsumer.java:296)
	at org.springframework.integration.endpoint.ReactiveStreamsConsumer$SubscriberDecorator.hookOnNext(ReactiveStreamsConsumer.java:277)
	at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:160)
	at reactor.core.publisher.FluxRefCount$RefCountInner.onNext(FluxRefCount.java:200)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:477)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:268)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
	at org.springframework.integration.channel.FluxMessageChannel.tryEmitMessage(FluxMessageChannel.java:82)
	at org.springframework.integration.channel.FluxMessageChannel.doSend(FluxMessageChannel.java:71)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272)
	at org.springframework.integration.channel.FluxMessageChannel.lambda$subscribeTo$5(FluxMessageChannel.java:123)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$null$6(ReactorSleuth.java:324)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.amqp.AmqpIOException: java.net.SocketTimeoutException: connect timed out
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:70)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:602)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:725)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.createConnection(ConnectionFactoryUtils.java:249)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:2173)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:2146)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.send(RabbitTemplate.java:1072)
	at org.springframework.integration.amqp.outbound.AmqpOutboundEndpoint.doRabbitSend(AmqpOutboundEndpoint.java:250)
	at org.springframework.integration.amqp.outbound.AmqpOutboundEndpoint.send(AmqpOutboundEndpoint.java:231)
	at org.springframework.integration.amqp.outbound.AmqpOutboundEndpoint.handleRequestMessage(AmqpOutboundEndpoint.java:180)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:136)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
	... 43 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1223)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1173)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.connectAddresses(AbstractConnectionFactory.java:640)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.connect(AbstractConnectionFactory.java:615)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:565)
	... 53 more
```

  [1]: https://i.stack.imgur.com/pRUNv.png

**Comment by onobc** [comment]
Hi @Jeff-Tian ,
Couple of things to try: 

- bump rabbitmq to 3.12.x w/ 
    ```
    rabbit-start='docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:3.12.2-management '
    ```
- try using the maven prepackage application instead of Docker-based ones. I think the docker containers are having trouble talking to one another (ie `log-sink` can't access `rabbitmq` as they are on different docker network).

**Comment by Jeff-Tian** [comment]
Hi @onobc, thanks for the guide! Fixed by connecting to rabbitmq using host IP as docker runs it.

Could you please elaborate more on using the Maven prepackage application? Does the documentation also need to be updated? As I followed the documentation to run the rabbitmq using docker:

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/3367820/ca814caa-4068-455d-b7c9-0770f22be045)

**Comment by onobc** [comment]
Good to hear you got it working by using the IP of the rabbitmq container. Where did you specify that at?

> Could you please elaborate more on using the Maven prepackage application? 

So when you did the install and registered the pre-built application (`http` and `log`), you can choose to use either the Maven-based uber-jar apps or the docker-based container apps. The latter of course will be launched in a docker container. The former will be launched in a process. Since you chose the docker-based ones they are launched as container and could not see the rabbitmq container by name. When launched as a process this is not an issue. 

When running locally I always just use the Maven artifacts for this reason. We should update the docs a bit in this area to differentiate the two and tell when to use one or the other. 

The ref guide explains the difference between the `maven://` and `docker://` based apps.

**Comment by Jeff-Tian** [comment]
> Good to hear you got it working by using the IP of the rabbitmq container. Where did you specify that at?
> 
> >

First I get the IP address of the Mac OSX host, for example:

```
ipconfig getifaddr en0
192.168.1.10
```

Then I specify it during deploying the stream step:

```
app.http.spring.rabbitmq.host=192.168.1.10
app.log.spring.rabbitmq.host=192.168.1.10
```

Thanks for the explanation. Let me elaborate more on my loss during reading docs:

I'm new to this and just followed the documents (https://dataflow.spring.io/docs/installation/local/manual/) to install manually and then followed this doc (https://dataflow.spring.io/docs/stream-developer-guides/getting-started/stream/) to deploy streams. But found out that when I type `http | log`, I am lacking the applications (`http` and `log`). 

So I think there were some gaps between the above two. 

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/3367820/c9faf656-7811-4e37-8cd5-e79355330a0d)

Although it mentioned there were prebuilt applications, I can't find the exact page. Instead, I found https://dataflow.spring.io/docs/applications/pre-packaged/#pre-packaged-applications which is "pre-packaged" not "prebuilt".

In this page I just copied the 1st URL, so lead to the issues. 

![image](https://github.com/spring-cloud/spring-cloud-dataflow/assets/3367820/f2c920d9-e133-49cc-8673-1e2b18c1315b)

Now I know the differences, thank you!

**Comment by onobc** [comment]
You are more than welcome @Jeff-Tian . 

We do have some doc issues opened to improve this getting started experience and reduce the amount of jumping back/forth one has to do to get started. 

Thanks for your input and glad you got going with it!
