### ISSUE TITLE
'NullPointerException' error in SCDF UI when accessing 'Schedules' tab.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#5454]

**Comment by onobc** [comment]
>   2023-08-29T12:47:09.11-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.113 DEBUG 19 --- [nio-8080-exec-8] o.apache.catalina.valves.RemoteIpValve   : Incoming request /tasks/schedules with originalRemoteAddr [10.253.5.20], originalRemoteHost=[10.253.5.20], originalSecure=[false], originalScheme=[http], originalServerName=[dataflow-9e242365-3a46-4ce2-81fa-a740a745a6bd.app.cde2.dal.pcf.syfbank.com], originalServerPort=[80] will be seen as newRemoteAddr=[10.160.123.100], newRemoteHost=[10.160.123.100], newSecure=[true], newScheme=[https], newServerName=[dataflow-9e242365-3a46-4ce2-81fa-a740a745a6bd.app.cde2.dal.pcf.syfbank.com], newServerPort=[443]
   2023-08-29T12:47:09.11-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.113 DEBUG 19 --- [nio-8080-exec-8] o.a.c.authenticator.AuthenticatorBase    : Security checking request GET /tasks/schedules
   2023-08-29T12:47:09.11-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.113 DEBUG 19 --- [nio-8080-exec-8] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
   2023-08-29T12:47:09.11-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.113 DEBUG 19 --- [nio-8080-exec-8] o.a.c.authenticator.AuthenticatorBase    : Not subject to any constraint
   2023-08-29T12:47:09.11-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.114 DEBUG 19 --- [nio-8080-exec-8] o.apache.catalina.core.StandardWrapper   :   Returning non-STM instance
   2023-08-29T12:47:09.11-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.114 DEBUG 19 --- [nio-8080-exec-8] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
   2023-08-29T12:47:09.11-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.115 DEBUG 19 --- [nio-8080-exec-8] org.apache.tomcat.util.http.Parameters   : Decoding query null UTF-8
   2023-08-29T12:47:09.11-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.115 DEBUG 19 --- [nio-8080-exec-8] org.apache.tomcat.util.http.Parameters   : Start processing with input [platform=default]
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.129 ERROR 19 --- [nio-8080-exec-8] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.cloud.dataflow.server.service.impl.DefaultSchedulerService.listForPlatform(DefaultSchedulerService.java:380)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController.list(TaskSchedulerController.java:88)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at java.lang.reflect.Method.invoke(Method.java:498)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:149)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
   2023-08-29T12:47:09.12-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:155)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:155)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:114)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter.doFilterInternal(DefaultLogoutPageGeneratingFilter.java:52)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:216)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:160)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:79)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2023-08-29T12:47:09.13-0400 [APP/PROC/WEB/0] OUT at java.lang.Thread.run(Thread.java:750)
   2023-08-29T12:47:09.14-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.142 DEBUG 19 --- [nio-8080-exec-8] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@7f32fef:org.apache.tomcat.util.net.NioChannel@33f59d98:java.nio.channels.SocketChannel[connected local=521a4ac1-f9fc-4e88-5121-712a/10.253.5.20:8080 remote=/10.253.5.20:59742]], Status in: [OPEN_READ], State out: [CLOSED]
   2023-08-29T12:47:09.14-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.142 DEBUG 19 --- [nio-8080-exec-8] o.a.coyote.http11.Http11NioProtocol      : Pushed Processor [org.apache.coyote.http11.Http11Processor@309f81b]
   2023-08-29T12:47:09.14-0400 [APP/PROC/WEB/0] OUT 2023-08-29 16:47:09.142 DEBUG 19 --- [nio-8080-exec-8] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-8080-exec-8] latch=15

**Comment by cppwfs** [comment]
In this case, it looks like the problem is that it could not find the launcher.   But the stack trace doesn't quite line up.  Curious as to what OSS version they are using.

**Comment by cppwfs** [comment]
In this case the user is on SCDF 2.7.2 that is no longer supported.   User is investigating the reason they have not upgraded.
