### ISSUE TITLE
cloud task prefix resets when using another datasource 

### ISSUE THREAD

**Issue by DeividasJakovlevas42** [spring-cloud/spring-cloud-dataflow#5463]
**Description:**
I'm trying to run a batch job using batch 5/boot 3 in SCDF 2.11.0-RC1. Currently the BOOT3_TASK_ prefix works if I run it locally and set it in application.properties with 
```
spring.batch.jdbc.table-prefix=BOOT3_BATCH_
spring.cloud.task.tablePrefix=BOOT3_TASK_
```
It also works if I execute it in SCDF but only if I don't create another datasource bean like this
```
@Bean(name = "scopedTarget.appDataSource")
    @ConfigurationProperties(prefix = "app.datasource")
    public DataSource appDataSource() {
        return DataSourceBuilder.create().build();
    }
```

Currently I need 2 datasources. One for spring batch/task tables, which is loaded automatically from SCDF and one for the task functionality itself. I can only create datasource bean for spring.datasource. If I create scopedTarget.appDataSource (or appDataSource but then I need to use DefaultTaskConfigurer) bean, the prefix resets to TASK_  and I get the below error

org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'
 at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-6.0.11.jar!/:6.0.11]
 at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357) ~[spring-context-6.0.11.jar!/:6.0.11]
 at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
 at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156) ~[spring-context-6.0.11.jar!/:6.0.11]
 at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124) ~[spring-context-6.0.11.jar!/:6.0.11]
 at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:958) ~[spring-context-6.0.11.jar!/:6.0.11]
 at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:611) ~[spring-context-6.0.11.jar!/:6.0.11]
 at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-3.1.3.jar!/:3.1.3]
 at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[spring-boot-3.1.3.jar!/:3.1.3]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.1.3.jar!/:3.1.3]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.3.jar!/:3.1.3]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.3.jar!/:3.1.3]
 at net.bitegroup.testjob.Main.main(Main.java:16) ~[classes!/:na]
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
 at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
 at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[testjob.jar:na]
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[testjob.jar:na]
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[testjob.jar:na]
 at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[testjob.jar:na]
Caused by: java.lang.IllegalArgumentException: Invalid TaskExecution, ID 35 not found
 at org.springframework.util.Assert.notNull(Assert.java:204) ~[spring-core-6.0.11.jar!/:6.0.11]
 at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:275) ~[spring-cloud-task-core-3.0.3.jar!/:3.0.3]
 at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:411) ~[spring-cloud-task-core-3.0.3.jar!/:3.0.3]
 at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[spring-context-6.0.11.jar!/:6.0.11]
```
I know it's reset because I can see this when I changed logging level to debug:
`2023-09-13T06:35:41.295Z DEBUG 7 --- [           main] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [SELECT TASK_EXECUTION_ID, START_TIME, END_TIME, TASK_NAME, EXIT_CODE, EXIT_MESSAGE, ERROR_MESSAGE, LAST_UPDATED, EXTERNAL_EXECUTION_ID, PARENT_EXECUTION_ID from TASK_EXECUTION where TASK_EXECUTION_ID = ?]`

**Comment by DeividasJakovlevas42** [comment]
Sorry. Only had to do this:
```
@Component
public class CustomTaskConfigurer extends DefaultTaskConfigurer {
    @Autowired
    public CustomTaskConfigurer(@Qualifier("dataSource") DataSource dataSource,TaskProperties taskProperties)  {
        super(dataSource,taskProperties.getTablePrefix(),null);
    }
}
```

**Comment by cppwfs** [comment]
This issue looks resolved.   Please comment if it is closed in error.
