### ISSUE TITLE
Spring Cloud Data Flow Shell: `Exception thrown from ApplicationListener handling ContextClosedEvent` after using `--logging.file.name="/scdfshell.log"`

### ISSUE THREAD

**Issue by r-heimann** [spring-cloud/spring-cloud-dataflow#5550]
**Description:**
The following error message appears after using `--logging.file.name="/scdfshell.log"` for `Spring Cloud Data Flow Shell`:

<details> <summary>Log</summary>

```
INFO 196 --- [main] o.s.c.dataflow.shell.ShellApplication    : Starting ShellApplication using Java 17.0.9 on <DNS> with PID 196 (/spring-cloud-dataflow-shell.jar started by ? in /)
INFO 196 --- [main] o.s.c.dataflow.shell.ShellApplication    : No active profile set, falling back to 1 default profile: "default"
WARN 196 --- [main] org.jline                                : Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
INFO 196 --- [main] o.s.c.dataflow.shell.ShellApplication    : Started ShellApplication in 3.61 seconds (JVM running for 4.328)
INFO 196 --- [main] .c.InitializeConnectionApplicationRunner : Successfully targeted https://localhost:<PORT>
WARN 196 --- [SpringApplicationShutdownHook] s.c.a.AnnotationConfigApplicationContext : Exception thrown from ApplicationListener handling ContextClosedEvent

java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
HandlerMethod details: 
Bean [org.springframework.shell.boot.LineReaderAutoConfiguration]
Method [public void org.springframework.shell.boot.LineReaderAutoConfiguration.onContextClosedEvent(org.springframework.context.event.ContextClosedEvent) throws java.io.IOException]
Resolved arguments: 
[0] [type=org.springframework.context.event.ContextClosedEvent] [value=org.springframework.context.event.ContextClosedEvent[source=org.springframework.context.annotation.AnnotationConfigApplicationContext@351d0846, started on <DATE>]]

	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:361) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1061) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1024) ~[spring-context-5.3.30.jar!/:5.3.30]
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145) ~[spring-boot-2.7.16.jar!/:2.7.16]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114) ~[spring-boot-2.7.16.jar!/:2.7.16]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.nio.file.AccessDeniedException: /spring-cloud-dataflow-shell.log
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[na:na]
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[na:na]
	at java.base/java.nio.file.Files.newOutputStream(Files.java:228) ~[na:na]
	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3008) ~[na:na]
	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3056) ~[na:na]
	at org.jline.reader.impl.history.DefaultHistory.internalWrite(DefaultHistory.java:225) ~[jline-3.23.0.jar!/:na]
	at org.jline.reader.impl.history.DefaultHistory.save(DefaultHistory.java:214) ~[jline-3.23.0.jar!/:na]
	at org.springframework.shell.boot.LineReaderAutoConfiguration.onContextClosedEvent(LineReaderAutoConfiguration.java:81) ~[spring-shell-autoconfigure-2.1.12.jar!/:2.1.12]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.30.jar!/:5.3.30]
	... 13 common frames omitted
```

</details>

**Release versions:**
spring-cloud-dataflow-server-2.11.1.jar
spring-cloud-dataflow-shell-2.11.1.jar
spring-cloud-skipper-server-2.11.1.jar

**Custom apps:**
\-

**Steps to reproduce:**
1. Start Spring Cloud Skipper
2. Start Spring Cloud Data Flow
3. Start Spring Cloud Data Flow Shell with a config file, example:

```
/bin/java -jar /spring-cloud-dataflow-shell.jar \
          --dataflow.uri=https://localhost:<PORT> \
          --spring.shell.commandFile="/scdf.shell" \
          --logging.file.name="/scdfshell.log"
```

**Screenshots:**
\-

**Additional context:**
\-

**Comment by cppwfs** [comment]
Hello,
I tested with the following settings --dataflow.uri=http://localhost:9393  --logging.file.name="/scdfshell.log"  spring.shell.commandFile="./auskap.shell" but was unable to reproduce the problem.

Just to clarify if you add the --logging.file.name is when the error occurs?

**Comment by r-heimann** [comment]
> Just to clarify if you add the --logging.file.name is when the error occurs?

Question: Did you do this as root, or as another user which doesn't have access to `/`?

Is the shell trying to create a log file in the location the user is after completing the script? I didn't see this behaviour in any documentation.

**Comment by r-heimann** [comment]
Yeah, i just checked it again and it seems like `Spring Cloud Data Flow Shell` creates a log file in the current directory of the users that executed the JAR file. I will close this issue and create a new one to suggest a parameter that you can use to specify the location of the log file.
