### ISSUE TITLE
Unable to view log from task executions in Spring Cloud Dataflow UI

### ISSUE THREAD

**Issue by knkhats** [spring-cloud/spring-cloud-dataflow#5558]
In v2.11.1, navigate to a task execution and click on "view log", the UI shows the spinner and does not show the logs
Browser inspect shows the following errors

_Mixed Content: The page at 'https://**' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://**'. This request has been blocked; the content must be served over HTTPS._

_ERROR TypeError: d is not iterable
    at catchError (main.145f644157e8c472.js:1:279671)
    at main.145f644157e8c472.js:1:185042_

This was working fine in v2.10

Can you please advice if there is a workaround for this? Changing browser security is not an option.

**Comment by knkhats** [comment]
Thank you for the response. I have the following 2 comments to add
1. The same setup and the same proxy settings work perfectly with v2.10. Is this a new change in v2.11? 
2. The problem does not manifest on the Task->View Log. However, Task Executions->View Log show this problem. Screenshots attached for reference
![works](https://github.com/spring-cloud/spring-cloud-dataflow/assets/151720800/9a98bba1-d93d-4b6b-b0c7-09c31bcc3fb5)
![does not work](https://github.com/spring-cloud/spring-cloud-dataflow/assets/151720800/7df41fbd-0147-4f68-afd0-27dfba06d31d)

**Comment by knkhats** [comment]
This is configured on CentOS8 on Kubernetes 1.25.8. Please note that this issue not observed in v2.10 on the same setup.

Thank you,
K

**Comment by corneil** [comment]
Can you use the browser developer tools to view the JSON response when viewing the task. This response should contain something like:
```json
"_links": {
        "tasks/logs": {
            "href": 
        }
}
```
Can you verify that the url is the same as the application?

**Comment by knkhats** [comment]
Hello @corneil ,
 The application url has https://. The url in  "_links": { "tasks/logs": { "href": has http://
Everything else in the url matches.
