### ISSUE TITLE
Cannot launch custom task due to SQL error: Could not increment ID for BOOT3_TASK_SEQ sequence table

### ISSUE THREAD

**Issue by drse** [spring-cloud/spring-cloud-dataflow#5623]
**Description:**

- SCDF installed into Kubernetes via Helm (https://bitnami.com/stack/spring-cloud-dataflow/helm), chart version 26.0.0
- Using default values for helm chart: deployed with mariadb and rabbitmq
- SCDF version 2.11.1

I created a sample task using the spring initializer. The task itself does nothing but print "Hello World" to the console. The following dependencies on the task app are used:

```gradle
implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
implementation 'org.springframework.cloud:spring-cloud-starter-task'
runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
testImplementation 'org.springframework.boot:spring-boot-starter-test'
```

Spring boot version is `3.2.1`

I'm able to register the task app via the shell, however, when running the task, an SQL error is encountered. It seems that this happens before the jar is actually executed:

```
dataflow:>app register sample-task --type task --bootVersion 3 --force --uri https://XXX/maven/sample-task/0.0.2/sample-task-0.0.2.jar
  Successfully registered application 'task:sample-task (boot 3)
dataflow:>task create sample-task --definition "sample-task"
  Created new task 'sample-task'
dataflow:>task launch sample-task
  Could not increment ID for BOOT3_TASK_SEQ sequence table; nested exception is java.sql.SQLSyntaxErrorException: (conn=20) Unknown column 'ID' in 'field list'
  Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
dataflow:>stacktrace
  org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not increment ID for BOOT3_TASK_SEQ sequence table; nested exception is java.sql.SQLSyntaxErrorException: (conn=20) Unknown column 'ID' in 'field list'
    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65)
    at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:825)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:783)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:443)
    at org.springframework.cloud.dataflow.rest.client.TaskTemplate.launch(TaskTemplate.java:205)
    at org.springframework.cloud.dataflow.shell.command.TaskCommands.launch(TaskCommands.java:234)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
    at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
    at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:160)
    at org.springframework.shell.Shell.evaluate(Shell.java:208)
    at org.springframework.shell.Shell.run(Shell.java:140)
    at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
    at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759)
    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
    at org.springframework.cloud.dataflow.shell.ShellApplication.main(ShellApplication.java:35)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

Looking at the schema, it appears that the `BOOT3_TASK_SEQ` table does not have an `ID` field where `TASK_SEQ` does:

```
MariaDB [dataflow]> describe BOOT3_TASK_SEQ;
+-----------------------+---------------------+------+-----+---------+-------+
| Field                 | Type                | Null | Key | Default | Extra |
+-----------------------+---------------------+------+-----+---------+-------+
| next_not_cached_value | bigint(21)          | NO   |     | NULL    |       |
| minimum_value         | bigint(21)          | NO   |     | NULL    |       |
| maximum_value         | bigint(21)          | NO   |     | NULL    |       |
| start_value           | bigint(21)          | NO   |     | NULL    |       |
| increment             | bigint(21)          | NO   |     | NULL    |       |
| cache_size            | bigint(21) unsigned | NO   |     | NULL    |       |
| cycle_option          | tinyint(1) unsigned | NO   |     | NULL    |       |
| cycle_count           | bigint(21)          | NO   |     | NULL    |       |
+-----------------------+---------------------+------+-----+---------+-------+
8 rows in set (0.001 sec)

MariaDB [dataflow]> describe TASK_SEQ;
+------------+------------+------+-----+---------+-------+
| Field      | Type       | Null | Key | Default | Extra |
+------------+------------+------+-----+---------+-------+
| ID         | bigint(20) | NO   |     | NULL    |       |
| UNIQUE_KEY | char(1)    | NO   | PRI | NULL    |       |
+------------+------------+------+-----+---------+-------+
2 rows in set (0.001 sec)
```

Note that registering this app as a `boot2` task does not raise this issue.

**Release versions:**
```json
{
  "featureInfo": {
    "analyticsEnabled": true,
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulesEnabled": true,
    "monitoringDashboardType": "NONE"
  },
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.11.1"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.11.1"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.4.1"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.11.1",
      "url": "https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.11.1/spring-cloud-dataflow-shell-2.11.1.jar"
    }
  },
  "securityInfo": {
    "authenticationEnabled": false,
    "authenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.11.1",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.11.1",
      "javaVersion": "17.0.9",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "kubernetes"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.7.16",
      "springVersion": "5.3.30"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "unknown",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "unknown",
        "javaVersion": "17.0.9",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "default",
          "master-url": "https://10.43.0.1:443/"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.7.16",
        "springVersion": "5.3.30"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "refreshInterval": 15,
    "dashboardType": "NONE",
    "source": "default-scdf-source"
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/about"
    }
  }
}
```

**Comment by corneil** [comment]
It seems the Helm chart configures the JDBC connection to support both MySQL 5.7 and MariaDB prior to 10.6
If you edit the configmaps for dataflow and skipper and remove `?useMysqlMetadata=true` then the system will use the sequence instead of assuming it is a sequence table.

**Comment by corneil** [comment]
I logged a [ticket](https://github.com/bitnami/charts/issues/21722)  with the Bitnami team
