### ISSUE TITLE
Spring Cloud Task execution fails when running via SpringCloud dataflow server 2.11.2 with Invalid TaskExecution ID, but works fine with 2.10

### ISSUE THREAD

**Issue by jaswka** [spring-cloud/spring-cloud-dataflow#5651]
**Description:**
I am writing a spring cloud task(Spring Boot 3, Java 17) that reads a flat file and inserts it into a database. So this is a multiple databases scenario. Running via SpringCloud dataflow server 2.11.2, it fails with " Invalid TaskExecution, ID ".
 I have tried debugging it and I noticed that tablePrefix is "TASK_" always and not "BOOT3_TASK_"

**Release versions:**
SpringCloud dataflow server 2.11.2, Spring Boot 3.2.2, Spring Cloud Version 2023.0.0 

**Custom apps:**
**Exception**
`Caused by: java.lang.IllegalArgumentException: Invalid TaskExecution, ID 50 not found
	at org.springframework.util.Assert.notNull(Assert.java:172) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:184) ~[!/:0.0.1-SNAPSHOT]
	at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:312) ~[!/:0.0.1-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:284) ~[spring-context-6.1.3.jar!/:6.1.3]
	... 19 common frames omitted`

**Datasource Configuration**
`spring:
  datasource-scdf:
    url: "jdbc:postgresql://localhost:5432/dataflow?schema=public"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/dataflow?schema=public"

  datasource-app:
    url: "jdbc:mysql://localhost:3306/test_task"
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver`

**Datasource configuration Class**
 `

@Configuration
public class CustomCloudTaskConfiguration {
    @Bean
    @ConfigurationProperties("spring.datasource-scdf")
    public DataSourceProperties customOperationsDataSourceProperties() {
        return new DataSourceProperties();
    }

    @Bean(name = "customDatasource")
    @ConfigurationProperties("spring.datasource-scdf.configuration")
    public DataSource customOperationsDataSource() {
        return customOperationsDataSourceProperties()
                .initializeDataSourceBuilder()
                .type( HikariDataSource.class )
                .build();
    }
    @Primary
    @Bean
    public DataSourceTransactionManager taskOperationsTransactionManager() {
        return new DataSourceTransactionManager( customOperationsDataSource() );
    }

}`

**CustomTaskConfigurer**
`
@Component
public class CustomTaskConfigurer extends DefaultTaskConfigurer {

    public CustomTaskConfigurer(@Qualifier("customDatasource") DataSource dataSource) {
        super(dataSource);
    }

}`

**Comment by jaswka** [comment]
I was able to resolve the issue by inserting TaskProperties to CustomTaskConfigurer 
`@Component
public class CustomTaskConfigurer extends DefaultTaskConfigurer {
    @Autowired
    public CustomTaskConfigurer(@Qualifier("springCloudDataSource") DataSource dataSource, TaskProperties taskProperties, ApplicationContext context) {
        super(dataSource, taskProperties.getTablePrefix(),context);
    }

}`

I also ensured the database configuration properties/name defined in the task matches with what SCDF server is passing on execution
