### ISSUE TITLE
Custom javaHomePath for Spring Boot 2 tasks ignored in spring-cloud-dataflow-server 2.11.2-jdk17 container

### ISSUE THREAD

**Issue by kherpel** [spring-cloud/spring-cloud-dataflow#5734]
**Description:**

We are using the 2.11.2-jdk17 containers for `spring-cloud-dataflow-server` and `spring-cloud-skipper-server` using local deployment with docker-compose. The JRE version 17.0.7 used in these containers has an incorrect timezone setting for Egypt. So we are now trying to switch to a custom JDK to run the streams and batch task. 

Skipper works fine with the custom JDK and `spring.cloud.deployer.local.javaHomePath.2=/usr/lib/jvm/temurin-17-jdk-amd64` and `spring.cloud.deployer.local.javaHomePath.3=/usr/lib/jvm/temurin-17-jdk-amd64` settings in docker-compose-`dataflow.yml`. The streams are deployed with the Temurin 17 JDK.

However, Spring Boot 2 batch tasks are getting deployed with the standard JDK `/layers/paketo-buildpacks_bellsoft-liberica/jre/bin/java`.

I've configured the custom `javaHomePath` for Spring Boot 2 and 3 in `docker-compose-dataflow.yml`:

```
      - spring.cloud.deployer.local.javaHomePath.2=/usr/lib/jvm/temurin-17-jdk-amd64
      - spring.cloud.deployer.local.javaHomePath.3=/usr/lib/jvm/temurin-17-jdk-amd64
      - spring.cloud.dataflow.defaults.boot3.local.javaHomePath=/usr/lib/jvm/temurin-17-jdk-amd64
      - spring.cloud.dataflow.defaults.boot2.local.javaHomePath=/usr/lib/jvm/temurin-17-jdk-amd64
```

From the dataflow logs below I can see that the task application is correctly identified as Spring Boot 2 (`app.changenotifier-task.spring.cloud.deployer.bootVersion=2`). The javaHomePath for Spring Boot 2 is then added to the LocalDeployerProperties with `/usr/lib/jvm/temurin-17-jdk-amd64`. But the `LocalDeployerProperties.deduceJavaCommand()` then somehow tries to use the javaHomePath for version 3 from the `javaHomePath` map in `LocalDeployerProperties`. As DefaultTaskExecutionService was only adding the custom javaHomePath for version 2 to this map it always falls back to `/layers/paketo-buildpacks_bellsoft-liberica/jre/bin/java`. 

Note: I've moved the `/layers/paketo-buildpacks_bellsoft-liberica/jre` to `/layers/paketo-buildpacks_bellsoft-liberica/jre-original` in my custom Dockerfile and then removed this folder to trigger the error.

See additional context for `docker-compose-dataflow.yml` and the Dockerfiles for Dataflow and Skipper.

Dataflow logs:

```
2024-03-11 10:30:37.001  INFO 1 --- [nio-9010-exec-2] .s.c.d.s.s.i.DefaultTaskExecutionService : adding:app.changenotifier-task.spring.cloud.task.initialize-enabled=false
2024-03-11 10:30:37.004  INFO 1 --- [nio-9010-exec-2] .s.c.d.s.s.i.DefaultTaskExecutionService : adding:app.changenotifier-task.spring.batch.jdbc.table-prefix=BATCH_
2024-03-11 10:30:37.004  INFO 1 --- [nio-9010-exec-2] .s.c.d.s.s.i.DefaultTaskExecutionService : adding:app.changenotifier-task.spring.cloud.task.tablePrefix=TASK_
2024-03-11 10:30:37.004  INFO 1 --- [nio-9010-exec-2] .s.c.d.s.s.i.DefaultTaskExecutionService : adding:app.changenotifier-task.spring.cloud.task.schemaTarget=boot2
2024-03-11 10:30:37.004  INFO 1 --- [nio-9010-exec-2] .s.c.d.s.s.i.DefaultTaskExecutionService : adding:app.changenotifier-task.spring.cloud.deployer.bootVersion=2
2024-03-11 10:30:37.006  INFO 1 --- [nio-9010-exec-2] .s.c.d.s.s.i.DefaultTaskExecutionService : adding:spring.cloud.deployer.local.javaHomePath.2=/usr/lib/jvm/temurin-17-jdk-amd64
2024-03-11 10:30:38.230  INFO 1 --- [nio-9010-exec-2] o.s.c.d.spi.local.LocalTaskLauncher      : Preparing to run an application from com.airxelerate.integration:changenotifier-task:jar:1.88.0-SNAPSHOT.151. This may take some time if the artifact must be downloaded from a remote host.
2024-03-11 10:30:38.261 ERROR 1 --- [nio-9010-exec-2] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.IllegalArgumentException: Java executable'/layers/paketo-buildpacks_bellsoft-liberica/jre-original/bin/java'discovered via 'java.home' system property '{2=/usr/lib/jvm/temurin-17-jdk-amd64, 3=/layers/paketo-buildpacks_bellsoft-liberica/jre-original}' does not exist.
        at org.springframework.util.Assert.isTrue(Assert.java:139)
        at org.springframework.cloud.deployer.spi.local.LocalDeployerProperties.deduceJavaCommand(LocalDeployerProperties.java:560)
        at org.springframework.cloud.deployer.spi.local.LocalDeployerProperties.getJavaCommand(LocalDeployerProperties.java:424)
        at org.springframework.cloud.deployer.spi.local.JavaCommandBuilder.buildExecutionCommand(JavaCommandBuilder.java:101)
        at org.springframework.cloud.deployer.spi.local.AbstractLocalDeployerSupport.buildProcessBuilder(AbstractLocalDeployerSupport.java:174)
        at org.springframework.cloud.deployer.spi.local.LocalTaskLauncher.launch(LocalTaskLauncher.java:110)
        at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.executeTask(DefaultTaskExecutionService.java:513)
        at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$FastClassBySpringCGLIB$$422cda43.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
```

**Release versions:**

Information from Dataflow GUI:

```json
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.11.2"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.11.2"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.4.2"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.11.2",
      "url": "https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.11.2/spring-cloud-dataflow-shell-2.11.2.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": false,
    "monitoringDashboardType": "NONE"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.11.2",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.11.2",
      "javaVersion": "17.0.10",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "local"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.7.18",
      "springVersion": "5.3.31"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "unknown",
        "deployerName": "LocalTaskLauncher",
        "deployerSpiVersion": "unknown",
        "javaVersion": "17.0.10",
        "platformApiVersion": "Linux 6.1.38-59.109.amzn2023.x86_64",
        "platformClientVersion": "6.1.38-59.109.amzn2023.x86_64",
        "platformHostVersion": "6.1.38-59.109.amzn2023.x86_64",
        "platformSpecificInfo": {},
        "platformType": "Local",
        "springBootVersion": "2.7.18",
        "springVersion": "5.3.31"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "git": {
    "commit": "86b53e0"
  }
}
```

**Steps to reproduce:**

* Deploy Spring Dataflow using docker-compose-dataflow.yml
* Configure custom javaHomePath for Spring Boot 2 and Spring Boot 3 tasks
* Run a Spring Boot 2 task
* Task will run with standard JRE from original container instead of custom JRE/JDK defined in javaHomePath

**Additional context:**

* [docker-compose-dataflow.yml.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/14557793/docker-compose-dataflow.yml.txt)
* [Dockerfile-dataflow.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/14557806/Dockerfile-dataflow.txt)
* [Dockerfile-skipper.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/14557816/Dockerfile-skipper.txt)

Kind regards,
Kristian

**Comment by corneil** [comment]
Can you provide more information as to how the timezone is incorrect in 17.0.7?

**Comment by corneil** [comment]
Instead of trying to patch the container with Dockerfile you could create a new container using Paketo [pack](https://buildpacks.io/docs/for-platform-operators/how-to/integrate-ci/pack/) using the following options:
```shell
pack build --builder gcr.io/paketo-buildpacks/builder:base \
        --path "<path to scdf jar>" \
        --buildpack paketo-buildpacks/azul-zulu --buildpack paketo-buildpacks/java \
        --trust-builder --verbose --env BP_JVM_VERSION=17 "<repo>/<app-name>:<tag>"
```
The latest azul-jdk is 17.0.10

**Comment by kherpel** [comment]
Hi Corneil,

here is our test case for this issue:

```java
package com.airxelerate.integration.touroperatorexport.processes.util;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.time.ZoneId;
import java.time.ZonedDateTime;

import org.junit.jupiter.api.Test;

class TimezoneTest {

	@Test
	void testEgypt() {

		ZonedDateTime utcTime = ZonedDateTime.of(2024, 5, 14, 14, 45, 0, 0, ZoneId.of("UTC"));
		ZonedDateTime egyptDateTime = utcTime.withZoneSameInstant(ZoneId.of("Africa/Cairo"));

		assertEquals(17, egyptDateTime.toLocalTime().getHour());
		assertEquals(45, egyptDateTime.toLocalTime().getMinute());

	}

}
```

OpenJDK 17.0.7+7 returns 16 instead of 17 for `egyptDateTime.toLocalTime().getHour()` (this is the JRE from the Spring Dataflow 2.11.2 containers). Temurin JDK 17.0.10+7 returns 17. 

Egypt was doing some back-and-forth with DST and Ramadan over the last years so I think the tz database could not keep up with the changes.

As a workaround we are now replacing the JRE through Dockerfile build. But we will have a look into setting up a build pipeline for the pack builds.

Kind regards,
Kristian

**Comment by corneil** [comment]
@kherpel Did the buildpack process work as expected?

**Comment by kherpel** [comment]
Hi @corneil, 

we are using the override via Dockerfile for now as this works fine for our local setup:

```
FROM springcloud/spring-cloud-dataflow-server:2.11.2-jdk17

USER root

# Install Temurin JDK 17 as default Java version
RUN apt-get update
RUN mkdir -p /usr/share/man/man1
RUN apt-get install -y wget apt-transport-https gpg man mc less
RUN wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
RUN echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
RUN apt-get update
RUN apt-get install -y temurin-17-jdk 

RUN cp -R /layers/paketo-buildpacks_bellsoft-liberica/jre/env.launch /usr/lib/jvm/temurin-17-jdk-amd64/

RUN rm -rf /layers/paketo-buildpacks_bellsoft-liberica/jre/*

RUN cp -R /usr/lib/jvm/temurin-17-jdk-amd64/* /layers/paketo-buildpacks_bellsoft-liberica/jre/

ENV JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64

USER cnb
```

Kind regards,
Kristian
