### ISSUE TITLE
Error while starting a batch task in spring data flow

### ISSUE THREAD

**Issue by shobhakamath** [spring-cloud/spring-cloud-dataflow#5872]
**Description:**
Unable to start a task

**Release versions:**
spring-data-flow-2.11.3

 

**Steps to reproduce:**
I have a batch application in springboot3 java 17.
I created a docker image of it .
I also have spring-data-flow-2.11.3 which I wget from the repo. I ran the spring-data-flow in docker.
When I register the application image and try to start the task, I get the following error.

dataflow-server  |      at org.springframework.cloud.deployer.spi.local.LocalTaskLauncher.launch(LocalTaskLauncher.java:125)
dataflow-server  |      at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService.executeTask(DefaultTaskExecutionService.java:513)
dataflow-server  |      at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$FastClassBySpringCGLIB$$422cda43.invoke(<generated>)
dataflow-server  |      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
dataflow-server  |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
dataflow-server  |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
dataflow-server  |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
dataflow-server  |      at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
dataflow-server  |      at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
dataflow-server  |      at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
dataflow-server  |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
dataflow-server  |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
dataflow-server  |      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
dataflow-server  |      at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskExecutionService$$EnhancerBySpringCGLIB$$f608a26a.executeTask(<generated>)
dataflow-server  |      at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.launchBoot3(TaskExecutionController.java:251)
dataflow-server  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dataflow-server  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
dataflow-server  |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dataflow-server  |      at java.base/java.lang.reflect.Method.invoke(Method.java:569)
dataflow-server  |      at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
dataflow-server  |      at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
dataflow-server  |      at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
dataflow-server  |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:903)
dataflow-server  |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:809)
dataflow-server  |      at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
dataflow-server  |      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
dataflow-server  |      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
dataflow-server  |      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
dataflow-server  |      at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
dataflow-server  |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
dataflow-server  |      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
dataflow-server  |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:200)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server  |      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:169)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server  |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:169)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server  |      at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
dataflow-server  |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:169)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server  |      at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
dataflow-server  |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:169)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server  |      at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
dataflow-server  |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:169)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server  |      at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
dataflow-server  |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:169)
dataflow-server  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
dataflow-server  |      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
dataflow-server  |      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
dataflow-server  |      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
dataflow-server  |      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
dataflow-server  |      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
dataflow-server  |      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
dataflow-server  |      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
dataflow-server  |      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
dataflow-server  |      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
dataflow-server  |      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
dataflow-server  |      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1786)
dataflow-server  |      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
dataflow-server  |      at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
dataflow-server  |      at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
dataflow-server  |      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
dataflow-server  |      at java.base/java.lang.Thread.run(Thread.java:840)
dataflow-server  | Caused by: java.io.IOException: Cannot run program "docker" (in directory "/tmp/5496560241204442/task-a8ffd859-77ef-47a6-b2c4-11b1d47660a5"): error=2, No such file or directory
dataflow-server  |      at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
dataflow-server  |      at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
dataflow-server  |      at org.springframework.cloud.deployer.spi.local.LocalTaskLauncher$TaskInstance.start(LocalTaskLauncher.java:354)
dataflow-server  |      at org.springframework.cloud.deployer.spi.local.LocalTaskLauncher$TaskInstance.access$200(LocalTaskLauncher.java:258)
dataflow-server  |      at org.springframework.cloud.deployer.spi.local.LocalTaskLauncher.launch(LocalTaskLauncher.java:119)
dataflow-server  |      ... 71 common frames omitted
dataflow-server  | Caused by: java.io.IOException: error=2, No such file or directory
dataflow-server  |      at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
dataflow-server  |      at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
dataflow-server  |      at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
dataflow-server  |      at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
dataflow-server  |      ... 75 common frames omitted

**Screenshots:**
Where applicable, add screenshots to help explain your problem.

**Additional context:**

**Comment by cppwfs** [comment]
Hello,
Are you Spring Cloud Data Flow on your local machine?   If so these instructions maybe useful : https://dataflow.spring.io/docs/installation/local/docker/#docker-stream--task-applications.

**Comment by cppwfs** [comment]
Closing this issue due to inactivity.  If this issue  needs to be reopened, please leave a comment.   Thank you!
