### ISSUE TITLE
Dataflow shell throws duplicate exception messages at the console

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#612]
Please see the following example:

```
dataflow:>stream destroy test
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find stream definition named test

Could not find stream definition named test

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find stream definition named test

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.delete(RestTemplate.java:429)
    at org.springframework.cloud.dataflow.rest.client.StreamTemplate.destroy(StreamTemplate.java:107)
    at org.springframework.cloud.dataflow.shell.command.StreamCommands.destroyStream(StreamCommands.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:745)
dataflow:>
```

As we can see from the above output, the error message is thrown couple of times.
1) The regular exception message shown by the JLineLogHandler via SimpleExecutionStrategy
2) Other one is from AbstractShell's loggning messageer logging warning message

**Comment by sabbyanandan** [comment]
This has been addressed already. Only the top-level error is now displayed.
