### ISSUE TITLE
Error when doing "task list" after a period of inactivity

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#655]
Running against the Kubernetes implementation I get an exception running "task list" after the server has been idle for a while. This might be due to some connection pool settings not refreshing stale connections. Needs to be investigated.

```
dataflow:>task list
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: PreparedStatementCallback; SQL [SELECT COUNT(*) FROM TASK_DEFINITIONS ]; Could not send query: Last packet not finished; nested exception is java.sql.SQLNonTransientConnectionException: Could not send query: Last packet not finished

PreparedStatementCallback; SQL [SELECT COUNT(*) FROM TASK_DEFINITIONS ]; Could not send query: Last packet not finished; nested exception is java.sql.SQLNonTransientConnectionException: Could not send query: Last packet not finished

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: PreparedStatementCallback; SQL [SELECT COUNT(*) FROM TASK_DEFINITIONS ]; Could not send query: Last packet not finished; nested exception is java.sql.SQLNonTransientConnectionException: Could not send query: Last packet not finished

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
    at org.springframework.cloud.dataflow.rest.client.TaskTemplate.list(TaskTemplate.java:99)
    at org.springframework.cloud.dataflow.rest.client.TaskTemplate.list(TaskTemplate.java:39)
    at org.springframework.cloud.dataflow.shell.command.TaskCommands.list(TaskCommands.java:88)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by trisberg** [comment]
Server side exception looks like:

**Comment by trisberg** [comment]
I resolved this for the Kubernetes server deployment by adding the following data source connection pool properties:

* "spring.datasource.testOnBorrow":true
* "spring.datasource.validationQuery":"SELECT 1"

https://github.com/spring-cloud/spring-cloud-dataflow-server-kubernetes/pull/82/commits/5892875e7e90071cad923c5eb7154fd70d48e3cb
