### ISSUE TITLE
Could not deploy docker app resources

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow#695]
When using app resource URI as docker URL, the stream deployment fails as it could not load the docker resource file.

To reproduce:

> dataflow:>app register --type source --name time --uri docker:springcloudstream/time-source-kafka:latest
> dataflow:>app register --type sink --name log --uri docker:springcloudstream/log-sink-kafka:latest
> dataflow:>stream create a1 --definition "time | log" --deploy

Following exception is thrown:

```
java.lang.RuntimeException: Exception trying to list configuration properties for application ServletContext resource [/docker:springcloudstream/log-sink-kafka:latest]
    at org.springframework.cloud.dataflow.configuration.metadata.ApplicationConfigurationMetadataResolver.listProperties(ApplicationConfigurationMetadataResolver.java:123) ~[spring-cloud-dataflow-configuration-metadata-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.qualifyParameters(StreamDeploymentController.java:267) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deployStream(StreamDeploymentController.java:243) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:186) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RE
...
...
Caused by: java.lang.IllegalArgumentException: File must exist
    at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:67) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:51) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:65) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.configuration.metadata.ApplicationConfigurationMetadataResolver.listProperties(ApplicationConfigurationMetadataResolver.java:87) ~[spring-cloud-dataflow-configuration-metadata-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
```

**Comment by ilayaperumalg** [comment]
It looks like this issue was introduced with this change: https://github.com/spring-cloud/spring-cloud-dataflow/commit/985e038d3b8f58da2dfab4d569cdddf3ce9a9475#diff-e6925c2ec0e82e9d426e01d83d3051b1R249

**Comment by donovanmuller** [comment]
Slightly different stacktrace when used in conjunction with `spring-cloud-dataflow-server-kubernetes`, see this: https://gitter.im/spring-cloud/spring-cloud?at=575ff053814a56807142ff47

**Comment by ilayaperumalg** [comment]
yeah, this would fail at all the server implementations as `StreamDeploymentController` is where it is failing. 

I think we need `DockerResourceLoader` as part of the `DelegatingResourceLoader`.
