### ISSUE TITLE
Error for 'could not find stream definition' is too verbose

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#696]
No need for a stack trace

```
dataflow:>stream create --name ticktcok --definition "time | log" --deploy
Created and deployed new stream 'ticktcok'
dataflow:>stream destroy --name ticktock
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find stream definition named ticktock

Could not find stream definition named ticktock

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find stream definition named ticktock

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.delete(RestTemplate.java:429)
    at org.springframework.cloud.dataflow.rest.client.StreamTemplate.destroy(StreamTemplate.java:107)
    at org.springframework.cloud.dataflow.shell.command.StreamCommands.destroyStream(StreamCommands.java:159)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ghillert** [comment]
This seems to be a Spring shell issue, at least in a sense that the output of errors cannot be customized in a decent manner. Currently there are 2 places exceptions are printed to the console:

`org.springframework.shell.core.SimpleExecutionStrategy`

```
private Object invoke(ParseResult parseResult) {
	try {
		Method method = parseResult.getMethod();
		ReflectionUtils.makeAccessible(method);
		return ReflectionUtils.invokeMethod(method, parseResult.getInstance(), parseResult.getArguments());
	} catch (Throwable th) {
		logger.severe("Command failed " + th);
		return handleThrowable(th);
	}
}
```

Produces:

```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find stream definition named ticktock
```
And then in:

```
org.springframework.shell.core.AbstractShell
```

```
public CommandResult executeCommand(String line)

} catch (RuntimeException e) {
			setShellStatus(Status.EXECUTION_FAILED, line, parseResult);
			logger.log(Level.WARNING, e.getMessage(), e);
			// We rely on execution strategy to log it
			try {
				logCommandIfRequired(line, false);
			} catch (Exception ignored) {}
			return new CommandResult(false, null, e);
		}
		
```

Which produces:

```
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Could not find stream definition named ticktock

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.delete(RestTemplate.java:429)
    at org.springframework.cloud.dataflow.rest.client.StreamTemplate.destroy(StreamTemplate.java:107)
    at org.springframework.cloud.dataflow.shell.command.StreamCommands.destroyStream(StreamCommands.java:159)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by ilayaperumalg** [comment]
We discussed about this issue before and here is the root cause analysis about this one:

https://github.com/spring-cloud/spring-cloud-dataflow/issues/612

**Comment by markpollack** [comment]
I think the command impl has to catch the exception and do something a bit nicer.  If we compare this to XD, I believe we will see that we didn't have these stack traces.

**Comment by ghillert** [comment]
@markpollack @ilayaperumalg The difference between Spring XD and SCDF is definitely in the used `Spring Shell` version. Spring XD uses Spring Shell version `1.1.0.RELEASE`. The log statement in `org.springframework.shell.core.AbstractShell` did not exist then, yet. It was introduced by @ericbottard  (Any particular reason for that?) in late 2015. Thus, we see the stacktrace behavior in SCDF.

Unfortunately the used `logger` class is very broad and you can't simply specify a different log-level to suppress the output:

```
<logger name="org.springframework.shell.core.JLineShellComponent" level="ERROR"/>
```

**Comment by markpollack** [comment]
We can prob revert that change in shell then...
