### ISSUE TITLE
Very long stack trace for 'NoSuchStreamDefinitionException'

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#741]
There is no need for a thee screenful exception if a stream definition is not found and an ERROR level message. This pollutes the log, in particular as the UI calls the stream endpoint to eagerly check if the stream name has already been used.

```
2016-06-28 07:21:35.897 ERROR 6498 --- [nio-9393-exec-7] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

org.springframework.cloud.dataflow.server.repository.NoSuchStreamDefinitionException: Could not find stream definition named ticktock
	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.display(StreamDefinitionController.java:201) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
```

**Comment by sabbyanandan** [comment]
The UI temporarily deactivated the validation via spring-cloud/spring-cloud-dataflow-ui#90, since it requires more server-side changes. If you switch to SNAPSHOT release (_currently, defaults to RC1_) of the UI project, you wouldn't see it in the logs. 

As for the stacktrace, I thought spring-cloud/spring-cloud-dataflow#730 would take care of it at least at the shell level?

**Comment by markpollack** [comment]
#730 is for the shell, there is still an ERROR message on the server side.  

`NoSuchStreamDefinitionException` is in RestControllerAdvice, but it seems like the stack trace is still getting logged.  Any insight @ilayaperumalg ?

**Comment by ilayaperumalg** [comment]
It looks like the `long` stacktrace is the case for all other exceptions that are updated in the `RestControllerAdvice` as well. Debugging.

**Comment by ilayaperumalg** [comment]
@markpollack Based on the `RestControllerAdvice` [logging] (https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java#L108) of `error`, we always log the `stacktrace` along with the message.

Do you think we need to truncate the stacktrace (possibly by applying some logback rule) or we don't want to stacktrace at all for the errors that are handled by `RestControllerAdvice`?
