### ISSUE TITLE
OAuth logout doesn't work

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#768]
I setup oauth with github. Github oauth normal setup with callback url `http://localhost:9393/login`.

```
java -jar spring-cloud-dataflow-server-local/target/spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar --security.basic.enabled=true --security.oauth2.client.client-id=xxx --security.oauth2.client.client-secret=xxx --security.oauth2.client.access-token-uri=https://github.com/login/oauth/access_token --security.oauth2.client.user-authorization-uri=https://github.com/login/oauth/authorize --security.oauth2.resource.user-info-uri=https://api.github.com/user
```

1. From firefox access `http://localhost:9393/dashboard`
2. It redirects to github, asks login and approve app
3. UI authenticates and shows "Signed in as jvalkeal`.
4. I logout from dataflow UI, shows "please sign in" page and "Not logged in"
5. Still logged to github, I logout from there.
6. UI still allows me to browse pages while says "Not logged in"
7. I refresh page, now it says "Signed in as jvalkeal", didn't ask to sign in back to github.
8. If I restart browser or open private browsing, UI forwards to github to sign-in.

Other than that if I try to use shell, with my secondary github account which have no 2factor outh, dataflow throws error:
```
server-unknown:>dataflow config server --username jvalkeal2 --password xxx --uri http://localhost:9393

2016-07-05 19:54:13.841  WARN 28559 --- [nio-9393-exec-3] .s.s.i.ManualOAuthAuthenticationProvider : Authenticating user 'jvalkeal2' using accessTokenUri 'https://github.com/login/oauth/access_token'.
2016-07-05 19:54:14.357 ERROR 28559 --- [nio-9393-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.lang.IllegalStateException: Access token provider returned a null access token, which is illegal according to the contract.
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:223) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
	at org.springframework.cloud.dataflow.server.service.impl.ManualOAuthAuthenticationProvider.authenticate(ManualOAuthAuthenticationProvider.java:86) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:167) ~[spring-security-core-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:192) ~[spring-security-core-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:178) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53) ~[spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
```

**Comment by ghillert** [comment]
@jvalkeal Please revisit this issue using the PR https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/102

I hope that PR improves the situation. It is not perfect, but the logout button will do a "hard-redirect" of the browser-window and upon successful logout, redirect to a static logout-success url. 

If you executed the logout link in a separate tab, you may still observe some strange behavior but I hope that is ok for the time being.

In order to improve the OAuth experiences, we may need to look at something like Satellizer:

https://github.com/sahat/satellizer

That project provides a tighter integration of the AngularJS application with OAuth providers. In the current implementation, I basically side-stepped that integration. Right now the AngularJS-based UI is not involved in the authentication process.

**Comment by jvalkeal** [comment]
closing as done
