### ISSUE TITLE
Remove stacktrace when app does not exist in the app registry.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#774]
```dataflow:>stream create --name http2file --definition "http | file"
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Application name 'file' with type 'sink' does not exist in the app registry.

Application name 'file' with type 'sink' does not exist in the app registry.

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Application name 'file' with type 'sink' does not exist in the app registry.

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:357)
```

**Comment by ghillert** [comment]
@markpollack Did you use an older version?

I am getting this which looks as expected:

![image](https://cloud.githubusercontent.com/assets/685363/16638272/9ab98c5e-4381-11e6-9ab9-212fc3186b94.png)

**Comment by markpollack** [comment]
I'll double check

**Comment by sabbyanandan** [comment]
I ran into a similar situation earlier today and I can also confirm that I see only the top-level error on both Local and CF servers. @markpollack would be the ultimate authority to verify/close. 😄

**Comment by markpollack** [comment]
```dataflow:>stream create --name tweets --definition "twitterstream | file --directory=/tmp/tweets --name=tweets --suffix=txt"
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Application name 'twitterstream' with type 'source' does not exist in the app registry.
Application name 'file' with type 'sink' does not exist in the app registry.
``` 

all good now :)  not sure what happened earlier.
