### ISSUE TITLE
binder.Kafka not accepting custom ports

### ISSUE THREAD

**Issue by bakabo** [spring-cloud/spring-cloud-dataflow#835]
This bug occurs when attempting to use a kafka broker not on the spring cloud default 9093.

How I found this bug.
Installed Kafka via ambari. Used ambari's default for kafka listener port 6667. 
Set servers.yml

```
  cloud:
    stream:
      kafka:
        binder:
          brokers: javelin:6667
          zkNodes: javelin:2181
```

Deployed a simple stream to test.

```
- http-source --port=11111 | file-sink --directory=/data1/scdf/output1
```

Used dataflow shell to send http POST request.

```
- http post --contentType 'text/plain' --target http://localhost:11111 --data "{\"name\": \"Foo\"}"
```

```
---- Yarn Logs ----
2016-08-24 11:33:22.892  INFO 18055 --- [           main] kafka.utils.VerifiableProperties         : Verifying properties
2016-08-24 11:33:22.894  INFO 18055 --- [           main] kafka.utils.VerifiableProperties         : Property client.id is overridden to groupid
2016-08-24 11:33:22.894  INFO 18055 --- [           main] kafka.utils.VerifiableProperties         : Property metadata.broker.list is overridden to javelin:**6667**
2016-08-24 11:33:22.894  INFO 18055 --- [           main] kafka.utils.VerifiableProperties         : Property request.timeout.ms is overridden to 10000
2016-08-24 11:33:22.935  INFO 18055 --- [           main] kafka.client.ClientUtils$                : Fetching metadata from broker id:0,host:javelin,port:6667 with correlation id 0 for 1 topic(s) Set(testfile.http-source)
2016-08-24 11:33:22.937  INFO 18055 --- [           main] kafka.producer.SyncProducer              : Connected to javelin:6667 for producing
2016-08-24 11:33:22.966  INFO 18055 --- [           main] kafka.producer.SyncProducer              : Disconnecting from javelin:6667
2016-08-24 11:33:22.994  INFO 18055 --- [33-javelin:2181] org.I0Itec.zkclient.ZkEventThread        : Terminate ZkClient event thread.
2016-08-24 11:33:23.000  INFO 18055 --- [           main] org.apache.zookeeper.ZooKeeper           : Session: 0x156b7dce6b60075 closed
2016-08-24 11:33:23.000  INFO 18055 --- [ain-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down
2016-08-24 11:33:23.007  INFO 18055 --- [           main] o.s.i.kafka.support.ProducerFactoryBean  : Using producer properties => {bootstrap.servers=javelin:9093, linger.ms=0, acks=1, compression.type=none, batch.size=16384}
2016-08-24 11:33:23.026  INFO 18055 --- [           main] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
	compression.type = none
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 60000
	acks = 1
	batch.size = 16384
	reconnect.backoff.ms = 10
	bootstrap.servers = [javelin:**9093**]
	receive.buffer.bytes = 32768
	retry.backoff.ms = 100
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	retries = 0
	max.request.size = 1048576
	block.on.buffer.full = true
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	metrics.sample.window.ms = 30000
	send.buffer.bytes = 131072
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	linger.ms = 0
	client.id = 
```

```
--- Error produced ---
2016-08-24 11:37:27.935  WARN 18055 --- [ad | producer-1] o.apache.kafka.common.network.Selector   : Error in I/O with javelin/10.2.1.64

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_60]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:238) ~[kafka-clients-0.8.2.2.jar!/:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192) [kafka-clients-0.8.2.2.jar!/:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191) [kafka-clients-0.8.2.2.jar!/:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122) [kafka-clients-0.8.2.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

--- Current workaround ---
Set kafka listener port to 9093

**Comment by sabbyanandan** [comment]
@bakabo: Once after you changed the `servers.yml`, did you cleanup `datafalow/apps` folder? The config settings wouldn't take into account, otherwise - see [here](http://docs.spring.io/spring-cloud-dataflow-server-yarn/docs/1.0.2.BUILD-SNAPSHOT/reference/htmlsingle/#yarn-how-it-works) for more details. 

Also, this issue belongs in SCDF's YARN implementation - I will move it.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-yarn#136
