### ISSUE TITLE
Check for Permissible Sort Properties

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#946]
This issue is related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/942

We should explicitly check the properties that are permissible for respective query/table. If non-permitted properties are being sorted on, an exception shall be raised.

Second, this would possibly also allow us to no require to name sort properties using the actual DB column-name.

Doing so we could also prevent leaky SQL abstractions, such as the following when entering a wrong sort property:

```
...
"message": "PreparedStatementCallback; bad SQL grammar [SELECT LIMIT 0 5 DEFINITION_NAME, DEFINITION FROM STREAM_DEFINITIONS ORDER BY name DESC]; nested exception is org.h2.jdbc.JdbcSQLException: Feld "NAME" nicht gefunden
Column "NAME" not found; SQL statement:
SELECT LIMIT 0 5 DEFINITION_NAME, DEFINITION FROM STREAM_DEFINITIONS ORDER BY name DESC [42122-192]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
    at org.h2.message.DbException.get(DbException.java:179)
    at org.h2.message.DbException.get(DbException.java:155)
    at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
    at org.h2.command.dml.Select.prepare(Select.java:852)
    at org.h2.command.Parser.prepareCommand(Parser.java:259)
    at org.h2.engine.Session.prepareLocal(Session.java:560)
    at org.h2.server.TcpServerThread.process(TcpServerThread.java:263)
    at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
    at java.lang.Thread.run(Thread.java:745)
",
...
```

**Comment by sabbyanandan** [comment]
This hasn't surfaced as a pressing problem for a few years now. Closing it.
