### ISSUE TITLE
Stream deployment failed but the shell reports it as successful

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#954]
_From @sabbyanandan on July 26, 2016 18:56_

As a user, I deployed the following stream and I get the error below. The shell reports successful "create and deployed" message, though. This is observed when running on top of spring-cloud/spring-cloud-deployer-cloudfoundry#63. 

**shell:**
```
dataflow:>stream create dddd --definition "time | log" --deploy
Created and deployed new stream 'dddd'
```

**error:**
```
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 2016-07-26 18:21:41.975 ERROR 30 --- [tcp-client-io-2] o.s.c.d.s.c.CloudFoundryAppDeployer      : Error creating app dataflow-muskier-otter-dddd-time
2016-07-26T11:21:41.97-0700 [APP/0]      OUT org.cloudfoundry.client.v2.CloudFoundryException: CF-InvalidAuthToken(1000): Invalid Auth Token
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at org.cloudfoundry.reactor.client.CloudFoundryExceptionBuilder.lambda$build$0(CloudFoundryExceptionBuilder.java:52) ~[cloudfoundry-client-reactor-2.0.0.M9.jar!/:2.0.0.M9]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoThenApply$MonoThenApplyManager.onNext(MonoThenApply.java:99) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:125) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:320) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:115) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:390) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.Operators$DeferredScalarSubscriber.complete(Operators.java:797) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.MonoReduce$ReduceSubscriber.onComplete(MonoReduce.java:152) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:157) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onComplete(FluxSubscribeOn.java:137) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.io.netty.common.NettyChannelHandler$InboundSink.drain(NettyChannelHandler.java:696) ~[reactor-netty-0.5.0.BUILD-SNAPSHOT.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.io.netty.common.NettyChannelHandler$InboundSink.request(NettyChannelHandler.java:772) ~[reactor-netty-0.5.0.BUILD-SNAPSHOT.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.Operators$DeferredSubscription.set(Operators.java:598) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnPipeline.onSubscribe(FluxSubscribeOn.java:117) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.io.netty.common.NettyChannelHandler.subscribe(NettyChannelHandler.java:543) ~[reactor-netty-0.5.0.BUILD-SNAPSHOT.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:59) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.publisher.FluxSubscribeOn$SourceSubscribeTask.run(FluxSubscribeOn.java:235) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:134) ~[reactor-core-3.0.0.RC1.jar!/:na]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
2016-07-26T11:21:41.97-0700 [APP/0]      OUT Caused by: reactor.io.netty.http.HttpException: HTTP request failed with code: 401
^C
```

_Copied from original issue: spring-cloud/spring-cloud-dataflow-server-cloudfoundry#148_

**Comment by sabbyanandan** [comment]
_From @ericbottard on July 27, 2016 9:51_

Stream deployment happens asynchronously (or at least could on some platforms), so there is no way to know about real success for the deployment at that time.

I think the core of the issue is that the message should be changed and be less "successfulish" in its use of words. Some thing like
```
Successfully created new stream xxx
Deployment request has been sent
```

Thoughts?

**Comment by sabbyanandan** [comment]
_From @ericbottard on October 17, 2016 13:46_

Thoughts? ^^
