### ISSUE TITLE
Re-deploying a failed stream deployment results in duplicate key database exception

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#960]
If a stream deployment fails the stream is reported as undeployed and a second deployment attempt results in a duplicate key exception since the stream's deployment ids are already in the DEPLOYMENT_IDS table.

```
2016-10-18 16:14:24.535  WARN 6203 --- [nio-9393-exec-6] o.s.c.d.s.c.StreamDeploymentController   : Exception when deploying the app StreamAppDefinition [streamName=ticktock, name=time, registeredAppName=time, properties={spring.cloud.stream.bindings.output.producer.requiredGroups=ticktock, spring.cloud.stream.bindings.output.destination=ticktock.time}]: PreparedStatementCallback; SQL [INSERT into DEPLOYMENT_IDS (DEPLOYMENT_KEY, DEPLOYMENT_ID)values (?, ?)]; Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.DEPLOYMENT_IDS(DEPLOYMENT_KEY) VALUES ('ticktock.time', 4)"; SQL statement:
INSERT into DEPLOYMENT_IDS (DEPLOYMENT_KEY, DEPLOYMENT_ID)values (?, ?) [23505-192]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.DEPLOYMENT_IDS(DEPLOYMENT_KEY) VALUES ('ticktock.time', 4)"; SQL statement:
INSERT into DEPLOYMENT_IDS (DEPLOYMENT_KEY, DEPLOYMENT_ID)values (?, ?) [23505-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:704)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:344)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by trisberg** [comment]
This is due to a problem with the local deployer - https://github.com/spring-cloud/spring-cloud-deployer/issues/136
